const {chromium}=require('playwright');const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const out=__dirname,url=process.env.PREVIEW_URL;if(!url)throw Error('PREVIEW_URL required');
const expectedPath=path.resolve(out,'../../experiments/art-slice-005/dist/manifest.json');
(async()=>{
const expectedBytes=await fs.readFile(expectedPath),expected=JSON.parse(expectedBytes);const result={url,release:'8ae9579b871520b3616619f0e67c060dc1db583f',source:'b2bb0734386f94c9e46e42c914768b123af0bd68',hashes:[],checks:[],pageErrors:[],externalRequests:[]};
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/workspace/scratch/1dc165285827/browser-runtime/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{
 const context=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true,deviceScaleFactor:1});const page=await context.newPage();result.browser=browser.version();
 page.on('pageerror',e=>result.pageErrors.push(e.message));page.on('request',r=>{if(new URL(r.url()).origin!==new URL(url).origin)result.externalRequests.push(r.url());});
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForSelector('html[data-ready=true]',{timeout:30000});await page.evaluate(()=>document.fonts.ready);
 // Fetch exact deployed bytes through the same browser origin; no canvas/image reconstruction.
 const targets=[...expected.entries.filter(e=>e.path!=='_headers'),{path:'manifest.json',bytes:expectedBytes.length,sha256:hash(expectedBytes)}];
 const observed=await page.evaluate(async paths=>{const results=[];for(let i=0;i<paths.length;i+=6){results.push(...await Promise.all(paths.slice(i,i+6).map(async path=>{const r=await fetch('./'+path,{cache:'no-store'}),b=await r.arrayBuffer(),sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b))).map(x=>x.toString(16).padStart(2,'0')).join('');return {path,status:r.status,bytes:b.byteLength,sha256:sha,type:r.headers.get('content-type')};})));}return results;},targets.map(e=>e.path));
 for(const e of targets){const a=observed.find(v=>v.path===e.path);result.hashes.push({...a,expectedSha256:e.sha256,match:a.status===200&&a.sha256===e.sha256&&a.bytes===e.bytes});}assert(result.hashes.every(x=>x.match),'live resource mismatch');result.configurationOnly={path:'_headers',validation:'exact Git blob matched before release; Cloudflare config, not a served file'};
 await page.locator('[data-unit-id="G-03"]').tap();await page.locator('[data-pick="G-02"]').tap();assert.equal(await page.evaluate(()=>window.sliceDebug.report().selected),'G-02');await page.locator('[data-unit-id="G-01"]').tap();assert.equal(await page.evaluate(()=>window.sliceDebug.report().selected),'G-01');result.checks.push('Live unit selection, stack disambiguation and switching');
 await page.locator('[data-label="V13"]').tap();assert.equal(await page.locator('#terrain-name').textContent(),'森林');await page.locator('[data-label="X14"]').tap();assert.equal(await page.locator('#terrain-name').textContent(),'城市');assert((await page.locator('#edge-list').textContent()).includes('铁路'));result.checks.push('Live terrain and edge inspector');
 const box=await page.locator('#map-wrap').boundingBox(),mx=box.x+box.width/2,my=box.y+box.height/2;const selected=await page.evaluate(()=>window.sliceDebug.report().cell);await page.mouse.move(mx,my);await page.mouse.down();await page.mouse.move(mx+65,my+20,{steps:12});await page.mouse.up();const state=await page.evaluate(()=>window.sliceDebug.report());assert(state.view.panX>50);assert.equal(state.cell,selected);result.checks.push('Live drag with selection suppression');
 await page.locator('#fit').click();await page.locator('#zoom-in').click();assert.equal(await page.evaluate(()=>window.sliceDebug.report().view.zoom),1.25);await page.locator('#zoom-out').click();assert.equal(await page.evaluate(()=>window.sliceDebug.report().view.zoom),1);result.checks.push('Live zoom buttons and fit');
 const cdp=await context.newCDPSession(page),t=(id,x,y)=>({id,x,y,radiusX:2,radiusY:2,force:1});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[t(0,mx-60,my),t(1,mx+60,my)]});for(let d=65;d<=105;d+=5)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[t(0,mx-d,my),t(1,mx+d,my)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert((await page.evaluate(()=>window.sliceDebug.report().view.zoom))>1.5);result.checks.push('Live emulated two-finger pinch; not Huawei');
 await page.locator('#fit').click();await page.screenshot({type:'jpeg',quality:90,path:path.join(out,'live-far-1024.jpg')});await page.locator('[data-unit-id="G-03"]').tap();await page.screenshot({type:'jpeg',quality:90,path:path.join(out,'live-stack-1024.jpg')});
 await page.setViewportSize({width:1363,height:936});await page.locator('#fit').click();await page.locator('[data-label="X14"]').click();await page.screenshot({type:'jpeg',quality:90,path:path.join(out,'live-far-1363.jpg')});for(let i=0;i<4;i++)await page.locator('#zoom-in').click();await page.screenshot({type:'jpeg',quality:90,path:path.join(out,'live-near-1363.jpg')});
 await page.locator('#variant').click();await page.waitForFunction(()=>window.sliceDebug.report().variant==='baseline');await page.locator('#variant').click();await page.waitForFunction(()=>window.sliceDebug.report().variant==='candidate');result.checks.push('Live same-scene baseline switch');
 result.operations=await page.evaluate(()=>window.sliceDebug.report());assert.deepEqual(result.pageErrors,[]);assert.deepEqual(result.externalRequests,[]);result.checks.push('No page errors or external/backend requests');result.status='PASS';
}catch(e){result.status='FAIL';result.failure={message:e.message,stack:e.stack};throw e;}finally{await fs.writeFile(path.join(out,'LIVE-RESULTS.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,browser:result.browser,hashes:result.hashes.length,checks:result.checks.length,failure:result.failure?.message}));await browser.close();}
})();
