import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';import * as api from '../scripts/mp017/web/export.mjs';import {VERSIONS} from '../scripts/mp017/config.mjs';
async function harness(){const nodes=Object.fromEntries(['game','device','purpose','version-choice','start','export','new-pair','version','status','fallback','result','pair'].map(k=>['#'+k,{disabled:true,value:'',textContent:'',hidden:true}]));nodes['#purpose'].value='warmup';nodes['#version-choice'].value='control';nodes['#game'].src='about:blank';nodes['#game'].contentWindow={postMessage(){}};let blob;const timers=[],downloads=[],listeners={},config={origin:'https://local-fixture.invalid',versions:VERSIONS,diagnosticSha256:'diag',serverSha:VERSIONS.control,snapshotFormat:'snapshot-v3-map-table',cachePolicy:'no-store'};
const ctx={api,crypto,location:{origin:config.origin},performance:{now:()=>12},Date,Blob,URL:{createObjectURL:b=>(blob=b,'blob:local'),revokeObjectURL(){}},fetch:async()=>({ok:true,json:async()=>config}),setTimeout:(f,delay)=>timers.push({f,delay}),addEventListener:(k,f)=>listeners[k]=f,document:{querySelector:s=>nodes[s],createElement:()=>{const a={click:()=>downloads.push(a.download)};return a;}}};const source=readFileSync('scripts/mp017/web/controller.mjs','utf8').replace(/^import .*;\r?\n/,'const {diagnosticMatches,sampleOf,exportRecord}=api;\n');await runInNewContext('(async()=>{'+source+'})()',ctx);return{nodes,config,downloads,timers,blob:()=>blob,message:data=>listeners.message({origin:config.origin,source:nodes['#game'].contentWindow,data}),foreign:()=>listeners.message({origin:'https://foreign.invalid',source:nodes['#game'].contentWindow,data:{source:'MP017',type:'ready'}})};}
function reply(h,version){h.message({source:'MP017',type:'result',build:{sourceSha:VERSIONS[version]},result:{requestId:'own',ackMs:20,acceptedRevision:1,appliedSequence:3,resyncCount:0,rejected:false,submitCount:1,flags:[]},finalState:{interactive:true,pendingMarker:false},preparation:{satisfiedAtInput:true,requiredVisibleMs:5000,continuousVisibleMs:5100}});h.message({source:'MP017-DIAG',version,sourceSha:VERSIONS[version],diagnosticSha256:'diag',report:{events:[],actions:[{requestId:'own',acceptedRevision:1,appliedSequence:3,completionCount:1,milestones:{authorityAppliedMs:40,canSelectMs:40,legalOptionsReadyMs:80,canSubmitMs:80}}]}});}
test('MP017 paired manual controller exports only performed versions, same pair/device, identical text backup',async()=>{
 const h=await harness(),n=h.nodes;assert.equal(h.downloads.length,0);n['#device'].value='component test only';const records=[];
 for(const version of ['control','candidate']){n['#start'].onclick();assert.match(n['#game'].src,new RegExp('/v/'+version+'/move/real/'));h.message({source:'MP017',type:'waiting',remainingMs:5000});h.message({source:'MP017',type:'ready'});assert.match(n['#status'].textContent,/五秒完成/);n['#export'].onclick();reply(h,version);h.timers.filter(t=>t.delay===500).at(-1).f();const text=await h.blob().text();assert.equal(n['#fallback'].value,text);const record=JSON.parse(text);assert.equal(record.version,version);assert.equal(record.classification,'warmup');assert.equal(record.parentAttempt.clock,'parent performance.now');records.push(record);assert.equal(n['#game'].src,'about:blank');}
 assert.equal(records[0].pairId,records[1].pairId);assert.equal(records[0].device,records[1].device);assert.notEqual(h.downloads[0],h.downloads[1]);assert.equal(n['#start'].disabled,true);n['#new-pair'].onclick();assert.equal(n['#start'].disabled,false);
});
test('MP017 startup failure exports missing values and prevents another version/retry',async()=>{const h=await harness(),n=h.nodes;n['#device'].value='synthetic';n['#start'].onclick();const before=n['#status'].textContent;h.foreign();assert.equal(n['#status'].textContent,before);h.message({source:'MP017-DIAG',version:'control',sourceSha:VERSIONS.control,diagnosticSha256:'diag',stage:'manifest/map',report:{events:[{kind:'caught-startup-error',at:1}],actions:[]}});h.message({source:'MP017',type:'ready'});assert.match(n['#status'].textContent,/异常/);n['#export'].onclick();h.timers.find(t=>t.delay===500).f();const r=JSON.parse(await h.blob().text());assert.equal(r.sample,null);assert.equal(r.classification,'exception-or-incomplete');assert.equal(n['#start'].disabled,true);n['#start'].onclick();assert.equal(n['#game'].src,'about:blank');});
