import {combatDom} from './helpers/combat-dom.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {harness,movementFixture,move,mapDom} from './helpers/animation-fixture.mjs';
import {battleRun,tacticalRun} from './helpers/tactical-fixture.mjs';
import {unit} from './helpers/combat-fixture.mjs';
import {dispatchGameAction,sessionPlayerView} from '../dist/app/core-adapter/session.js';
import {SeededRNG} from '../dist/vendor/eastfront-digital-core/dist/random/SeededRNG.js';
import {SvgUnitPresentation} from '../dist/app/presentation/svgUnits.js';
import {FogRuntime} from '../dist/app/fog/runtime.js';
import {SvgNode} from './helpers/svg-dom.mjs';
import {derivePlayerView,rememberPlayerView} from '../dist/app/player-view/playerView.js';
import {contactMarkers} from '../dist/app/render/contactMarkers.js';
import {modelControls,bindModelControls} from '../dist/app/ui/modelControls.js';
import {readModelDisplay,saveModelDisplay} from '../dist/app/presentation/modelDisplay.js';
import {setLocale,catalogs} from '../dist/app/localization/index.js';
const json=JSON.stringify;
function lod(h,v){h.dom().querySelector('#eastfront-map').setAttribute('data-lod',v);h.runtime.sync(h.s,h.dom());}
function face(h,id='g'){return h.dom().counter(id).querySelector('.counter-face');}
function plate(h,id='g'){return h.dom().counter(id).querySelector('.compact-unit');}
for(const level of ['far','medium','close'])test(`UA003R3 AUTO ${level} selects one information surface`,()=>{const h=harness();lod(h,level);assert.equal(face(h).getAttribute('visibility'),level==='far'?'visible':'hidden');assert.equal(plate(h).getAttribute('visibility'),level==='far'?'hidden':'visible');assert.equal(h.dom().querySelector('[data-unit-presence-layer]').getAttribute('visibility'),level==='far'?'hidden':'visible');assert.equal(h.time.pending(),0);h.runtime.dispose();});
test('UA003R3 OFF restores complete Counter at every zoom',()=>{const h=harness();h.runtime.setModelDisplay('off');for(const level of ['far','medium','close']){lod(h,level);assert.equal(face(h).getAttribute('visibility'),'visible');assert(face(h).querySelector('.unit-symbol'));assert.equal(plate(h).getAttribute('visibility'),'hidden');assert.equal(plate(h).querySelector('.model-hit-proxy').getAttribute('pointer-events'),'none');assert.equal(h.dom().hit('g').getAttribute('pointer-events'),'all');assert.equal(h.dom().querySelector('[data-unit-presence-layer]').getAttribute('visibility'),'hidden');}h.runtime.dispose();});
test('UA003R3 preference changes preserve GameState, selection, draft, session, Camera and RNG',ctx=>{const h=harness(),state=json(h.s.state),draft=json(h.p),root=h.dom();root.setAttribute('data-zoom','1.4');root.querySelector('#eastfront-map').setAttribute('transform','translate(14 -8) scale(1.4)');for(const method of ['nextFloat','rollDie','roll2D6'])ctx.mock.method(SeededRNG.prototype,method,()=>{throw Error('RNG read');});for(const mode of ['off','auto','off','auto'])h.runtime.setModelDisplay(mode);assert.equal(json(h.s.state),state);assert.equal(json(h.p),draft);assert.equal(root.getAttribute('data-zoom'),'1.4');assert.equal(root.querySelector('#eastfront-map').getAttribute('transform'),'translate(14 -8) scale(1.4)');assert.equal(h.dom(),root);assert.equal(h.time.pending(),0);h.runtime.dispose();});
test('UA003R3 model proxy bubbles to the existing unit button identity',()=>{const h=harness(),proxy=h.dom().querySelector('.model-hit-proxy');assert.equal(proxy.getAttribute('pointer-events'),'all');assert.equal(proxy.getAttribute('data-unit-id'),null);assert.equal(proxy.parentNode.parentNode,h.dom().counter('g'));assert.equal(proxy.parentNode.parentNode.getAttribute('role'),'button');const main=readFileSync('src/main.ts','utf8');assert(main.includes("element.dataset.unitId"));assert(main.includes('selectCounter(session!,presentation,id)'));assert(main.includes('chooseCounterTarget(id)'));h.runtime.dispose();});
test('UA003R3 stack proxies cover both distinct model centers with independently routed identities',()=>{const h=harness(movementFixture([unit('a','G-INF','GERMAN','INFANTRY',{q:0,r:0}),unit('b','G-PANZER','GERMAN','PANZER',{q:0,r:0})]));const boxes=['a','b'].map((id,i)=>{const proxy=h.dom().counter(id).querySelector('.model-hit-proxy'),x=Number(proxy.getAttribute('x'))+(i===0?-6.5:6.5),w=Number(proxy.getAttribute('width'));assert.equal(proxy.parentNode.parentNode.getAttribute('data-unit-id'),id);return {x,w};});assert(boxes[0].x+boxes[0].w<=boxes[1].x);h.runtime.dispose();});
test('UA003R3 HIDDEN enemy has no Counter, model, plate or proxy',()=>{const f=movementFixture([unit('g','G-INF','GERMAN','INFANTRY',{q:-2,r:-2}),unit('s','S-INF','SOVIET','INFANTRY',{q:2,r:2})]);f.s.viewOverride='GERMAN';const h=harness(f);for(const mode of ['auto','off']){h.runtime.setModelDisplay(mode);assert(!h.dom().counter('s'));assert(!h.dom().querySelector('[data-presence-id="s"]'));assert.equal(h.dom().querySelectorAll('.compact-unit').length,1);assert.equal(h.dom().querySelectorAll('.model-hit-proxy').length,1);}h.runtime.dispose();});
test('UA003R3 CONTACT and Last Known are unchanged by model preference',()=>{const f=movementFixture([unit('g','G-RECON','GERMAN','RECON',{q:-1,r:0}),unit('s','S-INF','SOVIET','INFANTRY',{q:2,r:0})]);f.s.viewOverride='GERMAN';const current=sessionPlayerView(f.s);assert.equal(current.contacts.length,1);const memory=rememberPlayerView(current);f.s.state.units.s.hex={q:2,r:2};f.s.state.units.g.hex={q:-2,r:-2};const view=derivePlayerView(f.s.state,'GERMAN',f.s.rules,memory);assert(view.lastKnown.length);const before=contactMarkers(view),h=harness(f);for(const mode of ['off','auto']){h.runtime.setModelDisplay(mode);assert.equal(contactMarkers(view),before);}h.runtime.dispose();});
for(const mode of ['normal','skip','instant'])test(`UA003R3 ${mode} keeps model/plate synchronized and settles canonically`,()=>{const h=harness();lod(h,'close');dispatchGameAction(h.s,move());h.remount();lod(h,'close');const state=json(h.s.state);for(let i=0;i<5;i++){h.time.tick(40);assert.equal(h.dom().querySelector('[data-presence-id="g"]').getAttribute('transform'),h.dom().counter('g').getAttribute('transform'));assert.equal(plate(h).parentNode,h.dom().counter('g'));}if(mode==='skip')h.runtime.skip();else if(mode==='instant')h.runtime.setSpeed('instant');else h.finish();const canonical=harness({s:h.s,p:h.p});lod(canonical,'close');assert.equal(h.dom().counter('g').serialize(),canonical.dom().counter('g').serialize());assert.equal(json(h.s.state),state);assert.equal(h.time.pending(),0);canonical.runtime.dispose();h.runtime.dispose();});
test('UA003R3 OFF skips active miniature paint work',()=>{const h=harness();dispatchGameAction(h.s,move());h.remount();h.runtime.setModelDisplay('off');const node=h.dom().querySelector('[data-unit-presence-layer]'),before=node.serialize();for(let i=0;i<4;i++)h.time.tick(30);assert.equal(node.serialize(),before);h.runtime.dispose();});
test('UA003R3 destroyed model/plate proxy becomes inert and is completely cleaned',()=>{const h=battleRun({destroy:true}),ghost=h.dom().querySelector('[data-presentation-ghost]');assert(ghost);for(const n of [ghost,...ghost.querySelectorAll('*')]){assert.equal(n.getAttribute('pointer-events'),'none');assert.equal(n.getAttribute('data-unit-id'),null);}h.runtime.skip();assert.equal(h.dom().querySelector('[data-presentation-ghost]'),null);assert.equal(h.dom().querySelector('[data-presence-ghost]'),null);h.runtime.dispose();});
test('UA003R3 animation and toggle do not rebuild the authorized fog mask',()=>{SvgNode.prototype.replaceChildren=function(){for(const c of [...this.children])c.remove();};const h=harness(),svg=h.dom().querySelector('#eastfront-map'),layer=svg.ownerDocument.createElementNS('','g');layer.setAttribute('id','fog-surface-layer');svg.appendChild(layer);let encodes=0;const fog=new FogRuntime(()=>{encodes++;return 'data:test';}),view={...sessionPlayerView(h.s),viewer:'GERMAN'};fog.sync(svg,view);const before=fog.buildCount;for(let i=0;i<10;i++){h.runtime.setModelDisplay(i%2?'auto':'off');fog.sync(svg,view,null,true);h.time.tick(16);}assert.equal(fog.buildCount,before);assert.equal(encodes,1);fog.clear();h.runtime.dispose();});
test('UA003R3 bilingual controls persist a presentation preference without remounting',()=>{const h=harness();let callback;const root={querySelector:()=>({addEventListener:(_,cb)=>{callback=cb;}})};bindModelControls(root,h.runtime);const before=json(h.s.state),dom=h.dom();callback({currentTarget:{value:'off'}});assert.equal(h.runtime.modelDisplay,'off');assert.equal(h.dom(),dom);for(const locale of ['zh-CN','en-US']){setLocale(locale);const markup=modelControls(h.runtime);assert(markup.includes(catalogs[locale]['models.label']));assert(markup.includes(catalogs[locale]['models.auto']));assert(markup.includes(catalogs[locale]['models.off']));}assert.equal(json(h.s.state),before);setLocale('zh-CN');h.runtime.dispose();});
test('UA003R3 preference safely defaults to AUTO without storage',()=>{assert(['auto','off'].includes(readModelDisplay()));assert.doesNotThrow(()=>saveModelDisplay('auto'));});
test('UA003R3 no R2 flattening; no new frame scheduler or terrain/fog imports',()=>{assert(!readFileSync('src/presentation/unitPresenceSvg.ts','utf8').includes('scale(1 .65)'));const text=readFileSync('src/presentation/unitPresence.ts','utf8');assert(!/requestAnimationFrame|setTimeout|rasterizeFog|buildCachedTerrainSurface/.test(text));});
test('UA003R3 freezes Core, Camera, FOW projection/material, VS2, startup and UA timing',()=>{for(const [p,hash]of Object.entries(JSON.parse(readFileSync('tests/fixtures/ua003r3-frozen-sha256.json'))))assert.equal(createHash('sha256').update(readFileSync(p)).digest('hex'),hash,p);});

test('UA003R3 both model proxy identities execute the actual application selection binding',()=>{
 const f=movementFixture([unit('a','G-INF','GERMAN','INFANTRY',{q:0,r:0}),unit('b','G-PANZER','GERMAN','PANZER',{q:0,r:0})]),root=mapDom(f.s,f.p),ui=combatDom(f.s,f.p),state=json(f.s.state);
 for(const id of ['a','b']){const proxy=root.counter(id).querySelector('.model-hit-proxy'),owner=proxy.parentNode.parentNode.getAttribute('data-unit-id');ui.click(`[data-unit-id="${owner}"]`);assert.equal(f.p.selectedUnitId,id);}assert.equal(json(f.s.state),state);
});

test('UA003R3 stack entry shares model interpolation with plate and its hit proxy',()=>{
 const h=harness(movementFixture([unit('g','G-INF','GERMAN','INFANTRY',{q:0,r:0}),unit('a','G-PANZER','GERMAN','PANZER',{q:1,r:0})]));lod(h,'close');dispatchGameAction(h.s,move('g',[{q:1,r:0}]));h.remount();lod(h,'close');
 const translation=n=>(n.getAttribute('transform')?.match(/translate\(([-\d.e]+) ([-\d.e]+)\)/)?.slice(1).map(Number)??[0,0]);
 for(let i=0;i<7;i++){h.time.tick(35);const ground=h.dom().querySelector('[data-presence-id="g"]').querySelector('[data-presence-ground]'),scale=Number(ground.getAttribute('transform').match(/scale\(([^)]+)\)/)[1]),g=translation(ground),offset=translation(plate(h)),label=translation(plate(h).querySelector('.compact-plate'));assert(Math.abs(label[0]+offset[0]-g[0])<1e-8);assert(Math.abs(label[1]+offset[1]-(g[1]+10*scale)-20)<1e-8);}
 h.runtime.skip();assert.equal(plate(h).getAttribute('transform'),null);h.runtime.dispose();
});
