import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {createLocalGameSession,controllerIdForSide,dispatchGameAction,setActiveViewer} from '../dist/app/core-adapter/session.js';
import {deriveBrowserRenderModel} from '../dist/app/render/coreModel.js';
import {coreSvgMarkup} from '../dist/app/render/coreSvg.js';
import {createPresentationState} from '../dist/app/state/presentation.js';
import {terrainAssetCatalog,manifestEntryCount,visualSeed,selectTerrainLod} from '../dist/app/render/terrainAssets.js';
import {productionFamilyForTerrain} from '../dist/app/render/productionTerrain.js';
import {deploymentHexKeysForSide} from '../dist/vendor/eastfront-digital-core/dist/index.js';
const raw=JSON.parse(await readFile(new URL('../vendor/eastfront-digital-core/reference/strategic-reset-f-map.json',import.meta.url),'utf8'));
const fresh=(seed=17)=>createLocalGameSession(raw,seed);
function planFor(s,side){const ids=s.scenario.deployment.units.filter(u=>u.side===side).map(u=>u.id).sort(),zone=deploymentHexKeysForSide(s.state,s.scenario,side),plan={};ids.forEach((id,i)=>plan[id]={...s.state.hexes[zone[Math.floor(i/s.rules.stackingLimit)]].coord});return {ids,plan};}
function deployAll(s,side){const cid=controllerIdForSide(s,side),{ids,plan}=planFor(s,side);for(const id of ids){const r=dispatchGameAction(s,{type:'DEPLOY_INITIAL_UNIT',controllerId:cid,deploymentUnitId:id,hex:plan[id]}).result;assert.equal(r.accepted,true);}}
function model(s,p){return deriveBrowserRenderModel(s,p)}
test('P4R3 manifest loads all 117 entries and required families',()=>{assert.equal(manifestEntryCount(),117);for(const f of ['ground','plain_ground','forest_mass','hill','rough','marsh_wet','city_medium','river','road','railway','bridge_road','bridge_rail'])assert(terrainAssetCatalog.byFamily(f).length>0,f);});
test('deterministic variant selection repeats for same seed/hex',()=>{const h={q:7,r:4};assert.equal(terrainAssetCatalog.selectVariant('forest_mass',17,h)?.id,terrainAssetCatalog.selectVariant('forest_mass',17,h)?.id);assert.equal(visualSeed(17,h,'x'),visualSeed(17,h,'x'));});
test('different visual seed deterministically changes at least one map variant',()=>{const s=fresh(),p=createPresentationState();const m=model(s,p);const a=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17});const b=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:19});assert.notEqual(a,b);});
test('rendering production terrain does not mutate GameState or RNG draws',()=>{const s=fresh(),p=createPresentationState(),before=JSON.stringify(s.state);coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod:'close',scenarioSeed:s.state.random.seed});assert.equal(JSON.stringify(s.state),before);});
test('same Hex selects identical production markup after rerender',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p);const a=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17});const b=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17});assert.equal(a,b);});
test('real 640 map renders all canonical production grid hexes',()=>{const s=fresh(),p=createPresentationState(),svg=coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod:'far'});assert.equal((svg.match(/data-grid-hex=/g)||[]).length,640);});
test('every production terrain type has a visual path or documented lake fallback',()=>{const s=fresh();for(const t of new Set(Object.values(s.state.hexes).map(h=>h.terrain))){assert(t==='LAKE'||productionFamilyForTerrain(t),t);}});
test('production infrastructure remains based on real Core edge count/types',()=>{const s=fresh(),p=createPresentationState(),svg=coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod:'medium'});assert(svg.includes('production-infrastructure-layer'));assert(svg.includes('prod-road'));assert(svg.includes('prod-river-water'));assert(svg.includes('prod-rail-ballast'));assert(svg.includes('prod-bridge'));});
test('production renderer preserves hidden German deployment zero-leak',()=>{const s=fresh(),p=createPresentationState();deployAll(s,'SOVIET');assert(dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:controllerIdForSide(s,'SOVIET')}).result.accepted);setActiveViewer(s,controllerIdForSide(s,'GERMAN'));const svg=coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod:'medium'});for(const id of s.scenario.deployment.units.filter(u=>u.side==='SOVIET').map(u=>u.id))assert.equal(svg.includes(`data-unit-id="${id}"`),false);});
test('production renderer preserves deployment/action hit testing markup',()=>{const s=fresh(),p=createPresentationState(),svg=coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod:'medium'});assert(svg.includes('data-role="deployment-hex"'));});
test('LOD thresholds follow Far/Medium/Close screen hex width contract',()=>{assert.equal(selectTerrainLod(55),'far');assert.equal(selectTerrainLod(56),'medium');assert.equal(selectTerrainLod(96),'medium');assert.equal(selectTerrainLod(97),'close');});
test('LOD changes presentation only and strips microdetail at Far',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),before=JSON.stringify(s.state),far=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'far'}),close=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'close'});assert.notEqual(far,close);assert.equal(JSON.stringify(s.state),before);assert(!far.includes('prod-rail-sleep'));assert(close.includes('prod-rail-sleep'));});
test('Prototype/Production switch is presentation-only and geometry hash remains locked',async()=>{const s=fresh(),p=createPresentationState(),before=JSON.stringify(s.state),m=model(s,p);coreSvgMarkup(m,{debug:false,rendererMode:'prototype'});p.rendererMode='production';coreSvgMarkup(m,{debug:false,rendererMode:'production'});assert.equal(JSON.stringify(s.state),before);const sha=createHash('sha256').update(await readFile(new URL('../src/geometry/hex.ts',import.meta.url))).digest('hex');assert.equal(sha,'283b0445e3bff1bc412dd76536ce49e517ffa1dd35dc26c1f8c194b88ba9ab7a');});

function cellMarkup(svg,key){const marker=`<g data-hex="${key}"`;const start=svg.indexOf(marker);assert(start>=0,`missing cell ${key}`);const next=svg.indexOf('<g data-hex="',start+marker.length);return svg.slice(start,next<0?svg.length:next);}
function firstCoordOfTerrain(s,terrain){const h=Object.values(s.state.hexes).find(x=>x.terrain===terrain);assert(h,`missing terrain ${terrain}`);return h.coord;}

test('UI006R1 Forest primary mass is rendered exactly once per Forest Hex',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'FOREST'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert.equal((cell.match(/data-family="forest_mass"/g)||[]).length,1);});
test('UI006R1 Marsh wet primary is rendered exactly once per Marsh Hex',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'MARSH'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert.equal((cell.match(/data-family="marsh_wet"/g)||[]).length,1);});
test('UI006R1 normal City uses exactly one medium primary family',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'CITY'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert.equal((cell.match(/data-family="city_medium"/g)||[]).length,1);assert.equal((cell.match(/data-family="city_major"|data-family="city_small"/g)||[]).length,0);});
test('UI006R1 Main City uses major primary without hidden medium duplicate',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'MAIN_CITY'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert.equal((cell.match(/data-family="city_major"/g)||[]).length,1);assert.equal((cell.match(/data-family="city_medium"/g)||[]).length,0);});
test('UI006R1 Outer City uses small primary without hidden medium duplicate',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'OUTER_CITY'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert.equal((cell.match(/data-family="city_small"/g)||[]).length,1);assert.equal((cell.match(/data-family="city_medium"/g)||[]).length,0);});
test('UI006R1 Hill height raster is mask input, not ordinary visible high-opacity artwork',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'HILL'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert(cell.includes('data-role="hill-height-mask"'));assert(cell.includes('data-role="hill-nw-light"'));assert(!/_height\.png"[^>]*opacity=/.test(cell));assert(cell.includes('/hill/material/'));});
test('UI006R1 Hill remains visually represented at Far LOD',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'HILL'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'far',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert(cell.includes('/hill/material/'));assert(cell.includes('data-role="hill-nw-light"'));});
test('UI006R1 Rough remains visually represented at Far LOD without close microdetail',()=>{const s=fresh(),p=createPresentationState(),m=model(s,p),c=firstCoordOfTerrain(s,'ROUGH'),svg=coreSvgMarkup(m,{debug:false,rendererMode:'production',lod:'far',scenarioSeed:17}),cell=cellMarkup(svg,`${c.q},${c.r}`);assert(cell.includes('data-role="rough-far-mass"'));assert(!cell.includes('rough_rock_cluster'));});
test('UI006R1 River Medium includes shadow bank water and highlight',()=>{const s=fresh(),p=createPresentationState(),svg=coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod:'medium',scenarioSeed:17});for(const cls of ['prod-river-shadow','prod-river-bank','prod-river-water','prod-river-highlight'])assert(svg.includes(cls),cls);assert(!svg.includes('prod-river-vegetation'));});
test('UI006R1 River Close adds edge vegetation',()=>{const s=fresh(),p=createPresentationState(),svg=coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod:'close',scenarioSeed:17});assert(svg.includes('prod-river-vegetation'));});
test('UI006R1 Railway Medium and Close include contact shadow',()=>{const s=fresh(),p=createPresentationState();for(const lod of ['medium','close']){const svg=coreSvgMarkup(model(s,p),{debug:false,rendererMode:'production',lod,scenarioSeed:17});assert(svg.includes('prod-rail-shadow'),lod);assert(svg.includes('data-asset-id="RAIL_SHADOW"'),lod);}});
test('UI006R1 active visual seed controls eligible asset transform variation',async()=>{const {terrainAssetTransform}=await import('../dist/app/render/productionTerrain.js');const entry=terrainAssetCatalog.byId('H01');assert(entry);const coords=[{q:0,r:0},{q:2,r:3},{q:7,r:-2},{q:13,r:5}];for(const c of coords)assert.equal(terrainAssetTransform(entry,c,17),terrainAssetTransform(entry,c,17));assert(coords.some(c=>terrainAssetTransform(entry,c,17)!==terrainAssetTransform(entry,c,19)));});
