import { setLocale, t, enumLabel, phaseName, formatMessage } from '../dist/app/localization/index.js';
setLocale('en-US');
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {readFile,readdir,stat} from 'node:fs/promises';
import {deploymentHexKeysForSide} from '../dist/vendor/eastfront-digital-core/dist/index.js';
import {createLocalGameSession,controllerIdForSide,dispatchGameAction,setActiveViewer} from '../dist/app/core-adapter/session.js';
import {createFreshProductionSession,defaultMapViewport,fatalMarkup,homeMarkup,loadingMarkup,productionDeveloperUiAllowed,responsiveProfile,zoomViewport} from '../dist/app/web/preview.js';
import {assetRoot} from '../dist/app/render/terrainAssets.js';
import {createPresentationState} from '../dist/app/state/presentation.js';import {deriveBrowserRenderModel} from '../dist/app/render/coreModel.js';
const raw=JSON.parse(await readFile(new URL('../vendor/eastfront-digital-core/reference/strategic-reset-f-map.json',import.meta.url),'utf8'));
const stateJson=s=>JSON.stringify(s.state);
function deployAll(s,side){const cid=controllerIdForSide(s,side),ids=s.scenario.deployment.units.filter(u=>u.side===side).map(u=>u.id).sort(),zone=deploymentHexKeysForSide(s.state,s.scenario,side);const counts={};for(const id of ids){const k=zone.find(k=>(counts[k]??0)<s.rules.stackingLimit);const r=dispatchGameAction(s,{type:'DEPLOY_INITIAL_UNIT',controllerId:cid,deploymentUnitId:id,hex:s.state.hexes[k].coord});assert(r.result.accepted);counts[k]=(counts[k]??0)+1;}}
test('UI008 Home renders formal branding and New Game',()=>{const h=homeMarkup('DESKTOP');assert(h.includes('EASTFRONT · 东线突击'));assert(h.includes('id="new-game-button"'));assert(h.includes('v0.0.10'));assert(h.includes('UI-009R2D2'));});
test('UI008 New Game helper creates real production Soviet deployment',()=>{const s=createFreshProductionSession(raw,17);assert.equal(s.state.phase,'SOVIET_DEPLOYMENT');assert.equal(Object.keys(s.state.hexes).length,640);assert.equal(s.integrityIssues.length,0);});
test('UI008 Restart helper path creates a fresh legal independent state',()=>{const a=createFreshProductionSession(raw,17),b=createFreshProductionSession(raw,17);deployAll(a,'SOVIET');assert.notEqual(stateJson(a),stateJson(b));assert.equal(b.state.phase,'SOVIET_DEPLOYMENT');assert.equal(b.integrityIssues.length,0);});
test('UI008 public hosts hide developer controls even with dev query',()=>{assert.equal(productionDeveloperUiAllowed('example.com','?dev=1'),false);assert.equal(productionDeveloperUiAllowed('127.0.0.1','?dev=1'),true);});
test('UI008 production dist excludes P4R3 A-B dev assets',async()=>{await assert.rejects(stat(new URL('../dist/dev-assets/',import.meta.url)));});
test('UI008 P5R1 runtime assets are present and S02 is the approved micro-fix',async()=>{const bytes=await readFile(new URL('../dist/assets/terrain/p4r3/city/small/S02.png',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),'914593e3fb5c28b412fd0aff47418728f9ff360fce19659f63b870352890c55e');});
test('UI008 Home-to-deployment hidden-view contract remains zero-leak',()=>{const s=createFreshProductionSession(raw,17);deployAll(s,'SOVIET');let r=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:controllerIdForSide(s,'SOVIET')});assert(r.result.accepted);setActiveViewer(s,controllerIdForSide(s,'GERMAN'));const m=deriveBrowserRenderModel(s,createPresentationState());assert.equal(m.counters.some(c=>c.side==='SOVIET'),false);});
test('UI008 fatal state is safe user-facing fallback',()=>{const h=fatalMarkup('<boom>');assert(h.includes('Unable to start EASTFRONT'));assert(h.includes('id="reload-button"'));assert.equal(h.includes('<boom>'),false);});
test('UI008 loading state is explicit',()=>{assert(loadingMarkup().includes('Loading EASTFRONT…'));});
test('UI008 desktop responsive profile',()=>{assert.equal(responsiveProfile(1920,1080),'DESKTOP');assert.equal(responsiveProfile(1366,768),'IPAD_LANDSCAPE');});
test('UI008 iPad landscape responsive profile covers target sizes',()=>{assert.equal(responsiveProfile(1024,768),'IPAD_LANDSCAPE');assert.equal(responsiveProfile(1180,820),'IPAD_LANDSCAPE');assert.equal(responsiveProfile(1366,1024),'IPAD_LANDSCAPE');});
test('UI008 mobile narrow stays renderable with advisory',()=>{assert.equal(responsiveProfile(390,844),'MOBILE_NARROW');assert(homeMarkup('MOBILE_NARROW').includes('For the best experience'));});
test('UI008 production asset URLs are relative for subpath hosting',()=>{assert.equal(assetRoot('p5'),'./assets/terrain/p4r3');});
test('UI008 locked Geometry SHA unchanged',async()=>{const b=await readFile(new URL('../src/geometry/hex.ts',import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),'283b0445e3bff1bc412dd76536ce49e517ffa1dd35dc26c1f8c194b88ba9ab7a');});
test('UI008 production New Game helper matches direct frozen session semantics',()=>{const a=createFreshProductionSession(raw,17),b=createLocalGameSession(raw,17);assert.equal(JSON.stringify(a.state),JSON.stringify(b.state));});
test('UI008 zoom viewport gives touch-accessible deterministic alternative to wheel zoom',()=>{let v=defaultMapViewport();v=zoomViewport(v,.2);assert.equal(v.zoom,1.2);v=zoomViewport(v,-9);assert.deepEqual(v,{zoom:1,panX:0,panY:0});});
test('UI008 CSS constrains gestures only to map and preserves large touch controls',async()=>{const css=await readFile(new URL('../styles.css',import.meta.url),'utf8');assert(css.includes('.map-wrap{')&&css.includes('touch-action:none'));assert(css.includes('min-height:42px'));});
test('UI008 final dist has no review/test/source-map directories',async()=>{const names=await readdir(new URL('../dist/',import.meta.url));for(const bad of ['dev-assets','screenshots','tests','review'])assert.equal(names.includes(bad),false);});
test('UI008 combat closure returns privacy handoff to the active side when defender owned the last decision', async()=>{
  const {getLegalRetreatStepOptions,validateMoveAction}=await import('../dist/vendor/eastfront-digital-core/dist/index.js');
  const intents=await import('../dist/app/interaction/intents.js');
  const s=createFreshProductionSession(raw,17),p=createPresentationState(false,false);
  const plan=(side,special={})=>{const ids=s.scenario.deployment.units.filter(u=>u.side===side).map(u=>u.id).sort(),zone=deploymentHexKeysForSide(s.state,s.scenario,side),counts={},out={};for(const [id,k] of Object.entries(special)){out[id]=s.state.hexes[k].coord;counts[k]=(counts[k]??0)+1;}for(const id of ids){if(out[id])continue;const k=zone.find(x=>(counts[x]??0)<s.rules.stackingLimit&&!Object.values(special).includes(x))??zone.find(x=>(counts[x]??0)<s.rules.stackingLimit);out[id]=s.state.hexes[k].coord;counts[k]=(counts[k]??0)+1;}return {ids,out};};
  for(const side of ['SOVIET','GERMAN']){if(side==='GERMAN')setActiveViewer(s,controllerIdForSide(s,'GERMAN'));const {ids,out}=plan(side,side==='SOVIET'?{'S-I-01':'3,-1'}:{'G-PZ-01':'2,-1'});for(const id of ids){const r=dispatchGameAction(s,{type:'DEPLOY_INITIAL_UNIT',controllerId:controllerIdForSide(s,side),deploymentUnitId:id,hex:out[id]});assert(r.result.accepted);}const rr=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:controllerIdForSide(s,side)});assert(rr.result.accepted);}
  while(s.state.phase!=='GERMAN_COMBAT'){const r=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:controllerIdForSide(s,'GERMAN')});assert(r.result.accepted);}
  setActiveViewer(s,controllerIdForSide(s,'GERMAN'));p.selectedUnitId='G-PZ-01';intents.toggleAttackUnit(s,p,'G-PZ-01');intents.selectAttackTarget(p,{q:3,r:-1});intents.declareAttack(s,p);assert.equal(p.privacyGate,'COMBAT_DECISION');intents.confirmPrivacyGate(s,p);assert.equal(s.state.controllers[s.activeViewerControllerId].side,'SOVIET');intents.passCombatReaction(s,p);if(!s.state.pendingDecision){assert.equal(p.privacyGate,'PASS_TURN_TO_GERMAN');intents.confirmPrivacyGate(s,p);assert.equal(s.state.controllers[s.activeViewerControllerId].side,'GERMAN');}
});
test('UI008 production manifest startup contract resolves exactly 123 P5R1 raster paths', async()=>{const {validateProductionRuntimeManifest}=await import('../dist/app/web/preview.js');const manifest=JSON.parse(await readFile(new URL('../dist/assets/terrain/p4r3/manifest.json',import.meta.url),'utf8'));const refs=validateProductionRuntimeManifest(manifest);assert.equal(refs.length,123);assert(refs.includes('city/small/S02.png'));});
