import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {
  RulesEngine,createGameState,defaultRules,defaultScenario,deploymentHexKeysForSide,getLegalRetreatStepOptions,getNeighbors,validateAttackAction,validateGameStateIntegrity,
} from '../dist/vendor/eastfront-digital-core/dist/index.js';
import {controllerIdForSide,createLocalGameSession,dispatchGameAction,setActiveViewer} from '../dist/app/core-adapter/session.js';
import {
  advanceAfterCombat,appendLossDraft,clearAttackDraft,commitBreakthrough,commitLosses,commitRetreat,commitSchwerpunkt,confirmPrivacyGate,declareAttack,extendBreakthroughDraft,extendRetreatDraft,passAdvance,passBreakthrough,passCombatReaction,passSchwerpunkt,selectAttackTarget,selectBreakthroughUnit,selectRetreater,selectSchwerpunktTarget,toggleAttackUnit,useDefenderArtillery,
} from '../dist/app/interaction/intents.js';
import {deriveBrowserRenderModel} from '../dist/app/render/coreModel.js';
import {coreSvgMarkup} from '../dist/app/render/coreSvg.js';
import {createPresentationState} from '../dist/app/state/presentation.js';

const G='G-HUMAN-1',S='S-AI-1';
const key=h=>`${h.q},${h.r}`;
const grid=(n=5)=>{const out=[];for(let q=-n;q<=n;q++)for(let r=-n;r<=n;r++)out.push({coord:{q,r},terrain:'PLAIN',control:null});return out;};
const unit=(id,templateId,side,type,hex)=>({id,templateId,side,type,step:0,alive:true,hex:{...hex},supplyState:'SUPPLIED',entrenched:false,hasMoved:false,hasAttacked:false,controllerId:side==='GERMAN'?G:S,temporarySupply:false,dedicatedRailRepair:false,reconZocIgnoreUsed:false,artillerySupportUsed:false,lastHQCommandTurn:null});
function fixture(units,seed=2722){const st=createGameState({scenario:defaultScenario,rules:defaultRules,hexes:grid(),edges:[],units,seed});for(const u of Object.values(st.units))if(u.alive)u.supplyState='SUPPLIED';st.phase='GERMAN_COMBAT';st.activeSide='GERMAN';return {state:st,scenario:defaultScenario,rules:defaultRules,engine:new RulesEngine(defaultRules,defaultScenario),activeViewerControllerId:G,lastResult:null,integrityIssues:[]};}
const cloneState=s=>JSON.stringify(s.state);
function declare(session,attackers=['g'],target={q:0,r:0}){const r=dispatchGameAction(session,{type:'ATTACK',controllerId:G,attackerUnitIds:attackers,target}).result;assert.equal(r.accepted,true,JSON.stringify(r.issues));return r.battleId;}
function passReactionCore(session,bid){setActiveViewer(session,S);const r=dispatchGameAction(session,{type:'PASS_REACTION',controllerId:S,battleId:bid}).result;assert.equal(r.accepted,true,JSON.stringify(r.issues));return r;}

// Draft state + handoff + pending lock.
test('UI attack draft is presentation-only; accepted ATTACK creates Core transaction and hot-seat reaction handoff',()=>{
  const s=fixture([unit('g','G-INF','GERMAN','INFANTRY',{q:-1,r:0}),unit('d','S-ELITE','SOVIET','ELITE_INFANTRY',{q:0,r:0})],2722);const p=createPresentationState(false,false);const before=cloneState(s);
  toggleAttackUnit(s,p,'g');selectAttackTarget(p,{q:0,r:0});assert.equal(cloneState(s),before);const m=deriveBrowserRenderModel(s,p);assert(m.combat.attackDraft.preview);assert(coreSvgMarkup(m,{debug:false}).includes('combat-attack-line'));
  declareAttack(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.pendingDecision.kind,'DEFENDER_REACTION');assert.equal(p.privacyGate,'COMBAT_DECISION');const actionState=cloneState(s);confirmPrivacyGate(s,p);assert.equal(cloneState(s),actionState);assert.equal(s.activeViewerControllerId,S);
  const blocked=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:S});assert.equal(blocked.result.accepted,false);assert(blocked.result.issues.length>0);
});

test('Defender Reaction PASS and defensive artillery both use real Core reaction transaction',()=>{
  let s=fixture([unit('g','G-INF','GERMAN','INFANTRY',{q:-1,r:0}),unit('d','S-ELITE','SOVIET','ELITE_INFANTRY',{q:0,r:0})],2722);let bid=declare(s);setActiveViewer(s,S);let p=createPresentationState();p.selectedBattleId=bid;passCombatReaction(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.combatTransactions[bid].resolution.crtResult,'NE');assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');
  s=fixture([unit('g','G-INF','GERMAN','INFANTRY',{q:-1,r:0}),unit('d','S-ELITE','SOVIET','ELITE_INFANTRY',{q:0,r:0}),unit('sa','S-ARTY','SOVIET','ARTILLERY',{q:0,r:2})],2722);bid=declare(s);setActiveViewer(s,S);p=createPresentationState();p.selectedBattleId=bid;assert(s.state.pendingDecision.eligibleArtilleryUnitIds.includes('sa'));useDefenderArtillery(s,p,'sa');assert.equal(s.lastResult.accepted,true);passCombatReaction(s,p);assert.equal(s.state.combatTransactions[bid].context.modifiers.defenderArtilleryShift,-1);
});

test('Loss Allocation player choice draft is non-mutating; accepted allocation comes only from Core result',()=>{
  const s=fixture([unit('g1','G-INF','GERMAN','INFANTRY',{q:-1,r:0}),unit('g2','G-INF','GERMAN','INFANTRY',{q:0,r:-1}),unit('d','S-ELITE','SOVIET','ELITE_INFANTRY',{q:0,r:0})],11);const bid=declare(s,['g1','g2']);passReactionCore(s,bid);assert.equal(s.state.pendingDecision.kind,'LOSS_ALLOCATION');assert.equal(s.state.pendingDecision.side,'GERMAN');setActiveViewer(s,G);const p=createPresentationState();p.selectedBattleId=bid;const before=cloneState(s);appendLossDraft(s,p,'g1');assert.equal(cloneState(s),before);commitLosses(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.units.g1.step,1);assert.equal(s.state,s.lastResult.state);
});

test('Unique loss auto-resolves without fabricating a loss dialog',()=>{
  const s=fixture([unit('g','G-INF','GERMAN','INFANTRY',{q:-1,r:0}),unit('d','S-ELITE','SOVIET','ELITE_INFANTRY',{q:0,r:0})],22);const bid=declare(s);passReactionCore(s,bid);assert.equal(s.state.units.g.step,1);assert.equal(s.state.pendingDecision,null);assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');assert(s.lastResult.events.some(e=>e.type==='LossesAllocated'&&e.automatic===true));
});

function retreatFixture(seed=5392,block=false){const units=[unit('g','G-INF','GERMAN','INFANTRY',{q:-1,r:0}),unit('d','S-ELITE','SOVIET','ELITE_INFANTRY',{q:0,r:0})];if(block)units.push(unit('b1','G-INF','GERMAN','INFANTRY',{q:1,r:0}),unit('b2','G-INF','GERMAN','INFANTRY',{q:1,r:-1}),unit('b3','G-INF','GERMAN','INFANTRY',{q:0,r:-1}),unit('b4','G-INF','GERMAN','INFANTRY',{q:-1,r:1}),unit('b5','G-INF','GERMAN','INFANTRY',{q:0,r:1}));return fixture(units,seed);}

test('Retreat path draft and Advance After Combat accept use ordered real Core actions',()=>{
  const s=retreatFixture();const bid=declare(s);passReactionCore(s,bid);assert.equal(s.state.pendingDecision.kind,'RETREAT');const p=createPresentationState();p.selectedBattleId=bid;setActiveViewer(s,S);selectRetreater(p,'d');const before=cloneState(s);const step=getLegalRetreatStepOptions(s.state,s.rules,s.state.units.d)[0];extendRetreatDraft(s,p,step);assert.equal(cloneState(s),before);commitRetreat(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.pendingDecision.kind,'ADVANCE_AFTER_COMBAT');setActiveViewer(s,G);advanceAfterCombat(s,p,'g');assert.equal(s.lastResult.accepted,true);assert.deepEqual(s.state.units.g.hex,{q:0,r:0});assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');
});

test('Pass Advance and retreat-impossible extra-loss branches are driven by Core',()=>{
  let s=retreatFixture();let bid=declare(s);passReactionCore(s,bid);setActiveViewer(s,S);let d=s.state.units.d;let step=getLegalRetreatStepOptions(s.state,s.rules,d)[0];let r=dispatchGameAction(s,{type:'RETREAT',controllerId:S,battleId:bid,retreats:[{unitId:'d',path:[step]}]});assert(r.result.accepted);setActiveViewer(s,G);const p=createPresentationState();p.selectedBattleId=bid;passAdvance(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');
  s=retreatFixture(5392,true);bid=declare(s);passReactionCore(s,bid);assert.equal(s.state.pendingDecision.kind,'RETREAT');assert.equal(s.state.pendingDecision.side,'SOVIET');setActiveViewer(s,S);r=dispatchGameAction(s,{type:'RETREAT',controllerId:S,battleId:bid,retreats:[{unitId:'d',path:[]}]});assert.equal(r.result.accepted,true,JSON.stringify(r.result.issues));assert(r.result.events.some(e=>e.type==='RetreatImpossible'));assert.equal(s.state.combatTransactions[bid].retreatImpossibleExtraLossApplied,true);
});

function d2rFixture(){return fixture([unit('p','G-PANZER','GERMAN','PANZER',{q:-1,r:0}),unit('d','S-TANK','SOVIET','TANK',{q:0,r:0}),unit('d2','S-INF','SOVIET','INFANTRY',{q:2,r:0})],8246);}
function reachBreakthrough(s){const bid=declare(s,['p']);passReactionCore(s,bid);assert.equal(s.state.combatTransactions[bid].resolution.crtResult,'D2R');const d=s.state.units.d;const first=getLegalRetreatStepOptions(s.state,s.rules,d).find(h=>key(h)!=='1,0')??getLegalRetreatStepOptions(s.state,s.rules,d)[0];const sim=structuredClone(s.state);sim.units.d.hex={...first};const second=getLegalRetreatStepOptions(sim,s.rules,sim.units.d,first)[0];let r=dispatchGameAction(s,{type:'RETREAT',controllerId:S,battleId:bid,retreats:[{unitId:'d',path:[first,second]}]});assert.equal(r.result.accepted,true,JSON.stringify(r.result.issues));setActiveViewer(s,G);r=dispatchGameAction(s,{type:'ADVANCE_AFTER_COMBAT',controllerId:G,battleId:bid,unitId:'p'});assert(r.result.accepted);assert.equal(s.state.pendingDecision.kind,'BREAKTHROUGH_OPTION');return bid;}

test('Breakthrough movement and Pass Breakthrough both follow real transaction state',()=>{
  let s=d2rFixture();let bid=reachBreakthrough(s);let p=createPresentationState();p.selectedBattleId=bid;selectBreakthroughUnit(p,'p');const before=cloneState(s);const model=deriveBrowserRenderModel(s,p);const opt=model.combat.breakthrough.options.find(o=>o.legal);assert(opt);extendBreakthroughDraft(s,p,opt.hex);assert.equal(cloneState(s),before);commitBreakthrough(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.pendingDecision?.kind,'SCHWERPUNKT_OPTION');
  s=d2rFixture();bid=reachBreakthrough(s);p=createPresentationState();p.selectedBattleId=bid;passBreakthrough(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');
});

test('Natural Schwerpunkt creates child combat; Pass Schwerpunkt closes source without child',()=>{
  let s=d2rFixture();let bid=reachBreakthrough(s);let p=createPresentationState();p.selectedBattleId=bid;selectBreakthroughUnit(p,'p');let model=deriveBrowserRenderModel(s,p);let opt=model.combat.breakthrough.options.find(o=>o.legal&&key(o.hex)==='1,0')??model.combat.breakthrough.options.find(o=>o.legal);assert(opt);extendBreakthroughDraft(s,p,opt.hex);commitBreakthrough(s,p);assert.equal(s.state.pendingDecision.kind,'SCHWERPUNKT_OPTION');const pHex=s.state.units.p.hex;const target=getNeighbors(pHex).find(h=>Object.values(s.state.units).some(u=>u.alive&&u.side==='SOVIET'&&key(u.hex)===key(h)));assert(target,'fixture needs adjacent second Soviet target');selectSchwerpunktTarget(p,target);commitSchwerpunkt(s,p,'p');assert.equal(s.lastResult.accepted,true,JSON.stringify(s.lastResult.issues));const child=s.lastResult.battleId;assert(child&&child!==bid);assert.equal(s.state.combatTransactions[child].sourceBattleId,bid);assert.equal(s.state.pendingDecision.kind,'DEFENDER_REACTION');assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');
  s=d2rFixture();bid=reachBreakthrough(s);p=createPresentationState();p.selectedBattleId=bid;selectBreakthroughUnit(p,'p');model=deriveBrowserRenderModel(s,p);opt=model.combat.breakthrough.options.find(o=>o.legal);extendBreakthroughDraft(s,p,opt.hex);commitBreakthrough(s,p);assert.equal(s.state.pendingDecision.kind,'SCHWERPUNKT_OPTION');passSchwerpunkt(s,p);assert.equal(s.lastResult.accepted,true);assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');assert.equal(s.state.combatTransactions[bid].schwerpunkt.childBattleId,null);
});

// Real production 20x32 smoke.
const raw=JSON.parse(await readFile(new URL('../vendor/eastfront-digital-core/reference/strategic-reset-f-map.json',import.meta.url),'utf8'));
function deployProductionSide(s,side,special={}){const cid=controllerIdForSide(s,side),ids=s.scenario.deployment.units.filter(u=>u.side===side).map(u=>u.id).sort(),zone=deploymentHexKeysForSide(s.state,s.scenario,side),counts={};for(const [id,k] of Object.entries(special)){const r=dispatchGameAction(s,{type:'DEPLOY_INITIAL_UNIT',controllerId:cid,deploymentUnitId:id,hex:s.state.hexes[k].coord});assert(r.result.accepted,JSON.stringify(r.result.issues));counts[k]=(counts[k]??0)+1;}for(const id of ids){if(id in special)continue;let k=zone.find(x=>(counts[x]??0)<2&&!Object.values(special).includes(x))??zone.find(x=>(counts[x]??0)<2);const r=dispatchGameAction(s,{type:'DEPLOY_INITIAL_UNIT',controllerId:cid,deploymentUnitId:id,hex:s.state.hexes[k].coord});assert(r.result.accepted,JSON.stringify(r.result.issues));counts[k]=(counts[k]??0)+1;}}

test('real production map declares and resolves one complete combat transaction to CLOSED',()=>{
  const s=createLocalGameSession(raw,17);deployProductionSide(s,'SOVIET',{'S-I-01':'3,-1'});let r=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:S});assert(r.result.accepted);setActiveViewer(s,G);deployProductionSide(s,'GERMAN',{'G-PZ-01':'2,-1'});r=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:G});assert(r.result.accepted);r=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:G});assert(r.result.accepted);r=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:G});assert(r.result.accepted);assert.equal(s.state.phase,'GERMAN_COMBAT');const action={type:'ATTACK',controllerId:G,attackerUnitIds:['G-PZ-01'],target:{q:3,r:-1}};assert.equal(validateAttackAction(s.state,s.rules,action).length,0);r=dispatchGameAction(s,action);assert(r.result.accepted);const bid=r.result.battleId;setActiveViewer(s,S);r=dispatchGameAction(s,{type:'PASS_REACTION',controllerId:S,battleId:bid});assert(r.result.accepted);while(s.state.pendingDecision){const p=s.state.pendingDecision;if(p.kind==='LOSS_ALLOCATION'){setActiveViewer(s,p.decisionOwnerControllerId);const seq=[];for(let i=0;i<p.lossSteps;i++)seq.push(p.eligibleUnitIds[i%p.eligibleUnitIds.length]);r=dispatchGameAction(s,{type:'ALLOCATE_LOSSES',controllerId:p.decisionOwnerControllerId,battleId:bid,unitIdsByStep:seq});}else if(p.kind==='RETREAT'){setActiveViewer(s,p.decisionOwnerControllerId);const retreats=p.unitIds.map(id=>{const u=s.state.units[id];const path=[];let sim=structuredClone(s.state),from={...u.hex};for(let i=0;i<p.retreatSteps;i++){const o=getLegalRetreatStepOptions(sim,s.rules,sim.units[id],from);if(!o.length)break;const h=o[0];path.push(h);sim.units[id].hex={...h};from={...h};}return {unitId:id,path};});r=dispatchGameAction(s,{type:'RETREAT',controllerId:p.decisionOwnerControllerId,battleId:bid,retreats});}else if(p.kind==='ADVANCE_AFTER_COMBAT'){setActiveViewer(s,p.decisionOwnerControllerId);r=dispatchGameAction(s,{type:'PASS_ADVANCE',controllerId:p.decisionOwnerControllerId,battleId:bid});}else if(p.kind==='BREAKTHROUGH_OPTION'){setActiveViewer(s,p.decisionOwnerControllerId);r=dispatchGameAction(s,{type:'PASS_BREAKTHROUGH',controllerId:p.decisionOwnerControllerId,battleId:bid});}else if(p.kind==='SCHWERPUNKT_OPTION'){setActiveViewer(s,p.decisionOwnerControllerId);r=dispatchGameAction(s,{type:'PASS_SCHWERPUNKT',controllerId:p.decisionOwnerControllerId,battleId:bid});}else throw new Error(`Unhandled ${p.kind}`);assert(r.result.accepted,JSON.stringify(r.result.issues));}
  assert.equal(s.state.combatTransactions[bid].stage,'CLOSED');assert.equal(validateGameStateIntegrity(s.state,s.rules,s.scenario).length,0);
});

test('UI-005 keeps frozen geometry SHA exactly locked',async()=>{const bytes=await readFile(new URL('../src/geometry/hex.ts',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),'283b0445e3bff1bc412dd76536ce49e517ffa1dd35dc26c1f8c194b88ba9ab7a');});
