import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {deploymentHexKeysForSide} from '../dist/vendor/eastfront-digital-core/dist/index.js';
import {controllerIdForSide,dispatchGameAction,setActiveViewer} from '../dist/app/core-adapter/session.js';
import {createFreshProductionSession,defaultMapViewport} from '../dist/app/web/preview.js';
import {beginMapGesture,clampMapViewport,dragSuppressesTap,gesturePanViewport,mapPanBounds,MAP_DRAG_THRESHOLD_PX,updateMapGesture} from '../dist/app/web/mapInteraction.js';
import {createPresentationState} from '../dist/app/state/presentation.js';
import {deriveBrowserRenderModel} from '../dist/app/render/coreModel.js';
import {coreSvgDynamicMarkup,coreSvgStaticMarkup} from '../dist/app/render/coreSvg.js';
import {deploySelectedUnit,selectDeploymentRosterUnit} from '../dist/app/interaction/intents.js';

const raw=JSON.parse(await readFile(new URL('../vendor/eastfront-digital-core/reference/strategic-reset-f-map.json',import.meta.url),'utf8'));
const mainSource=await readFile(new URL('../src/main.ts',import.meta.url),'utf8');
const css=await readFile(new URL('../styles.css',import.meta.url),'utf8');
const stateJson=s=>JSON.stringify(s.state);
const prodOpts=s=>({debug:false,rendererMode:'production',assetSet:'p5',lod:'medium',scenarioSeed:s.state.random.seed});
function deployAll(s,side){const cid=controllerIdForSide(s,side),ids=s.scenario.deployment.units.filter(u=>u.side===side).map(u=>u.id).sort(),zone=deploymentHexKeysForSide(s.state,s.scenario,side),counts={};for(const id of ids){const key=zone.find(k=>(counts[k]??0)<s.rules.stackingLimit);const r=dispatchGameAction(s,{type:'DEPLOY_INITIAL_UNIT',controllerId:cid,deploymentUnitId:id,hex:s.state.hexes[key].coord});assert(r.result.accepted);counts[key]=(counts[key]??0)+1;}}

test('UI009R1 pointerdown alone remains TAP candidate and does not start drag',()=>{const g=beginMapGesture(7,100,100,defaultMapViewport());assert.equal(g.dragging,false);assert.equal(dragSuppressesTap(g),false);});
test('UI009R1 movement at or below 6 CSS px remains TAP',()=>{const g=beginMapGesture(7,100,100,defaultMapViewport());assert.equal(MAP_DRAG_THRESHOLD_PX,6);assert.equal(updateMapGesture(g,106,100).dragging,false);assert.equal(updateMapGesture(g,103,104).dragging,false);});
test('UI009R1 movement above threshold becomes DRAG and suppresses tap',()=>{const g=updateMapGesture(beginMapGesture(7,100,100,defaultMapViewport()),107,100);assert.equal(g.dragging,true);assert.equal(dragSuppressesTap(g),true);});
test('UI009R1 pointercancel semantics never convert a drag into a click suppression leak',()=>{const g=updateMapGesture(beginMapGesture(7,100,100,defaultMapViewport()),120,100);assert.equal(dragSuppressesTap(g,true),false);});
test('UI009R1 zoom=1 still allows pan when rendered map content is larger than viewport',()=>{const b=mapPanBounds({viewportWidth:800,viewportHeight:600,contentWidth:1200,contentHeight:900},1);assert.deepEqual({maxX:b.maxX,maxY:b.maxY},{maxX:200,maxY:150});const c=clampMapViewport({zoom:1,panX:500,panY:-500},{viewportWidth:800,viewportHeight:600,contentWidth:1200,contentHeight:900});assert.deepEqual(c,{zoom:1,panX:200,panY:-150});});
test('UI009R1 map smaller than viewport stays centered on that axis',()=>{const c=clampMapViewport({zoom:1,panX:70,panY:-70},{viewportWidth:1000,viewportHeight:800,contentWidth:700,contentHeight:500});assert.deepEqual(c,{zoom:1,panX:0,panY:0});});
test('UI009R1 zoom recomputes pan range from rendered content bounds',()=>{const metrics={viewportWidth:800,viewportHeight:600,contentWidth:800,contentHeight:500};assert.equal(mapPanBounds(metrics,1).maxX,0);assert.equal(mapPanBounds(metrics,1.5).maxX,200);assert.equal(mapPanBounds(metrics,1.5).maxY,75);});
test('UI009R1 resize recomputes pan clamp rather than retaining stale zoom-only bounds',()=>{const v={zoom:1.5,panX:240,panY:140};const wide=clampMapViewport(v,{viewportWidth:1000,viewportHeight:800,contentWidth:900,contentHeight:700});const narrow=clampMapViewport(v,{viewportWidth:700,viewportHeight:500,contentWidth:900,contentHeight:700});assert.notDeepEqual(wide,narrow);assert.equal(narrow.panX,240);assert.equal(narrow.panY,140);});
test('UI009R1 pan arithmetic is presentation-only and cannot mutate authoritative GameState',()=>{const s=createFreshProductionSession(raw,17),before=stateJson(s),g=updateMapGesture(beginMapGesture(1,0,0,{zoom:1.4,panX:0,panY:0}),80,50);const proposed=gesturePanViewport(g,80,50,1.4);clampMapViewport(proposed,{viewportWidth:700,viewportHeight:500,contentWidth:1000,contentHeight:800});assert.equal(stateJson(s),before);});
test('UI009R1 unit selection changes dynamic layer but leaves static production terrain markup byte-identical',()=>{const s=createFreshProductionSession(raw,17),p=createPresentationState(false,false),m0=deriveBrowserRenderModel(s,p),static0=coreSvgStaticMarkup(m0,prodOpts(s)),dynamic0=coreSvgDynamicMarkup(m0,prodOpts(s));p.selectedDeploymentUnitId='S-I-01';const m1=deriveBrowserRenderModel(s,p),static1=coreSvgStaticMarkup(m1,prodOpts(s)),dynamic1=coreSvgDynamicMarkup(m1,prodOpts(s));assert.equal(static1,static0);assert.equal(dynamic1,dynamic0);});
test('UI009R1 accepted deployment changes dynamic map only while static terrain remains byte-identical',()=>{const s=createFreshProductionSession(raw,17),p=createPresentationState(false,false),m0=deriveBrowserRenderModel(s,p),static0=coreSvgStaticMarkup(m0,prodOpts(s));selectDeploymentRosterUnit(p,'S-I-01');const key=deploymentHexKeysForSide(s.state,s.scenario,'SOVIET')[0];deploySelectedUnit(s,p,s.state.hexes[key].coord);assert.equal(s.lastResult.accepted,true);const m1=deriveBrowserRenderModel(s,p);assert.equal(coreSvgStaticMarkup(m1,prodOpts(s)),static0);assert(coreSvgDynamicMarkup(m1,prodOpts(s)).includes('data-unit-id="S-I-01"'));});
test('UI009R1 deployment continues through formal DEPLOY_INITIAL_UNIT Core Action',()=>{const s=createFreshProductionSession(raw,17),p=createPresentationState(false,false),key=deploymentHexKeysForSide(s.state,s.scenario,'SOVIET')[0];selectDeploymentRosterUnit(p,'S-I-01');deploySelectedUnit(s,p,s.state.hexes[key].coord);assert.equal(s.lastResult.action.type,'DEPLOY_INITIAL_UNIT');assert.equal(s.lastResult.accepted,true);assert.equal(s.state.units['S-I-01'].hex.q,s.state.hexes[key].coord.q);assert.equal(s.state.units['S-I-01'].hex.r,s.state.hexes[key].coord.r);});
test('UI009R1 hidden Soviet deployment remains zero-leak after handoff',()=>{const s=createFreshProductionSession(raw,17);deployAll(s,'SOVIET');let r=dispatchGameAction(s,{type:'READY_FOR_PHASE_END',controllerId:controllerIdForSide(s,'SOVIET')});assert(r.result.accepted);setActiveViewer(s,controllerIdForSide(s,'GERMAN'));const m=deriveBrowserRenderModel(s,createPresentationState());assert.equal(m.counters.some(c=>c.side==='SOVIET'),false);});
test('UI009R1 drag suppression is map-local and map touch-action does not disable the whole page',()=>{assert(mainSource.includes("wrap.addEventListener('click'"));assert(mainSource.includes('stopImmediatePropagation'));assert(css.includes('.map-wrap{')&&css.includes('touch-action:none'));assert.equal(/body\s*\{[^}]*touch-action\s*:\s*none/s.test(css),false);});
test('UI009R1 frozen Core, Geometry and P5R1 remain exact',async()=>{const baseline=(await readFile(new URL('../vendor/eastfront-digital-core/BASELINE_SHA256.txt',import.meta.url),'utf8')).trim().split(/\s+/)[0];assert.equal(baseline,'b157991005b04e339ed0911a8e9dfdd9a7ab5f901cba1fc03f72f293b2dd5609');const geometry=await readFile(new URL('../src/geometry/hex.ts',import.meta.url));assert.equal(createHash('sha256').update(geometry).digest('hex'),'283b0445e3bff1bc412dd76536ce49e517ffa1dd35dc26c1f8c194b88ba9ab7a');const s02=await readFile(new URL('../dist/assets/terrain/p4r3/city/small/S02.png',import.meta.url));assert.equal(createHash('sha256').update(s02).digest('hex'),'914593e3fb5c28b412fd0aff47418728f9ff360fce19659f63b870352890c55e');});
