// English is the complete fallback catalog. Keys are independent of Core identifiers.
export const enUS = {
    "combat.flow.allocateHelp": "Choose units to take {steps} loss step(s). Apply automatically when all steps are assigned.",
    "combat.flow.preview": "Combat preview",
    "combat.flow.advanced": "Advanced options",
    "combat.flow.majorModifiers": "Main modifiers",
    "combat.flow.noModifiers": "No column shifts",
    "combat.flow.crtTable": "Full combat results table",
    "combat.flow.diceTotal": "Dice total",
    "combat.flow.completed": "Battle complete · {result}. Continue on the map.",
    "combat.flow.defender": "Choose defensive support, or decline remaining support.",
    "combat.flow.declineSupport": "Decline remaining support",
    "combat.flow.lastStand": "Last Stand · {id}",
    "combat.flow.retreat": "Choose retreat destination",
    "combat.flow.retreatHelp": "Click a highlighted map hex for {id}. Retreat is applied when all routes are complete.",
    "combat.flow.retreatHex": "Retreat to {hex}",
    "combat.flow.retreatOrder": "Choose the next retreating unit; order can affect available destinations.",
    "combat.flow.advance": "Choose advance destination",
    "combat.flow.chooseAdvancer": "Choose an advancing unit, then click the highlighted map hex, or decline advance.",
    "combat.flow.advanceHelp": "Click the highlighted hex to advance {id}, or decline advance.",
    "combat.flow.advanceHex": "Advance to {hex}",
    "combat.flow.advancer": "Advancing unit · {id}",
    "combat.flow.resultDetails": "Result and modifier details",
    "combat.flow.unitDetails": "Unit details",
    "combat.flow.ready": "Review the preview, then attack.",
    "combat.flow.breakthrough": "Choose a unit and plan its breakthrough on the map, or decline. Up to {max} hexes.",
    "combat.flow.schwerpunkt": "Schwerpunkt available: choose a highlighted enemy, then the attacking unit.",
    "combat.flow.targetHex": "Attack target {hex}",
    "game.newGame": "NEW GAME",
    "game.loading": "Loading EASTFRONT…",
    "game.preparing": "Preparing Strategic Reset F and production assets.",
    "game.title": "Operational Hex Wargame",
    "game.description": "A hot-seat operational campaign on the Strategic Reset F 20×32 map.",
    "game.advisory": "For the best experience, use landscape or a larger screen.",
    "game.controls": "About / Controls",
    "game.controlsHelp": "Tap counters and highlighted Hexes to act. Drag the map to pan; use + / − to zoom. Hidden deployment uses pass-device privacy handoffs.",
    "game.unableToStart": "Unable to start EASTFRONT",
    "game.reload": "RELOAD",
    "game.over": "GAME OVER",
    "game.noWinner": "No Winner",
    "game.noVictoryReason": "No victory reason supplied by Core.",
    "game.finished": "Authoritative Core victory state · no further actions",
    "game.restartTitle": "Start a fresh production game",
    "game.panel": "PANEL",
    "game.preview": "WEB PREVIEW",
    "game.webPreview": "EASTFRONT Web Preview",
    "game.command": "EASTFRONT · Operational Command",
    "game.noMap": "Production map surface is unavailable.",
    "game.noResources": "Required production resources could not be initialized.",
    "game.noSession": "No active production session.",
    "campaign.name": "STRATEGIC RESET F",
    "map.title": "Strategic Reset F · Operations map",
    "map.accessible": "Strategic Reset F operational map",
    "map.eastfront": "EASTFRONT operational map",
    "map.zoomControls": "Map zoom controls",
    "map.zoomOut": "Zoom out",
    "map.zoomIn": "Zoom in",
    "map.fitLabel": "Fit map",
    "map.fit": "FIT",
    "common.yes": "YES",
    "common.no": "NO",
    "common.unknown": "Unknown",
    "common.undo": "UNDO",
    "common.clear": "CLEAR",
    "common.commit": "COMMIT",
    "common.undoStep": "UNDO STEP",
    "common.available": "Available",
    "common.delayed": "Delayed",
    "common.position": "Position",
    "common.status": "Status",
    "common.phase": "PHASE",
    "common.advancePhase": "Advance phase",
    "common.legal": "Core preview: legal",
    "common.target": "Target",
    "common.terrain": "Terrain",
    "common.attack": "Attack",
    "common.defense": "Defense",
    "common.movement": "Movement",
    "common.supply": "Supply",
    "common.turn": "TURN",
    "common.selectUnit": "Select one of your units to begin.",
    "unit.inspect": "Select a unit to inspect strength, supply and movement.",
    "unit.entrenchedSuffix": " · Entrenched",
    "unit.infantryDescription": "Infantry formation",
    "unit.eliteDescription": "Elite infantry formation",
    "unit.jagerDescription": "Light infantry formation",
    "unit.panzerDescription": "Armored formation",
    "unit.tankDescription": "Tank formation",
    "unit.heavyDescription": "Heavy tank formation",
    "unit.artilleryDescription": "Artillery support",
    "unit.engineerDescription": "Engineer support",
    "unit.reconDescription": "Reconnaissance formation",
    "unit.motorizedDescription": "Motorized formation",
    "unit.atDescription": "Anti-tank formation",
    "unit.hqDescription": "Headquarters",
    "deployment.onMap": "ON MAP",
    "deployment.reserve": "RESERVE",
    "deployment.complete": "Complete",
    "deployment.placeAll": "Place all units",
    "deployment.selectUnit": "Select unit",
    "deployment.choosePosition": "Choose position",
    "deployment.deploy": "Deploy",
    "deployment.begin": "Choose a reserve unit to begin deployment.",
    "deployment.confirmPhase": "Confirm deployment",
    "deployment.hidden": "Viewer is not the active deployment side. Enemy setup remains hidden by the Core projection.",
    "deployment.chooseTerrain": "Choose deployment terrain",
    "deployment.chooseDestination": "Choose a destination",
    "deployment.confirm": "CONFIRM DEPLOYMENT",
    "deployment.deployed": "DEPLOYED",
    "deployment.cannotDeploy": "CANNOT DEPLOY",
    "deployment.readyToConfirm": "READY TO CONFIRM",
    "deployment.noVisibleUnits": "No visible units",
    "deployment.submitting": "DEPLOYING…",
    "deployment.stackLimit": "Maximum units reached. Choose another position.",
    "deployment.invalidHex": "This position is outside your deployment area. Choose a highlighted position.",
    "deployment.unavailable": "This unit is unavailable. Select another reserve unit.",
    "deployment.wrongPhase": "Deployment is no longer active.",
    "deployment.wrongSide": "Wait for your side’s deployment phase.",
    "deployment.invalidController": "Your side could not be identified. Return to the current player’s view.",
    "deployment.rejected": "This deployment could not be completed. Choose another unit or position and try again.",
    "deployment.retry": "This deployment could not be completed. Please select the unit and position again.",
    "combat.mode": "COMBAT · ATTACK MODE",
    "combat.chooseEnemy": "Choose a highlighted enemy on the map.",
    "combat.review": "Review the attack, then confirm.",
    "combat.selectAttacker": "Select attacker",
    "combat.selectEnemy": "Select enemy target",
    "combat.versus": "VS",
    "combat.odds": "Combat odds",
    "combat.modifiers": "Modifiers",
    "combat.previewHelp": "Preview before defender reaction. Dice determine the result.",
    "combat.attack": "ATTACK",
    "combat.advanced": "Add supporting units / Advanced",
    "combat.advancedHelp": "Select additional direct attackers. The Core validates the combined attack.",
    "combat.noArtillery": "No Artillery",
    "combat.clear": "Clear attack selection",
    "combat.detailsSummary": "CRT / Combat details",
    "combat.endPhase": "End combat phase",
    "combat.details": "COMBAT DETAILS",
    "combat.resolvedContext": "RESOLVED COMBAT CONTEXT",
    "combat.baseOdds": "Base odds",
    "combat.baseColumn": "Base column",
    "combat.finalShift": "Final shift",
    "combat.finalCRT": "Final CRT",
    "combat.rawCapped": "Raw / capped",
    "combat.river": "River",
    "combat.engineer": "Engineer",
    "combat.combinedArms": "Combined Arms",
    "combat.armorPenalty": "Armor penalty",
    "combat.antiTank": "AT",
    "combat.attackerArtillery": "Attacker Artillery",
    "combat.defenderArtillery": "Defender Artillery",
    "combat.flank": "Flank",
    "combat.entrenchment": "Entrenchment",
    "combat.hq": "HQ",
    "combat.secondAttack": "Second attack",
    "combat.history": "BATTLE HISTORY",
    "combat.battle": "Battle",
    "combat.decisionOwner": "Decision owner",
    "combat.defenderHelp": "Defender reaction window. Choose eligible defensive artillery or pass to resolve Core dice/CRT.",
    "combat.noDefensiveArtillery": "No eligible defensive artillery.",
    "combat.passReaction": "PASS REACTION / RESOLVE",
    "combat.noLossDraft": "No drafted losses",
    "combat.commitLosses": "COMMIT LOSSES",
    "combat.noRetreatStep": "No further legal step shown for this unit. Review the other units before committing.",
    "combat.commitRetreat": "COMMIT RETREAT",
    "combat.advanceHelp": "Advance into the vacated combat target, or pass.",
    "combat.passAdvance": "PASS ADVANCE",
    "combat.noBreakthroughDraft": "No extra Hex drafted",
    "combat.passBreakthrough": "PASS ALL BREAKTHROUGH",
    "combat.schwerpunktHelp": "Optional German Schwerpunkt second attack. Select adjacent highlighted Soviet target.",
    "combat.passSchwerpunkt": "PASS SCHWERPUNKT",
    "combat.resolvedCRT": "RESOLVED CORE CRT",
    "combat.crt": "CRT",
    "combat.attackerLoss": "Attacker loss",
    "combat.defenderLoss": "Defender loss",
    "combat.defenderRetreat": "Defender retreat",
    "combat.submitting": "Submitting attack…",
    "rail.title": "GERMAN SUPPLY / RAIL",
    "rail.help": "Optional Rail Repair uses real Core railway edges. Ready skips repair.",
    "rail.plan": "Plan",
    "rail.used": "Repair used",
    "rail.mode": "RAIL REPAIR MODE",
    "rail.noEngineer": "No Engineer",
    "rail.clear": "CLEAR PLAN",
    "rail.commit": "COMMIT REPAIR",
    "movement.title": "MOVEMENT",
    "movement.help": "Select a controlled unit, then tap adjacent Hexes to draft a path. The Counter stays put until Core accepts Commit Move.",
    "movement.path": "Path",
    "movement.mp": "MP",
    "movement.cancel": "CANCEL PATH",
    "movement.commit": "COMMIT MOVE",
    "reinforcement.title": "SOVIET REINFORCEMENT / SUPPLY",
    "reinforcement.required": "Deployable reinforcement remains. Core will reject Ready until it is handled.",
    "reinforcement.none": "No available reinforcements.",
    "reinforcement.entryHelp": "Tap a highlighted East Rail Exit to deploy the selected reinforcement.",
    "reinforcement.selectHelp": "Select a reinforcement to deploy.",
    "reinforcement.delayedPrefix": "DELAYED · ",
    "recovery.title": "RECOVERY",
    "recovery.recovered": "Recovered",
    "recovery.rp": "Side RP",
    "recovery.cost": "Selected cost",
    "recovery.commit": "RECOVER 1 STEP",
    "recovery.help": "Select a damaged controlled unit. Recovery bases are softly outlined on the map.",
    "entrenchment.title": "ENTRENCHMENT",
    "entrenchment.commit": "ENTRENCH UNIT",
    "entrenchment.help": "Select a controlled unit to preview Entrench legality.",
    "panel.title": "COMMAND PANEL",
    "panel.report": "ORDER REPORT",
    "privacy.combatTitle": "COMBAT DECISION HANDOFF",
    "privacy.combatHelp": "Pass device, then continue. GameState is not changed by this gate.",
    "privacy.title": "HOT-SEAT PRIVACY",
    "privacy.sovietLocked": "Soviet deployment locked.",
    "privacy.passGerman": "Pass the device to the German player.",
    "privacy.beginGerman": "BEGIN GERMAN DEPLOYMENT",
    "privacy.deploymentComplete": "DEPLOYMENT COMPLETE",
    "privacy.ready": "Both sides are ready.",
    "privacy.reveal": "The full board will now be revealed for German Turn 1.",
    "privacy.beginTurnOne": "BEGIN TURN 1",
    "privacy.turnTitle": "PLAYER TURN HANDOFF",
    "privacy.turnHelp": "The authoritative GameState is unchanged by this presentation gate.",
    "game.turn": "Turn {turn}",
    "game.restartPrompt": "Start a new game?\nCurrent progress will be lost.",
    "game.resourceFailure": "Required production resources could not be loaded. {detail}",
    "unit.step": "Step {step}",
    "unit.readings": "A {attack} · D {defense} · M {movement}",
    "deployment.title": "{side} DEPLOYMENT",
    "deployment.selectedHelp": "Selected: {id} — choose a terrain card or tap the map, then confirm deployment.",
    "deployment.unitTitle": "{unit} deployment",
    "deployment.terrain": "Terrain · {terrain}",
    "deployment.occupancy": "Occupancy · {occupancy}",
    "deployment.visibleUnits": "{count} visible unit(s)",
    "deployment.position": "Position {position}",
    "deployment.locationsHelp": "{count} zone positions · choose a card to mark it on the map",
    "combat.lastResult": "Last result · {result}",
    "combat.dice": "Dice {die1} + {die2} = {total}",
    "combat.transaction": "COMBAT TRANSACTION · {kind}",
    "combat.artilleryUnit": "ART {id}",
    "combat.allocateHelp": "Allocate {steps} loss step(s). Draft is presentation-only until commit.",
    "combat.capacity": "{id} · cap {count}",
    "combat.retreatHelp": "Required retreat: {steps} step(s). Resolve units in an explicit order.",
    "combat.retreatDestination": "Choose a retreat destination for {id}. Plan each listed unit, then commit all paths.",
    "combat.advanceUnit": "ADVANCE {id}",
    "combat.breakthroughHelp": "Breakthrough path contains only extra Hexes after the original target. Max for selected unit: {max}.",
    "combat.attackWith": "ATTACK WITH {id}",
    "rail.edges": "{count} edges",
    "movement.steps": "{count} steps",
    "map.viewer": "{side} view · {phase}",
    "privacy.combatDecision": "{side} Side decision required.",
    "privacy.continueAs": "CONTINUE AS {side}",
    "privacy.passTurn": "Pass device to {side} side.",
    "privacy.beginTurn": "BEGIN {side} PLAYER TURN",
    "map.deploymentHex": "Deployment hex {hex}",
    "map.legalMove": "Legal move {hex}",
    "map.illegalMove": "Illegal move {hex}",
    "map.railEdge": "Rail edge {edge}",
    "counter.damage": "Damage level {step}",
    "counter.fullStrength": "Full strength",
    "counter.label": "{side} {type} {id}; {status}; attack {attack}, defense {defense}, movement {movement}; {supply}; {count} unit(s) in hex{entrenched}",
    "counter.entrenchedSuffix": "; entrenched",
    "counter.stack": "{count} units in this hex",
    "language.label": "Language",
    "resource.cp": "CP",
    "resource.rp": "RP",
    "faction.german": "German",
    "faction.soviet": "Soviet",
    "unit.infantry": "Infantry",
    "unit.eliteInfantry": "Elite Infantry",
    "unit.jager": "Jäger",
    "unit.armor": "Panzer",
    "unit.tank": "Tank",
    "unit.heavyTank": "Heavy Tank",
    "unit.motorized": "Motorized",
    "unit.artillery": "Artillery",
    "unit.engineer": "Engineer",
    "unit.recon": "Recon",
    "unit.antiTank": "Anti-Tank",
    "unit.hq": "HQ",
    "terrain.plain": "Plain",
    "terrain.forest": "Forest",
    "terrain.hill": "Hill",
    "terrain.rough": "Rough",
    "terrain.marsh": "Marsh",
    "terrain.city": "City",
    "terrain.lake": "Lake",
    "terrain.river": "River",
    "terrain.road": "Road",
    "terrain.railway": "Railway",
    "terrain.hex": "Hex",
    "status.supplied": "Supplied",
    "status.outOfSupply": "Out of Supply",
    "status.entrenched": "Entrenched",
    "status.damaged": "Damaged",
    "status.destroyed": "Destroyed",
    "status.selected": "Selected",
    "status.ready": "Ready",
    "phase.deployment": "Deployment",
    "phase.supplyRail": "Supply / Rail",
    "phase.movement": "Movement",
    "phase.combat": "Combat",
    "phase.reinforcementSupply": "Reinforcement / Supply",
    "phase.recovery": "Recovery",
    "phase.entrenchment": "Entrenchment",
    "phase.gameOver": "Game Over",
    "combat.stage.defenderReaction": "Defender reaction",
    "combat.stage.lossAllocation": "Loss allocation",
    "combat.stage.retreat": "Retreat",
    "combat.stage.advance": "Advance after combat",
    "combat.stage.breakthrough": "Breakthrough option",
    "combat.stage.schwerpunkt": "Schwerpunkt option",
    "combat.stage.closed": "Closed",
    "combat.stage.resolved": "Resolved",
    "combat.stage.declared": "Declared",
    "reinforcement.unresolved": "Unresolved",
    "reinforcement.ambiguous": "Ambiguous",
    "victory.finalCapture": "German capital capture on the final turn",
    "victory.heldCapital": "German capital held through the Soviet turn",
    "victory.defended": "Soviet capital defended to the turn limit",
    "faction.side": "{side} Side",
    "phase.side": "{side} {phase}",
    "feedback.chooseEnemy": "Choose a highlighted enemy to preview your attack.",
    "feedback.noLegalAttack": "This unit has no legal attack available. Select another unit.",
    "feedback.selectDeployment": "Select a deployment unit first.",
    "feedback.deploymentSelected": "Position selected. Confirm to deploy.",
    "feedback.deploymentSelectAgain": "Select a unit and a deployment position again.",
    "feedback.deployedNext": "{id} deployed. Next reserve selected when available.",
    "feedback.deployed": "{id} deployed to {hex}.",
    "feedback.phaseComplete": "{phase} complete.",
    "feedback.deploymentRevealed": "Deployment revealed. German Turn 1.",
    "feedback.sideActive": "{side} interface active.",
    "feedback.developerViewer": "Development viewer switched to {side}.",
    "feedback.selectControlled": "Select a controlled unit first.",
    "feedback.unitUnavailable": "Selected unit is unavailable.",
    "feedback.undoPath": "Removed last path step.",
    "feedback.adjacentOnly": "Path draft can only extend to an adjacent Hex.",
    "feedback.pathDraft": "Path drafted to {hex}. Commit only when ready.",
    "feedback.pathCleared": "Path draft cleared.",
    "feedback.moveCancelled": "Movement draft cancelled.",
    "feedback.needPath": "Draft at least one movement step first.",
    "feedback.moved": "{id} moved to {hex} through {count} step(s).",
    "feedback.railMode": "Tap railway edges to add/remove them from the repair plan.",
    "feedback.notRailway": "That edge is not railway.",
    "feedback.railPlan": "Rail plan: {count} edge(s) selected.",
    "feedback.railCleared": "Rail Repair plan cleared.",
    "feedback.needRail": "Select at least one railway edge.",
    "feedback.railAccepted": "Rail Repair accepted: {count} edge(s).",
    "feedback.needReinforcement": "Select a Soviet reinforcement first.",
    "feedback.reinforced": "{id} deployed at {hex}.",
    "feedback.needDamaged": "Select a damaged controlled unit first.",
    "feedback.recovered": "{id} recovered one damage step.",
    "feedback.entrenched": "{id} entrenched.",
    "feedback.combatAccepted": "{action} accepted by Core.",
    "feedback.pendingCombat": "Resolve the current combat decision before declaring another attack.",
    "feedback.unavailable": "Unit unavailable.",
    "feedback.needAttacker": "Select a controlled attacker.",
    "feedback.attackDraft": "Attack draft: {count} direct attacker(s).",
    "feedback.invalidTarget": "Cannot select attack target: {issues}",
    "feedback.targetSelected": "Target {hex} selected.",
    "feedback.attackCleared": "Attack draft cleared.",
    "feedback.needTarget": "Choose attacker(s) and an enemy target Hex first.",
    "feedback.noReaction": "No defender reaction is pending.",
    "feedback.invalidLossUnit": "Unit is not eligible for this loss allocation.",
    "feedback.lossDraft": "Loss draft: {count}/{steps} step(s).",
    "feedback.undoLoss": "Removed last drafted loss.",
    "feedback.lossCleared": "Loss draft cleared.",
    "feedback.noLoss": "No loss allocation is pending.",
    "feedback.needRetreater": "Choose a required retreater first.",
    "feedback.retreaterUnavailable": "Retreater unavailable.",
    "feedback.retreatComplete": "Required retreat distance already planned. Choose the next unit or commit.",
    "feedback.illegalRetreat": "Core retreat helper marks that next Hex illegal.",
    "feedback.retreatDraft": "{id} retreat draft: {count} step(s).",
    "feedback.noRetreat": "No retreat is pending.",
    "feedback.breakthroughDraft": "Breakthrough draft: {count} extra Hex(es).",
    "action.attack": "Attack",
    "action.pass_reaction": "Pass reaction",
    "action.combat_reaction": "Defender artillery support",
    "action.allocate_losses": "Allocate losses",
    "action.pass_advance": "Pass advance",
    "action.breakthrough": "Breakthrough",
    "action.pass_breakthrough": "Pass breakthrough",
    "action.schwerpunkt_attack": "Schwerpunkt attack",
    "action.pass_schwerpunkt": "Pass Schwerpunkt",
    "error.ACTION_ID_DUPLICATE": "This action has already been submitted.",
    "error.ARTILLERY_ALREADY_USED": "This artillery has already provided support in its current support window.",
    "error.BATTLE_ID_DUPLICATE": "This battle identifier is already in use.",
    "error.CANNOT_ENTRENCH": "This unit type cannot entrench.",
    "error.COMBAT_STAGE_MISMATCH": "This decision does not match the current combat stage.",
    "error.COMBAT_TRANSACTION_NOT_FOUND": "The referenced battle is unavailable.",
    "error.COMMITMENT_NOT_FOUND": "The unit commitment is unavailable.",
    "error.CONTROLLER_ALREADY_READY": "Your side is already ready for this phase.",
    "error.CORE_CANNOT_ENTRENCH": "Capital core hexes cannot be entrenched.",
    "error.DEPLOYMENT_UNIT_UNAVAILABLE": "This deployment unit is unavailable.",
    "error.DUPLICATE_ID": "The selection contains duplicate entries.",
    "error.EMPTY_MOVE_PATH": "Choose at least one movement step.",
    "error.ENEMY_OCCUPIED_HEX": "An enemy unit occupies this location.",
    "error.ENEMY_ZOC_STOP": "Enemy control prevents this action.",
    "error.ENEMY_ZOC_TO_ZOC": "Movement directly between these enemy-controlled hexes is not allowed.",
    "error.HEX_OUT_OF_BOUNDS": "This location is outside the map.",
    "error.HQ_ALREADY_USED": "This HQ has already been used.",
    "error.HQ_OUT_OF_RANGE": "The unit is outside HQ range.",
    "error.IMPASSABLE_TERRAIN": "The terrain cannot be entered.",
    "error.INITIAL_DEPLOYMENT_INCOMPLETE": "Deploy all units legally before ending deployment.",
    "error.INSUFFICIENT_CP": "Not enough command points.",
    "error.INSUFFICIENT_MP": "Not enough movement points.",
    "error.INVALID_ADVANCE": "This advance cannot be completed.",
    "error.INVALID_BATTLE_REFERENCE": "The battle reference is invalid.",
    "error.INVALID_BREAKTHROUGH": "This breakthrough cannot be completed.",
    "error.INVALID_CONTROLLER": "The acting player is invalid.",
    "error.INVALID_DEPLOYMENT_HEX": "This position is not a legal deployment location.",
    "error.INVALID_LOSS_ALLOCATION": "This loss allocation cannot be accepted.",
    "error.INVALID_REACTION": "This defender reaction is not available.",
    "error.INVALID_RETREAT": "This retreat plan cannot be accepted.",
    "error.INVALID_SUPPORT": "The selected units or support do not meet this action's requirements.",
    "error.MOVED_THIS_TURN": "The unit has already moved this turn.",
    "error.NON_ADJACENT_HEX": "The next step must enter an adjacent hex.",
    "error.NOT_ADJACENT_TO_TARGET": "The attacker must be adjacent to the target.",
    "error.NOT_UNIT_CONTROLLER": "You do not control this unit.",
    "error.NO_DEFENDER": "There is no enemy defender in the target hex.",
    "error.PENDING_DECISION_BLOCKS_ACTION": "Complete the pending decision before taking another action.",
    "error.PENDING_DECISION_BLOCKS_PHASE_END": "Complete the pending decision before ending the phase.",
    "error.PENDING_DECISION_CONTROLLER_MISMATCH": "The other player must make this decision.",
    "error.RULE_NOT_IMPLEMENTED": "This action is not supported.",
    "error.SCHWERPUNKT_UNAVAILABLE": "This Schwerpunkt attack is not available.",
    "error.STACKING_LIMIT": "The stacking limit has been reached.",
    "error.UNAUTHORIZED_UNIT_COMMITMENT": "This unit is not authorized for this battle.",
    "error.UNIT_ALREADY_ATTACKED": "The unit has already attacked.",
    "error.UNIT_ALREADY_MOVED": "The unit has already moved.",
    "error.UNIT_DESTROYED": "The unit has been destroyed.",
    "error.UNIT_NOT_FOUND": "The unit cannot be found.",
    "error.WRONG_PHASE": "This action is not available in the current phase.",
    "error.WRONG_SIDE": "It is not this side's turn to act.",
    "error.reason.DEDICATED_RAIL_REPAIR": "This engineer is dedicated to rail repair for the remainder of this turn.",
    "error.reason.DEPLOYABLE_REINFORCEMENT_REMAINS": "Deployable reinforcements must be handled first.",
    "error.reason.GAME_OVER": "The game has ended.",
    "error.reason.INITIAL_DEPLOYMENT": "Only deployment and ending deployment are available now.",
    "error.reason.REINFORCEMENT_ALREADY_DEPLOYED": "This reinforcement has already been deployed.",
    "error.reason.REINFORCEMENT_ENTRY_INACTIVE": "This East Rail Exit is not connected to the active eastern rail network.",
    "error.reason.REINFORCEMENT_ENTRY_IN_GERMAN_ZOC": "This East Rail Exit is in a German control zone.",
    "error.reason.REINFORCEMENT_ENTRY_NOT_EAST_EXIT": "Deploy reinforcements at an East Rail Exit.",
    "error.reason.REINFORCEMENT_NOT_YET_AVAILABLE": "This reinforcement is not yet available.",
    "error.reason.REINFORCEMENT_SLOT_UNKNOWN": "This reinforcement cannot be found.",
    "error.reason.REINFORCEMENT_TEMPLATE_UNRESOLVED": "This reinforcement's unit template is unavailable.",
    "error.reason.REINFORCEMENT_TEMPLATE_AMBIGUOUS": "This reinforcement's unit template cannot be determined.",
    "error.reason.RAIL_REPAIR_ALREADY_USED": "Rail repair has already been used this turn.",
    "error.reason.EMPTY_RAIL_REPAIR_PLAN": "Select at least one railway edge.",
    "error.reason.INVALID_RAIL_ENGINEER": "The selected engineer is not eligible for rail repair support.",
    "error.reason.RAIL_REPAIR_LIMIT_EXCEEDED": "The repair plan exceeds this turn's allowance.",
    "error.reason.UNKNOWN_RAIL_EDGE": "The selected railway edge does not exist.",
    "error.reason.EDGE_HAS_NO_RAILWAY": "There is no railway on this edge.",
    "error.reason.EDGE_ALREADY_GERMAN_REPAIRED": "This railway is already operational for the German side.",
    "error.reason.RAIL_PLAN_DISCONNECTED": "All repairs must connect to the resulting active German rail network.",
    "error.reason.UNIT_NOT_DAMAGED": "A full-strength unit cannot recover.",
    "error.reason.NORMAL_SUPPLY_REQUIRED": "Normal supply is required for recovery.",
    "error.reason.ARTILLERY_USED_THIS_TURN": "A unit that provided artillery support this turn cannot recover.",
    "error.reason.ENEMY_ADJACENT": "A unit adjacent to an enemy cannot recover.",
    "error.reason.RECOVERY_BASE_TOO_FAR": "The unit is outside recovery base range.",
    "error.reason.UNIT_TEMPLATE_NOT_FOUND": "The unit's recovery template is unavailable.",
    "error.reason.INSUFFICIENT_RP": "Not enough replacement points.",
    "error.reason.UNIT_ALREADY_RECOVERED_THIS_TURN": "The unit has already recovered this turn.",
    "error.reason.RECOVERY_UNIT_LIMIT_REACHED": "This turn's recovery unit limit has been reached.",
    "error.support.needAttacker": "Attack requires at least one direct attacker.",
    "error.support.supportOnly": "Support-only unit cannot be a direct attacker.",
    "error.support.attackerArtillery": "Selected attacker artillery is not eligible/ranged/supplied for this target.",
    "error.support.schwerpunktArtillery": "Selected Schwerpunkt artillery is not alive/supplied/eligible/in range.",
    "error.unknown": "This action could not be completed ({code}).",
    "terrain.mainCity": "Main City",
    "terrain.outerCity": "Outer City",
    "status.temporarySupply": "Temporary Supply"
};
