/* ART-PREVIEW-002: preview-only measurement. No Core/session/network access. */
const style=document.createElement('style');style.textContent=`
:root{--preview-reserved:44px;--preview-header:56px;--preview-footer:28px}
#app .workspace{height:calc(100dvh - var(--preview-header) - var(--preview-footer) - var(--preview-reserved))!important;min-height:0!important}
#preview-measure{position:fixed;inset:auto 0 0;z-index:10000;height:var(--preview-reserved);background:#152b34;color:#f1f5f6;border-top:1px solid #a4b7bf;font:13px/1.4 sans-serif;box-sizing:border-box}
#preview-measure>summary{height:44px;min-width:44px;padding:12px;cursor:pointer;color:#f1f5f6}
#preview-measure .measure-body{height:172px;overflow:auto;padding:6px 12px;display:grid;grid-template-columns:minmax(300px,1fr) minmax(260px,1fr);gap:10px}
#preview-measure button,#preview-measure a{min-height:44px;min-width:44px;display:inline-flex;align-items:center;padding:8px;border:1px solid #a4b7bf;background:#29434e;color:#fff;font:inherit;box-sizing:border-box}
#preview-measure button:disabled{background:#263239;color:#bccbd1;border-style:dashed;opacity:1}
#preview-measure textarea{width:100%;height:150px;background:#eef3f4;color:#142b34;font:12px monospace}
#preview-measure p{margin:4px 0;color:#ecf3f5}
`;document.head.append(style);
const box=document.createElement('details');box.id='preview-measure';box.open=false;
box.innerHTML=`<summary>本地规则场景 · 测量工具</summary><div class="measure-body"><div><p>独立预览；RAF不是GPU耗时。首次访问不等于受控冷启动。</p><button id="preview-sample">采集 5 秒：点击后拖动地图</button> <button id="preview-report">读取资源与布局</button> <button id="preview-reload">预热后重新加载</button><p id="preview-sample-status">未采集</p><a href="../index.html" target="_top">返回比较入口</a></div><textarea readonly aria-label="预览测量结果"></textarea></div>`;document.body.append(box);
box.addEventListener('toggle',()=>{document.documentElement.style.setProperty('--preview-reserved',box.open?'216px':'44px');});
const headerObserver=new ResizeObserver(()=>{const h=document.querySelector('.topbar'),f=document.querySelector('#app>footer');if(h)document.documentElement.style.setProperty('--preview-header',h.getBoundingClientRect().height+'px');if(f)document.documentElement.style.setProperty('--preview-footer',f.getBoundingClientRect().height+'px');});
let watched=null,readyMs=null;const watch=new MutationObserver(()=>{const h=document.querySelector('.topbar');if(h&&h!==watched){watched=h;headerObserver.observe(h);}if(document.documentElement.dataset.previewReady==='true'&&readyMs===null)readyMs=performance.now();});watch.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['data-preview-ready']});
let frames=[],sample=null;const interactions=[];
document.addEventListener('click',e=>{const n=e.target.closest?.('button,select,[role="button"]');if(!n||n.closest('#preview-measure'))return;const start=performance.now(),label=n.getAttribute('aria-label')||n.id||n.textContent.trim().slice(0,60);requestAnimationFrame(()=>requestAnimationFrame(()=>{interactions.push({label,clickToSecondRafMs:performance.now()-start});if(interactions.length>30)interactions.shift();}));},true);
function report(){const svg=document.querySelector('#eastfront-map');const bounds=s=>{const n=document.querySelector(s);if(!n)return null;const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,clientWidth:n.clientWidth,scrollWidth:n.scrollWidth,clientHeight:n.clientHeight,scrollHeight:n.scrollHeight,scrollTop:n.scrollTop};};
const resources=performance.getEntriesByType('resource').map(r=>({name:r.name,type:r.initiatorType,duration:r.duration,transferSize:r.transferSize,encodedBodySize:r.encodedBodySize}));
const value={scope:'ART-PREVIEW-002 local rules scene; browser measurement',actualViewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,embedded:window!==window.top},visibility:document.visibilityState,readyMs,navigation:performance.getEntriesByType('navigation').map(n=>({type:n.type,duration:n.duration})),scene:document.documentElement.dataset.previewScene,ready:document.documentElement.dataset.previewReady,viewBox:svg?.getAttribute('viewBox'),camera:svg?.style.transform,modelMode:document.querySelector('#unit-models')?.value,layout:{topbar:bounds('.topbar'),toolbar:bounds('.map-toolbar'),panel:bounds('#side-panel'),map:bounds('#map-wrap'),panelScroll:bounds('.command-panel-scroll'),footer:bounds('#app>footer'),measurement:bounds('#preview-measure')},smallVisibleButtons:[...document.querySelectorAll('button,select,summary')].filter(n=>!n.closest('#preview-measure')&&n.getClientRects().length&&getComputedStyle(n).visibility!=='hidden').map(n=>({id:n.id||n.textContent.trim().slice(0,40),width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})).filter(r=>r.width<44||r.height<44),svgElements:svg?.querySelectorAll('*').length,canvasPresent:!!document.querySelector('#terrain-surface'),resources,raf:sample,interactions,notes:['Second RAF latency is not engine/network completion or GPU timing','Cache not forcibly cleared; transferSize is only a cache hint','If embedded, viewport is the actual iframe window; outer/device acceptance remains separate','Measurement dock reserves layout space; expand/close before comparing']};box.querySelector('textarea').value=JSON.stringify(value,null,2);}
box.querySelector('#preview-report').onclick=report;box.querySelector('#preview-reload').onclick=()=>location.reload();
box.querySelector('#preview-sample').onclick=()=>{const button=box.querySelector('#preview-sample');button.disabled=true;frames=[];let previous=null,start=performance.now();box.querySelector('#preview-sample-status').textContent='采集中：请拖动地图';function tick(now){if(previous!==null)frames.push(now-previous);previous=now;if(now-start<5000){requestAnimationFrame(tick);return;}const sorted=[...frames].sort((a,b)=>a-b);sample={durationMs:now-start,frames:frames.length,meanMs:frames.reduce((a,b)=>a+b,0)/frames.length,p95Ms:sorted[Math.floor(sorted.length*.95)],over33ms:frames.filter(x=>x>33).length};button.disabled=false;box.querySelector('#preview-sample-status').textContent='采集完成';report();}requestAnimationFrame(tick);};
