import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {records} from '../../ai/lab/runner.mjs';
import {atomic} from '../../ai/lab/common.mjs';
const out='evidence/ai-attack-reserve-019',stats=a=>{const s=[...a].sort((a,b)=>a-b);return {n:s.length,mean:s.reduce((a,b)=>a+b,0)/Math.max(1,s.length),p95:s[Math.ceil(s.length*.95)-1]??0,max:s.at(-1)??0,sum:s.reduce((a,b)=>a+b,0)};},games=[];
for(const seed of [1017,1018])for(const version of ['014','017','019']){
 const p=version==='019'?out:'evidence/ai-maneuver-017',a=JSON.parse(readFileSync(`${p}/${seed}-${version}-audit.json`)),dir=version==='014'?`evidence/ai-advance-014/batch/development-${seed}-experiment-GERMAN`:version==='017'?`evidence/ai-maneuver-017/batch/development-${seed}-experiment-GERMAN`:`${out}/batch/development-${seed}-experiment-GERMAN`,rows=records(dir+'/trace.ndjson'),record=JSON.parse(readFileSync(dir+'/record.json'));
 const accepted=rows.filter(r=>r.side==='GERMAN'&&r.result.status==='ACCEPTED'),probes=rows.filter(r=>r.movementProbe?.reserve),blocks=probes.flatMap(r=>r.movementProbe.reserve.checks.filter(c=>c.blocked).map(c=>({n:r.n,turn:r.turn,...c}))),unique=new Set(blocks.flatMap(c=>c.protectedTargets.map(t=>`${c.turn}:${c.intent.unitId}:${t}`)));
 const g={seed,version,status:record.status,winner:record.winner,turn:record.turn,integrity:record.integrity,attacks:accepted.filter(r=>r.choice?.intent?.type==='ATTACK').length,moves:accepted.filter(r=>r.choice?.intent?.type==='MOVE').length,adjacentMoves:a.mobility.acceptedMoves,globalRejects:record.metrics.sides.GERMAN.rejections+record.metrics.sides.SOVIET.rejections,rejectionReasons:record.metrics.rejected,losses:record.metrics.sides,distance:a.final.statistics,distribution:a.final.distribution,fixed:a.final.fixed,cityCounts:a.final.cityCounts,capital:a.final.capitalControlled,elapsedMs:record.elapsedMs,reserve:version==='019'?{blockedCandidates:blocks.length,affectedDecisions:probes.filter(r=>r.movementProbe.reserve.metrics.blocked).length,changedDecisions:probes.filter(r=>r.movementProbe.reserve.changed).length,uniqueUnitTurnTargets:unique.size,unknownDecisions:probes.filter(r=>r.movementProbe.reserve.metrics.unknown).length,checks:stats(probes.map(r=>r.movementProbe.reserve.metrics.checks)),pools:stats(probes.map(r=>r.movementProbe.reserve.metrics.pools)),scored:stats(probes.map(r=>r.movementProbe.reserve.metrics.scored)),guardMs:stats(probes.map(r=>r.movementProbe.reserve.guardMs)),policy019Ms:stats(probes.map(r=>r.policyMs)),sameView017Ms:stats(probes.map(r=>r.movementProbe.reserve.original017Ms)),routeExpanded:stats(probes.map(r=>r.movementProbe.newMetrics.expanded)),routeExhausted:probes.filter(r=>r.movementProbe.newMetrics.exhausted).length,blocks}:null};
 assert.equal(g.integrity,'PASS');games.push(g);
}
atomic(out+'/comparison.json',{newGames:2,baselineGamesRerun:0,classification:'DEVELOPMENT_NOT_HOLDOUT',games});
let md='# AI-ATTACK-RESERVE-019 开发对照\n\n仅019德军1017/1018为本轮新局；014/017读取既有完整记录。拒绝为双方总计；损失为损步数（德/苏）；距离为存活德军到首都核心最近六角距离。保护候选次数含同一单位反复出现，不代表独立战机。\n\n|种子/版本|保护候选/影响决策|攻击|移动/邻敌移动|拒绝|损步 德/苏|平均/最近距离|城格占领/控制|首都控制|自然终局|\n|---|---|---|---|---|---|---|---|---|---|\n';
for(const g of games)md+=`|${g.seed}/${g.version}|${g.reserve?g.reserve.blockedCandidates+'/'+g.reserve.affectedDecisions:'—'}|${g.attacks}|${g.moves}/${g.adjacentMoves}|${g.globalRejects}|${g.losses.GERMAN.lossSteps}/${g.losses.SOVIET.lossSteps}|${g.distance.mean.toFixed(2)}/${g.distance.min}|${g.cityCounts.germanOccupied}/${g.cityCounts.germanControlled}|${g.capital}|${g.status} T${g.turn} ${g.winner}|\n`;
md+='\n|019种子|唯一单位/回合/目标|未知放行决策|保护检查/评分次数总计|保护ms均值/P95/最大|同视图019/017策略ms均值|路线展开最大/耗尽决策|\n|---|---|---|---|---|---|---|\n';
for(const g of games.filter(g=>g.reserve)){const r=g.reserve;md+=`|${g.seed}|${r.uniqueUnitTurnTargets}|${r.unknownDecisions}|${r.checks.sum}/${r.scored.sum}|${r.guardMs.mean.toFixed(3)}/${r.guardMs.p95.toFixed(3)}/${r.guardMs.max.toFixed(3)}|${r.policy019Ms.mean.toFixed(3)}/${r.sameView017Ms.mean.toFixed(3)}|${r.routeExpanded.max}/${r.routeExhausted}|\n`;}
md+='\n计时受JIT、缓存和被动复算顺序影响，仅作本批计算开销诊断，不能作为历史版本速度基准。完整拒绝原因、活单位距离排序、固定四单位位置/状态与逐回合数据见comparison.json及各audit.json；相同种子不保证行动分叉后逐战同骰。\n';
writeFileSync(out+'/comparison.md',md);console.log(md);
