import { getLocale } from '../localization/index.js';
const en = {
    syncing: 'Syncing', submitting: 'Submitting', reconnected: 'Reconnected', outdated: 'State outdated, resyncing', opponentDeploying: 'Opponent is deploying', opponentDecision: 'Waiting for opponent decision', matchLost: 'Match connection lost', waitingReconnect: 'Waiting for opponent to reconnect', aborted: 'Opponent connection timed out or left. Network session ended.', actionRejected: 'Action rejected. Check the current legal options.',
    title: 'Multiplayer', create: 'Create Room', join: 'Join Room', code: 'Room Code', name: 'Nickname',
    germany: 'Germany', soviet: 'Soviet', chooseGermany: 'Choose Germany', chooseSoviet: 'Choose Soviet',
    prepare: 'Ready', ready: 'Ready', notReady: 'Not Ready', unready: 'Cancel Ready', leave: 'Leave Room', back: 'Back',
    waiting: 'Waiting for opponent', empty: 'Available seat', you: 'You', connected: 'Connected',
    connecting: 'Connecting', disconnected: 'Connection interrupted', reconnecting: 'Reconnecting',
    reconnect: 'Reconnect', connect: 'Connect', copy: 'Copy code', copied: 'Copied', copyHelp: 'Select the code to copy it',
    starting: 'Preparing match', created: 'Match created', snapshot: 'Your initial view is ready',
    foundation: 'The room is ready. Online battlefield actions will be available in the next update.',
    activeReconnect: 'Identity restored. Returning to an active battlefield will be available in a later update.',
    noService: 'Multiplayer service is not configured yet.', invalidUrl: 'Multiplayer service address is unavailable.',
    unavailable: 'Unable to connect. Check your connection and try again.', invalidServer: 'Incompatible server response.',
    intro: 'Create a room and share its code with your opponent.', select: 'Choose a side, then confirm you are ready.',
    match: 'Match', roomClosed: 'The room has closed.', pending: 'Waiting for server confirmation',
    'error.BAD_MESSAGE': 'Invalid request.', 'error.VERSION_MISMATCH': 'Client and server versions do not match.',
    'error.UNSUPPORTED_MESSAGE': 'This request is not supported.', 'error.NOT_IDENTIFIED': 'Connect before continuing.',
    'error.ALREADY_IDENTIFIED': 'This connection already has an identity.', 'error.INVALID_TOKEN': 'Your reconnect session has expired. Connect again to create a new identity.',
    'error.SESSION_CONNECTED': 'This player is already connected in another window. Close that connection first.',
    'error.ALREADY_IN_ROOM': 'Leave the current room first.', 'error.ROOM_NOT_FOUND': 'Room not found. Check the room code.',
    'error.ROOM_FULL': 'This room already has two players.', 'error.NOT_IN_ROOM': 'You are no longer in this room.',
    'error.ROOM_PHASE': 'This room has already started or closed.', 'error.SEAT_TAKEN': 'That seat is occupied.',
    'error.NO_SEAT': 'Choose a side before getting ready.', 'error.CAPACITY': 'The server is full. Try again later.',
    'error.RATE_LIMIT': 'Too many requests. Please wait a moment.', 'error.MATCH_FAILED': 'The match could not be created. Please ready up again.',
};
const zh = {
    syncing: '正在同步', submitting: '正在提交', reconnected: '连接已恢复', outdated: '状态已过期，正在重新同步', opponentDeploying: '对方正在部署', opponentDecision: '等待对方决定', matchLost: '对局连接中断', waitingReconnect: '等待对手重新连接', aborted: '对手连接超时或已离开，网络对局已结束。', actionRejected: '操作未被接受，请检查当前合法选项。',
    title: '多人游戏', create: '创建房间', join: '加入房间', code: '房间码', name: '玩家昵称',
    germany: '德国', soviet: '苏联', chooseGermany: '选择德国', chooseSoviet: '选择苏联',
    prepare: '准备', ready: '已准备', notReady: '未准备', unready: '取消准备', leave: '离开房间', back: '返回',
    waiting: '等待对方', empty: '空闲席位', you: '你', connected: '已连接', connecting: '连接中',
    disconnected: '连接中断', reconnecting: '正在重连', reconnect: '重新连接', connect: '连接',
    copy: '复制房间码', copied: '已复制', copyHelp: '可选中房间码进行复制', starting: '正在创建对局',
    created: '对局已创建', snapshot: '已收到你的初始视野',
    foundation: '房间已就绪，联机战场操作将在后续更新中开放。',
    activeReconnect: '身份已恢复，返回进行中的战场将在后续更新中开放。',
    noService: '多人服务尚未配置。', invalidUrl: '多人服务地址不可用。',
    unavailable: '连接失败，请检查网络后重试。', invalidServer: '服务器响应版本不兼容。',
    intro: '创建房间，将房间码分享给对方。', select: '选择阵营后，确认准备。',
    match: '对局', roomClosed: '房间已关闭。', pending: '等待服务器确认',
    'error.BAD_MESSAGE': '请求格式无效。', 'error.VERSION_MISMATCH': '客户端与服务器版本不一致。',
    'error.UNSUPPORTED_MESSAGE': '暂不支持此请求。', 'error.NOT_IDENTIFIED': '请先连接服务器。',
    'error.ALREADY_IDENTIFIED': '当前连接已有玩家身份。', 'error.INVALID_TOKEN': '重连身份已过期，请重新连接以建立新身份。',
    'error.SESSION_CONNECTED': '此玩家已在另一窗口连接，请先关闭原连接。',
    'error.ALREADY_IN_ROOM': '请先离开当前房间。', 'error.ROOM_NOT_FOUND': '找不到房间，请检查房间码。',
    'error.ROOM_FULL': '房间已有两名玩家。', 'error.NOT_IN_ROOM': '你已不在此房间中。',
    'error.ROOM_PHASE': '房间已开始或关闭。', 'error.SEAT_TAKEN': '该席位已被占用。',
    'error.NO_SEAT': '请先选择阵营再准备。', 'error.CAPACITY': '服务器已满，请稍后再试。',
    'error.RATE_LIMIT': '操作太快，请稍后再试。', 'error.MATCH_FAILED': '对局创建失败，请重新准备。',
};
export function mt(key) { return getLocale() === 'zh-CN' ? zh[key] : en[key]; }
export const multiplayerCatalogs = { 'zh-CN': zh, 'en-US': en };
