import type {CityArtView,CityArtSelection} from './cityArtView.js';
import {hexToPixel,hexKey} from '../geometry/hex.js';
import {CITY_ART_VERSION,districtScene,facilityMarkup,cityWallPlan,wallsMarkup,bridgeStateMarkup,railStateMarkup,type CityLod} from './cityArt.js';
import {terrainImageCacheStats} from './terrainSurface.js';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let lastSvg:SVGSVGElement|null=null,lastStamp='';
const cache=new Map<string,string>();let bytes=0,generation=0,timer:ReturnType<typeof setTimeout>|null=null,observer:MutationObserver|null=null,wrap:Element|null=null,lastView:CityArtView|null=null,lastSelect:CityArtSelection=()=>{};
export const CITY_DETAIL_BUDGET={maxVisible:16,maxEntries:48,maxBytes:2*1024*1024,sliceMs:4};
export function disposeCityArt(){lastSvg=null;lastStamp='';generation++;if(timer!==null)clearTimeout(timer);timer=null;observer?.disconnect();observer=null;wrap=null;lastView=null;cache.clear();bytes=0;}
function getScene(d:any,edges:any[],lod:CityLod){const k=JSON.stringify([CITY_ART_VERSION,d.id,d.type,d.hex,d.slots,lod,edges.filter(e=>hexKey(e.a)===d.hex||hexKey(e.b)===d.hex).map(e=>[e.key,e.road,e.railway?.present,e.river])]);let s=cache.get(k);if(s){cache.delete(k);cache.set(k,s);return s;}s=districtScene(d,edges,lod);cache.set(k,s);bytes+=s.length*2;while(cache.size>CITY_DETAIL_BUDGET.maxEntries||bytes>CITY_DETAIL_BUDGET.maxBytes){const [key,value]=cache.entries().next().value!;cache.delete(key);bytes-=value.length*2;}return s;}
function status(svg:SVGSVGElement,pending:number,lod:string){let node=document.querySelector<HTMLElement>('#city-detail-status');if(!node){const toolbar=document.querySelector('.map-toolbar');node=document.createElement('span');node.id='city-detail-status';node.setAttribute('role','status');toolbar?.appendChild(node);}node.textContent=pending?'城区细节加载中':lod==='far'?'':'城区细节已就绪';node.dataset.pending=String(pending);svg.dataset.cityCacheBytes=String(bytes);svg.dataset.cityCacheEntries=String(cache.size);svg.dataset.cityImageCache=JSON.stringify(terrainImageCacheStats());}
export function scheduleCityArt(){if(lastView)paintAuthorizedCities(lastView,lastSelect);}
export function paintAuthorizedCities(data:CityArtView,select:CityArtSelection){const svg=document.querySelector<SVGSVGElement>('#eastfront-map');if(!svg)return;lastView=data;lastSelect=select;const currentWrap=document.querySelector('#map-wrap');if(wrap!==currentWrap){observer?.disconnect();wrap=currentWrap;observer=new MutationObserver(()=>scheduleCityArt());if(wrap)observer.observe(wrap,{attributes:true,attributeFilter:['data-zoom']});}
 const edges=data.edges,cities=data.cities,all=cities.flatMap((c:any)=>c.districts.map((d:any)=>({c,d}))),matrix=svg.getScreenCTM(),viewport=currentWrap?.getBoundingClientRect();
 const scale=matrix?Math.hypot(matrix.a,matrix.b):.1,pixels=84*scale,lod:CityLod=pixels<45?'far':pixels<110?'medium':'close';
 const visible=all.filter(({d}:any)=>{if(!matrix||!viewport)return false;const[q,r]=d.hex.split(',').map(Number),pos=hexToPixel({q,r}),x=pos.x*matrix.a+pos.y*matrix.c+matrix.e,y=pos.x*matrix.b+pos.y*matrix.d+matrix.f;return x>viewport.left-80&&x<viewport.right+80&&y>viewport.top-80&&y<viewport.bottom+80;}).slice(0,CITY_DETAIL_BUDGET.maxVisible);
 const stamp=JSON.stringify([data.revision,data.viewer,lod,visible.map(({d}:any)=>d.id)]);if(svg===lastSvg&&stamp===lastStamp&&svg.querySelector('#city-art-static')){svg.dataset.cityImageCache=JSON.stringify(terrainImageCacheStats());return;}lastStamp=stamp;lastSvg=svg;generation++;const ticket=generation;if(timer!==null)clearTimeout(timer);
 const visibleIds=new Set(visible.map(({d}:any)=>d.id));
 for(const id of ['city-art-static','city-art-facilities','city-districts','city-bridges'])svg.querySelector('#'+id)?.remove();
 const at=(d:any)=>{const[q,r]=d.hex.split(',').map(Number);const pos=hexToPixel({q,r});return `translate(${pos.x} ${pos.y})`;};
 const content=all.map(({d}:any)=>`<g data-scene-id="${esc(d.id)}" transform="${at(d)}">${getScene(d,edges,'far')}</g>`).join('')+cities.map((c:any)=>wallsMarkup(cityWallPlan(c,edges),lod==='close'?'close':'far')).join('');
 svg.querySelector('#fog-surface-layer')?.insertAdjacentHTML('beforebegin',`<g id="city-art-static" pointer-events="none">${content}</g><g id="city-art-facilities" pointer-events="none">${all.map(({d}:any)=>`<g transform="${at(d)}">${facilityMarkup(d,edges,visibleIds.has(d.id)?lod:'far')}</g>`).join('')}</g><g id="city-bridges" pointer-events="none">${railStateMarkup(edges,new Set(data.knownHexKeys))}${bridgeStateMarkup(edges,new Set(data.knownHexKeys))}</g>`);
 const labels=all.map(({c,d}:any)=>`<g transform="${at(d)}" data-city-map="${esc(c.id)}" data-city-hex="${d.hex}" data-city-did="${esc(d.id)}" role="button" tabindex="0" aria-label="${esc(c.label+' '+d.paper)}"><rect x="-24" y="29" width="48" height="7" rx="1.5" fill="${d.control==='GERMAN'?'#516b70':d.control==='SOVIET'?'#895f4e':'#7e7e68'}" opacity=".82"/><text class="city-art-label" x="0" y="34" text-anchor="middle" font-size="4.5" fill="#f4e9d0" pointer-events="none">${esc(d.paper+' '+({MAIN:'主城',STATION:'站区',INDUSTRIAL:'工业区',RESIDENTIAL:'近郊'} as any)[d.type]+(d.unconfirmed?' ?':''))}</text></g>`).join('');
 svg.insertAdjacentHTML('beforeend',`<g id="city-districts" class="city-art-labels">${labels}</g>`);
 svg.querySelectorAll<SVGElement>('[data-city-map]').forEach(el=>{const choose=()=>select(el.dataset.cityMap!,el.dataset.cityDid!);el.addEventListener('click',e=>{e.stopPropagation();choose();});el.addEventListener('keydown',e=>{if(e.key==='Enter')choose();});});
 let index=0;const batch=()=>{if(ticket!==generation||!svg.isConnected)return;const start=performance.now();while(index<visible.length){const {d}=visible[index++]!;const el=svg.querySelector(`[data-scene-id="${d.id}"]`);if(el)el.innerHTML=getScene(d,edges,lod);if(performance.now()-start>=CITY_DETAIL_BUDGET.sliceMs)break;}status(svg,visible.length-index,lod);if(index<visible.length)timer=setTimeout(batch,0);else timer=null;};
 if(lod!=='far'&&visible.length){status(svg,visible.length,lod);timer=setTimeout(batch,0);}else status(svg,0,lod);
 svg.dataset.cityVisible=String(visible.length);svg.dataset.cityDetail=lod;
}
