/* Preview-only passive resource readout and opt-in RAF sampling. No gameplay access. */
const box=document.createElement('details');box.id='preview-measure';box.style.cssText='position:fixed;right:8px;bottom:32px;z-index:10000;background:#152b34;color:white;padding:8px;max-width:460px;font:13px sans-serif';
box.innerHTML='<summary>本地规则场景 · 测量工具</summary><p>基线/候选都保留旧启动管线。测量会产生少量自身开销。</p><button id="preview-sample">采集 5 秒：点击后拖动地图</button> <button id="preview-report">读取资源与布局</button><p id="preview-sample-status">未采集</p><textarea readonly aria-label="预览测量结果" style="width:420px;height:240px"></textarea><p><a href="../index.html" style="color:white">返回比较入口</a></p>';
document.body.append(box);let frames=[],sample=null;
function report(){const svg=document.querySelector('#eastfront-map'),panel=document.querySelector('#side-panel');const bounds=s=>{const n=document.querySelector(s);if(!n)return null;const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,clientWidth:n.clientWidth,scrollWidth:n.scrollWidth,clientHeight:n.clientHeight,scrollHeight:n.scrollHeight};};
 const resources=performance.getEntriesByType('resource').map(r=>({name:r.name,type:r.initiatorType,duration:r.duration,transferSize:r.transferSize,encodedBodySize:r.encodedBodySize}));
 const value={scope:'preview browser measurement; local rules scene',actualViewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},scene:document.documentElement.dataset.previewScene,ready:document.documentElement.dataset.previewReady,viewBox:svg?.getAttribute('viewBox'),camera:svg?.style.transform,modelMode:document.querySelector('#unit-models')?.value,layout:{topbar:bounds('.topbar'),toolbar:bounds('.map-toolbar'),panel:bounds('#side-panel'),map:bounds('#map-wrap'),panelScroll:bounds('.command-panel-scroll')},smallVisibleButtons:[...document.querySelectorAll('button,select')].filter(n=>!n.closest('#preview-measure')&&n.getClientRects().length).map(n=>({id:n.id,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})).filter(r=>r.width<44||r.height<44),svgElements:svg?.querySelectorAll('*').length,canvasPresent:!!document.querySelector('#terrain-surface'),resources,raf:sample,notes:['RAF interval is a proxy, not GPU/paint timing','Zero transferSize can indicate cache or unavailable data','Route occlusion requires visual inspection']};box.querySelector('textarea').value=JSON.stringify(value,null,2);}
box.querySelector('#preview-report').onclick=report;
box.querySelector('#preview-sample').onclick=()=>{const button=box.querySelector('#preview-sample');button.disabled=true;frames=[];let previous=null,start=performance.now();box.querySelector('#preview-sample-status').textContent='采集中：请拖动地图';function tick(now){if(previous!==null)frames.push(now-previous);previous=now;if(now-start<5000){requestAnimationFrame(tick);return;}const sorted=[...frames].sort((a,b)=>a-b);sample={durationMs:now-start,frames:frames.length,meanMs:frames.reduce((a,b)=>a+b,0)/frames.length,p95Ms:sorted[Math.floor(sorted.length*.95)],over33ms:frames.filter(x=>x>33).length};button.disabled=false;box.querySelector('#preview-sample-status').textContent='采集完成';report();}requestAnimationFrame(tick);};
