// Replay only stored020 choices. Authority is confined to offline reporting.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {FairHost} from '../../.ai-dist/ai/authority/FairHost.js';
import {defaultRules,defaultScenario} from '../../.ai-dist/vendor/eastfront-digital-core/dist/index.js';
import {hexDistance,hexKey} from '../../.ai-dist/vendor/eastfront-digital-core/dist/core/hex.js';
import {initial} from '../../ai/lab/match.mjs';
import {hash,atomic} from '../../ai/lab/common.mjs';
import {records} from '../../ai/lab/runner.mjs';
const out='evidence/ai-move-tie-020',config=JSON.parse(readFileSync(out+'/config.json'));
const stats=a=>{const b=[...a].sort((x,y)=>x-y);return {n:b.length,min:b[0]??null,median:b.length?(b[Math.floor((b.length-1)/2)]+b[Math.floor(b.length/2)])/2:null,mean:b.length?b.reduce((s,n)=>s+n,0)/b.length:null,max:b.at(-1)??null,p95:b[Math.ceil(b.length*.95)-1]??null};};
const distance=h=>Math.min(...defaultScenario.capitalCoreHexes.map(g=>hexDistance(h,g)));
function snapshot(state){const units=Object.values(state.units).filter(u=>u.side==='GERMAN').map(u=>({id:u.id,alive:u.alive,hex:u.hex,step:u.step,distance:distance(u.hex)})).sort((a,b)=>a.id.localeCompare(b.id)),distribution=units.filter(u=>u.alive).map(u=>u.distance).sort((a,b)=>a-b),cities=Object.values(state.hexes).filter(h=>h.cityId||['CITY','MAIN_CITY','OUTER_CITY'].includes(h.terrain)).map(h=>({hex:h.coord,control:h.control,occupants:Object.values(state.units).filter(u=>u.alive&&hexKey(u.hex)===hexKey(h.coord)).map(u=>({id:u.id,side:u.side}))}));return {turn:state.turn,phase:state.phase,units,dead:units.filter(u=>!u.alive).map(u=>u.id),distribution,statistics:stats(distribution),fixed:config.fixedUnits.map(id=>units.find(u=>u.id===id)),cities,cityCounts:{germanOccupied:cities.filter(c=>c.occupants.some(u=>u.side==='GERMAN')).length,germanControlled:cities.filter(c=>c.control==='GERMAN').length,total:cities.length},capitalControlled:defaultScenario.capitalCoreHexes.filter(h=>state.hexes[hexKey(h)]?.control==='GERMAN').length};}
const games=[];
for(const seed of config.seeds){
 const dir=`${out}/batch/development-${seed}-experiment-GERMAN`,record=JSON.parse(readFileSync(dir+'/record.json')),rows=records(dir+'/trace.ndjson');assert.equal(record.integrity,'PASS');assert.equal(hash(readFileSync(dir+'/trace.ndjson')),record.traceFileHash);assert.equal(hash(rows),record.traceHash);assert(rows.every((r,i)=>r.n===i));
 const host=new FairHost({matchId:record.job.id,initialState:initial(seed),rules:defaultRules,scenario:defaultScenario,agentSeeds:config.agentSeeds}),turns=[],moves=[];let previousTurn=1;
 for(const row of rows){
  const agent=input=>{assert.equal(input.observationKey,row.observationKey);assert.equal(hash(input),row.inputHash);return row.choice;};
  assert.deepEqual(host.step({GERMAN:agent,SOVIET:agent}),row.result);
  if(row.side==='GERMAN'&&row.choice?.intent?.type==='MOVE'&&row.result.status==='ACCEPTED'){
   const u=host.auditOmniscient().units[row.choice.intent.unitId],p=row.movementProbe;assert.deepEqual(u.hex,row.choice.intent.path.at(-1));moves.push({n:row.n,turn:row.turn,unitId:u.id,fromDistance:p.unitOriginDistance,to:u.hex,toDistance:distance(u.hex),changed:p.changed,original:p.original.intent});
  }
  const end=host.auditOmniscient();if(end.turn!==previousTurn||end.phase==='GAME_OVER'&&row.choice){turns.push({completedTurn:previousTurn,n:row.n,...snapshot(end)});previousTurn=end.turn;}
 }
 const state=host.auditOmniscient();assert.equal(hash(state),record.finalHash);const probes=rows.filter(r=>r.movementProbe),changed=probes.filter(r=>r.movementProbe.changed),acceptedChanged=moves.filter(m=>m.changed);
 const a={seed,version:'020',status:record.status,winner:record.winner,turn:record.turn,finalHash:record.finalHash,traceFileHash:record.traceFileHash,sides:record.metrics.sides,rejected:record.metrics.rejected,turns,final:snapshot(state),moves,ties:{changedDecisions:changed.length,acceptedChanged:acceptedChanged.length,rejectedChanged:changed.filter(r=>r.result.status==='REJECTED').length,sameUnitChanges:changed.filter(r=>r.choice.intent.unitId===r.movementProbe.original.intent.unitId).length,differentUnitChanges:changed.filter(r=>r.choice.intent.unitId!==r.movementProbe.original.intent.unitId).length,actualChangedCloser:acceptedChanged.filter(m=>m.toDistance<m.fromDistance).length,actualChangedEqual:acceptedChanged.filter(m=>m.toDistance===m.fromDistance).length,actualChangedFarther:acceptedChanged.filter(m=>m.toDistance>m.fromDistance).length,rows:changed.map(r=>({n:r.n,turn:r.turn,choice:r.choice,result:r.result,probe:r.movementProbe}))},cost:{movementDecisions:probes.length,policyMs:stats(probes.map(r=>r.policyMs)),sameView014Ms:stats(probes.map(r=>r.movementProbe.oldPolicyMs)),tieMs:stats(probes.map(r=>r.movementProbe.tieMs)),expanded:stats(probes.map(r=>r.movementProbe.metrics.expanded)),exhausted:probes.filter(r=>r.movementProbe.metrics.exhausted).length}};
 atomic(`${out}/${seed}-020-audit.json`,a);games.push(JSON.parse(readFileSync(`${out}/baseline-${seed}.json`)),a);console.log(JSON.stringify({seed,ties:{...a.ties,rows:undefined},final:a.final.statistics,sides:a.sides,cost:a.cost}));
}
atomic(out+'/comparison.json',{newGames:2,baselineGamesRerun:0,preregisteredCommit:JSON.parse(readFileSync(out+'/manifest.json')).preRegistrationCommit,games:games.map(g=>({...g,turns:undefined,moves:undefined,ties:g.ties?{...g.ties,rows:undefined}:undefined}))});
let md='# AI-MOVE-TIE-020 开发对照\n\n014读取既有记录，020仅新跑两局德军。距离为存活德军到公开首都核心的最小六角距离；死亡另列。损步为德/苏。拒绝为双方总计。\n\n|种子/版|同分改选/接受/拒绝|接受MOVE近/平/远|均距/最近|I08距离/损步|攻击|损步德/苏；德消灭|拒绝|占城/控制；首都|自然终局|\n|---|---|---|---|---|---|---|---|---|---|\n';
for(const g of games){const i=g.final.units.find(u=>u.id==='G-I-08'),m=g.moves;md+=`|${g.seed}/${g.version}|${g.ties?`${g.ties.changedDecisions}/${g.ties.acceptedChanged}/${g.ties.rejectedChanged}`:'—'}|${m?`${m.filter(m=>m.toDistance<m.fromDistance).length}/${m.filter(m=>m.toDistance===m.fromDistance).length}/${m.filter(m=>m.toDistance>m.fromDistance).length}`:'见014原回放'}|${g.final.statistics.mean.toFixed(2)}/${g.final.statistics.min}|${i.alive?i.distance:'死亡'}/${i.step}|${g.sides.GERMAN.attacks}|${g.sides.GERMAN.lossSteps}/${g.sides.SOVIET.lossSteps}；${g.sides.GERMAN.destroyedUnits}|${g.sides.GERMAN.rejections+g.sides.SOVIET.rejections}|${g.final.cityCounts.germanOccupied}/${g.final.cityCounts.germanControlled}；${g.final.capitalControlled}|${g.status} T${g.turn} ${g.winner}|\n`;}
md+='\n逐回合活单位均值/最近距离：\n\n|T|1017/014|1017/020|1018/014|1018/020|\n|---|---|---|---|---|\n';for(let t=1;t<=16;t++)md+=`|${t}|${games.map(g=>{const s=g.turns.find(x=>x.completedTurn===t)?.statistics;return s?`${s.mean.toFixed(2)}/${s.min}`:'—';}).join('|')}|\n`;
md+='\n同分改选的旧选择仅为同一020授权视图的014选择，不是014原局在相同n的动作；异单位改选不能解释为同单位多前进。局部分数完全相同、终点更近不等于未来战略增强。开发种子不构成留出验证；行动分叉后不保证逐战同骰。全军距离分布、固定单位位置、死亡名单和拒绝原因见JSON。\n';writeFileSync(out+'/comparison.md',md);
