// Offline only: never alters the raw record or declares pixel correctness from a label.
import {readFileSync,writeFileSync} from 'node:fs';import {dirname,resolve} from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const path=resolve(process.argv[2]),out=process.argv[3];assert(out,'Use a new output path');
const raw=readFileSync(path),d=JSON.parse(raw),receipt=JSON.parse(readFileSync(path.replace(/\.json$/,'.receipt.json'))),sha=b=>createHash('sha256').update(b).digest('hex');
assert.equal(sha(raw),receipt.sha256);assert.equal(raw.length,receipt.bytes);assert.equal(d.sourceCommit,'380047b5dccd9cc247ac50d4fb3d81a2336df394');assert.equal(d.mode,'default');assert.equal(d.events.filter(e=>e.kind==='local-start-request').length,1);
const samples=d.samples.filter(s=>s.withinBudget),close=samples.flatMap(s=>s.active.filter(w=>w.lod==='close'&&w.stage==='rasterizeVS2WorldSurface').map(w=>({at:s.at,elapsedMs:s.elapsedMs,visible:s.visibility,pipelineActive:s.pipeline?.active,...w})));
const comparisons=[];for(let i=1;i<close.length;i++){const a=close[i-1],b=close[i];if(a.id!==b.id)continue;const delta=b.steps-a.steps;let observation=delta>0?'ADVANCED_BETWEEN_SAMPLES':'NO_ADVANCEMENT_OBSERVED';if(delta===0&&a.pipelineActive===false&&b.pipelineActive===false&&a.state==='checkpoint'&&b.state==='checkpoint')observation='PAUSED_CHECKPOINT_AT_BOTH_SAMPLES';else if(delta===0&&a.state==='yielding'&&b.state==='yielding'&&a.pipelineActive===true&&b.pipelineActive===true)observation='YIELD_NOT_RESUMED_BETWEEN_SAMPLES';comparisons.push({fromElapsedMs:a.elapsedMs,toElapsedMs:b.elapsedMs,intervalMs:b.at-a.at,fromSteps:a.steps,toSteps:b.steps,state:b.state,observation});}
const shots=d.screenshots.map(s=>{const bytes=readFileSync(resolve(dirname(path),s.id));assert.equal(sha(bytes),s.sha256);assert.equal(bytes.length,s.bytes);assert.equal(bytes.subarray(0,8).toString('hex'),'89504e470d0a1a0a');return {...s,pngWidth:bytes.readUInt32BE(16),pngHeight:bytes.readUInt32BE(20),fileVerified:true};});
const reached=samples.filter(s=>s.current.panelExpanded==='false'&&s.camera?.screenHexWidth>96),finished=d.events.filter(e=>e.kind==='terrain-complete'&&e.lod==='close'&&e.at-d.marks.startAt<=d.budget.limitMs),validShots=shots.filter(s=>s.lod==='close'&&s.readyClose&&s.withinBudget);
const A={result:reached.length?'REACHED':'NOT_OBSERVED_REACHED',maxActualZoom:Math.max(0,...samples.map(s=>s.camera?.zoom??0)),maxCollapsedScreenHexWidth:Math.max(0,...samples.filter(s=>s.current.panelExpanded==='false').map(s=>s.camera?.screenHexWidth??0)),thresholdRule:'close requires >96',initial:d.firstMap,observations:reached.map(s=>({elapsedMs:s.elapsedMs,camera:s.camera,current:s.current}))};
const B={closeCompletedWithinBudget:finished.length>0,completedElapsedMs:finished.map(e=>e.at-d.marks.startAt),actualCloseCanvasPngCount:validShots.length,userReportsCorrect:d.observations.closeContentCorrect,pixelVisualReview:'REQUIRED_SEPARATELY; PNG identity and nonblank appearance alone cannot prove all content correct',result:finished.length&&validShots.length&&d.observations.closeContentCorrect?'EVIDENCE_READY_FOR_VISUAL_REVIEW':'NOT_CONFIRMED',screenshots:validShots};
const result={record:path,receipt,kind:receipt.kind,actualDeviceClaim:receipt.kind==='device',sourceCommit:d.sourceCommit,viewport:d.viewport,conditions:{device:d.device,network:d.network,cacheCondition:d.cacheCondition},outcome:d.outcome,stopReason:d.stopReason,budget:d.budget,A,B,closeRasterSamples:close,comparisons,lastIntervalObservation:comparisons.at(-1)?.observation??'INSUFFICIENT_COMPARABLE_SAMPLES',caution:'No progress between snapshots does not establish deadlock. Yield delay does not establish its cause. A frozen JS thread may prevent new exports. Do not call remaining time network time.',milestones:{mapDomMs:d.marks.mapDomReadyAt===null?null:d.marks.mapDomReadyAt-d.marks.startAt,controlsAvailableMs:d.marks.controlsAvailableAt===null?null:d.marks.controlsAvailableAt-d.marks.startAt,terrain:d.events.filter(e=>e.kind==='terrain-complete').map(e=>({lod:e.lod,elapsedMs:e.at-d.marks.startAt}))},imageJobs:d.diagnostics.imageJobs};
writeFileSync(out,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({kind:receipt.kind,A:A.result,B:B.result,lastInterval:result.lastIntervalObservation,stopReason:d.stopReason}));
