import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {resolve,dirname,basename} from 'node:path';import assert from 'node:assert/strict';
const file=resolve(process.argv[2]),bytes=readFileSync(file),data=JSON.parse(bytes),receipt=JSON.parse(readFileSync(file.replace(/\.json$/,'.receipt.json')));
const hash=createHash('sha256').update(bytes).digest('hex');assert.equal(hash,receipt.sha256);assert.equal(bytes.length,receipt.bytes);assert.equal(data.sourceCommit,'b9927e072d30fac8b732b815c0d817ce490d7d6e');assert.equal(data.diagnostics.build,data.sourceCommit);
for(const shot of data.screenshots??[]){assert.equal(basename(shot.id),shot.id);const png=readFileSync(resolve(dirname(file),shot.id));assert.equal(png.length,shot.bytes);assert.equal(createHash('sha256').update(png).digest('hex'),shot.sha256);}
const completed=data.events.filter(e=>e.kind==='terrain-complete'),mounted=[...new Set(data.events.filter(e=>e.kind==='lod-mounted').map(e=>e.lod))],start=data.marks.startAt;
const reasons=[];if(data.failed||data.outcome==='failed')reasons.push('failed');if(data.outcome!=='observed-success')reasons.push('not-observed-success');if(!Object.values(data.observations).every(v=>v===true))reasons.push('missing-visual-observation');if(!['far','medium','close'].every(lod=>mounted.includes(lod)))reasons.push('missing-mounted-lod');if(data.diagnostics.imageJobs.active!==0||data.diagnostics.imageJobs.failed!==0)reasons.push('image-jobs-not-successfully-complete');
const first=completed[0]?.at,all=completed.length===3?Math.max(...completed.map(e=>e.at)):null;
if(![start,first,data.marks.mapDomReadyAt,data.marks.controlsAvailableAt].every(Number.isFinite)||data.marks.mapDomReadyAt<first||data.marks.controlsAvailableAt<data.marks.mapDomReadyAt)reasons.push('milestone-order-or-missing');
if(data.progress.stage!=='ready')reasons.push('terrain-details-not-ready-at-export');
const result={file,receipt,completeAndHashVerified:true,screenshotReceiptsVerified:true,kind:receipt.kind,mode:data.mode,device:data.device,userAgent:data.userAgent,viewport:data.viewport,network:data.network,cacheCondition:data.cacheCondition,outcome:data.outcome,reasons,mounted,progress:data.progress,current:data.current,observations:data.observations,notes:data.notes,screenshots:data.screenshots,
 firstTerrainAfterStartMs:first==null?null:first-start,allTerrainAfterStartMs:all==null?null:all-start,mapDomAfterStartMs:data.marks.mapDomReadyAt==null?null:data.marks.mapDomReadyAt-start,controlsObservedAfterStartMs:data.marks.controlsAvailableAt==null?null:data.marks.controlsAvailableAt-start,
 imageJobs:data.diagnostics.imageJobs,terrainResources:data.resources.filter(r=>r.path.includes('/assets/terrain/')).length,terrainResourcePaths:new Set(data.resources.filter(r=>r.path.includes('/assets/terrain/')).map(r=>r.path)).size,loaderBudgetAndFallback:data.diagnostics.recent.map(r=>({asset:r.asset,webkit:r.webkitFallback,timeoutMs:r.timeoutMs,elapsedMs:r.elapsedMs,outcome:r.outcome,attempts:r.attempts})),
 limitations:['One observation does not establish stable speedup.','Current timings begin at the STARTUP004 local-start request; do not compare directly with MP015 or the artificial slow-response benchmark.','DOM availability is not visible paint; actual appearance/interaction are user observations.','New page is not proof of cold cache; resource timing reports do not fully identify browser caching.']};
if(process.argv[3])writeFileSync(process.argv[3],JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result,null,2));
