import type { enUS } from './en-US.js';
export const zhCN = {
  "fow.contact": "敌军接触",
  "fow.lastKnown": "最后已知位置",
  "fow.lastKnownTurn": "最后已知位置 · 第 {turn} 回合",
  "fow.insufficient": "情报不足",
  "fow.view": "玩家视角",
  "fow.german": "德军视角",
  "fow.soviet": "苏军视角",
  "fow.observer": "观察者视角",
  "fow.inspection": "只读检视视角",

  "startup.progress": "已完成启动步骤",
  "startup.steps": "启动步骤 · {completed} / {total}",
  "startup.initializing": "正在初始化游戏",
  "startup.assets": "正在加载地图素材",
  "startup.building": "正在构建战场",
  "startup.ready": "准备完成",
  "startup.failed": "加载失败",
  "startup.batch": "当前素材批次 · {completed} / {total}",
  "startup.loaded": "已加载 {completed} 项素材",

  "animation.speed": "动画速度",
  "animation.normal": "正常",
  "animation.fast": "快速",
  "animation.instant": "即时",
  "animation.skip": "跳过动画",
  "combat.group.count": "攻击单位：{count}",
  "combat.group.hint": "点击高亮友军加入攻击，再次点击即可移除。",
  "combat.group.primary": "主攻击者",
  "combat.group.selected": "已加入联合攻击",
  "combat.group.eligible": "可加入攻击",
  "combat.group.remove": "将{unit}移出攻击组",
  "combat.group.strength": "攻击总战力",
  "combat.group.added": "{id} 已加入攻击组，当前攻击单位：{count}。",
  "combat.group.removed": "{id} 已移出攻击组，当前攻击单位：{count}。",
  "combat.group.unavailable": "无法加入本次攻击：{issues}",
  "combat.group.primaryHelp": "主攻击者保持选中，点击其他高亮单位可加入攻击。",
  "combat.flow.allocateHelp": "选择承担 {steps} 级损失的单位，选满后自动结算。",
  "combat.flow.preview": "战斗预览",
  "combat.flow.advanced": "高级选项",
  "combat.flow.majorModifiers": "主要修正",
  "combat.flow.noModifiers": "无列修正",
  "combat.flow.crtTable": "完整战斗结果表",
  "combat.flow.diceTotal": "骰子合计",
  "combat.flow.completed": "战斗结束 · {result}。可继续操作地图。",
  "combat.flow.defender": "选择防守支援，或放弃剩余支援。",
  "combat.flow.declineSupport": "不使用剩余支援",
  "combat.flow.lastStand": "坚守 · {id}",
  "combat.flow.retreat": "选择撤退位置",
  "combat.flow.retreatHelp": "为 {id} 点击地图高亮格。路线完成后自动执行撤退。",
  "combat.flow.retreatHex": "撤退至 {hex}",
  "combat.flow.retreatOrder": "可选择下一个撤退单位；顺序会影响可用位置。",
  "combat.flow.advance": "选择推进位置",
  "combat.flow.chooseAdvancer": "选择推进单位，再点击地图高亮格。也可以放弃推进。",
  "combat.flow.advanceHelp": "点击高亮格推进 {id}，或放弃推进。",
  "combat.flow.advanceHex": "推进至 {hex}",
  "combat.flow.advancer": "推进单位 · {id}",
  "combat.flow.resultDetails": "战斗结果与详细修正",
  "combat.flow.unitDetails": "单位详情",
  "combat.flow.ready": "核对预览后，点击攻击。",
  "combat.flow.breakthrough": "选择单位并点击地图规划突破；可放弃。最多 {max} 格。",
  "combat.flow.schwerpunkt": "可发动重点突击：点击高亮敌军，选择攻击单位。",
  "combat.flow.targetHex": "攻击目标 {hex}",

  "game.newGame": "新游戏",
  "game.loading": "正在加载 EASTFRONT…",
  "game.preparing": "正在准备战略重置 F 地图与游戏资源。",
  "game.title": "六角格战役兵棋",
  "game.description": "在战略重置 F 的 20×32 地图上，双方轮流操作，展开战役。",
  "game.advisory": "建议横屏游玩，或使用更大的屏幕。",
  "game.controls": "关于／操作说明",
  "game.controlsHelp": "点击棋子和高亮六角格进行操作。拖动地图平移，使用 +／− 缩放。秘密部署时，请按提示将设备交给另一位玩家。",
  "game.unableToStart": "无法启动 EASTFRONT",
  "game.reload": "重新加载",
  "game.over": "游戏结束",
  "game.noWinner": "无获胜方",
  "game.noVictoryReason": "未提供胜利原因。",
  "game.finished": "对局已结束，无法继续操作",
  "game.restartTitle": "开始一局新游戏",
  "game.panel": "面板",
  "game.preview": "网页版预览",
  "game.webPreview": "EASTFRONT 网页版预览",
  "game.command": "EASTFRONT · 战役指挥",
  "game.noMap": "地图画面尚未就绪。",
  "game.noResources": "无法初始化游戏所需资源。",
  "game.noSession": "当前没有进行中的对局。",
  "campaign.name": "战略重置 F",
  "map.title": "战略重置 F · 作战地图",
  "map.accessible": "战略重置 F 作战地图",
  "map.eastfront": "EASTFRONT 作战地图",
  "map.zoomControls": "地图缩放控制",
  "map.zoomOut": "缩小",
  "map.zoomIn": "放大",
  "map.fitLabel": "适应地图",
  "map.fit": "适应地图",
  "common.yes": "是",
  "common.no": "否",
  "common.unknown": "未知",
  "common.undo": "撤销",
  "common.clear": "清空",
  "common.commit": "确认",
  "common.undoStep": "撤销一步",
  "common.available": "可用",
  "common.delayed": "延迟",
  "common.position": "位置",
  "common.status": "状态",
  "common.phase": "阶段",
  "common.advancePhase": "结束阶段",
  "common.legal": "预览：可以执行",
  "common.target": "目标",
  "common.terrain": "地形",
  "common.attack": "攻击",
  "common.defense": "防御",
  "common.movement": "移动",
  "common.supply": "补给",
  "common.turn": "回合",
  "common.selectUnit": "选择己方单位开始操作。",
  "unit.inspect": "选择单位，查看战力、补给和移动信息。",
  "unit.entrenchedSuffix": " · 已掘壕",
  "unit.infantryDescription": "步兵编队",
  "unit.eliteDescription": "精锐步兵编队",
  "unit.jagerDescription": "轻步兵编队",
  "unit.panzerDescription": "装甲编队",
  "unit.tankDescription": "坦克编队",
  "unit.heavyDescription": "重型坦克编队",
  "unit.artilleryDescription": "炮兵支援",
  "unit.engineerDescription": "工兵支援",
  "unit.reconDescription": "侦察编队",
  "unit.motorizedDescription": "摩托化编队",
  "unit.atDescription": "反坦克编队",
  "unit.hqDescription": "司令部",
  "deployment.onMap": "已部署",
  "deployment.reserve": "预备队",
  "deployment.complete": "完成",
  "deployment.placeAll": "部署全部单位",
  "deployment.selectUnit": "选择单位",
  "deployment.choosePosition": "选择位置",
  "deployment.deploy": "部署",
  "deployment.begin": "选择预备队单位，开始部署。",
  "deployment.confirmPhase": "完成部署阶段",
  "deployment.hidden": "当前由另一方部署，敌方部署仍然保密。",
  "deployment.chooseTerrain": "选择部署地形",
  "deployment.chooseDestination": "选择部署位置",
  "deployment.confirm": "确认部署",
  "deployment.deployed": "部署成功",
  "deployment.cannotDeploy": "无法部署",
  "deployment.readyToConfirm": "可确认部署",
  "deployment.noVisibleUnits": "无可见单位",
  "deployment.submitting": "正在部署…",
  "deployment.stackLimit": "已达到堆叠上限，请选择其他位置。",
  "deployment.invalidHex": "此位置不在己方部署区域内，请选择高亮位置。",
  "deployment.unavailable": "此单位无法部署，请选择其他预备队单位。",
  "deployment.wrongPhase": "当前已不在部署阶段。",
  "deployment.wrongSide": "请等待己方部署阶段。",
  "deployment.invalidController": "无法识别己方，请返回当前玩家的视角。",
  "deployment.rejected": "无法完成部署，请更换单位或位置后重试。",
  "deployment.retry": "无法完成部署，请重新选择单位和位置。",
  "combat.mode": "战斗 · 攻击模式",
  "combat.chooseEnemy": "选择地图上高亮的敌方单位。",
  "combat.review": "查看战斗预览，然后确认攻击。",
  "combat.selectAttacker": "选择攻击方",
  "combat.selectEnemy": "选择敌方目标",
  "combat.versus": "对阵",
  "combat.odds": "战斗比",
  "combat.modifiers": "修正",
  "combat.previewHelp": "当前为防御方反应前的预览，最终结果由骰子决定。",
  "combat.attack": "攻击",
  "combat.advanced": "追加参战单位／高级选项",
  "combat.advancedHelp": "选择更多直接参战单位，系统将检查联合攻击是否可行。",
  "combat.noArtillery": "不使用炮兵",
  "combat.clear": "清空攻击选择",
  "combat.detailsSummary": "战斗结果表（CRT）／战斗详情",
  "combat.endPhase": "结束战斗阶段",
  "combat.details": "战斗详情",
  "combat.resolvedContext": "已结算战斗信息",
  "combat.baseOdds": "基础战斗比",
  "combat.baseColumn": "基础列",
  "combat.finalShift": "最终列修正",
  "combat.finalCRT": "最终战斗结果表列",
  "combat.rawCapped": "原始／限幅后",
  "combat.river": "河流",
  "combat.engineer": "工兵",
  "combat.combinedArms": "步坦协同",
  "combat.armorPenalty": "装甲惩罚",
  "combat.antiTank": "反坦克",
  "combat.attackerArtillery": "攻击方炮兵",
  "combat.defenderArtillery": "防御方炮兵",
  "combat.flank": "侧翼",
  "combat.entrenchment": "掘壕",
  "combat.hq": "司令部",
  "combat.secondAttack": "第二次攻击",
  "combat.history": "战斗记录",
  "combat.battle": "战斗编号",
  "combat.decisionOwner": "决策方",
  "combat.defenderHelp": "防御方反应：选择可用炮兵支援，或跳过反应并掷骰结算。",
  "combat.noDefensiveArtillery": "没有可用的防御炮兵。",
  "combat.passReaction": "跳过反应／结算",
  "combat.noLossDraft": "尚未分配损失",
  "combat.commitLosses": "确认损失",
  "combat.noRetreatStep": "此单位没有其他可行的撤退步，请检查其他单位后再确认。",
  "combat.commitRetreat": "确认撤退",
  "combat.advanceHelp": "向腾空的战斗目标格推进，或跳过推进。",
  "combat.passAdvance": "跳过推进",
  "combat.noBreakthroughDraft": "尚未规划额外格位",
  "combat.passBreakthrough": "跳过全部突破",
  "combat.schwerpunktHelp": "可选择德军重点突击的第二次攻击。请选择相邻且高亮的苏军目标。",
  "combat.passSchwerpunkt": "跳过重点突击",
  "combat.resolvedCRT": "战斗结果表结算",
  "combat.crt": "战斗结果表",
  "combat.attackerLoss": "攻击方损失",
  "combat.defenderLoss": "防御方损失",
  "combat.defenderRetreat": "防御方撤退",
  "combat.submitting": "正在提交攻击…",
  "rail.title": "德军补给／铁路",
  "rail.help": "可选择修复地图上的铁路区段。结束阶段将跳过修复。",
  "rail.plan": "计划",
  "rail.used": "已使用修复",
  "rail.mode": "铁路修复模式",
  "rail.noEngineer": "不使用工兵",
  "rail.clear": "清空计划",
  "rail.commit": "确认修复",
  "movement.title": "移动",
  "movement.help": "选择己方单位，点击相邻六角格规划路径。确认移动并通过检查后，棋子才会移动。",
  "movement.path": "路径",
  "movement.mp": "移动点",
  "movement.cancel": "取消路径",
  "movement.commit": "确认移动",
  "reinforcement.title": "苏军增援／补给",
  "reinforcement.required": "仍有可部署的增援，请先处理后再结束阶段。",
  "reinforcement.none": "没有可用增援。",
  "reinforcement.entryHelp": "点击高亮的东部铁路出口，部署所选增援。",
  "reinforcement.selectHelp": "选择要部署的增援。",
  "reinforcement.delayedPrefix": "延迟 · ",
  "recovery.title": "恢复",
  "recovery.recovered": "已恢复",
  "recovery.rp": "己方补充点",
  "recovery.cost": "所选单位消耗",
  "recovery.commit": "恢复 1 级损伤",
  "recovery.help": "选择受损的己方单位。地图上以浅色轮廓标出了恢复基地。",
  "entrenchment.title": "掘壕",
  "entrenchment.commit": "单位掘壕",
  "entrenchment.help": "选择己方单位，查看是否可以掘壕。",
  "panel.title": "指挥面板",
  "panel.report": "命令反馈",
  "privacy.combatTitle": "交接战斗决策",
  "privacy.combatHelp": "请交接设备后继续，交接不会改变对局状态。",
  "privacy.title": "轮流操作 · 保密交接",
  "privacy.sovietLocked": "苏军部署已锁定。",
  "privacy.passGerman": "请将设备交给德军玩家。",
  "privacy.beginGerman": "开始德军部署",
  "privacy.deploymentComplete": "部署完成",
  "privacy.ready": "双方均已就绪。",
  "privacy.reveal": "即将进入德军第 1 回合。敌军仅在被识别或发现接触时显示。",
  "privacy.beginTurnOne": "开始第 1 回合",
  "privacy.turnTitle": "玩家回合交接",
  "privacy.turnHelp": "交接不会改变对局状态。",
  "game.turn": "第 {turn} 回合",
  "game.restartPrompt": "开始新游戏？\n当前进度将丢失。",
  "game.resourceFailure": "无法加载游戏所需资源。{detail}",
  "unit.step": "损伤等级 {step}",
  "unit.readings": "攻 {attack} · 防 {defense} · 移 {movement}",
  "deployment.title": "{side}部署",
  "deployment.selectedHelp": "已选择：{id}。请选择地形卡片或点击地图，然后确认部署。",
  "deployment.unitTitle": "{unit}部署",
  "deployment.terrain": "地形 · {terrain}",
  "deployment.occupancy": "占用 · {occupancy}",
  "deployment.visibleUnits": "{count} 个可见单位",
  "deployment.position": "位置 {position}",
  "deployment.locationsHelp": "共 {count} 个区域位置 · 选择卡片以在地图上标记",
  "combat.lastResult": "上次结果 · {result}",
  "combat.dice": "骰子 {die1} + {die2} = {total}",
  "combat.transaction": "战斗结算 · {kind}",
  "combat.artilleryUnit": "炮兵 {id}",
  "combat.allocateHelp": "分配 {steps} 级损失，确认后才会生效。",
  "combat.capacity": "{id} · 可承受 {count} 级",
  "combat.retreatHelp": "需要撤退 {steps} 步，请依次规划各单位的撤退。",
  "combat.retreatDestination": "为 {id} 选择撤退位置。规划所有列出的单位后，统一确认路径。",
  "combat.advanceUnit": "推进 {id}",
  "combat.breakthroughHelp": "突破路径仅包含原目标格之后的额外格位。所选单位最多可前进 {max} 格。",
  "combat.attackWith": "使用 {id} 攻击",
  "rail.edges": "{count} 个区段",
  "movement.steps": "{count} 步",
  "map.viewer": "{side}视角 · {phase}",
  "privacy.combatDecision": "请由{side}作出决策。",
  "privacy.continueAs": "以{side}继续",
  "privacy.passTurn": "请将设备交给{side}玩家。",
  "privacy.beginTurn": "开始{side}回合",
  "map.deploymentHex": "部署位置 {hex}",
  "map.legalMove": "可移动至 {hex}",
  "map.illegalMove": "无法移动至 {hex}",
  "map.railEdge": "铁路区段 {edge}",
  "counter.damage": "损伤等级 {step}",
  "counter.fullStrength": "满编",
  "counter.label": "{side} {type} {id}；{status}；攻击 {attack}，防御 {defense}，移动 {movement}；{supply}；格内 {count} 个单位{entrenched}",
  "counter.entrenchedSuffix": "；已掘壕",
  "counter.stack": "本格共有 {count} 个单位",
  "language.label": "语言",
  "resource.cp": "指挥点",
  "resource.rp": "补充点",
  "faction.german": "德军",
  "faction.soviet": "苏军",
  "unit.infantry": "步兵",
  "unit.eliteInfantry": "精锐步兵",
  "unit.jager": "猎兵",
  "unit.armor": "装甲部队",
  "unit.tank": "坦克",
  "unit.heavyTank": "重型坦克",
  "unit.motorized": "摩托化部队",
  "unit.artillery": "炮兵",
  "unit.engineer": "工兵",
  "unit.recon": "侦察",
  "unit.antiTank": "反坦克部队",
  "unit.hq": "司令部",
  "terrain.plain": "平原",
  "terrain.forest": "森林",
  "terrain.hill": "丘陵",
  "terrain.rough": "崎岖地",
  "terrain.marsh": "沼泽",
  "terrain.city": "城市",
  "terrain.lake": "湖泊",
  "terrain.river": "河流",
  "terrain.road": "公路",
  "terrain.railway": "铁路",
  "terrain.hex": "六角格",
  "status.supplied": "补给正常",
  "status.outOfSupply": "补给中断",
  "status.entrenched": "已掘壕",
  "status.damaged": "受损",
  "status.destroyed": "已消灭",
  "status.selected": "已选择",
  "status.ready": "就绪",
  "phase.deployment": "部署",
  "phase.supplyRail": "补给／铁路",
  "phase.movement": "移动",
  "phase.combat": "战斗",
  "phase.reinforcementSupply": "增援／补给",
  "phase.recovery": "恢复",
  "phase.entrenchment": "掘壕",
  "phase.gameOver": "游戏结束",
  "combat.stage.defenderReaction": "防御方反应",
  "combat.stage.lossAllocation": "分配损失",
  "combat.stage.retreat": "撤退",
  "combat.stage.advance": "战后推进",
  "combat.stage.breakthrough": "突破选择",
  "combat.stage.schwerpunkt": "重点突击选择",
  "combat.stage.closed": "已完成",
  "combat.stage.resolved": "已结算",
  "combat.stage.declared": "已发起",
  "reinforcement.unresolved": "未解析",
  "reinforcement.ambiguous": "无法确定",
  "victory.finalCapture": "德军在最后回合占领首都",
  "victory.heldCapital": "德军占领首都并保持至苏军回合结束",
  "victory.defended": "苏军守住首都直至回合上限",
  "faction.side": "{side}",
  "phase.side": "{side} · {phase}",
  "feedback.chooseEnemy": "选择高亮的敌方单位，查看战斗预览。",
  "feedback.noLegalAttack": "此单位当前无法攻击，请选择其他单位。",
  "feedback.selectDeployment": "请先选择要部署的单位。",
  "feedback.deploymentSelected": "已选择位置，请确认部署。",
  "feedback.deploymentSelectAgain": "请重新选择单位和部署位置。",
  "feedback.deployedNext": "{id} 已部署；如有其他预备队，已自动选中下一个。",
  "feedback.deployed": "{id} 已部署至 {hex}。",
  "feedback.phaseComplete": "{phase}已完成。",
  "feedback.deploymentRevealed": "部署完成，进入德军第 1 回合；玩家视野已启用。",
  "feedback.sideActive": "已切换至{side}界面。",
  "feedback.developerViewer": "开发视角已切换至{side}。",
  "feedback.selectControlled": "请先选择己方可控制的单位。",
  "feedback.unitUnavailable": "所选单位不可用。",
  "feedback.undoPath": "已撤销最后一步路径。",
  "feedback.adjacentOnly": "路径只能延伸至相邻六角格。",
  "feedback.pathDraft": "已规划至 {hex}，准备好后请确认移动。",
  "feedback.pathCleared": "已清空路径。",
  "feedback.moveCancelled": "已取消移动计划。",
  "feedback.needPath": "请先规划至少一步移动。",
  "feedback.moved": "{id} 已移动 {count} 步，到达 {hex}。",
  "feedback.railMode": "点击铁路区段，将其加入修复计划或从计划中移除。",
  "feedback.notRailway": "此区段没有铁路。",
  "feedback.railPlan": "铁路计划：已选择 {count} 个区段。",
  "feedback.railCleared": "已清空铁路修复计划。",
  "feedback.needRail": "请至少选择一个铁路区段。",
  "feedback.railAccepted": "已修复 {count} 个铁路区段。",
  "feedback.needReinforcement": "请先选择苏军增援。",
  "feedback.reinforced": "{id} 已部署在 {hex}。",
  "feedback.needDamaged": "请先选择受损的己方单位。",
  "feedback.recovered": "{id} 已恢复一级损伤。",
  "feedback.entrenched": "{id} 已掘壕。",
  "feedback.combatAccepted": "{action}已执行。",
  "feedback.pendingCombat": "请先完成当前战斗决策，再发起新的攻击。",
  "feedback.unavailable": "单位不可用。",
  "feedback.needAttacker": "请选择己方可控制的攻击单位。",
  "feedback.attackDraft": "攻击计划：{count} 个直接参战单位。",
  "feedback.invalidTarget": "无法选择攻击目标：{issues}",
  "feedback.targetSelected": "已选择目标 {hex}。",
  "feedback.attackCleared": "已清空攻击计划。",
  "feedback.needTarget": "请先选择攻击单位和敌方目标格。",
  "feedback.noReaction": "当前没有待处理的防御方反应。",
  "feedback.invalidLossUnit": "此单位不能承担本次损失。",
  "feedback.lossDraft": "损失分配：{count}/{steps} 级。",
  "feedback.undoLoss": "已撤销最后一级损失分配。",
  "feedback.lossCleared": "已清空损失分配。",
  "feedback.noLoss": "当前没有待分配的损失。",
  "feedback.needRetreater": "请先选择需要撤退的单位。",
  "feedback.retreaterUnavailable": "撤退单位不可用。",
  "feedback.retreatComplete": "已规划所需撤退距离，请选择下一个单位或确认撤退。",
  "feedback.illegalRetreat": "无法撤退至该格。",
  "feedback.retreatDraft": "{id} 的撤退计划：{count} 步。",
  "feedback.noRetreat": "当前没有待处理的撤退。",
  "feedback.breakthroughDraft": "突破计划：额外前进 {count} 格。",
  "action.attack": "攻击",
  "action.pass_reaction": "跳过反应",
  "action.combat_reaction": "防御炮兵支援",
  "action.allocate_losses": "分配损失",
  "action.pass_advance": "跳过推进",
  "action.breakthrough": "突破",
  "action.pass_breakthrough": "跳过突破",
  "action.schwerpunkt_attack": "重点突击",
  "action.pass_schwerpunkt": "跳过重点突击",
  "error.ACTION_ID_DUPLICATE": "此操作已经提交。",
  "error.ARTILLERY_ALREADY_USED": "此炮兵已在当前支援时段提供过支援。",
  "error.BATTLE_ID_DUPLICATE": "此战斗编号已被使用。",
  "error.CANNOT_ENTRENCH": "此类单位无法掘壕。",
  "error.COMBAT_STAGE_MISMATCH": "此决策与当前战斗阶段不符。",
  "error.COMBAT_TRANSACTION_NOT_FOUND": "找不到对应的战斗。",
  "error.COMMITMENT_NOT_FOUND": "找不到对应的单位参战授权。",
  "error.CONTROLLER_ALREADY_READY": "己方已完成本阶段操作。",
  "error.CORE_CANNOT_ENTRENCH": "首都核心格无法掘壕。",
  "error.DEPLOYMENT_UNIT_UNAVAILABLE": "此单位无法部署。",
  "error.DUPLICATE_ID": "选择中存在重复项目。",
  "error.EMPTY_MOVE_PATH": "请至少规划一步移动。",
  "error.ENEMY_OCCUPIED_HEX": "此位置被敌方单位占用。",
  "error.ENEMY_ZOC_STOP": "敌方控制区阻止了此操作。",
  "error.ENEMY_ZOC_TO_ZOC": "无法在这些敌方控制格之间直接移动。",
  "error.HEX_OUT_OF_BOUNDS": "此位置超出地图范围。",
  "error.HQ_ALREADY_USED": "此司令部已使用过。",
  "error.HQ_OUT_OF_RANGE": "单位超出司令部范围。",
  "error.IMPASSABLE_TERRAIN": "无法进入此地形。",
  "error.INITIAL_DEPLOYMENT_INCOMPLETE": "请将全部单位部署到合法位置后再结束部署。",
  "error.INSUFFICIENT_CP": "指挥点不足。",
  "error.INSUFFICIENT_MP": "移动点不足。",
  "error.INVALID_ADVANCE": "无法执行此次推进。",
  "error.INVALID_BATTLE_REFERENCE": "战斗引用无效。",
  "error.INVALID_BREAKTHROUGH": "无法执行此次突破。",
  "error.INVALID_CONTROLLER": "当前操作方无效。",
  "error.INVALID_DEPLOYMENT_HEX": "此位置无法部署。",
  "error.INVALID_LOSS_ALLOCATION": "此损失分配无法确认。",
  "error.INVALID_REACTION": "无法执行此防御方反应。",
  "error.INVALID_RETREAT": "此撤退计划无法确认。",
  "error.INVALID_SUPPORT": "所选单位或支援不满足此操作的要求。",
  "error.MOVED_THIS_TURN": "此单位已在本回合移动。",
  "error.NON_ADJACENT_HEX": "下一步必须进入相邻六角格。",
  "error.NOT_ADJACENT_TO_TARGET": "攻击单位必须与目标相邻。",
  "error.NOT_UNIT_CONTROLLER": "你无法控制此单位。",
  "error.NO_DEFENDER": "目标格内没有敌方防御单位。",
  "error.PENDING_DECISION_BLOCKS_ACTION": "请先完成待处理决策，再执行其他操作。",
  "error.PENDING_DECISION_BLOCKS_PHASE_END": "请先完成待处理决策，再结束阶段。",
  "error.PENDING_DECISION_CONTROLLER_MISMATCH": "此决策需要由另一位玩家作出。",
  "error.RULE_NOT_IMPLEMENTED": "当前不支持此操作。",
  "error.SCHWERPUNKT_UNAVAILABLE": "无法执行此次重点突击。",
  "error.STACKING_LIMIT": "已达到堆叠上限。",
  "error.UNAUTHORIZED_UNIT_COMMITMENT": "此单位未获得本次战斗的参战授权。",
  "error.UNIT_ALREADY_ATTACKED": "此单位已经攻击过。",
  "error.UNIT_ALREADY_MOVED": "此单位已经移动过。",
  "error.UNIT_DESTROYED": "此单位已被消灭。",
  "error.UNIT_NOT_FOUND": "找不到此单位。",
  "error.WRONG_PHASE": "当前阶段无法执行此操作。",
  "error.WRONG_SIDE": "当前不是该方的操作时机。",
  "error.reason.DEDICATED_RAIL_REPAIR": "此工兵在本回合剩余时间内专用于铁路修复。",
  "error.reason.DEPLOYABLE_REINFORCEMENT_REMAINS": "请先处理仍可部署的增援。",
  "error.reason.GAME_OVER": "对局已结束。",
  "error.reason.INITIAL_DEPLOYMENT": "当前只能部署单位或结束部署阶段。",
  "error.reason.REINFORCEMENT_ALREADY_DEPLOYED": "此增援已经部署。",
  "error.reason.REINFORCEMENT_ENTRY_INACTIVE": "此东部铁路出口未连接至有效的东部铁路网。",
  "error.reason.REINFORCEMENT_ENTRY_IN_GERMAN_ZOC": "此东部铁路出口位于德军控制区内。",
  "error.reason.REINFORCEMENT_ENTRY_NOT_EAST_EXIT": "请在东部铁路出口部署增援。",
  "error.reason.REINFORCEMENT_NOT_YET_AVAILABLE": "此增援尚未可用。",
  "error.reason.REINFORCEMENT_SLOT_UNKNOWN": "找不到此增援。",
  "error.reason.REINFORCEMENT_TEMPLATE_UNRESOLVED": "此增援的单位模板不可用。",
  "error.reason.REINFORCEMENT_TEMPLATE_AMBIGUOUS": "无法确定此增援的单位模板。",
  "error.reason.RAIL_REPAIR_ALREADY_USED": "本回合已使用铁路修复。",
  "error.reason.EMPTY_RAIL_REPAIR_PLAN": "请至少选择一个铁路区段。",
  "error.reason.INVALID_RAIL_ENGINEER": "所选工兵无法支援铁路修复。",
  "error.reason.RAIL_REPAIR_LIMIT_EXCEEDED": "修复计划超出本回合的额度。",
  "error.reason.UNKNOWN_RAIL_EDGE": "所选铁路区段不存在。",
  "error.reason.EDGE_HAS_NO_RAILWAY": "此区段没有铁路。",
  "error.reason.EDGE_ALREADY_GERMAN_REPAIRED": "此铁路已可供德军使用。",
  "error.reason.RAIL_PLAN_DISCONNECTED": "全部修复区段必须接入修复后的有效德军铁路网。",
  "error.reason.UNIT_NOT_DAMAGED": "满编单位无需恢复。",
  "error.reason.NORMAL_SUPPLY_REQUIRED": "恢复需要正常补给。",
  "error.reason.ARTILLERY_USED_THIS_TURN": "本回合提供过炮兵支援的单位无法恢复。",
  "error.reason.ENEMY_ADJACENT": "与敌方单位相邻时无法恢复。",
  "error.reason.RECOVERY_BASE_TOO_FAR": "单位超出恢复基地范围。",
  "error.reason.UNIT_TEMPLATE_NOT_FOUND": "找不到此单位的恢复模板。",
  "error.reason.INSUFFICIENT_RP": "补充点不足。",
  "error.reason.UNIT_ALREADY_RECOVERED_THIS_TURN": "此单位本回合已恢复过。",
  "error.reason.RECOVERY_UNIT_LIMIT_REACHED": "已达到本回合可恢复单位数量上限。",
  "error.support.needAttacker": "攻击需要至少一个直接参战单位。",
  "error.support.supportOnly": "仅能提供支援的单位不能直接参与攻击。",
  "error.support.attackerArtillery": "所选攻击方炮兵不满足该目标的支援资格、射程或补给要求。",
  "error.support.schwerpunktArtillery": "所选重点突击炮兵不满足存活、补给、支援资格或射程要求。",
  "error.unknown": "无法完成此操作（{code}）。",
  "terrain.mainCity": "主城区",
  "terrain.outerCity": "外围城区",
  "status.temporarySupply": "临时补给"
} satisfies Record<keyof typeof enUS,string>;
