import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {hash,atomic} from '../../ai/lab/common.mjs';
const out='evidence/ai-midgame-015',phase=JSON.parse(readFileSync(out+'/phase.json')),ds=JSON.parse(readFileSync(out+'/decisions.json')),reps=JSON.parse(readFileSync(out+'/representatives.json'));
const coord=h=>`(${h.q},${h.r})`,path=a=>a.path.map(coord).join('→'),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const types={ARTILLERY:'炮兵',ENGINEER:'工兵',INFANTRY:'步兵',JAGER:'猎兵',MOTORIZED:'摩步',PANZER:'装甲',RECON:'侦察'};
const inventory=phase.before.units.map(before=>{
 const after=phase.after.units.find(u=>u.id===before.id),actions=ds.filter(d=>d.choice.intent.unitId===before.id),d=actions[0]??ds.at(-1),at=d.units.find(u=>u.id===before.id),candidates=d.offlineCoreCandidates.filter(c=>c.intent.unitId===before.id),scores=d.candidateScores.filter(c=>c.intent.unitId===before.id),forward=candidates.filter(c=>c.distance<at.distance),legalForward=forward.filter(c=>!c.core.issues.length),actual=actions[0]?.choice.intent;
 const submitted=actual?candidates.find(c=>same(c.intent,actual)):null,search=reps.searches.find(s=>s.n===d.n&&s.unitId===before.id),entry=ds[0].offlineCoreCandidates.filter(c=>c.intent.unitId===before.id);
 const qualification={n:d.n,alive:at.alive,hasMoved:at.hasMoved,dedicatedRailRepair:at.dedicatedRailRepair,baseMP:at.baseMP,submittedMove:submitted?{spentMP:submitted.core.spentMP,maxMP:submitted.core.maxMP,arithmeticUnused:submitted.core.maxMP-submitted.core.spentMP,reusableAfterMove:false}:null};
 let classification;
 if(actual&&after.distance<before.distance)classification='单位前进；全军最近值不变';
 else if(legalForward.length)classification=actual?'有已核验前进候选；选择等距MOVE':'有已核验前进候选；未提交该单位MOVE';
 else if(search?.immobileFirstStepProof)classification='六首步均不可跨越；固定局面普通MOVE无路';
 else if(search?.witness)classification='Core有多格前进路线；不在Host候选';
 else if(search?.exhaustedWithinScope)classification='有界多格检查未发现前进路线';
 else classification='候选受规则阻挡；多格路线证据不足';
 return {id:before.id,type:before.type,before,after,decisionCheckpoint:d.n,qualification,strategicTarget:null,targetStatus:'UNKNOWN: no original target/assignment field; endpoint is not intent',submittedActions:actions.map(d=>({n:d.n,traceLine:d.traceLine,choice:d.choice,status:d.result.status})),playerView:{baseCandidates:scores.length,finiteScores:scores.filter(c=>Number.isFinite(c.score)).length,hostMoveCandidates:candidates.length,candidateScores:scores},offlineCore:{legalForwardCandidates:legalForward,otherCandidates:candidates.filter(c=>!legalForward.includes(c)),search:search??null},phaseEntryVsDecision:{entryN:ds[0].n,entryCandidateCount:entry.length,decisionN:d.n,changedSameIntentChecks:candidates.flatMap(c=>{const old=entry.find(x=>same(x.intent,c.intent));return old&&!same(old.core.issues,c.core.issues)?[{intent:c.intent,entryIssues:old.core.issues,decisionIssues:c.core.issues}]:[]})},classification};
});
const startMin=Math.min(...phase.before.units.filter(u=>u.alive).map(u=>u.distance)),endMin=Math.min(...phase.after.units.filter(u=>u.alive).map(u=>u.distance));
const summary={task:'AI-MIDGAME-015',source:'a655892a1eed5f8a136b6c73b9d9000560df8d91',scope:'1017/E T6 GERMAN_MOVEMENT n373..389 only',units:inventory.length,submittedMoves:inventory.reduce((n,u)=>n+u.submittedActions.length,0),acceptedMoves:inventory.flatMap(u=>u.submittedActions).filter(a=>a.status==='ACCEPTED').length,rejectedMoves:inventory.flatMap(u=>u.submittedActions).filter(a=>a.status==='REJECTED').length,advancedTowardCapital:inventory.filter(u=>u.after.distance<u.before.distance).map(u=>u.id),movedEqualDistance:inventory.filter(u=>u.submittedActions.length&&u.after.distance===u.before.distance).map(u=>u.id),unmoved:inventory.filter(u=>!u.submittedActions.length).map(u=>u.id),nearest:{before:startMin,after:endMin,beforeUnits:phase.before.units.filter(u=>u.distance===startMin).map(u=>u.id),afterUnits:phase.after.units.filter(u=>u.distance===endMin).map(u=>u.id)},rngUnchanged:same(phase.rngBefore,phase.rngAfter),recordedTargetAndScores:'UNKNOWN / absent in original trace; ranking numbers are offline reconstruction that exactly reproduces saved choices',noForwardCandidateDoesNotMeanNoMultiHexRoute:true,newGames:0,policyOrRulesChanges:false};
assert.equal(inventory.length,26);assert.equal(summary.submittedMoves,16);assert(summary.rngUnchanged);
atomic(out+'/units.json',inventory);atomic(out+'/summary.json',summary);
let md=`# 1017/E T6 德军逐单位表\n\n范围仅 n373–389（原 trace 行374–390），26个在册德军单位全部列入。首都距离为到两个首都核心格的最小六角距离。n373前/ n389后是阶段快照；“决策点”则是该单位实际提交 MOVE 前的冻结状态，未提交单位采用全军 READY 前 n389，二者不得混用。\n\n战力写为“耐损余量/最大；当前基础攻/防（失补有效攻）”；耐损余量不是战斗胜率。本阶段所有德军失补。M0/R0 表示未普通移动/未专职修铁，均活着且属德军控制，属于资格检查而非路径合法性保证。B为扣失补后的单次基础MP；花/限为实际完整MOVE的spentMP/maxMP。成功MOVE后hasMoved=true，即使算术余额为正也不可再次MOVE。未行动单位只有基础额度，没有可自由反复消费的MP池。\n\n原记录没有战略目标或兵力指派字段：**每个单位实际战略目标均未知**，下表路径是动作内容，不从终点反推意图。评分是原策略在冻结PlayerView上的离线复现，不是原日志记载。PlayerView候选与权威Core移动验证分列；“通过”默认指移动验证，代表节点另有完整Engine接受证据。\n\n| 单位/兵种 | 剩余战力 | 阶段位置；距 | 实际决策点资格/MP | 目标；提交→接受 | PlayerView候选 | Core前进选项/阻挡 | 判断 |
|---|---|---|---|---|---|---|---|\n`;
for(const u of inventory){const b=u.before,a=u.after,q=u.qualification,acts=u.submittedActions,own=u.playerView,core=u.offlineCore,seen=core.legalForwardCandidates;let option;
 if(seen.length){const best=seen.slice().sort((a,b)=>a.distance-b.distance||a.intent.path.length-b.intent.path.length)[0];option=`${seen.length}条通过；例${path(best.intent)}，距${best.distance}，${best.core.spentMP}/${best.core.maxMP}MP`;}
 else if(core.search?.witness){const w=core.search.witness;option=`无前进单步；离线多格${path(w.intent)}获Engine接受；不在Host候选`;}
 else {const reasons=[...new Set(core.otherCandidates.flatMap(c=>c.core.issues.map(i=>i.code)))];option=`未见合法前进候选；${reasons.join('/')||'—'}；${core.search?`有界查${core.search.tested}路径，未命中`:'未扩展多格，未知'}`;}
 const mp=q.submittedMove?`花${q.submittedMove.spentMP}/${q.submittedMove.maxMP}；算术余${q.submittedMove.arithmeticUnused}但不可再MOVE`:'未用普通MOVE';
 md+=`| ${u.id} ${types[u.type]} | ${b.remainingDamageCapacity}/${b.maxDamageSteps}；${b.stats.attack}/${b.stats.defense}（${b.effectiveAttack}） | ${coord(b.hex)}→${coord(a.hex)}；${b.distance}→${a.distance} | n${q.n} M${Number(q.hasMoved)}/R${Number(q.dedicatedRailRepair)} B${q.baseMP}；${mp} | 未知；${acts.length?acts.map(a=>`n${a.n} ${path(a.choice.intent)}→接受`).join('；'):'无本单位MOVE；n389全军READY'} | 单步${own.baseCandidates}，有限分${own.finiteScores}；Host含前缀${own.hostMoveCandidates} | ${option} | ${u.classification} |\n`;
}
md+='\n逐个原候选、评分/tie、Core问题码、阶段入口与实际决策差异见 [units.json](units.json)；17个完整决策见 [decisions.json](decisions.json)。代表路线和多格边界见 [representatives.json](representatives.json)。证据索引见 [checkpoint-index.json](checkpoint-index.json)。\n';writeFileSync(out+'/units.md',md);
let actions='# T6 原始行动顺序（非目标指派）\n\n| n / 原行号 | 已提交且接受动作 | 本阶段重建排名检查 |\n|---|---|---|\n';for(const d of ds)actions+=`| ${d.n}/${d.traceLine} | ${d.choice.intent.type==='MOVE'?d.choice.intent.unitId+' '+path(d.choice.intent):d.choice.intent.type} | 与原选择完全一致；${d.baseCandidateCount}基础候选；搜索预算耗尽=${d.scorerMetrics.exhausted} |\n`;writeFileSync(out+'/actions.md',actions);
console.log(JSON.stringify(summary));
