const $=id=>document.getElementById(id),game=$('game');
const config=await fetch('/s006/config.json',{cache:'no-store'}).then(r=>r.json());
if(new URLSearchParams(location.search).has('terrainLoad'))throw Error('Only one default run is authorized');
const local=location.hostname==='127.0.0.1',budgetMs=local&&new URLSearchParams(location.search).has('localBudgetMs')?Math.min(300000,Math.max(1000,Number(new URLSearchParams(location.search).get('localBudgetMs')))):300000;
let snapshot=null,started=false,stopped=false,finishing=false,startAt=0,claim=null,lastJSON='',receipt=null,samplingTimer,deadlineTimer,clockTimer,firstMap=null,closeShotRequested=false,capturePending=null,saveChain=Promise.resolve(),wasVisible=true,visibleAt=0,visibleMs=0;
const samples=[],screenshots=[],captureRequests=new Map();let requestId=0;
const elapsed=()=>started?performance.now()-startAt:0;
const send=(type,extra={})=>{if(game.isConnected)game.contentWindow.postMessage({startup006:type,...extra},location.origin);};
const conditions=()=>({device:$('device').value.trim()||'未填',network:$('network').value.trim()||'未填',cacheCondition:$('cache').value});
const hex=buffer=>Array.from(new Uint8Array(buffer)).map(v=>v.toString(16).padStart(2,'0')).join('');
function addSample(reason){if(!snapshot||!started)return;const t=snapshot.diagnostics.terrainBuild;const row={reason,elapsedMs:snapshot.snapshotAt-snapshot.marks.startAt,outerElapsedMs:elapsed(),visibility:snapshot.visibility,at:snapshot.snapshotAt,camera:t.camera,current:snapshot.current,pipeline:t.pipeline,active:t.active,recent:t.recent};row.withinBudget=row.elapsedMs>=0&&row.elapsedMs<=budgetMs&&row.outerElapsedMs<=budgetMs;if(samples.length<40&&samples.at(-1)?.at!==row.at)samples.push(row);}
function status(){if(stopped||finishing||!snapshot)return;const t=snapshot.diagnostics.terrainBuild,c=t.camera,close=t.pipeline?.ready.includes('close'),mounted=snapshot.current.lod==='close';$('status').textContent=`已观察 ${Math.floor(elapsed()/1000)} / ${budgetMs/1000} 秒；视口 ${snapshot.viewport.width}×${snapshot.viewport.height}，DPR ${snapshot.viewport.dpr}\nA 阈值指标 ${c?.screenHexWidth?.toFixed(3)??'尚无'}（近景须 >96）；缩放 ${c?.zoom??'尚无'} / ${c?.maxZoom??'尚无'}；面板 ${snapshot.current.panelExpanded==='true'?'展开':'收起/未出现'}\nB 构建 ${close?'close 已完成':'close 未完成'}；实际画布 ${snapshot.current.lod??'尚无'}${mounted?'（仍需核验内容和截图）':''}`;$('shot').disabled=!snapshot.current.canvas;}
async function uploadRecord(reason,final=false){if(!snapshot)return;addSample(reason);const observed=$('visual').checked;
 const valid=samples.filter(s=>s.withinBudget),a=valid.some(s=>s.current.panelExpanded==='false'&&s.camera?.screenHexWidth>96),evidence=screenshots.some(s=>s.lod==='close'&&s.withinBudget&&s.readyClose);
 const outcome=snapshot.failed||reason==='user-error'?'failed':final?(a&&evidence&&observed?'observed-success':'incomplete'):'sampling';
 const data={schema:'STARTUP006-device-v1',sourceCommit:config.sourceCommit,deliveryHead:config.deliveryHead,claimId:claim?.id,mode:'default',...conditions(),exportedAt:new Date().toISOString(),outcome,final,stopReason:final?reason:null,observations:{closeContentCorrect:observed,notes:$('notes').value},assessmentHints:{A_reachedWhileCollapsed:a,B_readyMountedScreenshot:evidence,B_userConfirmed:observed,notFinalAcceptance:true},budget:{limitMs:budgetMs,outerElapsedMs:elapsed(),foregroundObservedMs:visibleMs+(wasVisible?performance.now()-visibleAt:0),continuedObservationAfterStop:false},firstMap,samples:[...samples],screenshots:[...screenshots],...snapshot};
 const text=JSON.stringify(data,null,2)+'\n';lastJSON=text;$('backup').value=text;$('download').disabled=false;
 const expected=hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));const r=await fetch('/s006/records',{method:'POST',headers:{'Content-Type':'application/json'},body:text});if(!r.ok)throw Error('JSON save HTTP '+r.status);const saved=await r.json();if(saved.sha256!==expected||saved.bytes!==new TextEncoder().encode(text).length)throw Error('JSON receipt mismatch');receipt=saved;$('receipt').textContent=`JSON 已实际保存并校验：${saved.id}\nSHA256 ${saved.sha256}`;return saved;
}
function queueSave(reason,final=false){const run=saveChain.then(()=>uploadRecord(reason,final));saveChain=run.catch(()=>{});return run;}
async function capture(){if(capturePending)return capturePending;if(!snapshot?.current.canvas)return;
 capturePending=(async()=>{const id=++requestId;const data=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{captureRequests.delete(id);reject(Error('Screenshot unavailable within capture deadline'));},8000);captureRequests.set(id,value=>{clearTimeout(timeout);resolve(value);});send('screenshot',{requestId:id});});if(data.error)throw Error(data.error);
  const expected=hex(await crypto.subtle.digest('SHA-256',await data.blob.arrayBuffer()));const r=await fetch('/s006/screenshot',{method:'POST',headers:{'Content-Type':'image/png'},body:data.blob,signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('PNG save HTTP '+r.status);const saved=await r.json();if(saved.sha256!==expected||saved.bytes!==data.blob.size)throw Error('PNG receipt mismatch');const d=data.state.diagnostics.terrainBuild;
  const shot={...saved,at:data.at,lod:data.lod,width:data.width,height:data.height,elapsedMs:data.at-data.state.marks.startAt,withinBudget:data.at-data.state.marks.startAt<=budgetMs&&elapsed()<=budgetMs,readyClose:d.pipeline?.ready.includes('close')===true,camera:d.camera,progress:data.state.progress};screenshots.push(shot);$('receipt').textContent=`地形 PNG 已保存并校验：${saved.id}，实际画布 ${shot.lod}`;return shot;
 })();try{return await capturePending;}finally{capturePending=null;}}
async function finish(reason){if(finishing||stopped)return;finishing=true;clearInterval(samplingTimer);clearInterval(clockTimer);clearTimeout(deadlineTimer);$('start').disabled=$('shot').disabled=$('save').disabled=$('failure').disabled=true;game.style.pointerEvents='none';$('status').textContent='正在保存截止时诊断；观察已停止，请勿刷新。';
 send('snapshot');await new Promise(r=>setTimeout(r,100));
 try{if(reason!=='budget-expired'&&snapshot?.current.canvas)await capture();}catch(error){$('receipt').textContent='截图未确认：'+error.message;}
 // Detach the candidate before final network saving so no new terrain work is observed.
 game.remove();stopped=true;visibleMs+=wasVisible?performance.now()-visibleAt:0;wasVisible=false;
 try{await queueSave(reason,true);$('status').textContent=`本次观察已停止（${reason==='budget-expired'?'五分钟采样预算到时':reason==='user-error'||snapshot?.failed?'出现异常':'用户结束观察'}）。JSON 保存回执见下方。请回到聊天告知实际画面结果；不要刷新或追加串行测试。`;}catch(error){$('status').textContent='观察已停止，但本机保存未确认：'+error.message+'。请下载当前 JSON 并报告，不要重试启动。';}
}
window.addEventListener('message',e=>{if(!game.isConnected||e.source!==game.contentWindow||e.origin!==location.origin||!e.data?.startup006)return;
 const {startup006:type,data}=e.data;
 if(type==='ready'){$('start').disabled=false;send('snapshot');}
 if(type==='screenshot')captureRequests.get(data.requestId)?.(data);
 if(type==='snapshot'){snapshot=data;if(started&&!firstMap&&data.marks.mapDomReadyAt!==null)firstMap={viewport:data.viewport,current:data.current,camera:data.diagnostics.terrainBuild.camera,at:data.snapshotAt};status();if(started&&!finishing&&!stopped){if(data.failed){void finish('detected-error');return;}if(elapsed()>=budgetMs){void finish('budget-expired');return;}if(data.current.lod==='close'&&data.diagnostics.terrainBuild.pipeline?.ready.includes('close')&&!closeShotRequested){closeShotRequested=true;void capture().then(()=>queueSave('first-real-close-canvas')).catch(error=>{$('receipt').textContent='自动截图未确认：'+error.message;});}}}
});
game.onload=()=>{const doc=game.contentDocument;if(!doc.querySelector('#app'))return;const script=doc.createElement('script');script.type='module';script.src='/s006/observer.mjs';doc.head.append(script);};game.src='/r1/index.html?startupDiag=1';
$('start').onclick=async()=>{if(started||stopped||finishing)return;const c=conditions();if(c.device==='未填'||c.network==='未填'){$('status').textContent='请先填写实际设备和网络。';return;}$('start').disabled=true;
 try{const r=await fetch('/s006/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});if(!r.ok)throw Error('本次启动未获准，请不要刷新（'+r.status+'）');claim=await r.json();started=true;startAt=performance.now();visibleAt=startAt;wasVisible=document.visibilityState==='visible';game.style.pointerEvents='auto';$('save').disabled=$('failure').disabled=false;send('start');
  samplingTimer=setInterval(()=>{if(elapsed()>=budgetMs){void finish('budget-expired');return;}send('snapshot');setTimeout(()=>{if(!finishing)void queueSave('interval').catch(error=>{$('receipt').textContent='定时保存未确认：'+error.message;});},100);},config.sampleIntervalMs);
  deadlineTimer=setTimeout(()=>void finish('budget-expired'),budgetMs);clockTimer=setInterval(()=>{if(elapsed()>=budgetMs)void finish('budget-expired');else status();},1000);
 }catch(error){$('status').textContent=error.message;stopped=true;game.remove();}};
document.addEventListener('visibilitychange',()=>{if(!started||stopped)return;const t=performance.now();if(wasVisible)visibleMs+=t-visibleAt;wasVisible=document.visibilityState==='visible';visibleAt=t;if(elapsed()>=budgetMs)void finish('budget-expired');});
$('shot').onclick=()=>void capture().then(()=>queueSave('manual-screenshot')).catch(error=>{$('receipt').textContent='截图未确认：'+error.message;});
$('save').onclick=()=>void finish('user-finished');$('failure').onclick=()=>void finish('user-error');
$('download').onclick=()=>{if(!lastJSON)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([lastJSON],{type:'application/json'}));a.href=url;a.download='startup006-default.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
