import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{gunzipSync}from'node:zlib';
import * as c from '../../.ai003-preview/vendor/eastfront-digital-core/dist/index.js';
import{isQueryDraft,isNetworkAction,queryDraft}from'../../.ai003-preview/src/multiplayer/gameplayProtocol.js';import{createPresentationState}from'../../.ai003-preview/src/state/presentation.js';import{LocalMatch}from'../../.ai003-preview/ai/local/LocalMatch.js';
const replay=JSON.parse(gunzipSync(readFileSync('evidence/ai-playtest-002/GERMAN.replay.json.gz'))),engine=new c.RulesEngine(c.defaultRules,c.defaultScenario);let s=replay.initial;
for(const e of replay.attempts){if(s.phase==='GERMAN_SUPPLY_RAIL')break;let r=engine.apply(structuredClone(s),{...e.choice.intent,controllerId:Object.values(s.controllers).find(x=>x.side===e.owner).id});if(r.accepted)s=r.state;}
const action={type:'RAIL_REPAIR',controllerId:Object.values(s.controllers).find(x=>x.side==='GERMAN').id,edgeKeys:['0,4|1,4']},r=engine.apply(structuredClone(s),action);assert(r.accepted);assert.equal(r.state.edges[action.edgeKeys[0]].railway.repairedBy,'GERMAN');assert.deepEqual(r.state.rp,s.rp);assert.deepEqual(r.state.cp,s.cp);assert(c.hasGermanRailRepairActionThisTurn(r.state));assert(!engine.apply(structuredClone(r.state),action).accepted);
const draft=queryDraft(createPresentationState());draft.railRepairEdgeKeys=action.edgeKeys;assert(isQueryDraft(draft));const{controllerId,...intent}=action;assert(isNetworkAction(intent));assert(!isNetworkAction({...intent,edgeKeys:['0,4|1,4|2,4']}));assert(!isNetworkAction({...intent,edgeKeys:['0,4|1,4;bad']}));
const match=new LocalMatch({state:structuredClone(s),rules:c.defaultRules,scenario:c.defaultScenario,engine,activeViewerControllerId:controllerId,lastResult:null,integrityIssues:[]},'GERMAN');const first=match.snapshot().payload;const query=match.request('QUERY_MATCH',{matchId:first.matchId,expectedRevision:0,draft},'rail-query');assert.equal(query[0].messageType,'MATCH_QUERY');assert.equal(query[0].payload.model.railRepair.selectedEdgeKeys[0],action.edgeKeys[0]);const submit=match.request('SUBMIT_ACTION',{matchId:first.matchId,expectedRevision:0,action:intent},'rail-submit');assert.equal(submit[0].messageType,'ACTION_ACCEPTED');assert.equal(match.audit().edges[action.edgeKeys[0]].railway.repairedBy,'GERMAN');
const invalid=engine.apply(structuredClone(s),{...action,engineerUnitId:Object.values(s.units).find(u=>u.alive&&u.side==='GERMAN'&&u.type!=='ENGINEER').id});assert(!invalid.accepted);console.log(invalid.issues);
// Existing replay's later qualified engineer, if any, is used without modifying status.
let source=replay.initial,qualified=null;
for(const e of replay.attempts){if(source.phase==='GERMAN_SUPPLY_RAIL')for(const u of Object.values(source.units)){if(!u.alive||u.type!=='ENGINEER'||u.side!=='GERMAN')continue;for(const edge of Object.values(source.edges)){if(!edge.railway?.present)continue;const a={...action,edgeKeys:[edge.key],engineerUnitId:u.id};const q=engine.apply(structuredClone(source),a);if(q.accepted){qualified={turn:source.turn,unit:u.id,edge:edge.key,dedicated:q.state.units[u.id].dedicatedRailRepair,rpSame:JSON.stringify(source.rp)===JSON.stringify(q.state.rp),cpSame:JSON.stringify(source.cp)===JSON.stringify(q.state.cp)};break;}}if(qualified)break;}if(qualified)break;const q=engine.apply(structuredClone(source),{...e.choice.intent,controllerId:Object.values(source.controllers).find(x=>x.side===e.owner).id});if(q.accepted)source=q.state;}
writeFileSync('evidence/playable-002/rail-check.json',JSON.stringify({source:'AI002 existing legal replay; no modified state',ordinary:{action,before:s.edges[action.edgeKeys[0]].railway,after:r.state.edges[action.edgeKeys[0]].railway,rp:s.rp,cp:s.cp,repeat:engine.apply(structuredClone(r.state),action).issues},hunter:invalid.issues,engineer:qualified},null,2)+'\n');console.log('Rail Core action, free RP/CP, once guard, invalid hunter and existing engineer checked',qualified);
