import type {GrandPort} from './grand.js';
import {controlRegions,frontPath} from './controlRegions.js';
import {hexKey,hexNeighbors,hexPolygon,pointString} from '../geometry/hex.js';
let viewportPaint=()=>{};let endedTimer:ReturnType<typeof setTimeout>|null=null,endedScope='';const endedUntil=new Map<string,number>();
export function refreshBattleMapViewport(){viewportPaint();}
const NS='http://www.w3.org/2000/svg',esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const stages:Record<string,string>={ACTIVE:'持续交战',WITHDRAWING:'发生撤退',ENDED:'交战结束'};
function attr(el:Element,key:string,value:string){if(el.getAttribute(key)!==value)el.setAttribute(key,value);}
function keyed(parent:Element,key:string,tag='g'){let el=Array.from(parent.children).find(el=>el.getAttribute('data-map-key')===key);if(!el){el=document.createElementNS(NS,tag);el.setAttribute('data-map-key',key);parent.append(el);}return el as SVGElement;}
function clean(parent:Element,keys:Set<string>){for(const el of Array.from(parent.children))if(!keys.has(el.getAttribute('data-map-key')!))el.remove();}
const patch=(el:Element,html:string)=>{if(el.getAttribute('data-markup')!==html){el.innerHTML=html;el.setAttribute('data-markup',html);}};
export function mapPanel(p:GrandPort,id:string|null){const m=p.data.continuous.map;if(!m)return '';const all=[...m.battles,...m.history],b=all.find((b:any)=>b.id===p.selections.battle),g=p.data.continuous.corps.find((g:any)=>g.id===(p.selections['campaign-group']??p.data.continuous.corps[0].id));
 const f=m.fronts.find((f:any)=>f.id===g.id),draft=JSON.parse(p.selections.frontDraft??'[]'),active=b&&b.status!=='ENDED',own=b?.participants.filter((u:any)=>u.side===p.data.viewer)??[],unit=p.data.continuous.units[id!];
 return `<section class="panel-block battle-map-panel"><h3>战线与交战</h3><p class="map-legend">蓝灰：己方 · 赭红：敌方 · 灰：已确认中立<br>实线：控制交界；点线：视野边缘（对侧未知）；金虚线：选中军团计划</p><label><input type="checkbox" id="map-tactical" ${p.selections.tactical?'checked':''}>显示已知敌邻接（战术参考）</label><p>本共同时间规则无旧ZOC停步。未知区域不补画归属。</p><details ${draft.length?'open':''}><summary>为 ${esc(g.name)} 指定前沿</summary><p>逐格添加1–8个相连地块。守备覆盖至邻格；推进任务分散至各指定点。目标外不追踪敌军。直属部队不自动加入。</p><div class="button-row"><button id="front-add">把当前地图目标加入前沿</button><button id="front-clear">清空草案</button><button id="front-submit">按当前任务委托此地段</button><button id="front-release">解除地段，恢复单点命令</button></div><p>草案：${esc(draft.map(hexKey).join(' → ')||'未选择，先从地图指定目标')}</p><p>已授权 ${g.order.front?.length??0}格；参与 ${f.count}队；无分配 ${f.unassigned.length}格；当前邻域已覆盖 ${f.covered.length}格。满员、缺补给或搜索受阻时保留原位并报告。</p></details>
 <div class="battle-list">${m.battles.map((x:any)=>`<button data-open-battle="${x.id}" aria-pressed="${b?.id===x.id}">⚔ ${x.id} · ${esc(x.role)} · ${x.ticks*5}分</button>`).join('')||'<p>当前无已知持续战斗。</p>'}</div>
 ${b?`<article id="battle-detail"><h3>⚔ ${b.id} · ${esc(stages[b.status])}</h3><p>${esc(b.role)} · ${b.ticks*5}分钟已实际交战<br><b>${esc(b.assessment)}</b>：${esc(b.reason)}</p>${b.result?`<p>${esc(b.result)}</p>`:''}<p>接触位置 ${hexKey(b.hex)}；已知地形 ${esc(b.terrain)}。接触图标不表示占领。</p>${b.participants.map((u:any)=>`<p><b>${esc(u.id)}</b> ${u.side===p.data.viewer?'己方':'已识别敌方'} ${esc(u.type)}<br>组织度 ${u.org===null?'未知':Math.round(u.org)+'%'}；人员 ${u.personnel===null?'未知':Math.ceil(u.personnel)+'/'+u.max}；补给 ${u.supply===null?'未知':u.supply.toFixed(2)+' SP'}<br>装备 ${u.equipment?esc(Object.entries(u.equipment).map(([k,v])=>k+':'+v+'/'+(u.equipmentCapacity?.[k]??'?')).join(' ')):'未知'}<br>所在地 ${esc(u.terrain??'未知')} · 地形承伤除数 ${u.cover??'未知'}${u.reason?'<br>'+esc(u.reason):''}</p>`).join('')}${b.unknownParticipants?'<p>另有未识别交战对象；不披露编号与位置。</p>':''}<details><summary>实际结算因素</summary>${b.factors.map((s:string)=>'<p>'+esc(s)+'</p>').join('')}<p>地形作用于各目标所在地，不将接触位置当作双方同一种地形。未获授权的敌方系数不显示。</p></details><div class="button-row">${own.map((u:any)=>`<button data-battle-take="${u.id}" ${!active||p.locked?'disabled':''}>接管 ${u.id} / 停止主动攻击</button><button data-battle-retreat="${u.id}" ${!active||p.locked||!p.officerTarget?'disabled':''}>${u.id} 撤向地图目标</button>`).join('')}<button id="battle-reinforce" ${!active||!unit?.alive||own.some((u:any)=>u.id===id)||p.locked?'disabled':''}>所选部队增援</button></div><p>${active?'撤回需先从地图指定目的地；增援需先选不在此战斗中的己方单位。接管不冻结敌军攻击。':'战斗已结束，不能再对旧战斗下令。'}撤回仍受通行和占位裁决，无安全保证。</p></article>`:''}
 <details><summary>已结束战斗记录（最近20场）</summary>${m.history.slice().reverse().map((x:any)=>`<button data-open-battle="${x.id}">${x.id} · ${esc(x.result)}</button>`).join('')||'暂无'}</details></section>`;
}
export function bindMapPanel(p:GrandPort,id:string|null,refresh:()=>void){if(!p.data.continuous.map)return;const c=p.data.continuous,group=()=>c.corps.find((g:any)=>g.id===(p.selections['campaign-group']??c.corps[0].id)),run=(op:any)=>void p.operation(op);
 document.querySelectorAll<HTMLElement>('[data-open-battle]').forEach(el=>el.onclick=()=>{p.selections.battle=el.dataset.openBattle!;refresh();});
 document.getElementById('map-tactical')?.addEventListener('change',e=>{p.selections.tactical=(e.target as HTMLInputElement).checked?'1':'';refresh();});
 document.getElementById('front-add')?.addEventListener('click',()=>{const a=JSON.parse(p.selections.frontDraft??'[]');if(p.officerTarget&&a.length<8&&!a.some((h:any)=>hexKey(h)===hexKey(p.officerTarget!)))a.push(p.officerTarget);p.selections.frontDraft=JSON.stringify(a);refresh();});
 document.getElementById('front-clear')?.addEventListener('click',()=>{p.selections.frontDraft='[]';refresh();});
 document.getElementById('front-submit')?.addEventListener('click',()=>{const g=group(),front=JSON.parse(p.selections.frontDraft??'[]'),value=(id:string)=>(document.getElementById(id) as HTMLSelectElement).value;run({type:'ORDER',group:g.id,order:{kind:value('campaign-kind'),risk:value('campaign-risk'),target:p.officerTarget??g.order.target,front,paused:false}});});
 document.getElementById('front-release')?.addEventListener('click',()=>{const g=group(),{front,...order}=g.order;run({type:'ORDER',group:g.id,order});});
 const direct=(unit:string,kind:string,target:any,paused=false)=>run({type:'DIRECT',unit,battleId:p.selections.battle,order:{kind,target,risk:'LOW',paused}});
 document.querySelectorAll<HTMLElement>('[data-battle-take]').forEach(el=>el.onclick=()=>direct(el.dataset.battleTake!,'HOLD',c.units[el.dataset.battleTake!].hex,true));
 document.querySelectorAll<HTMLElement>('[data-battle-retreat]').forEach(el=>el.onclick=()=>direct(el.dataset.battleRetreat!,'RETREAT',p.officerTarget));
 document.getElementById('battle-reinforce')?.addEventListener('click',()=>{const b=c.map.battles.find((b:any)=>b.id===p.selections.battle);if(b&&id)direct(id,'ADVANCE',b.hex);});
}
export function paintBattleMap(p:GrandPort,point:(h:any)=>{x:number;y:number},refresh:()=>void,canInspect:()=>boolean){
 const paintStarted=performance.now();const svg=document.querySelector<SVGSVGElement>('#eastfront-map'),c=p.data.continuous,m=c.map;if(!svg||!m)return;
 viewportPaint=()=>{if(svg.isConnected)paintBattleMap(p,point,refresh,canInspect);};
 const layer=(id:string,before=false)=>{let el=svg.querySelector<SVGGElement>('#'+id);if(!el){el=document.createElementNS(NS,'g');el.id=id;el.setAttribute('pointer-events','none');if(before)svg.insertBefore(el,svg.querySelector('#city-art-static')??svg.querySelector('#fog-surface-layer'));else svg.append(el);}return el;};
 const region=layer('control-regions',true),bounds=layer('control-boundaries'),fronts=layer('corps-fronts'),bubbles=layer('battle-bubbles');
 const bubbleNext=svg.querySelector('#corps-markers')??svg.querySelector('#map-dynamic-layer');if(bubbles.nextElementSibling!==bubbleNext)svg.insertBefore(bubbles,bubbleNext);
 const view=p.data.game.message.payload.view,signature=JSON.stringify([view.viewer,view.identifiedHexKeys,view.hexes.map((h:any)=>h.control)]);
 if(region.getAttribute('data-control-signature')!==signature){const data=controlRegions(view);region.setAttribute('data-control-signature',signature);const keys=new Set<string>();for(const [side,d]of Object.entries(data.fills)){keys.add(side);const el=keyed(region,side,'path');attr(el,'d',d);attr(el,'fill',side===view.viewer?'#28677a':side==='NEUTRAL'?'#a49e84':'#a94739');attr(el,'opacity','.20');}clean(region,keys);
  const wanted=new Set(Object.keys(data.edges));for(const[k,v]of Object.entries(data.edges)){const el=keyed(bounds,k,'path');attr(el,'d',v.d);attr(el,'stroke',v.unknown?'#c8bea2':'#ead09d');attr(el,'stroke-width',v.unknown?'1.2':'3');attr(el,'stroke-dasharray',v.unknown?'2 5':'none');attr(el,'fill','none');}clean(bounds,wanted);
 }
 const group=c.corps.find((g:any)=>g.id===(p.selections['campaign-group']??c.corps[0].id));const front=group.order.front??[];
 const slots=keyed(fronts,'slots');patch(slots,front.map((h:any)=>{const q=point(h);return `<circle cx="${q.x}" cy="${q.y}" r="15" fill="none" stroke="#f8d56e" stroke-dasharray="3 3" stroke-width="3"/>`;}).join(''));
 const plan=keyed(fronts,'plan','path');attr(plan,'d',frontPath(front,point));attr(plan,'stroke','#f8d56e');attr(plan,'stroke-width','6');attr(plan,'stroke-dasharray','10 7');attr(plan,'fill','none');
 const member=c.units[group.members.find((id:string)=>c.units[id]?.alive&&!c.units[id].direct)],arrow=keyed(fronts,'direction');
 if(member){const a=point(member.hex),b=point(group.order.target),ang=Math.atan2(b.y-a.y,b.x-a.x),end={x:b.x-12*Math.cos(ang),y:b.y-12*Math.sin(ang)};patch(arrow,`<path d="M${a.x},${a.y}L${b.x},${b.y}M${end.x+7*Math.sin(ang)},${end.y-7*Math.cos(ang)}L${b.x},${b.y}L${end.x-7*Math.sin(ang)},${end.y+7*Math.cos(ang)}" fill="none" stroke="#f8d56e" stroke-width="3" stroke-dasharray="8 5"/><text x="${a.x}" y="${a.y-48}" fill="#f8d56e" stroke="#182823" stroke-width=".3" font-size="12">${esc(group.name)} · ${group.order.paused?'暂停计划':'命令方向'}</text>`);}else patch(arrow,'');
 const tactical=keyed(fronts,'tactical');if(p.selections.tactical){const map=new Set(view.hexes.map((h:any)=>hexKey(h.coord))),cells=new Map<string,any>();for(const e of view.units.filter((u:any)=>u.side!==view.viewer))for(const h of hexNeighbors(e.hex))if(map.has(hexKey(h)))cells.set(hexKey(h),h);patch(tactical,`<path d="${[...cells.values()].map(h=>'M'+hexPolygon(h).map(p=>pointString(p)).join('L')+'Z').join('')}" fill="none" stroke="#e8af5c" stroke-width="1.3" stroke-dasharray="2 4"/>`);}else patch(tactical,'');
 // Stable battle hosts; compact collisions into an expandable actual-ID list.
 const matrix=svg.getScreenCTM(),scale=Math.max(.03,Math.hypot(matrix?.a??1,matrix?.b??0)),size=Math.max(1,1/scale);
 attr(svg,'data-map-strategy',scale<.28?'yes':'no');attr(svg,'data-map-planning',canInspect()?'no':'yes');
 const scope=p.data.instanceId+':'+view.viewer;if(endedScope!==scope){endedScope=scope;endedUntil.clear();}const now=performance.now();for(const b of m.recent)if(!endedUntil.has(b.id))endedUntil.set(b.id,now+8000);for(const id of endedUntil.keys())if(!m.recent.some((b:any)=>b.id===id))endedUntil.delete(id);
 const recent=m.recent.filter((b:any)=>(endedUntil.get(b.id)??0)>now);if(endedTimer)clearTimeout(endedTimer);endedTimer=recent.length?setTimeout(()=>viewportPaint(),Math.max(1,Math.min(...recent.map((b:any)=>endedUntil.get(b.id)!))-now+5)):null;
 const all=[...m.battles,...recent],clusters:any[][]=[];for(const b of all){const pos=point(b.hex),touching=clusters.filter(a=>a.some(other=>{const q=point(other.hex);return Math.hypot(q.x-pos.x,q.y-pos.y)*scale<100;}));if(touching.length){const merged=[...touching.flat(),b];for(const a of touching)clusters.splice(clusters.indexOf(a),1);clusters.push(merged);}else clusters.push([b]);}
 const wanted=new Set<string>();for(const cluster of clusters){const lead=cluster[0],expanded=p.selections['battle-cluster']===lead.id,pos=point(lead.hex);
  for(const [i,b]of cluster.entries()){wanted.add(b.id);const el=keyed(bubbles,b.id);attr(el,'data-battle-id',b.id);attr(el,'transform',`translate(${pos.x+36*size+(expanded?i%3*60*size:0)} ${pos.y-36*size+(expanded?Math.floor(i/3)*32*size:0)}) scale(${size})`);attr(el,'display',i&&!expanded?'none':'inline');attr(el,'role','button');attr(el,'tabindex','0');attr(el,'aria-label',`${b.id} ${b.role} ${stages[b.status]}`);attr(el,'pointer-events',canInspect()?'auto':'none');attr(el,'class','battle-bubble');
   patch(el,`<rect x="-27" y="-13" width="54" height="26" rx="11" fill="${b.status==='ENDED'?'#555d59':b.role==='我方防守'?'#365f83':'#924c38'}" stroke="${p.selections.battle===b.id?'#fff4b5':'#efd9ad'}" stroke-width="2"/><text text-anchor="middle" y="4" fill="#fff5df" font-size="11">${b.status==='ENDED'?'终':b.status==='WITHDRAWING'?'↶':b.role==='我方防守'?'守':b.role==='我方进攻'?'攻':'↔'} ${cluster.length>1&&!expanded?cluster.length+'场':b.ticks*5+'分'}</text><title>${esc(b.id+' · '+b.role+' · '+b.reason)}</title>`);
   let down:{x:number;y:number}|null=null;el.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};};el.onclick=e=>{if(!canInspect()||down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;e.stopPropagation();p.selections.battle=b.id;if(cluster.length>1)p.selections['battle-cluster']=expanded?'':lead.id;refresh();document.getElementById('battle-detail')?.scrollIntoView({block:'nearest'});};el.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&canInspect()){e.preventDefault();p.selections.battle=b.id;p.selections['battle-cluster']=lead.id;refresh();}};
  }
 }clean(bubbles,wanted);
 const contest=keyed(fronts,'city-contested');patch(contest,(p.data.cities?.items??[]).filter((city:any)=>city.contested).map((city:any)=>{const main=city.districts.find((d:any)=>d.type==='MAIN');const [q,r]=main.hex.split(',').map(Number),a=point({q,r});return `<text x="${a.x}" y="${a.y+48}" fill="#f5d5ac" stroke="#2a201b" stroke-width=".4" font-size="12">${city.unconfirmed?'已知争夺 · 部分待确认':'附属区争夺'}</text>`;}).join(''));
 const groups=layer('corps-markers');const groupKeys=new Set<string>();c.corps.forEach((g:any,index:number)=>{const us=g.members.map((id:string)=>c.units[id]).filter((u:any)=>u?.alive&&!u.direct);if(!us.length)return;groupKeys.add(g.id);const ps=us.map((u:any)=>point(u.hex)),x=ps.reduce((s:number,p:any)=>s+p.x,0)/ps.length,y=ps.reduce((s:number,p:any)=>s+p.y,0)/ps.length;const el=keyed(groups,g.id);attr(el,'transform',`translate(${x-100*size} ${y+(index-1)*24*size}) scale(${size})`);attr(el,'pointer-events',canInspect()?'auto':'none');attr(el,'role','button');attr(el,'tabindex','0');attr(el,'aria-label','选择'+g.name);patch(el,`<rect x="-35" y="-10" width="70" height="20" rx="3" fill="#28463f" stroke="${g.id===group.id?'#ffe4a0':'#adbcac'}"/><text text-anchor="middle" y="4" fill="#fff1cd" font-size="11">${['Ⅰ 机动','Ⅱ 中央','Ⅲ 预备'][index]} ${g.order.paused?'Ⅱ':'›'}</text>`);el.onclick=e=>{if(canInspect()){e.stopPropagation();p.selections['campaign-group']=g.id;refresh();}};el.onkeydown=e=>{if(e.key==='Enter'&&canInspect()){p.selections['campaign-group']=g.id;refresh();}};});clean(groups,groupKeys);if(groups.nextElementSibling?.id!=='map-dynamic-layer')svg.insertBefore(groups,svg.querySelector('#map-dynamic-layer'));
 attr(svg,'data-map-paint-ms',(performance.now()-paintStarted).toFixed(2));

}
