import {paintCompactForces} from './compactForces.js';
import type {GrandPort} from './grand.js';
import {paintActionArrows,planArrow} from './actionArrows.js';
import {controlRegions,frontPath} from './controlRegions.js';
import {hexKey,hexNeighbors,hexPolygon,pointString} from '../geometry/hex.js';
let viewportPaint=()=>{};
export function refreshBattleMapViewport(){viewportPaint();}
const NS='http://www.w3.org/2000/svg',esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const stages:Record<string,string>={ACTIVE:'持续交战',WITHDRAWING:'发生撤退',ENDED:'交战结束'};
function attr(el:Element,key:string,value:string){if(el.getAttribute(key)!==value)el.setAttribute(key,value);}
function keyed(parent:Element,key:string,tag='g'){let el=Array.from(parent.children).find(el=>el.getAttribute('data-map-key')===key);if(!el){el=document.createElementNS(NS,tag);el.setAttribute('data-map-key',key);parent.append(el);}return el as SVGElement;}
function clean(parent:Element,keys:Set<string>){for(const el of Array.from(parent.children))if(!keys.has(el.getAttribute('data-map-key')!))el.remove();}
const patch=(el:Element,html:string)=>{if(el.getAttribute('data-markup')!==html){el.innerHTML=html;el.setAttribute('data-markup',html);}};
export function mapPanel(p:GrandPort,id:string|null){const m=p.data.continuous.map;if(!m)return '';if(p.selections['map-selected-unit']!==(id??'')){p.selections['map-emphasis']='unit';p.selections['map-selected-unit']=id??'';}const all=[...m.battles,...m.history],b=all.find((b:any)=>b.id===p.selections.battle),g=p.data.continuous.corps.find((g:any)=>g.id===(p.selections['campaign-group']??p.data.continuous.corps[0].id));
 const f=m.fronts.find((f:any)=>f.id===g.id),draft=JSON.parse(p.selections.frontDraft??'[]'),active=b&&b.status!=='ENDED',own=b?.participants.filter((u:any)=>u.side===p.data.viewer)??[],unit=p.data.continuous.units[id!],action=(m.actions??[]).find((a:any)=>a.id===p.selections.action);
 return `<section class="panel-block battle-map-panel"><details class="r2-map-tools"><summary>战线、计划与图层</summary><p class="map-legend">蓝灰：己方 · 赭红：敌方 · 灰：已确认中立<br>实线：控制交界；点线：视野边缘（对侧未知）；金色点划线：军团前沿；宽透明箭头：计划</p><label><input type="checkbox" id="map-tactical" ${p.selections.tactical?'checked':''}>显示已知敌邻接（战术参考）</label><label><input type="checkbox" id="map-all-arrows" ${p.selections.allArrows?'checked':''}>突出全部行动箭头</label><p class="action-legend"><span>➜ 绿：行军</span> · <span>➤ 红：攻击</span> · <span>⊕ 蓝：支援（不跟进）</span> · 灰折箭：撤回</p><p>圆标颜色表示本方可知战况；箭头颜色表示动作。中性圆标表示依据不足，不代表胜率。</p><p>本共同时间规则无旧ZOC停步。未知区域不补画归属。</p><details ${draft.length?'open':''}><summary>为 ${esc(g.name)} 指定前沿</summary><p>逐格添加1–8个相连地块。守备覆盖至邻格；推进任务分散至各指定点。目标外不追踪敌军。直属部队不自动加入。</p><div class="button-row"><button id="front-add">把当前地图目标加入前沿</button><button id="front-clear">清空草案</button><button id="front-submit">按当前任务委托此地段</button><button id="front-release">解除地段，恢复单点命令</button></div><p>草案：${esc(draft.map(hexKey).join(' → ')||'未选择，先从地图指定目标')}</p><p>已授权 ${g.order.front?.length??0}格；参与 ${f.count}队；无分配 ${f.unassigned.length}格；当前邻域已覆盖 ${f.covered.length}格。满员、缺补给或搜索受阻时保留原位并报告。</p></details>
 </details>${action?`<p class="action-detail"><b>${esc(action.unit)} · ${esc(({MOVE:'行军',ATTACK:'攻击',SUPPORT:'支援攻击',RETREAT:'撤回'} as Record<string,string>)[action.kind])}</b><br>${hexKey(action.from)} → ${hexKey(action.to)} · ${action.status==='ACCEPTED'?'已接受，等待演算':'执行中'}<br>${esc(action.reason)}</p>`:''}<details class="r2-battle-list"><summary>进行中的交战 · ${m.battles.length}</summary><div class="battle-list">${m.battles.map((x:any)=>`<button data-open-battle="${x.id}" aria-pressed="${b?.id===x.id}">⚔ ${x.hex.q},${x.hex.r} · ${esc(x.role)}</button>`).join('')||'<p>当前无已知持续战斗。</p>'}</div></details>
 ${b?`<article id="battle-detail"><header><h3>⚔ ${b.hex.q},${b.hex.r} · ${esc(stages[b.status])}</h3><button id="battle-close" aria-label="收起战斗详情">×</button></header><p>${esc(b.role)} · ${b.ticks*5}分钟<br><b>${esc(b.assessment)}</b>：${esc(b.reason)}</p>
 <div class="button-row"><button id="battle-attack" ${!active||!unit?.alive||!(b.attackEligible??[]).includes(id)||p.locked?'disabled':''}>${esc(id??"未选部队")} 正面攻击</button><button id="battle-support" ${!active||!unit?.alive||!(b.supportEligible??[]).includes(id)||p.locked?'disabled':''}>${esc(id??"未选部队")} 支援攻击（不跟进）</button>${own.map((u:any)=>`<button data-battle-take="${u.id}" ${!active||p.locked?'disabled':''}>接管 ${u.id}</button><button data-battle-retreat="${u.id}" ${!active||p.locked||!p.officerTarget?'disabled':''}>${u.id} 撤向目标</button>`).join('')}</div>
 ${id&&b.eligibilityReasons?.[id]?`<p>${esc(id+'：'+b.eligibilityReasons[id])}</p>`:''}${b.result?`<p>${esc(b.result)}</p>`:''}
 <p>位置 ${hexKey(b.hex)} · ${esc(b.terrain)}；接触不表示占领。</p><table class="battle-roster"><thead><tr><th>已知单位</th><th>组织</th><th>人员</th><th>SP</th></tr></thead><tbody>${b.participants.map((u:any)=>`<tr><th>${u.side===p.data.viewer?`<button data-battle-select="${esc(u.id)}">${esc(u.id)} · ${m.actions?.some((a:any)=>a.unit===u.id&&a.battleId===b.id&&a.kind==='SUPPORT')?'⊕ 支援':m.actions?.some((a:any)=>a.unit===u.id&&a.battleId===b.id&&a.kind==='ATTACK')?'➤ 主攻':'接战'}</button>`:esc(u.id)}<small>${u.side===p.data.viewer?'己方':'敌方'} ${esc(u.type)}</small></th><td>${u.org===null?'?':Math.round(u.org)+'%'}</td><td>${u.personnel===null?'?':Math.ceil(u.personnel)+'/'+u.max}</td><td>${u.supply===null?'?':u.supply.toFixed(2)}</td></tr>`).join('')}</tbody></table>${b.unknownParticipants?'<p>另有未识别对象；编号与位置不披露。</p>':''}
 <details><summary>装备、结算因素与操作说明</summary>${b.participants.map((u:any)=>`<p><b>${esc(u.id)}</b> 装备 ${u.equipment?esc(Object.entries(u.equipment).map(([k,v])=>k+':'+v+'/'+(u.equipmentCapacity?.[k]??'?')).join(' ')):'未知'}<br>所在地 ${esc(u.terrain??'未知')} · 承伤除数 ${u.cover??'未知'}${u.reason?'<br>'+esc(u.reason):''}</p>`).join('')}${b.factors.map((x:string)=>'<p>'+esc(x)+'</p>').join('')}<p>地形作用于各目标所在地。未授权敌方系数不显示。</p><p>${active?'攻击和支援均需邻接、组织与补给合格；支援支付战斗消耗但不因胜利前进。撤回需先选地图目的地。接管仅停止主动命令，敌方攻击仍继续。':'已结束，旧战斗不能下令。'}撤回仍受通行、占位裁决。</p><details><summary>诊断标识</summary>${esc(b.id)}</details></details></article>`:''}
 <details><summary>已结束战斗记录（最近20场）</summary>${m.history.slice().reverse().map((x:any)=>`<button data-open-battle="${x.id}">${x.hex.q},${x.hex.r} · ${esc(x.result)}</button>`).join('')||'暂无'}</details></section>`;
}
export function bindMapPanel(p:GrandPort,id:string|null,refresh:()=>void){if(!p.data.continuous.map)return;const c=p.data.continuous,group=()=>c.corps.find((g:any)=>g.id===(p.selections['campaign-group']??c.corps[0].id)),run=(op:any)=>void p.operation(op);
 document.getElementById('battle-close')?.addEventListener('click',()=>{delete p.selections.battle;delete p.selections.action;p.selections['map-emphasis']='unit';refresh();});
 document.querySelectorAll<HTMLElement>('[data-open-battle]').forEach(el=>el.onclick=()=>{p.selections.battle=el.dataset.openBattle!;p.selections['map-emphasis']='battle';refresh();});
 document.getElementById('map-tactical')?.addEventListener('change',e=>{p.selections.tactical=(e.target as HTMLInputElement).checked?'1':'';refresh();});
 document.getElementById('map-all-arrows')?.addEventListener('change',e=>{p.selections.allArrows=(e.target as HTMLInputElement).checked?'1':'';refresh();});
 document.getElementById('front-add')?.addEventListener('click',()=>{const a=JSON.parse(p.selections.frontDraft??'[]');if(p.officerTarget&&a.length<8&&!a.some((h:any)=>hexKey(h)===hexKey(p.officerTarget!)))a.push(p.officerTarget);p.selections.frontDraft=JSON.stringify(a);refresh();});
 document.getElementById('front-clear')?.addEventListener('click',()=>{p.selections.frontDraft='[]';refresh();});
 document.getElementById('front-submit')?.addEventListener('click',()=>{const g=group(),front=JSON.parse(p.selections.frontDraft??'[]'),value=(id:string)=>(document.getElementById(id) as HTMLSelectElement).value;run({type:'ORDER',group:g.id,order:{kind:value('campaign-kind'),risk:value('campaign-risk'),target:p.officerTarget??g.order.target,front,paused:false}});});
 document.getElementById('front-release')?.addEventListener('click',()=>{const g=group(),{front,...order}=g.order;run({type:'ORDER',group:g.id,order});});
 const direct=(unit:string,kind:string,target:any,paused=false)=>run({type:'DIRECT',unit,battleId:p.selections.battle,order:{kind,target,risk:kind==='SUPPORT'||kind==='ATTACK'?'NORMAL':'LOW',paused}});
 document.querySelectorAll<HTMLElement>('[data-battle-take]').forEach(el=>el.onclick=()=>direct(el.dataset.battleTake!,'HOLD',c.units[el.dataset.battleTake!].hex,true));
 document.querySelectorAll<HTMLElement>('[data-battle-retreat]').forEach(el=>el.onclick=()=>direct(el.dataset.battleRetreat!,'RETREAT',p.officerTarget));
 for(const kind of ['ATTACK','SUPPORT'])document.getElementById('battle-'+kind.toLowerCase())?.addEventListener('click',e=>{const current=p.data.continuous,b=current.map.battles.find((b:any)=>b.id===p.selections.battle),key=kind==='ATTACK'?'attackEligible':'supportEligible';if(!(e.currentTarget as HTMLElement).isConnected||p.locked||!id||p.selections['map-selected-unit']!==id||!current.units[id]?.alive||!b?.[key]?.includes(id))return;direct(id,kind,b.hex);});
}
export function paintBattleMap(p:GrandPort,point:(h:any)=>{x:number;y:number},refresh:()=>void,canInspect:()=>boolean,selectUnit:(id:string)=>void=()=>{}){
 const paintStarted=performance.now();const svg=document.querySelector<SVGSVGElement>('#eastfront-map'),c=p.data.continuous,m=c.map;if(!svg||!m)return;
 viewportPaint=()=>{if(svg.isConnected)paintBattleMap(p,point,refresh,canInspect,selectUnit);};
 const layer=(id:string,before=false)=>{let el=svg.querySelector<SVGGElement>('#'+id);if(!el){el=document.createElementNS(NS,'g');el.id=id;el.setAttribute('pointer-events','none');if(before)svg.insertBefore(el,svg.querySelector('#city-art-static')??svg.querySelector('#fog-surface-layer'));else svg.append(el);}return el;};
 const region=layer('control-regions',true),bounds=layer('control-boundaries'),fronts=layer('corps-fronts'),bubbles=layer('battle-bubbles');

 const view=p.data.game.message.payload.view,signature=JSON.stringify([view.viewer,view.identifiedHexKeys,view.hexes.map((h:any)=>h.control)]);
 if(region.getAttribute('data-control-signature')!==signature){const data=controlRegions(view);region.setAttribute('data-control-signature',signature);const keys=new Set<string>();for(const [side,d]of Object.entries(data.fills)){keys.add(side);const el=keyed(region,side,'path');attr(el,'d',d);attr(el,'fill',side===view.viewer?'#28677a':side==='NEUTRAL'?'#a49e84':'#a94739');attr(el,'opacity','.20');}clean(region,keys);
  const wanted=new Set(Object.keys(data.edges));for(const[k,v]of Object.entries(data.edges)){const el=keyed(bounds,k,'path');attr(el,'d',v.d);attr(el,'stroke',v.unknown?'#c8bea2':'#ead09d');attr(el,'stroke-width',v.unknown?'1.2':'3');attr(el,'stroke-dasharray',v.unknown?'2 5':'none');attr(el,'fill','none');}clean(bounds,wanted);
 }
 const group=c.corps.find((g:any)=>g.id===(p.selections['campaign-group']??c.corps[0].id));const front=group.order.front??[];
 const slots=keyed(fronts,'slots');patch(slots,front.map((h:any)=>{const q=point(h);return `<circle cx="${q.x}" cy="${q.y}" r="15" fill="none" stroke="#f8d56e" stroke-dasharray="3 3" stroke-width="3"/>`;}).join(''));
 const plan=keyed(fronts,'plan','path');attr(plan,'d',frontPath(front,point));attr(plan,'stroke','#f8d56e');attr(plan,'stroke-width','6');attr(plan,'stroke-dasharray','10 7');attr(plan,'fill','none');
 const member=c.units[group.members.find((id:string)=>c.units[id]?.alive&&!c.units[id].direct)],arrow=keyed(fronts,'direction');
 if(member){patch(arrow,planArrow(point(member.hex),point(group.order.target),group.order.paused));}else patch(arrow,'');
 const tactical=keyed(fronts,'tactical');if(p.selections.tactical){const map=new Set(view.hexes.map((h:any)=>hexKey(h.coord))),cells=new Map<string,any>();for(const e of view.units.filter((u:any)=>u.side!==view.viewer))for(const h of hexNeighbors(e.hex))if(map.has(hexKey(h)))cells.set(hexKey(h),h);patch(tactical,`<path d="${[...cells.values()].map(h=>'M'+hexPolygon(h).map(p=>pointString(p)).join('L')+'Z').join('')}" fill="none" stroke="#e8af5c" stroke-width="1.3" stroke-dasharray="2 4"/>`);}else patch(tactical,'');
 // One stable badge per authoritative target engagement, never a distance-derived battle.
 const matrix=svg.getScreenCTM(),scale=Math.max(.03,Math.hypot(matrix?.a??1,matrix?.b??0)),size=1/scale;
 attr(svg,'data-r2-focus',p.selections['map-emphasis']??'');attr(svg,'data-map-strategy',scale<.28?'yes':'no');attr(svg,'data-map-planning',canInspect()?'no':'yes');
 const forces=layer('compact-forces'),actions=layer('action-arrows'),leaders=layer('battle-leaders');paintCompactForces(forces,p,point,size,refresh,canInspect,selectUnit);paintActionArrows(actions,p,point,size,canInspect,refresh);
 const wanted=new Set<string>(),placed:{x:number;y:number}[]=[],compactAnchors=view.units.map((u:any)=>point(u.hex));
 for(const b of m.battles){if(b.status==='ENDED')continue;wanted.add(b.id);const anchor=point(b.hex);let pos={x:anchor.x+34*size,y:anchor.y+40*size};
  for(const [dx,dy] of [[34,40],[-34,40],[34,-40],[-34,-40],[56,0],[-56,0]]){const q={x:anchor.x+dx!*size,y:anchor.y+dy!*size};if(!placed.some(o=>Math.hypot(o.x-q.x,o.y-q.y)<42*size)&&!compactAnchors.some((o:any)=>Math.abs(o.x-q.x)<49*size&&Math.abs(o.y-q.y)<38*size)){pos=q;break;}}placed.push(pos);
  const el=keyed(bubbles,b.id);attr(el,'data-battle-id',b.id);attr(el,'transform',`translate(${pos.x} ${pos.y}) scale(${size})`);attr(el,'role','button');attr(el,'tabindex','0');attr(el,'aria-label',`${b.hex.q},${b.hex.r} ${b.role} ${stages[b.status]}`);attr(el,'pointer-events',canInspect()?'auto':'none');attr(el,'class','battle-bubble battle-medallion');
  const leader=keyed(leaders,b.id,'path');attr(leader,'d',`M${pos.x},${pos.y}L${anchor.x},${anchor.y}`);attr(leader,'fill','none');attr(leader,'stroke','#272d27');attr(leader,'stroke-width',String(2*size));attr(leader,'pointer-events','none');
  const selected=p.selections.battle===b.id,color=b.outlook==='FAVORABLE'?'#63865a':b.outlook==='STRAINED'?'#b5634c':'#898879';
  const minor=b.status==='WITHDRAWING'?'撤':b.role==='我方防守'?'守':'攻';
  patch(el,`<circle r="19" fill="transparent"/><circle r="15" fill="#171e20" stroke="${selected?'#d8e5e2':'#101717'}" stroke-width="2"/><circle r="12" fill="${color}" stroke="#34423f" stroke-width="1"/><g stroke="#f2eee1" fill="none" stroke-width="2" stroke-linecap="square"><path d="M-7,-7L6,6M7,-7L-6,6M-8,3L-3,8M3,8L8,3M-7,-7L-3,-6M7,-7L3,-6"/></g><rect x="8" y="8" width="14" height="13" rx="2" fill="#1e2b2e" stroke="#a5b7b5"/><text x="15" y="18" text-anchor="middle" font-size="9" fill="#edf1e8">${minor}</text><title>${esc(b.hex.q+','+b.hex.r+' · '+b.role+' · 已交战'+b.ticks*5+'分钟 · '+b.assessment+'：'+b.reason)}</title>`);
  let down:{x:number;y:number}|null=null;el.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};};const select=()=>{p.selections.battle=b.id;p.selections['map-emphasis']='battle';refresh();document.getElementById('battle-detail')?.scrollIntoView({block:'nearest'});};
  el.onclick=e=>{if(!canInspect()||down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;e.stopPropagation();select();};el.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&canInspect()){e.preventDefault();select();}};
 }clean(bubbles,wanted);clean(leaders,wanted);
 const contest=keyed(fronts,'city-contested');patch(contest,(p.data.cities?.items??[]).filter((city:any)=>city.contested).map((city:any)=>{const main=city.districts.find((d:any)=>d.type==='MAIN');const [q,r]=main.hex.split(',').map(Number),a=point({q,r});return `<text x="${a.x}" y="${a.y+48}" fill="#f5d5ac" stroke="#2a201b" stroke-width=".4" font-size="12">${city.unconfirmed?'已知争夺 · 部分待确认':'附属区争夺'}</text>`;}).join(''));
 const groups=layer('corps-markers'),corpsPlaced:{x:number;y:number}[]=[],unitPoints=view.units.map((u:any)=>point(u.hex));const groupKeys=new Set<string>();c.corps.forEach((g:any,index:number)=>{const us=g.members.map((id:string)=>c.units[id]).filter((u:any)=>u?.alive&&!u.direct);if(!us.length)return;groupKeys.add(g.id);const ps=us.map((u:any)=>point(u.hex)),x=ps.reduce((s:number,p:any)=>s+p.x,0)/ps.length,y=ps.reduce((s:number,p:any)=>s+p.y,0)/ps.length;const el=keyed(groups,g.id);let label={x:Math.min(...ps.map((q:any)=>q.x))-75*size,y};
 const collides=(q:{x:number;y:number})=>unitPoints.some((u:any)=>Math.abs(u.x-q.x)<67*size&&Math.abs(u.y-q.y)<34*size)||placed.some(u=>Math.abs(u.x-q.x)<60*size&&Math.abs(u.y-q.y)<35*size)||corpsPlaced.some(u=>Math.abs(u.x-q.x)<78*size&&Math.abs(u.y-q.y)<27*size);
 for(let n=0;n<24&&collides(label);n++)label={x:Math.min(...ps.map((q:any)=>q.x))-75*size,y:y+(n%2?1:-1)*(Math.floor(n/2)+1)*30*size};corpsPlaced.push(label);
 attr(el,'transform',`translate(${label.x} ${label.y}) scale(${size})`);attr(el,'pointer-events',canInspect()?'auto':'none');attr(el,'role','button');attr(el,'tabindex','0');attr(el,'aria-label','选择'+g.name);patch(el,`<rect x="-35" y="-10" width="70" height="20" rx="3" fill="#28463f" stroke="${g.id===group.id?'#ffe4a0':'#adbcac'}"/><text text-anchor="middle" y="4" fill="#fff1cd" font-size="11">${['Ⅰ 机动','Ⅱ 中央','Ⅲ 预备'][index]} ${g.order.paused?'Ⅱ':'›'}</text>`);el.onclick=e=>{if(canInspect()){e.stopPropagation();p.selections['campaign-group']=g.id;p.selections['map-emphasis']='group';refresh();}};el.onkeydown=e=>{if(e.key==='Enter'&&canInspect()){p.selections['campaign-group']=g.id;p.selections['map-emphasis']='group';refresh();}};});clean(groups,groupKeys);for(const l of [groups,forces,actions,leaders,bubbles])svg.append(l);
 attr(svg,'data-map-paint-ms',(performance.now()-paintStarted).toFixed(2));

}
