import {mapPanel,bindMapPanel,paintBattleMap} from './battleMap.js';
import type {GrandPort} from './grand.js';
const esc=(x:any)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const kinds:Record<string,string>={HOLD:'守住防线',ADVANCE:'向目标推进',RETREAT:'撤回防线',REFIT:'停止进攻，整顿补充'};
export function campaignTime(p:GrandPort){const c=p.data.continuous;return `<section class="panel-block campaign-clock"><h2>第聂伯中央战线</h2><strong>${String(Math.floor(c.minutes/60)).padStart(2,'0')}:${String(c.minutes%60).padStart(2,'0')} / 15:00 · ${c.ended?'已终局':c.paused?'已暂停':'共同时间推进中'}</strong><div class="button-row"><button id="campaign-toggle" ${c.ended||p.locked?'disabled':''}>${c.paused?'继续时间':'暂停时间'}</button>${[1,2,4].map(n=>`<button data-campaign-speed="${n}" aria-pressed="${c.speed===n}">${n}×</button>`).join('')}</div><p>双方同时行动。${c.nextEconomy*5}分钟后结算生产与配送。普通配送不打断。</p>${c.ended?`<p><b>${c.ended.winner==='GERMAN'?'德军达成战役目标':c.ended.winner==='SOVIET'?'苏军达成战役目标':'战役未分胜负'}</b> · ${esc(c.ended.reason)}</p>`:''}<div class="button-row"><button id="campaign-save">保存战役</button><button id="campaign-load">${p.selections['load-confirm']?'确认加载并替换当前':'加载存档（暂停）'}</button>${p.selections['load-confirm']?'<button id="campaign-load-cancel">取消加载</button>':''}</div><p role="status">${esc(p.notice)}</p><details><summary>连接与恢复</summary><p>${esc(p.wireStatus)}</p><p>两个端共同指挥德军，苏军为AI。暂停军官只停止其新命令；暂停世界才停止双方模拟。</p><label>本机模拟延迟<select id="campaign-link"><option value="clean">正常本机</option><option value="rtt1000" ${p.wire?.profile==='rtt1000'?'selected':''}>约1000ms往返</option><option value="constrained" ${p.wire?.profile==='constrained'?'selected':''}>300ms＋抖动限速</option></select></label><button id="campaign-disconnect">短暂断线并重连</button><button id="campaign-resync">重新读取完整授权状态</button><p>未确认意图 ${p.wire?.pending.size??0}/16；状态年龄下界（不含传输） ${p.wire?.serverQueueMs===null?'未知':Math.round((p.wire?.serverQueueMs??0)+(p.wire?.lastViewAt?performance.now()-p.wire.lastViewAt:0))+'ms'}。读取存档会暂停并要求两端重新规划旧意图。</p></details><details><summary>目标与操作帮助</summary><p>夺取中央枢纽，并保有西岸或东岸站区，连续守住120分钟且战役已进行12小时30分；否则15小时后比较三个地点控制。德军由你指挥，苏军由公平视图AI指挥。</p><p>暂停下令 → 委托军团 → 继续。先看组织度与补给，再决定增援或撤回。1×约8秒推进5分钟，完整期限约24分钟，提前达标会结束。</p><label><input id="campaign-autopause" type="checkbox" ${c.autopause?'checked':''}>首次接敌自动暂停</label><p>加载覆盖当前未保存进度。只支持本规则版本；退出前保存。旧兵棋在新局规则列表中保留。</p></details></section>`;}
export function campaignUnit(p:GrandPort,id:string|null){const v=id&&p.data.continuous.units[id],u=p.data.units.find((u:any)=>u.id===id);if(!v)return '<p>在地图选择己方部队，或在军团内定位。可随时调回直属。</p>';return `<h3>${esc(id)} · ${esc(u?.label)}</h3><p>组织度 <b>${v.org.toFixed(0)}%</b> · 人员 ${Math.ceil(v.personnel)}/${v.max}<br>库存 ${(v.stock/4).toFixed(2)} SP · 战役伤亡 ${Math.ceil(v.losses)}</p><p>火力 ${v.fire.toFixed(1)} · 装甲防护 ${v.protection.toFixed(1)} · 机动 ${v.mobility.toFixed(1)}<br>${v.march?`行军剩余 ${v.march.remaining*5}分钟`:v.engaged?'持续交战中':'驻留'} · ${esc(v.reason)}</p><div class="button-row"><button id="campaign-direct">暂停该部队并调回直属</button><button id="campaign-unit-attack" ${p.locked||!p.officerTarget?'disabled':''}>攻击当前地图目标</button></div><p>进攻需先指定已识别敌军所在地，资格由当前授权规则检查。支援攻击请点击现有战斗圆标后下令。</p><p>调回后仍承受正在发生的敌方攻击；不能撤销既有战果。</p>`;}
export function campaignOrders(p:GrandPort,id:string|null){const c=p.data.continuous,sel=(key:string,fallback:string)=>p.selections[key]??fallback;
 const group=sel('campaign-group',c.corps[0].id),g=c.corps.find((g:any)=>g.id===group)??c.corps[0];
 return mapPanel(p,id)+`<section class="panel-block campaign-orders"><h3>军团命令</h3><label>军团<select id="campaign-group">${c.corps.map((g:any)=>`<option value="${g.id}" ${group===g.id?'selected':''}>${esc(g.name)} · ${esc(g.officer)}</option>`).join('')}</select></label><p>${g.order.paused?'待命 / 直属操作':esc(kinds[g.order.kind])}；当前目标 ${g.order.target.q},${g.order.target.r}；${g.members.filter((u:string)=>c.units[u]?.alive).length}支部队</p><div class="button-row">${g.members.filter((u:string)=>c.units[u]?.alive).map((u:string)=>`<button data-campaign-focus="${u}">${u}</button>`).join('')}</div>
 <label>持续任务<select id="campaign-kind">${Object.entries(kinds).map(([k,v])=>`<option value="${k}" ${sel('campaign-kind','ADVANCE')===k?'selected':''}>${v}</option>`).join('')}</select></label><label>目标<select id="campaign-target">${c.goals.map((g:any,i:number)=>`<option value="${i}" ${sel('campaign-target','1')===String(i)?'selected':''}>${esc(g.name)} · ${g.control==='GERMAN'?'己方':g.control==='SOVIET'?'已知敌方':'未确认'}</option>`).join('')}</select></label><button id="campaign-pick">从地图指定目标</button><p>${p.officerTarget?`地图目标 ${p.officerTarget.q},${p.officerTarget.r}`:'未指定地图目标，使用上方地点'}</p><label>允许风险<select id="campaign-risk">${[['LOW','谨慎'],['NORMAL','通常'],['HIGH','加大进攻力度']].map(([k,v])=>`<option value="${k}" ${sel('campaign-risk','NORMAL')===k?'selected':''}>${v}</option>`).join('')}</select></label><div class="button-row"><button id="campaign-order">委托军团执行</button><button id="campaign-stop-group">暂停军团 / 取消行军</button>${id&&c.units[id]?'<button id="campaign-unit-order">向选中直属部队下令</button><button id="campaign-assign">将选中部队委托给当前军团</button>':''}</div><p>普通地图计划不构成授权。命令跨时间保留；暂停军团不会停止全战线时钟。停止行军留在出发格，已付消耗不返还。</p><details><summary>军官与战况报告</summary>${c.reports.slice().reverse().map((r:any)=>`<p>${r.tick*5}分 ${esc(r.unit??'')} · ${esc(r.text)}</p>`).join('')||'<p>尚无事件。</p>'}${g.members.map((id:string)=>`<p>${id}：${esc(c.units[id]?.reason)}</p>`).join('')}</details></section>`;
}
export function campaignEconomy(p:GrandPort,id:string|null){const d=p.data,x=d.ux,disabled=p.locked?'disabled':'',g=x.equipment.find((g:any)=>g.id===id),b=x.last;
 const reason:Record<string,string>={TRUCK_SHORTAGE:'卡车能力不足',TRAIN_SHORTAGE:'火车能力不足',LINE_CAPACITY:'线路容量不足',ROUTE_UNAVAILABLE:'线路当前受阻',MATERIAL_SHORTAGE:'来源物资不足',LINE_OR_SERVICE_RANGE:'无连通线路或超出配送范围'};
 return `<section class="panel-block"><h3>战役生产与配送</h3><p>每120分钟统一结算一次；维护 → 装备 → 补储备。已完成${d.epoch}次结算。新出厂装备下一次配送可发运，送达后进入可用库存。</p><p><b>火车 ${x.vehicles.TRAIN.available} / ${x.vehicles.TRAIN.needed??'—'}；卡车 ${x.vehicles.TRUCK.available} / ${x.vehicles.TRUCK.needed??'—'}</b> 可用 / 上次需求估计</p><p>${b?[...new Set(b.blocked.map((v:any)=>reason[v.reason]??'当前通路无法服务'))].map(esc).join('、')||'本周期无缺额':'等待首次结算'}</p><p>行政预算 ${d.account.I} I · 有限后备 ${d.account.reserve} P。停产工业转为原节点收入；生产不同时领I。接驳2I/P，照管每4P每周期1I，不能免费补员。</p>
 <details open><summary>生产线 · 城市与交通可在地图定位</summary>${x.lines.map((l:any)=>`<div class="ux-line"><label>${esc(l.label)}<select data-ux-line="${esc(l.id)}" ${disabled||!l.controlled?'disabled':''}><option value="IDLE" ${l.product==='IDLE'?'selected':''}>转行政预算</option>${Object.entries(x.products).map(([k,v]:any)=>`<option value="${k}" ${l.product===k?'selected':''}>${esc(v.label)} · ${v.work}工时/件</option>`).join('')}</select></label><p>${l.factories.length}座厂，${l.factories.length*x.work}工时/周期；${l.product==='IDLE'?'当前不生产装备':`进度${l.progress[l.product]}/${x.products[l.product].work}，已产${l.completed[l.product]}件`}</p><button data-ux-focus="${l.hex}">定位工厂</button></div>`).join('')}</details>
 <details><summary>军团补给优先级</summary><p>1优先，5最后；所有维护始终先于装备。改变优先级不创造运力。</p>${x.armies.map((a:any)=>`<div data-ux-army="${esc(a.id)}"><b>${esc(a.id)} · ${a.units}单位 · 净维护缺${a.missingSP}SP</b><label>配送优先<select data-ux-priority ${disabled}>${[1,2,3,4,5].map(n=>`<option value="${n}" ${a.priority===n?'selected':''}>${n}</option>`).join('')}</select></label><label><input type="checkbox" data-ux-materials ${a.materials?'checked':''}>自动人员与装备补充</label><label>额外预备包<select data-ux-reserve>${[0,1,2,3].map(n=>`<option value="${n}" ${a.reserve===n?'selected':''}>${n}</option>`).join('')}</select></label></div>`).join('')}</details>
 ${g?`<details open><summary>${esc(id)}装备与补充</summary>${Object.entries(g.required).map(([k,n]:any)=>`<p>${esc(x.products[k].label)}：${g.held[k]}/${n}；在途/待用${g.staged.filter((l:any)=>l.type===k).reduce((s:number,l:any)=>s+l.qty,0)}</p>`).join('')}<p>补充一个损伤编制组需1P＋${Object.entries(g.recipe).map(([k,n])=>`${n}${x.products[k].label}`).join('＋')}。未交战驻留30分钟、补给正常、材料到账才自动支付。组织度休整不返还伤亡。</p></details>`:''}
 <details><summary>库存、运输路线与真实回执</summary>${d.warehouses.map((w:any)=>`<p>${esc(w.label)}：${w.controlled?'己方':'失去控制'}；${w.lots.filter((l:any)=>l.qty>0).map((l:any)=>`${esc(x.products[l.type]?.label??l.type)} ${l.qty}`).join('、')||'空仓'}</p>`).join('')}<pre>${esc(JSON.stringify({deliveries:b?.deliveries,blocked:b?.blocked,production:d.lastLedger?.production,repairs:d.uses},null,1))}</pre></details></section>`;
}
export function bindCampaign(p:GrandPort,id:string|null,refresh:()=>void,focus:(id:string)=>void,pick:()=>void){
 bindMapPanel(p,id,refresh);
 document.getElementById('campaign-link')?.addEventListener('change',e=>p.wire?.setProfile((e.target as HTMLSelectElement).value));
 document.getElementById('campaign-disconnect')?.addEventListener('click',()=>p.wire?.disconnect());
 document.getElementById('campaign-resync')?.addEventListener('click',()=>p.wire?.resync());
 const c=p.data.continuous,run=(op:any)=>void p.operation(op),value=(id:string)=>(document.getElementById(id) as HTMLSelectElement)?.value;
 for(const key of ['campaign-group','campaign-kind','campaign-target','campaign-risk'])document.getElementById(key)?.addEventListener('change',()=>{p.selections[key]=value(key);if(key==='campaign-group')p.selections['map-emphasis']='group';if(key==='campaign-target')p.officerTarget=null;refresh();});
 const order=(paused=false)=>({kind:value('campaign-kind'),target:p.officerTarget??c.goals[Number(value('campaign-target'))].hex,risk:value('campaign-risk'),paused,...(c.corps.find((g:any)=>g.id===value('campaign-group'))?.order.front?{front:c.corps.find((g:any)=>g.id===value('campaign-group')).order.front}:{})});
 document.getElementById('campaign-toggle')?.addEventListener('click',()=>run({type:'CLOCK',paused:!c.paused,speed:c.speed}));
 document.querySelectorAll<HTMLElement>('[data-campaign-speed]').forEach(el=>el.addEventListener('click',()=>run({type:'CLOCK',paused:c.paused,speed:Number(el.dataset.campaignSpeed)})));
 document.getElementById('campaign-autopause')?.addEventListener('change',e=>run({type:'AUTOPAUSE',enabled:(e.target as HTMLInputElement).checked}));
 document.getElementById('campaign-order')?.addEventListener('click',()=>run({type:'ORDER',group:value('campaign-group'),order:order()}));
 document.getElementById('campaign-stop-group')?.addEventListener('click',()=>run({type:'ORDER',group:value('campaign-group'),order:order(true)}));
 document.getElementById('campaign-assign')?.addEventListener('click',()=>run({type:'ASSIGN',unit:id,group:value('campaign-group')}));
 document.getElementById('campaign-unit-order')?.addEventListener('click',()=>run({type:'DIRECT',unit:id,order:order()}));
 document.getElementById('campaign-direct')?.addEventListener('click',()=>run({type:'DIRECT',unit:id,order:{kind:'HOLD',target:c.units[id!].hex,risk:'LOW',paused:true}}));
 document.getElementById('campaign-unit-attack')?.addEventListener('click',()=>{if(id&&p.officerTarget)run({type:'DIRECT',unit:id,order:{kind:'ATTACK',target:p.officerTarget,risk:'NORMAL',paused:false}});});
 // Select before a network repaint can replace the pressed roster button. Keyboard activation remains click-based.
 document.querySelectorAll<HTMLElement>('[data-campaign-focus]').forEach(el=>{el.onpointerdown=e=>{if(e.button===0)focus(el.dataset.campaignFocus!);};el.onclick=e=>{if(e.detail===0)focus(el.dataset.campaignFocus!);};});
 document.getElementById('campaign-save')?.addEventListener('click',()=>void p.campaignFile('save'));
 document.getElementById('campaign-load')?.addEventListener('click',()=>{if(p.selections['load-confirm']){delete p.selections['load-confirm'];void p.campaignFile('load');}else{p.selections['load-confirm']='1';refresh();}});
 document.getElementById('campaign-load-cancel')?.addEventListener('click',()=>{delete p.selections['load-confirm'];refresh();});
 document.getElementById('campaign-pick')?.addEventListener('click',pick);
}
export function paintCampaign(p:GrandPort,point:(h:{q:number;r:number})=>{x:number;y:number},refresh:()=>void=()=>{},canInspect:()=>boolean=()=>true,selectedUnitId?:string|null){if(selectedUnitId!==undefined&&p.selections['map-selected-unit']!==(selectedUnitId??'')){p.selections['map-selected-unit']=selectedUnitId??'';p.selections['map-emphasis']='unit';}const svg=document.querySelector('#eastfront-map');if(!p.data.continuous?.map)svg?.querySelector('#campaign-overlay')?.remove();const c=p.data.continuous;if(!svg||!c)return;
 document.getElementById('campaign-hud')?.remove();document.querySelector('.topbar .brand')?.insertAdjacentHTML('afterend',`<strong id="campaign-hud">共同时间 ${Math.floor(c.minutes/60)}:${String(c.minutes%60).padStart(2,'0')} · ${c.paused?'暂停':'推进中'} · 德军统帅 / 苏军AI</strong>`);
 svg.querySelectorAll<SVGElement>('[data-unit-id],[data-hit-unit-id]').forEach(el=>{const id=el.dataset.unitId??el.dataset.hitUnitId!,v=c.units[id];el.querySelectorAll('.counter-stats,.compact-stats').forEach(s=>{s.textContent=v?`${Math.round(v.org)}% · ${Math.ceil(v.personnel)}员`:'已识别';});if(el.hasAttribute('aria-label'))el.setAttribute('aria-label',v?`${id} 己方；组织度${Math.round(v.org)}%；人员${Math.ceil(v.personnel)}；${v.reason}`:`${id} 已识别敌军`);});
 if(c.map){paintBattleMap(p,point,refresh,canInspect);return;}
 const marker=(h:any,text:string,color:string)=>{const pos=point(h);return `<g transform="translate(${pos.x} ${pos.y})"><circle r="24" fill="none" stroke="${color}" stroke-width="3"/><text y="-27" text-anchor="middle" fill="${color}" stroke="#142018" stroke-width=".4" font-size="12">${esc(text)}</text></g>`;};
 svg.insertAdjacentHTML('beforeend',`<g id="campaign-overlay" pointer-events="none">${c.goals.slice(0,3).map((g:any)=>marker(g.hex,g.name,'#f8df82')).join('')}${c.battles.map((b:any)=>marker(b.hex,`交战 ${b.ticks*5}分`,'#ff8b6a')).join('')}${c.corps.map((g:any)=>{const u=c.units[g.members.find((id:string)=>c.units[id]?.alive)];return u?marker(u.hex,g.name,'#aee4ca'):'';}).join('')}</g>`);
}
