import {paintAuthorizedCities} from '../render/cityArtRuntime.js';
import type {GrandPort} from './grand.js';
import {hexToPixel,HEX_SIZE} from '../geometry/hex.js';
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const types:Record<string,string>={MAIN:'主城区',STATION:'铁路站区',INDUSTRIAL:'工业区',RESIDENTIAL:'普通城区'};
const reason:Record<string,string>={OCCUPATION:'占领封存',PERSONNEL_EXPIRED:'人员到期隔离',PERSONNEL_CARE_UNPAID:'人员照管欠付隔离',PRIOR_QUARANTINE:'既有隔离未解除',ROUTE_OR_STATION_UNAVAILABLE:'铁路／站场／线路不通',NOT_YET_AVAILABLE:'尚未到可用回合'};
const side=(s:string)=>s==='GERMAN'?'德军':s==='SOVIET'?'苏军':'归属未确认';
export function cityMarkup(p:GrandPort){const data=p.data.cities;if(!data)return '';const city=data.items.find((c:any)=>c.id===p.selections.city)??data.items[0],d=city.districts.find((d:any)=>d.id===p.selections.district)??city.districts[0],off=p.locked||p.data.owner!==p.data.viewer||!!p.data.game.message.payload.view.pendingDecision;
 const w=p.data.warehouses.find((w:any)=>w.id===d.warehouse),line=p.data.ux.lines.find((l:any)=>l.id===d.warehouse);
 return `<section class="panel-block city-panel"><p role="status">${esc(p.notice)}</p>${p.locked?'<button id="city-reconcile">核对上次请求并刷新账本</button><button id="city-retry">使用原请求核对／重试</button>':''}<span class="eyebrow">城市与近郊 · 约10公里/格</span><h3>${esc(city.label)}</h3><label>查看城市<select id="city-select">${data.items.map((c:any)=>`<option value="${esc(c.id)}" ${c.id===city.id?'selected':''}>${esc(c.label)}</option>`).join('')}</select></label><p><b>${side(city.owner)} · ${city.contested?'争夺中':city.unconfirmed?'附属区状态待确认':'已确认控制一致'}</b> · 主城 ${city.vp} VP（原节点合并、不叠加）</p>
 <div class="city-tabs">${city.districts.map((x:any)=>`<button data-city-district="${esc(x.id)}" aria-pressed="${x.id===d.id}">${x.paper} ${types[x.type]}</button>`).join('')}</div>
 <h4>${d.paper} ${types[d.type]} · ${d.unconfirmed&&d.control?'最后确认：'+side(d.control)+'（当前待侦察）':side(d.control)}</h4><p>${d.control===p.data.viewer?(d.service?'运输服务可用':'当前无可用运输服务；控制、铁路连通与路线资格仍须同时满足'):'本方不可使用；不披露隐藏守军或生产情况'}</p>
 <p>工厂槽位 ${d.facilities.length}/${d.slots} · 已建 ${d.facilities.filter((f:any)=>f.status==='BUILT').length}</p>
 ${d.facilities.map((f:any)=>`<p>${f.status==='BUILT'?'▣ 已建厂房':f.status==='BUILDING'?`▧ 施工 ${f.progress}/${data.policy.constructionEpochs}`:'▧ 易手停工 · 进度封存'} ${f.status==='BUILT'&&f.line!=='IDLE'?esc(p.data.ux.products[f.line]?.label):'未分配生产'}</p>`).join('')}
 <button data-city-build="${esc(d.id)}" ${off||!d.canBuild||p.data.account.I<data.policy.constructionI?'disabled':''}>建一座工厂 · ${data.policy.constructionI}I · ${data.policy.constructionEpochs}E</button>
 ${line?`<label>本区持续生产<select data-ux-line="${esc(line.id)}" ${off||!line.controlled?'disabled':''}>${[['IDLE','暂停'],...Object.entries(p.data.ux.products).map(([k,v]:any)=>[k,v.label])].map(([k,v])=>`<option value="${k}" ${k===line.product?'selected':''}>${v}</option>`).join('')}</select></label><p>已分配 ${line.factories.length}座 · ${line.factories.length*p.data.ux.work}产能/E；${line.product==='IDLE'?'暂停':`本产品进度 ${line.progress[line.product]}/${p.data.ux.products[line.product].work}`}；新厂建成自动加入本区线。</p>`:''}
 <div class="city-assets">${(d.sealedConstruction??[]).map((f:any)=>`<p>原方在建厂房 · 占领封存 · ${f.progress}/${data.policy.constructionEpochs}E · 已付${f.paidI}I</p>`).join('')}${(d.assets??[]).map((l:any)=>`<p data-asset-id="${esc(l.id)}">${esc(l.type==='P'?'后备人员':p.data.ux.products[l.type]?.label??l.type)} ×${l.qty} · ${l.recoveredTurn?'夺回恢复；':''}${l.reasons.length?l.reasons.map((r:string)=>reason[r]??r).join('；'):(l.recoveredTurn?'夺回后恢复原库存／可用':'可用')} · 原可用 T${l.availableTurn<Number.MAX_SAFE_INTEGER?l.availableTurn:'—'}</p>`).join('')}${(d.waitingWork??[]).map((l:any)=>`<p>在制品${l.status==='OCCUPATION'?'占领封存':'待分配'}：${esc(p.data.ux.products[l.product]?.label??l.product)}；原进度 ${Object.values(l.progress).reduce((a:any,b:any)=>a+b,0)}。${l.status==='OCCUPATION'?'原方夺回后自动核验恢复。':'生产线分配冲突；先完成现有产品并暂停，后续E自动再核验，不覆盖或合并进度。'}</p>`).join('')}</div>${w?`<p>本区仓储 ${w.lots.reduce((n:number,l:any)=>n+l.qty,0)}/${w.capacity}；配送自动运行。</p>`:''}<button data-city-zoom data-ux-focus="${d.hex}">定位城区</button>
 <details><summary>易手和收益规则</summary><p>主城换旗只带动可安全转移的已列明城区。敌守或敌ZOC城区不投降。建筑保留；旧库存和在制品封存，生产线暂停。施工易手后停工且不退款；原方夺回保留原付款及进度，后续E继续。在制品原产品与进度保留；分配冲突时待分配。人员隔离与占领封存分别判断，夺回不返还过期人员。新厂只增加产能，不增补给来源、不重复领城市收入；原节点收入仍按实际地块控制每E结算一次。</p><p>本方建厂累计支出 ${data.constructionSpentI}I。控制与建设由服务端核验。</p></details></section>`;
}
export function bindCities(p:GrandPort,update:()=>void){if(!p.data?.cities)return;
 document.querySelector('#city-reconcile')?.addEventListener('click',()=>void p.reconcile());
 document.querySelector('#city-retry')?.addEventListener('click',()=>void p.retryPending());
 document.querySelector('#city-select')?.addEventListener('change',e=>{p.selections.city=(e.target as HTMLSelectElement).value;p.selections.district='';update();});
 document.querySelectorAll<HTMLElement>('[data-city-district]').forEach(b=>b.addEventListener('click',()=>{p.selections.district=b.dataset.cityDistrict!;update();}));
 document.querySelectorAll<HTMLElement>('[data-city-build]').forEach(b=>b.addEventListener('click',()=>void p.operation({type:'BUILD_FACTORY',district:b.dataset.cityBuild})));
}
const boundCityMaps=new WeakSet<Element>();
export function paintCities(p:GrandPort,update:()=>void,enhanced=false,canInspect:()=>boolean=()=>true){if(enhanced){const view=p.data.game.message.payload.view;paintAuthorizedCities({revision:p.data.version,viewer:p.data.viewer,cities:p.data.cities.items,edges:view.edges,knownHexKeys:view.contactHexKeys??[]},(cityId,districtId)=>{p.selections.city=cityId;p.selections.district=districtId;update();document.querySelector('.city-panel')?.scrollIntoView({block:'nearest'});},{canInspect});return;}const svg=document.querySelector('#eastfront-map');svg?.querySelector('#city-districts')?.remove();if(!svg||!p.data?.cities)return;
 if(!boundCityMaps.has(svg)){boundCityMaps.add(svg);svg.addEventListener('click',event=>{const target=(event.target as Element).closest<SVGElement>('[data-hex]');if(!target)return;const city=p.data.cities?.items.find((c:any)=>c.districts.some((d:any)=>d.hex===target.dataset.hex));if(!city)return;p.selections.city=city.id;p.selections.district=city.districts.find((d:any)=>d.hex===target.dataset.hex).id;queueMicrotask(update);},{capture:true});}
 const color=(s:string)=>s==='GERMAN'?'#617d92':s==='SOVIET'?'#a16856':'#a39169';
 const markup=p.data.cities.items.flatMap((c:any)=>c.districts.map((d:any)=>{const[q,r]=d.hex.split(',').map(Number),pos=hexToPixel({q,r}),built=d.facilities.filter((f:any)=>f.status==='BUILT'),building=d.facilities.filter((f:any)=>f.status!=='BUILT');
 return `<g transform="translate(${pos.x} ${pos.y})" data-city-map="${esc(c.id)}" data-city-hex="${d.hex}" data-city-did="${esc(d.id)}" role="button" tabindex="0" aria-label="${esc(c.label+' '+d.paper+' '+types[d.type])}"><path d="M-19 -20 L19 -20 L24 0 L19 20 L-19 20 L-24 0 Z" fill="none" stroke="${color(d.control)}" stroke-width="1.5" stroke-dasharray="3 2" pointer-events="none"/><g class="city-near" pointer-events="none">${built.map((f:any,i:number)=>`<g class="built-factory ${d.service?'':'factory-unavailable'}" data-facility-id="${esc(f.id)}" transform="translate(${-18+(i%2)*24} ${-7+Math.floor(i/2)*18})"><image href="./assets/terrain/vs2-002/assets/city/reuse_BC08.png" x="-6" y="-8" width="21" height="20"/><path d="M-6 4 V-5 L0 -9 V-5 L6 -9 V-5 H13 V4Z" fill="#94836a" stroke="#4b4438" stroke-width=".7"/><path d="M0 -5 V-17 H3 V-5" fill="#685c4f" stroke="#302d28" stroke-width=".7"/></g>`).join('')}${building.map((f:any,i:number)=>`<rect data-facility-id="${esc(f.id)}" data-status="${f.status}" x="${-12+i*10}" y="4" width="9" height="8" fill="none" stroke="#b88942" stroke-dasharray="2 1"/>`).join('')}${d.type==='STATION'?'<image href="./assets/terrain/vs2-002/assets/city/station_structure.png" x="-18" y="-16" width="36" height="28"/>':''}</g><text class="city-far" y="5" text-anchor="middle" font-size="28" fill="#fff" stroke="#403b2e" stroke-width=".5" pointer-events="none">${built.length?'厂'+built.length:types[d.type]}${building.length?' 建'+building.length:''}</text><rect x="-23" y="15" width="46" height="11" rx="2" fill="${color(d.control)}"/><text y="23" text-anchor="middle" fill="#fff" font-size="7" pointer-events="none">${esc(d.paper+' '+types[d.type]+(d.unconfirmed?' ?':''))}</text></g>`;})).join('');
 svg.insertAdjacentHTML('beforeend',`<g id="city-districts">${markup}</g>`);
 svg.querySelectorAll<SVGElement>('[data-city-map]').forEach(el=>{const select=()=>{p.selections.city=el.dataset.cityMap!;p.selections.district=el.dataset.cityDid!;update();document.querySelector('.city-panel')?.scrollIntoView({block:'nearest'});};el.addEventListener('click',e=>{e.stopPropagation();select();});el.addEventListener('keydown',e=>{if(e.key==='Enter')select();});});
}
