import {visionPanel} from './territoryVision.js';
import type {GrandPort} from './grand.js';
import {campaignUnit,campaignOrders,campaignEconomy,recoveryPanel} from './campaign.js';
import {mapPanel} from './battleMap.js';
import {cityMarkup} from './cities.js';
import {stackPanel} from './compactForces.js';
import {ownStatus,aggregateStatus,gearSummary,escStatus as esc,numberStatus} from './unitStatus.js';
export const corpsColors=['#8fb9c9','#c6a58d','#b1b889'];
export const tasks:Record<string,string>={HOLD:'守住防线',ADVANCE:'向目标推进',RETREAT:'撤回防线',REFIT:'整顿补充',ATTACK:'攻击',SUPPORT:'支援'};
export function commandedMembers(c:any,g:any){return g.members.filter((id:string)=>c.units[id]?.alive&&!c.units[id].direct);}
export function directMembers(c:any){return Object.keys(c.units).filter(id=>c.units[id].alive&&(c.units[id].direct||!c.corps.some((g:any)=>g.members.includes(id))));}
export function commandSummary(p:GrandPort){const d=p.data,c=d.continuous,ss=Object.keys(c.units).map(id=>ownStatus(p,id)).filter(Boolean),a=aggregateStatus(ss),types=d.ux.products;
 const stock:Record<string,number>={};for(const w of d.warehouses.filter((w:any)=>w.controlled))for(const l of w.lots)if(l.qty>0&&l.availableTurn<=d.turn)stock[l.type]=(stock[l.type]??0)+l.qty;
 return {a,stock,equipment:ss.filter((s:any)=>s.gear?.some((g:any)=>g.missing>0)).map((s:any)=>s.id),low:ss.filter((s:any)=>s.low).map((s:any)=>s.id),supply:ss.filter((s:any)=>s.stock<=0).map((s:any)=>s.id),lines:d.ux.lines.filter((l:any)=>l.controlled&&l.product!=='IDLE').length,blocked:[...new Set((d.ux.last?.blocked??[]).map((x:any)=>x.reason))],stockText:Object.entries(stock).map(([k,v])=>(types[k]?.label??k)+' '+v).join('、')||'暂无可用仓储'};
}
const bottlenecks:Record<string,string>={TRUCK_SHORTAGE:'卡车不足',TRAIN_SHORTAGE:'火车不足',LINE_CAPACITY:'线路容量不足',ROUTE_UNAVAILABLE:'线路中断',MATERIAL_SHORTAGE:'缺物资',LINE_OR_SERVICE_RANGE:'线路或配送范围受限'};
export function commandDock(p:GrandPort,id:string|null,extra:string){const d=p.data,c=d.continuous,s=commandSummary(p),mode=p.selections['ui-panel']??'',group=c.corps.find((g:any)=>g.id===p.selections['campaign-group'])??c.corps[0],direct=directMembers(c),time=String(Math.floor(c.minutes/60)).padStart(2,'0')+':'+String(c.minutes%60).padStart(2,'0');
 const toolbar=`<div class="ui-top"><b class="ui-brand">EASTFRONT <small>第聂伯战线</small></b><button data-ui-panel="economy" title="可用行政预算；不重复累计军团资源">▣ 预算 <strong>${d.account.I}</strong><small>${s.lines}条生产线</small></button><button data-ui-panel="economy" title="${esc(s.stockText)}">▤ 补充<small>${c.recovery?.waiting??s.a?.shortUnits??0}队缺额 · 查库存</small></button><button data-ui-panel="economy">▰ 火车 ${d.ux.vehicles.TRAIN.available}/${d.ux.vehicles.TRAIN.needed??'—'}<small>卡车 ${d.ux.vehicles.TRUCK.available}/${d.ux.vehicles.TRUCK.needed??'—'} · 可用/上次需求</small></button><button data-ui-panel="alerts" class="${s.low.length||s.supply.length||(c.recovery?.waiting??s.equipment.length)||s.blocked.length?'ui-warning':''}">⚑ 待办 ${s.low.length+s.supply.length+(c.recovery?.waiting??s.equipment.length)+s.blocked.length}<small>低组织${s.low.length} · 空补给${s.supply.length}</small></button><div class="ui-clock"><strong>${time}</strong><span>${c.ended?'战役结束':c.paused?'世界暂停':'时间推进'}</span><button id="campaign-toggle" ${c.ended||p.locked?'disabled':''}>${c.paused?'▶ 继续':'Ⅱ 暂停'}</button>${[1,2,4].map(n=>`<button data-campaign-speed="${n}" aria-pressed="${c.speed===n}">${n}×</button>`).join('')}<button id="campaign-save">保存</button><button data-ui-panel="settings">设置／读档</button></div></div>`;
 let body='',title='';
 if(mode==='army'){title=group.name;body=`<p class="ui-front-summary">责任地段 ${group.order.front?.length??0}/8格 · ${c.map.fronts.find((f:any)=>f.id===group.id)?.unassigned.length??0}格未分配</p>`+(c.recovery?`<p>本军团${c.recovery.rows.filter((r:any)=>r.group===group.id&&r.attention).length}队等待编制补充</p><button data-ui-panel="economy">查看缺额与处理入口</button>`:'')+campaignOrders(p,id,false).replace('<details class="r2-orders">','<details open class="r2-orders">')+mapPanel(p,id);}
 if(mode==='unit'){title='部队指挥';body=stackPanel(p)+(id?campaignUnit(p,id)+recoveryPanel(p,id)+`<button data-ui-locate-unit="${esc(id)}">定位所选部队</button><details><summary>下令与编组</summary>${campaignOrders(p,id,false)}</details>`:'<p>点击地图部队，查看状态并下令。</p>');}
 if(mode==='direct'){title='直属部队 · '+direct.length+'队';body='<p>仅由你直接下令；不会自动加入军团。</p>'+direct.map((id:string)=>`<button class="ui-unit-choice" data-ui-unit="${esc(id)}">${esc(id)} · ${esc(ownStatus(p,id)?.action)}<small>${ownStatus(p,id)?.low?'低组织 · ':''}${esc(gearSummary(ownStatus(p,id)))}</small></button>`).join('');}
 if(mode==='battle'||mode==='tools'){title=mode==='battle'?'战斗指挥':'战线与图层';body=mapPanel(p,id)+(mode==='tools'?`<div hidden>${campaignOrders(p,id,false)}</div>`:'');}
 if(mode==='city'){title='城市管理';body=cityMarkup(p);}
 if(mode==='economy'){title='生产与运输';body=`<p>可用仓储：${esc(s.stockText)}</p><p>库存仅计当前已可用的本方仓储；不加在制、在途或部队持有量。</p>`+campaignEconomy(p,id);}
 if(mode==='alerts'){title='统帅待办';body=recoveryPanel(p)+`<h3>低组织 ${s.low.length}队</h3>${s.low.map(id=>`<button data-ui-unit="${id}">${id} · 查看并接管</button>`).join('')||'<p>当前无低组织部队。</p>'}<h3>补给已耗尽 ${s.supply.length}队</h3>${s.supply.map(id=>`<button data-ui-unit="${id}">${id}</button>`).join('')}<h3>装备缺额 ${s.equipment.length}队</h3>${s.equipment.map((id:string)=>`<button data-ui-unit="${id}">${id} · ${esc(gearSummary(ownStatus(p,id)))}</button>`).join('')}<h3>运输瓶颈</h3><p>${s.blocked.map(x=>bottlenecks[String(x)]??'当前通路受限').join('、')||'尚无已报告瓶颈'}</p><button data-ui-panel="economy">管理生产与配送</button><h3>正在交战 ${c.map.battles.length}处</h3>${c.map.battles.map((b:any)=>`<button data-open-battle="${b.id}">⚔ ${b.hex.q},${b.hex.r} · ${esc(b.role)}</button>`).join('')}`;}
 if(mode==='vision'){title='领土视野与历史情报';body=visionPanel(p);}
 if(mode==='settings'){title='战役与连接';body=`<button id="campaign-load">${p.selections['load-confirm']?'确认加载并替换当前':'加载存档（默认暂停）'}</button>${p.selections['load-confirm']?'<button id="campaign-load-cancel">取消加载</button>':''}<p>离开前暂停并保存。加载会使旧请求失效；本候选独立存档。</p><p>${esc(p.wireStatus)}</p><label>连接模拟<select id="campaign-link"><option value="clean">正常本机</option><option value="rtt1000" ${p.wire?.profile==='rtt1000'?'selected':''}>约1000ms往返</option><option value="constrained" ${p.wire?.profile==='constrained'?'selected':''}>300ms＋抖动限速</option></select></label><button id="campaign-disconnect">短暂断线并重连</button><button id="campaign-resync">重新读取授权状态</button><label><input id="campaign-autopause" type="checkbox" ${c.autopause?'checked':''}>首次接敌自动暂停</label><details><summary>目标、图例与口径</summary><p>夺取中央枢纽，保有西岸或东岸站区，连续守住120分钟且已进行12小时30分；15小时截止按原地点控制判断。暂停军官不停止敌军，暂停世界才停止演算。</p><p>绿条组织，金条人员。人员数字四舍五入为整数，比例仍由原始值计算。堆叠组织为各队比例均值，人员为总现有/总满编。低组织低于18，可能触发撤退，退路受阻仍会留在战场。</p><p>实线是当前已知控制交界；灰点线是对侧未知；彩色点划线为所选军团最多8格责任地段，宽箭头是计划。${c.vision?'己方实控区持续可见。灰色斜线地块仅为最后已知；失守不提供敌军后续位置。':'地图没有全域领土记忆，城市的最后已知归属另有待确认标记。'}</p></details><details><summary>普通计划与原操作工具</summary>${extra}</details><button id="ui-exit">返回入口（保留进度）</button><a href="http://127.0.0.1:4233/">打开原4233回退</a>`;}
 const bar=`<nav class="ui-corps-bar" aria-label="常驻军团栏">${c.corps.map((g:any,i:number)=>{const us=commandedMembers(c,g),a=aggregateStatus(us.map((id:string)=>ownStatus(p,id)));return `<div class="ui-corps-card ${p.selections['map-emphasis']==='group'&&group.id===g.id?'selected':''}" style="--corps:${corpsColors[i%3]}"><button data-ui-corps="${esc(g.id)}"><span class="ui-badge">${['Ⅰ','Ⅱ','Ⅲ'][i]??'◇'}</span><span><b>${esc(g.name)}</b><small>${esc(g.officer)} · 指挥${us.length}队</small><small>${g.order.paused?'已暂停':esc(tasks[g.order.kind]??'待命')} ${a?.low?'· 低组织'+a.low:''}</small></span></button><button data-ui-locate="${esc(g.id)}" aria-label="定位${esc(g.name)}">◎</button><button data-ui-stop="${esc(g.id)}" aria-label="暂停${esc(g.name)}">Ⅱ</button></div>`;}).join('')}<button class="ui-direct" data-ui-panel="direct">◇ 直属<small>${direct.length}队</small></button><button data-ui-panel="tools">战线／图层</button><button data-ui-panel="city">城市</button>${c.vision?`<button data-ui-panel="vision">视野<small>实控${c.vision.controlled}格</small></button>`:''}</nav>`;
 return `<div class="r2-dock command-ui">${toolbar}${c.ended||p.notice?`<div class="ui-notice" role="status">${c.ended?esc((c.ended.winner==='GERMAN'?'德军达成战役目标':c.ended.winner==='SOVIET'?'苏军达成战役目标':'战役未分胜负')+' · '+c.ended.reason):esc(p.notice)}</div>`:''}${mode?`<aside class="ui-sidebar" data-mode="${mode}"><header><h2>${esc(title)}</h2><button id="ui-close" aria-label="收起详情">×</button></header><div class="ui-content">${body}</div></aside>`:''}<div class="ui-map-legend">绿条 组织 · 金条 人员　<span>实线 控制交界 · 切角虚框 跨格群组</span></div>${bar}</div>`;
}
export function bindCommandInterface(p:GrandPort,id:string|null,refresh:()=>void,select:(id:string)=>void,locate:(h:any)=>void){const c=p.data.continuous;
 document.querySelectorAll<HTMLElement>('[data-ui-panel]').forEach(el=>el.onclick=()=>{p.selections['ui-panel']=el.dataset.uiPanel!;refresh();});
 document.querySelectorAll<HTMLElement>('[data-vision-locate]').forEach(el=>el.onclick=()=>{const [q,r]=el.dataset.visionLocate!.split(',').map(Number);locate({q,r});});
 document.querySelectorAll<HTMLElement>('[data-ui-locate-force]').forEach(el=>el.onclick=()=>{const u=p.data.game.message.payload.view.units.find((u:any)=>u.id===el.dataset.uiLocateForce);if(u)locate(u.hex);});
 document.getElementById('ui-close')?.addEventListener('click',()=>{p.selections['ui-panel']='';refresh();});
 document.getElementById('ui-exit')?.addEventListener('click',()=>document.getElementById('ai-exit')?.click());
 document.querySelectorAll<HTMLElement>('[data-ui-corps]').forEach(el=>el.onclick=()=>{const g=c.corps.find((g:any)=>g.id===el.dataset.uiCorps);p.selections['campaign-group']=g.id;p.selections['campaign-kind']=g.order.kind;p.selections['campaign-risk']=g.order.risk;p.officerTarget={...g.order.target};p.selections['map-emphasis']='group';p.selections['ui-panel']='army';refresh();});
 document.querySelectorAll<HTMLElement>('[data-ui-locate]').forEach(el=>el.onclick=()=>{const g=c.corps.find((g:any)=>g.id===el.dataset.uiLocate),us=commandedMembers(c,g);if(us.length)locate(c.units[us[0]].hex);});
 document.querySelectorAll<HTMLElement>('[data-ui-locate-unit]').forEach(el=>el.onclick=()=>{const u=c.units[el.dataset.uiLocateUnit!];if(u)locate(u.hex);});
 document.querySelectorAll<HTMLElement>('[data-ui-stop]').forEach(el=>el.onclick=()=>{const g=c.corps.find((g:any)=>g.id===el.dataset.uiStop);void p.operation({type:'ORDER',group:g.id,order:{...g.order,paused:true}});});
 document.querySelectorAll<HTMLElement>('[data-ui-unit]').forEach(el=>el.onclick=()=>{p.selections['ui-panel']='unit';select(el.dataset.uiUnit!);});
}
