import {ownStatus,aggregateStatus,statusBars,statusText,gearSummary,numberStatus} from './unitStatus.js';
import type {GrandPort} from './grand.js';
import {PRESENCE_FAMILY} from '../presentation/unitPresenceTypes.js';
const NS='http://www.w3.org/2000/svg';
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const names:Record<string,string>={INFANTRY:'步',PANZER:'装',TANK:'装',HEAVY_TANK:'重',MOTORIZED:'摩',ARTILLERY:'炮',ENGINEER:'工',RECON:'侦',ANTI_TANK:'反',HQ:'部',TRANSPORT:'运'};
export function stackPanel(p:GrandPort){const view=p.data.game.message.payload.view,us=view.units.filter((u:any)=>u.side+':'+u.hex.q+','+u.hex.r===p.selections.stack);if(!us.length)return '';const a=aggregateStatus(us.map((u:any)=>ownStatus(p,u.id)));return `<section class="r2-stack"><header><b>${us[0].hex.q},${us[0].hex.r} · ${us.length}支已知部队</b><button id="stack-close" aria-label="收起部队堆叠">×</button></header>${a?`<small>组织：各队归一化均值 ${numberStatus(a.orgRatio*100)}%；人员：合计${numberStatus(a.personnel)}/${a.max}（${numberStatus(a.personnelRatio*100)}%）<br>低组织 ${a.low}队（低于${a.threshold}触发原撤退检查，不保证能撤出）</small>`:'<small>仅已识别敌军数量；组织与人员未知</small>'}${us.map((u:any)=>{const v=ownStatus(p,u.id);return `<button data-stack-unit="${esc(u.id)}" ${v?'':'disabled'} title="${esc(statusText(v))}"><b>${esc(u.id)} · ${names[u.type]??u.type}</b>${statusBars(v)}${v?`<small>${esc(v.action)} · ${numberStatus(v.stock)} SP<br>${esc(gearSummary(v))}</small>`:''}</button>`;}).join('')}</section>`;}
/** Display-only grouping of already authorized units; no invented enemy count or merged unit state. */
export function paintCompactForces(layer:SVGElement,p:GrandPort,point:(h:any)=>{x:number;y:number},size:number,refresh:()=>void,canInspect:()=>boolean,select:(id:string)=>void){
 const view=p.data.game.message.payload.view,groups=new Map<string,any[]>(),selected=p.selections['map-selected-unit'],battle=p.data.continuous.map.battles.find((b:any)=>b.id===p.selections.battle);
 for(const u of view.units){const k=u.side+':'+u.hex.q+','+u.hex.r;if(!groups.has(k))groups.set(k,[]);groups.get(k)!.push(u);}
 const keep=new Set<string>();for(const[k,units]of groups){keep.add(k);let el=Array.from(layer.children).find(x=>x.getAttribute('data-stack-key')===k) as SVGGElement|undefined;if(!el){el=document.createElementNS(NS,'g');el.setAttribute('data-stack-key',k);layer.append(el);}units.sort((a,b)=>a.id.localeCompare(b.id));const u=units[0],own=u.side===view.viewer,at=point(u.hex),statuses=units.map(u=>ownStatus(p,u.id)),summary=own?aggregateStatus(statuses):null,chosen=units.some(u=>u.id===selected),inBattle=units.some(u=>battle?.participants.some((x:any)=>x.id===u.id)),f=(PRESENCE_FAMILY as Record<string,string>)[u.type]??'infantry';
 el.setAttribute('transform',`translate(${at.x} ${at.y}) scale(${size})`);el.setAttribute('data-anchor',u.hex.q+','+u.hex.r);el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`${own?'己方':'已识别敌方'} ${u.hex.q},${u.hex.r} ${units.length}支 ${units.map(u=>u.id).join(' ')}，展开选择`);el.setAttribute('pointer-events',canInspect()?'auto':'none');el.setAttribute('opacity',p.selections['map-emphasis']==='battle'&&!inBattle?'.48':'1');
 const summaryText=summary?`汇总组织：各队归一化均值 ${numberStatus(summary.orgRatio*100)}%；人员 ${numberStatus(summary.personnel)}/${summary.max}（${numberStatus(summary.personnelRatio*100)}%）；低组织 ${summary.low}队（低于${summary.threshold}触发撤退检查）；${gearSummary(summary)}`:'敌军组织度、人员、装备及补给未知';
 el.setAttribute('data-org-ratio',summary?String(summary.orgRatio):'unknown');el.setAttribute('data-personnel-ratio',summary?String(summary.personnelRatio):'unknown');el.setAttribute('data-low-count',summary?String(summary.low):'unknown');el.setAttribute('aria-label',`${own?'己方':'已识别敌方'} ${u.hex.q},${u.hex.r} ${units.length}支；${summaryText}；点击逐队选择`);
 const html=`${units.length>1?'<rect x="-25" y="-18" width="54" height="35" rx="3" fill="#1b252a" stroke="#9aa599"/>':''}<rect x="-28" y="-15" width="54" height="35" rx="3" fill="${own?'#263f4a':'#643e38'}" stroke="${chosen?'#e9e8d4':'#a5aaa0'}" stroke-width="${chosen?2:1}"/><text x="-24" y="-5" font-size="8" fill="#f0ebd9">${u.side==='GERMAN'?'DE':'SU'}</text><use href="#presence-${f}" transform="translate(-1 -5) scale(.36)" color="${own?'#9baeb0':'#c0988b'}"/><text x="13" y="-5" font-size="10" fill="#fff1d9">${units.length}</text><text x="-24" y="4" font-size="7" fill="#e0e4d9">${[...new Set(units.map(u=>names[u.type]??'部'))].slice(0,2).join('·')}</text>${summary?.shortUnits?'<text x="0" y="4" font-size="7" fill="#ffd275">缺</text>':''}${summary?.low?`<text x="13" y="4" font-size="8" font-weight="bold" fill="#ffb1a0">!${summary.low}</text>`:''}${summary?`<text x="-24" y="11" font-size="6.5" fill="#bce0b6">组</text><rect x="-13" y="7" width="36" height="4" fill="#101c1b"/><rect data-bar="org" x="-13" y="7" width="${36*summary.orgRatio}" height="4" fill="#82c984"/><text x="-24" y="17" font-size="6.5" fill="#f1d390">员</text><rect x="-13" y="13" width="36" height="4" fill="#101c1b"/><rect data-bar="personnel" x="-13" y="13" width="${36*summary.personnelRatio}" height="4" fill="#d5ad52"/>`:'<text x="0" y="14" text-anchor="middle" font-size="7" fill="#d1beb3">组织／人员 ?</text>'}<title>${esc(summaryText+'\n'+units.map((u,i)=>u.id+' '+statusText(statuses[i]??null)).join('\n'))}</title>`;
 if(el.getAttribute('data-markup')!==html){el.innerHTML=html;el.setAttribute('data-markup',html);}let down:{x:number;y:number}|null=null;el.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};};const choose=()=>{p.selections.stack=k;if(own&&units.length===1)select(u.id);else refresh();};el.onclick=e=>{if(!canInspect()||down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;e.stopPropagation();choose();};el.onkeydown=e=>{if(canInspect()&&['Enter',' '].includes(e.key)){e.preventDefault();choose();}};
 }for(const el of Array.from(layer.children))if(!keep.has(el.getAttribute('data-stack-key')!))el.remove();
}
