import type {GrandPort} from './grand.js';
import {PRESENCE_FAMILY} from '../presentation/unitPresenceTypes.js';
const NS='http://www.w3.org/2000/svg';
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const names:Record<string,string>={INFANTRY:'步',PANZER:'装',TANK:'装',HEAVY_TANK:'重',MOTORIZED:'摩',ARTILLERY:'炮',ENGINEER:'工',RECON:'侦',ANTI_TANK:'反',HQ:'部',TRANSPORT:'运'};
export function stackPanel(p:GrandPort){const view=p.data.game.message.payload.view,us=view.units.filter((u:any)=>u.side+':'+u.hex.q+','+u.hex.r===p.selections.stack);if(!us.length)return '';return `<section class="r2-stack"><header><b>${us[0].hex.q},${us[0].hex.r} · ${us.length}支已知部队</b><button id="stack-close" aria-label="收起部队堆叠">×</button></header>${us.map((u:any)=>{const v=p.data.continuous.units[u.id];return `<button data-stack-unit="${esc(u.id)}" ${v?'':'disabled'}>${esc(u.id)} · ${names[u.type]??u.type}${v?`<small>组织 ${Math.round(v.org)}% · 人员 ${Math.ceil(v.personnel)} · ${(v.stock/4).toFixed(2)}SP</small>`:'<small>已识别敌军 · 详细实力未知</small>'}</button>`;}).join('')}</section>`;}
/** Display-only grouping of already authorized units; no invented enemy count or merged unit state. */
export function paintCompactForces(layer:SVGElement,p:GrandPort,point:(h:any)=>{x:number;y:number},size:number,refresh:()=>void,canInspect:()=>boolean,select:(id:string)=>void){
 const view=p.data.game.message.payload.view,groups=new Map<string,any[]>(),selected=p.selections['map-selected-unit'],battle=p.data.continuous.map.battles.find((b:any)=>b.id===p.selections.battle);
 for(const u of view.units){const k=u.side+':'+u.hex.q+','+u.hex.r;if(!groups.has(k))groups.set(k,[]);groups.get(k)!.push(u);}
 const keep=new Set<string>();for(const[k,units]of groups){keep.add(k);let el=Array.from(layer.children).find(x=>x.getAttribute('data-stack-key')===k) as SVGGElement|undefined;if(!el){el=document.createElementNS(NS,'g');el.setAttribute('data-stack-key',k);layer.append(el);}units.sort((a,b)=>a.id.localeCompare(b.id));const u=units.find(u=>u.id===selected)??units[0],own=u.side===view.viewer,at=point(u.hex),v=own?p.data.continuous.units[u.id]:null,chosen=units.some(u=>u.id===selected),inBattle=units.some(u=>battle?.participants.some((x:any)=>x.id===u.id)),f=(PRESENCE_FAMILY as Record<string,string>)[u.type]??'infantry';
 el.setAttribute('transform',`translate(${at.x} ${at.y}) scale(${size})`);el.setAttribute('data-anchor',u.hex.q+','+u.hex.r);el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`${own?'己方':'已识别敌方'} ${u.hex.q},${u.hex.r} ${units.length}支 ${units.map(u=>u.id).join(' ')}，展开选择`);el.setAttribute('pointer-events',canInspect()?'auto':'none');el.setAttribute('opacity',p.selections['map-emphasis']==='battle'&&!inBattle?'.48':'1');
 const html=`${units.length>1?'<rect x="-25" y="-16" width="54" height="27" rx="3" fill="#1b252a" stroke="#9aa599"/>':''}<rect x="-28" y="-13" width="54" height="27" rx="3" fill="${own?'#263f4a':'#643e38'}" stroke="${chosen?'#e9e8d4':'#a5aaa0'}" stroke-width="${chosen?2:1}"/><text x="-24" y="-2" font-size="8" fill="#f0ebd9">${own?'DE':'SU'}</text><use href="#presence-${f}" transform="translate(-1 -1) scale(.40)" color="${own?'#9baeb0':'#c0988b'}"/><text x="13" y="-1" font-size="10" fill="#fff1d9">${units.length}</text><text x="-22" y="9" font-size="8" fill="#e0e4d9">${[...new Set(units.map(u=>names[u.type]??'部'))].slice(0,4).join('·')}</text>${v?`<rect x="-27" y="14" width="52" height="3" fill="#17211b"/><rect x="-27" y="14" width="${52*Math.max(0,Math.min(1,v.org/100))}" height="3" fill="#8eb384"/>`:''}<title>${esc(units.map(u=>u.id+' '+(names[u.type]??u.type)).join(' / '))}${v?esc('；所选/首队组织 '+Math.round(v.org)+'%，人员 '+Math.ceil(v.personnel)+'；点击逐队查看'):'；敌军精确实力未知'}</title>`;
 if(el.getAttribute('data-markup')!==html){el.innerHTML=html;el.setAttribute('data-markup',html);}let down:{x:number;y:number}|null=null;el.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};};const choose=()=>{p.selections.stack=k;if(own&&units.length===1)select(u.id);else refresh();};el.onclick=e=>{if(!canInspect()||down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;e.stopPropagation();choose();};el.onkeydown=e=>{if(canInspect()&&['Enter',' '].includes(e.key)){e.preventDefault();choose();}};
 }for(const el of Array.from(layer.children))if(!keep.has(el.getAttribute('data-stack-key')!))el.remove();
}
