import {ownStatus,aggregateStatus,statusBars,statusText,gearSummary,numberStatus} from './unitStatus.js';
import {forceAffiliation,groupForces,retainGroupKeys,scaleMode,type ForceGroup,type ScaleMode} from './forceScale.js';
import type {GrandPort} from './grand.js';
import {PRESENCE_FAMILY} from '../presentation/unitPresenceTypes.js';
const NS='http://www.w3.org/2000/svg',cache=new WeakMap<Element,{mode:ScaleMode;groups:ForceGroup[]}>();
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const names:Record<string,string>={INFANTRY:'步兵',PANZER:'装甲',TANK:'装甲',HEAVY_TANK:'重装',MOTORIZED:'摩托',ARTILLERY:'炮兵',ENGINEER:'工兵',RECON:'侦察',ANTI_TANK:'反坦',HQ:'总部',TRANSPORT:'运输'};
function stackMembers(p:GrandPort){const ids=new Set(JSON.parse(p.selections['scale-members']??'[]'));const v=p.data.game.message.payload.view,c=p.data.continuous;return v.units.filter((u:any)=>ids.has(u.id)&&(!p.selections['scale-affiliation']||forceAffiliation(u,v.viewer,c.corps,c.units).id===p.selections['scale-affiliation']));}
export function stackPanel(p:GrandPort){const us=stackMembers(p);if(us.length<2)return '';const a=aggregateStatus(us.map((u:any)=>ownStatus(p,u.id))),cross=new Set(us.map((u:any)=>u.hex.q+','+u.hex.r)).size>1;return `<details class="r2-stack" ${p.selections['stack-open']==='1'?'open':''}><summary><b>${cross?'跨格群组 · 非同格驻地':'同格部队'} · ${us.length}队</b><button id="stack-close" aria-label="收起部队堆叠">×</button></summary><p>点成员仅选择，定位按钮单独移动镜头。地图小圆点为各队真实位置。</p>${a?`<small>平均组织 ${numberStatus(a.orgRatio*100)}%；人员合计${Math.round(a.personnel)}/${a.max}<br>低组织 ${a.low}队 · 缺补给 ${us.filter((u:any)=>ownStatus(p,u.id)?.stock===0).length}队 · 缺装备 ${a.shortUnits}队</small>`:'<small>仅统计当前已识别敌军；状态未知。</small>'}${us.map((u:any)=>{const v=ownStatus(p,u.id);return `<article><button data-stack-unit="${esc(u.id)}" ${v?'':'disabled'} title="${esc(statusText(v))}"><b>${esc(u.id)} · ${names[u.type]??u.type} · ${u.hex.q},${u.hex.r}</b>${statusBars(v)}</button><button data-ui-locate-force="${esc(u.id)}">定位 ${esc(u.id)}</button>${v?`<small>${esc(v.action)} · ${v.supplyLabel??(numberStatus(v.stock)+' SP')} · ${esc(gearSummary(v))}</small>`:''}</article>`;}).join('')}</details>`;}
const set=(el:Element,k:string,v:string)=>{if(el.getAttribute(k)!==v)el.setAttribute(k,v);};
/** View-only LOD. No game action or authoritative mutation is reachable from a marker click. */
export function paintCompactForces(layer:SVGElement,p:GrandPort,point:(h:any)=>{x:number;y:number},size:number,refresh:()=>void,canInspect:()=>boolean,select:(id:string)=>void){
 const view=p.data.game.message.payload.view,c=p.data.continuous,previous=cache.get(layer),mode=scaleMode(72.746/size,previous?.mode),groups=retainGroupKeys(groupForces(view.units,view.viewer,c.corps,c.units,mode,1/size,point),previous?.groups??[]),selected=p.selections['map-selected-unit'],battle=c.map.battles.find((b:any)=>b.id===p.selections.battle);
 cache.set(layer,{mode,groups});p.selections['map-scale-mode']=mode;set(layer,'data-scale-mode',mode);set(layer,'data-visible-units',String(view.units.length));set(layer,'data-hex-pixels',String(72.746/size));
 const keep=new Set<string>(),occupied:{x:number;y:number;w:number;h:number}[]=[],selectedMembers=stackMembers(p),selectedSet=new Set(selectedMembers.map((u:any)=>u.id));
 // Deterministic order keeps selecting a unit from reshuffling unrelated markers.
 const sorted=groups.slice().sort((a,b)=>a.key.localeCompare(b.key));
 for(const g of sorted){const units=g.units,own=units[0]!.side===view.viewer,summary=own?aggregateStatus(units.map(u=>ownStatus(p,u.id))):null,chosen=units.some(u=>u.id===selected),inBattle=units.some(u=>battle?.participants.some((v:any)=>v.id===u.id)),supply=own?units.filter(u=>ownStatus(p,u.id)?.stock===0).length:0;
  keep.add(g.key);let el=Array.from(layer.children).find(x=>x.getAttribute('data-stack-key')===g.key) as SVGGElement|undefined;if(!el){el=document.createElementNS(NS,'g');set(el,'data-stack-key',g.key);layer.append(el);}
  const w=mode==='far'?106:74,h=44,anchor={x:g.at.x/size,y:g.at.y/size};let pos={...anchor};
  const intersects=(x:number,y:number)=>occupied.some(o=>Math.abs(x-o.x)<(w+o.w)/2+5&&Math.abs(y-o.y)<(h+o.h)/2+5)||c.map.battles.some((b:any)=>{const a=point(b.hex);return Math.abs(x-a.x/size-34)<w/2+55&&Math.abs(y-a.y/size-40)<h/2+60;});
  // Stable candidate slots and a leader preserve the distinction between a label and its actual footprint.
  const offsets=[[0,0],[-(w+12),0],[w+12,0],[0,-(h+8)],[0,h+8]];offsets.push([-(w+12),-(h+8)],[-(w+12),h+8],[w+12,-(h+8)],[w+12,h+8]);for(let n=2;n<=6;n++)offsets.push([-n*(w+10),0],[n*(w+10),0],[0,-n*(h+8)],[0,n*(h+8)]);
  for(const [dx,dy]of offsets){pos={x:anchor.x+dx!,y:anchor.y+dy!};if(!intersects(pos.x,pos.y))break;}occupied.push({...pos,w,h});
  set(el,'transform',`translate(${pos.x*size} ${pos.y*size}) scale(${size})`);set(el,'data-label-x',String(pos.x*size));set(el,'data-label-y',String(pos.y*size));set(el,'data-marker-width',String(w));set(el,'data-anchor',units[0]!.hex.q+','+units[0]!.hex.r);set(el,'data-members',JSON.stringify(units.map(u=>u.id)));set(el,'data-group-kind',g.crossHex?'area':units.length>1?'stack':'single');
  set(el,'role','button');set(el,'tabindex','0');set(el,'pointer-events',canInspect()?'auto':'none');set(el,'opacity',p.selections['map-emphasis']==='battle'&&!inBattle&&!chosen?'.42':'1');
  const warning=summary?`低组织${summary.low} · 缺补给${supply} · 缺装${summary.shortUnits}`:'敌方状态未知',summaryText=summary?`平均组织 ${numberStatus(summary.orgRatio*100)}%；人员 ${Math.round(summary.personnel)}/${summary.max}；${warning}`:warning;
  set(el,'aria-label',`${g.name} ${g.crossHex?'跨格群组':units.length>1?'同格堆叠':'单队'} ${units.length}队；${summaryText}；点击选择成员`);set(el,'data-org-ratio',summary?String(summary.orgRatio):'unknown');set(el,'data-personnel-ratio',summary?String(summary.personnelRatio):'unknown');set(el,'data-low-count',summary?String(summary.low):'unknown');
  const leader=Math.hypot(pos.x-anchor.x,pos.y-anchor.y)>2?`<path d="M0,0L${anchor.x-pos.x},${anchor.y-pos.y}" stroke="${g.color}" stroke-width="1" opacity=".6" pointer-events="none"/><circle cx="${anchor.x-pos.x}" cy="${anchor.y-pos.y}" r="2.5" fill="${g.color}" pointer-events="none"/>`:'';
  const scope=selectedSet.size&&units.some(u=>selectedSet.has(u.id))?units.map(u=>{const a=point(u.hex),x=a.x/size-pos.x,y=a.y/size-pos.y;return `<path d="M0,0L${x},${y}" stroke="${g.color}" stroke-width="1" stroke-dasharray="2 3" opacity=".7" pointer-events="none"/><circle cx="${x}" cy="${y}" r="5" fill="none" stroke="${g.color}" stroke-width="2" pointer-events="none"/>`;}).join(''):'';
  const selectedPoint=chosen?(()=>{const a=point(units.find(u=>u.id===selected)!.hex);return `<circle cx="${a.x/size-pos.x}" cy="${a.y/size-pos.y}" r="7" fill="none" stroke="#f3ebc5" stroke-width="2" pointer-events="none"/>`;})():'';
  set(el,'data-command-owner',g.affiliation);
  const shortWarning=summary?[summary.low?'低组织'+summary.low:'',supply?'缺供'+supply:'',summary.shortUnits?'缺装'+summary.shortUnits:''].filter(Boolean).join(' '):'状态未知';
  const border=chosen?'#fff1bc':g.color,fill=own?'#213c43':'#5b3733',frame=g.crossHex?`<path data-marker-face="1" d="M${-w/2+7},${-h/2}H${w/2-7}l7,7V${h/2-7}l-7,7H${-w/2+7}l-7,-7V${-h/2+7}Z" fill="${fill}" stroke="${border}" stroke-width="${chosen?2:1.3}" stroke-dasharray="5 2"/>`:`${units.length>1?`<rect x="${-w/2+4}" y="${-h/2-4}" width="${w}" height="${h}" rx="2" fill="#182b2e" stroke="${g.color}"/>`:''}<rect data-marker-face="1" x="${-w/2}" y="${-h/2}" width="${w}" height="${h}" rx="3" fill="${fill}" stroke="${border}" stroke-width="${chosen?2:1.2}"/>`;
  let inside='';if(mode==='far')inside=`<text x="${-w/2+6}" y="-5" fill="#eceddd" font-size="10">${chosen?'◆ ' :''}${esc(g.name)} · ${units.length}</text><text x="${-w/2+6}" y="10" fill="${summary&&(summary.low||supply||summary.shortUnits)?'#efbd90':'#adcbc9'}" font-size="8">${summary&&(summary.low||supply||summary.shortUnits)?shortWarning:g.crossHex?'局部群组 · 分布多格':'同格驻留'}</text>`;
  else {const family=(PRESENCE_FAMILY as Record<string,string>)[units[0]!.type]??'infantry',name=units.length===1?units[0]!.id.split('-').at(-1):`${units.length}队`,warn=summary&&(summary.low||supply||summary.shortUnits)?'!':'';
  inside=`<use href="#presence-${family}" transform="translate(-23 -9) scale(.38)" color="${g.color}"/><text x="0" y="-5" font-size="12" text-anchor="middle" fill="#f0eddd">${own&&g.affiliation.startsWith('direct:')?'◇':''}${name}</text><text x="30" y="-6" text-anchor="end" font-size="11" fill="#efb189">${warn}${g.crossHex?'⋯':units.length>1?'▣':''}</text>${summary?`<rect x="-30" y="2" width="60" height="6" fill="#0e1c1c"/><rect data-bar="org" x="-30" y="2" width="${60*summary.orgRatio}" height="6" fill="#82c984"/><rect x="-30" y="12" width="60" height="6" fill="#0e1c1c"/><rect data-bar="personnel" x="-30" y="12" width="${60*summary.personnelRatio}" height="6" fill="#d5ad52"/>`:'<text y="13" text-anchor="middle" font-size="10" fill="#dbc4b6">状态未知</text>'}`;}

  const footprint=mode==='far'?Array.from(new Map(units.map(u=>[u.hex.q+','+u.hex.r,u.hex])).values()).map(h=>{const at=point(h);return `<circle cx="${at.x/size-pos.x}" cy="${at.y/size-pos.y}" r="2.5" fill="${g.color}" stroke="#142a2e" stroke-width=".7" pointer-events="none"/>`;}).join(''):'';
  const hit=`<rect x="${-w/2}" y="-22" width="${w}" height="44" fill="transparent"/>`;
  const pending=own&&Array.from(p.wire?.pending.values()??[]).some((r:any)=>units.some(u=>r.command?.payload?.unit===u.id));
  const waiting=pending?`<g><circle cx="${w/2-2}" cy="${-h/2}" r="9" fill="#e7d5a3" stroke="#263b40"/><text x="${w/2-2}" y="${-h/2+4}" font-size="12" text-anchor="middle" fill="#263b40">⌛</text><title>命令等待确认；兵位未提前改变</title></g>`:'';
  const html=leader+footprint+scope+selectedPoint+hit+frame+inside+waiting+`<title>${esc(g.name+'；'+summaryText+'；'+units.map(u=>u.id+' '+u.hex.q+','+u.hex.r).join('；'))}</title>`;if(el.getAttribute('data-markup')!==html){el.innerHTML=html;set(el,'data-markup',html);}
  let down:{x:number;y:number}|null=null;el.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};};const choose=()=>{p.selections['stack-open']='1';p.selections['ui-panel']='unit';p.selections.stack=g.key;p.selections['scale-affiliation']=g.affiliation;p.selections['scale-members']=JSON.stringify(units.map(u=>u.id));if(own&&units.length===1)select(units[0]!.id);else refresh();};el.onclick=e=>{if(!canInspect()||down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;e.stopPropagation();choose();};el.onkeydown=e=>{if(canInspect()&&['Enter',' '].includes(e.key)){e.preventDefault();choose();}};
 }
 for(const el of Array.from(layer.children))if(!keep.has(el.getAttribute('data-stack-key')!))el.remove();
}
