import {integratedPanel,bindIntegrated} from './integratedDesigner.js';
import type {GrandPort} from './grand.js';
import {escStatus as esc,ownStatus,statusBars,equipmentDetail} from './unitStatus.js';
type Draft={name:string;regiments:(string|null)[][];support:(string|null)[]};
type Editor={instance:string;id:string|null;version:number;draft:Draft;slot:{column:number;row:number}|null;dirty:boolean;pending:boolean;adoptUnit?:string|undefined;adoptRevision?:number|undefined};
const equipmentNames:Record<string,string>={infantry_equipment:'步兵装备',motorized_equipment:'卡车',artillery_equipment:'火炮',anti_tank_equipment:'反坦克炮',medium_tank_chassis:'中型坦克底盘',heavy_tank_chassis:'重型坦克底盘',support_equipment:'支援装备'};
function requirements(d:Draft,reference:any){let manpower=0;const equipment:Record<string,number>={};for(const id of [...d.regiments.flat(),...d.support]){if(!id)continue;const u=reference.units[id];if(!u)throw Error('编制需求资料缺失');manpower+=u.manpower;for(const [k,v]of Object.entries(u.equipment))equipment[k]=(equipment[k]??0)+Number(v);}return {manpower,equipment};}
const editors=new WeakMap<GrandPort,Editor>();
const blank=(profile:any):Draft=>({name:'新编制草案',regiments:Array.from({length:profile.columns},()=>Array(profile.rows).fill(null)),support:Array(profile.supportSlots).fill(null)});
function editor(p:GrandPort){let e=editors.get(p);if(!e||e.instance!==p.data.instanceId){e={instance:p.data.instanceId,id:null,version:0,draft:blank(p.data.divisions.profile),slot:null,dirty:false,pending:false};editors.set(p,e);}return e;}
function choose(p:GrandPort,t:any,copy=false){const e=editor(p);if(e.dirty&&!confirm('放弃尚未保存的草案修改？'))return;e.id=copy?null:t.id;e.version=copy?0:t.version;e.draft={name:t.name+(copy?' 副本':''),regiments:structuredClone(t.regiments),support:[...t.support]};e.dirty=copy;e.slot=null;e.adoptUnit=undefined;}
function piecePanel(p:GrandPort,e:Editor){
 const f=p.data.divisions.pieceFixture;if(!f)return '';
 return `<section class="division-piece-test"><h3>${esc(f.label)}</h3><p>已显式注入测试经验、人员及整数件数库存。每次采用扣 ${f.fee} 经验是夹具报价，不是原版费用公式。仅步兵营／工兵支援可采用；战斗、生产、经验来源未接入。</p><p>国家经验 ${f.nation.xp} · 可用人员 ${f.nation.manpower} · 步兵装备 ${f.nation.stock.infantry_equipment} 件 · 支援装备 ${f.nation.stock.support_equipment} 件</p>${f.units.map((u:any)=>`<article><h4>${esc(u.id)} · ${u.templateId?'已采用 v'+u.templateVersion:'测试初始编制'}</h4><p>人员 ${u.personnel}／${u.target.manpower} · 缺 ${Math.max(0,u.target.manpower-u.personnel)} 人<br>组织度 ${u.org}（新上限未接入） · 训练经验 ${u.trainingExperience}（换编损耗未接入）</p><table><tr><th>装备</th><th>实有／目标（件）</th><th>缺额（件）</th></tr>${['infantry_equipment','support_equipment'].map(k=>`<tr><td>${equipmentNames[k]}</td><td>${u.held[k]}／${u.target.equipment[k]??0}</td><td>${Math.max(0,(u.target.equipment[k]??0)-u.held[k])}</td></tr>`).join('')}</table><button data-piece-adopt="${esc(u.id)}" data-piece-revision="${u.revision}" ${!e.id||e.dirty||e.pending||p.locked?'disabled':''}>采用当前已保存草案 · 测试扣 ${f.fee} 经验</button></article>`).join('')}${e.adoptUnit?`<div role="group" aria-label="确认测试换编"><p>确认 ${esc(e.adoptUnit)} 采用当前保存版本：测试扣 ${f.fee} 经验，多余人员装备立即退库，缺额另行补充。</p><button id="piece-adopt-confirm">确认测试换编</button><button id="piece-adopt-cancel">取消</button></div>`:''}<button id="piece-refill-step" ${p.locked?'disabled':''}>执行一次真实扣库补充（测试步）</button><p>已结算 ${f.tick} 步；每阵营共享测试额度：${f.refill.personnel} 人、${f.refill.infantry_equipment} 件步兵装备、${f.refill.support_equipment} 件支援装备／步。缺货或断路不补；不是已获批准的正常速率。</p><small>${f.lastRefill.map((x:any)=>x.blocked?esc(x.unit+'：'+x.blocked):esc(x.unit+' 最近补充步实际补 '+x.personnel+' 人，步兵装备 '+x.equipment.infantry_equipment+' 件，支援装备 '+x.equipment.support_equipment+' 件')).join('<br>')}</small></section>`;
}
function conversionPanel(p:GrandPort,unit:string|null,e:Editor,after:ReturnType<typeof requirements>){
 const d=p.data.divisions,u=d.units?.find((x:any)=>x.id===unit);if(!u)return '<p>选择己方部队，查看当前实装与换编需求差额。</p>';
 const n=p.data.modern,plan=d.usage.find((x:any)=>x.unit===unit),t=plan&&d.templates.find((x:any)=>x.id===plan.templateId),missing=Math.max(0,after.manpower-u.personnel),surplus=Math.max(0,u.personnel-after.manpower);
 return `<section class="division-conversion"><h3>${esc(unit)} · 换编差额预览</h3><p>当前 ${Math.round(u.personnel)} 人 → 草案要求 ${after.manpower} 人 · ${missing?'待补 '+Math.ceil(missing)+' 人':surplus?'多出 '+Math.floor(surplus)+' 人（返还待裁决）':'人员无差额'}。国家可用人力 ${Math.floor(n?.manpower??0)}。</p><p>${u.engaged?'正在交战':u.marching?'正在行军':'未交战、未行军'} · ${u.routeAvailable?'有补充路线':'没有已确认补充路线'}。草案不会改变当前组织度 ${Number(u.org).toFixed(1)}。</p><details open><summary>当前装备缺额与国家库存（现有库存单位）</summary><table><thead><tr><th>装备</th><th>部队实有／现需求</th><th>待补</th><th>国库</th></tr></thead><tbody>${Object.entries(u.equipmentTarget).map(([k,v])=>`<tr><td>${esc(n?.products?.[k]?.label??k)}</td><td>${Number(u.held[k]??0).toFixed(2)}／${v}</td><td>${Math.max(0,Number(v)-(u.held[k]??0)).toFixed(2)}</td><td>${Number(n?.stock?.[k]??0).toFixed(2)}</td></tr>`).join('')}</tbody></table><small>上表沿用真实库存和自动补充。草案装备为原版件数，换算未批准，不能与此表直接相减；库存也不代表已经送达。</small></details><p>${plan?`已记录计划：${esc(t?.name??plan.templateId)} v${plan.templateVersion}${t?.version!==plan.templateVersion?' · 模板已更新，请重新记录计划':''}`:'尚未记录换编计划'}。计划仅记录意图，不扣费、不改现役编制或战力。</p><div class="button-row"><button id="division-plan-set" data-unit="${esc(unit)}" ${!e.id||e.dirty||e.pending||p.locked?'disabled':''}>为此队记录换编计划</button><button id="division-plan-clear" data-unit="${esc(unit)}" ${!plan||p.locked?'disabled':''}>取消计划</button></div><small>先保存草案再记录计划。正式采用、缩编返还与属性接入尚未开放。</small></section>`;
}
export function divisionPanel(p:GrandPort,unit:string|null){if(p.data.divisions?.integrated)return integratedPanel(p);const d=p.data.divisions;if(!d)return '';const e=editor(p),catalog=d.catalog,old=d.templates.find((x:any)=>x.id===e.id),count=(x:Draft)=>x.regiments.flat().filter(Boolean).length,sc=(x:Draft)=>x.support.filter(Boolean).length;
 const slot=(column:number,row:number,value:string|null)=>`<button class="division-slot" data-division-slot="${column}:${row}" aria-label="${column<0?'支援连':'第'+(column+1)+'团'}第${row+1}槽：${value?esc(catalog[value].label):'空'}" ${column>=0&&row>=d.profile.draftEditableRows&&!value?'disabled title="第五排解锁条件未核实"':''} aria-pressed="${e.slot?.column===column&&e.slot?.row===row}"><b>${value?esc(catalog[value].symbol):'＋'}</b><small>${value?esc(catalog[value].label):column>=0&&row>=d.profile.draftEditableRows?'未核实':'空槽'}</small></button>`;
 const before=requirements(old??blank(d.profile),d.demandReference),after=requirements(e.draft,d.demandReference);
 const demandRows=[['人员',before.manpower,after.manpower],...Array.from(new Set([...Object.keys(before.equipment),...Object.keys(after.equipment)])).sort().map(k=>[equipmentNames[k]??k,before.equipment[k]??0,after.equipment[k]??0])];
 const options=e.slot&&!(e.slot.column>=0&&e.slot.row>=d.profile.draftEditableRows)?Object.entries(catalog).filter(([,x]:any)=>x.role===(e.slot!.column<0?'support':'line')):[];
 return `<section class="division-designer"><fieldset ${e.pending?'disabled':''}><p class="division-review">${d.pieceFixture?"内部件数换编测试 · 不用于正常战役":"编制草案 · 尚未开放换编"}</p><div class="division-head"><div class="button-row"><button id="division-new">新建</button><button id="division-copy">复制当前</button></div><label>草案库<select id="division-library"><option value="">选择已保存草案</option>${d.templates.map((t:any)=>`<option value="${esc(t.id)}" ${t.id===e.id?'selected':''}>${esc(t.name)} · v${t.version}</option>`).join('')}</select></label><label>名称<input id="division-name" maxlength="48" value="${esc(e.draft.name)}"></label></div>
 <div class="division-grid"><div class="division-column"><small>支援连</small>${e.draft.support.map((x,r)=>slot(-1,r,x)).join('')}</div>${e.draft.regiments.map((xs,c)=>`<div class="division-column"><small>第${c+1}团</small>${xs.map((x,r)=>slot(c,r,x)).join('')}</div>`).join('')}</div>
 ${e.slot?`<div class="division-palette" aria-label="选择营或支援连">${options.map(([k,x]:any)=>`<button data-division-type="${k}">${esc(x.symbol)} ${esc(x.label)}</button>`).join('')}<button data-division-type="">移除此槽</button></div>`:''}
 <details class="division-demands"><summary>逐项需求与保存前后对照</summary><table><thead><tr><th>人员／装备</th><th>保存前</th><th>当前草案</th></tr></thead><tbody>${demandRows.map(([name,a,b])=>`<tr><td>${esc(String(name))}</td><td>${a}</td><td>${b}</td></tr>`).join('')}</tbody></table><small>按本机1.19.3基础营定义逐项相加；不是当前实装或有效战力。不含科技与学说修正。</small></details>
 <div class="division-save-bar"><span>${count(e.draft)}营 · ${sc(e.draft)}支援 · 人员 ${after.manpower}<small>${Object.entries(after.equipment).map(([k,v])=>esc(equipmentNames[k]??k)+' '+v).join(' · ')}</small></span><button id="division-save" ${e.pending||p.locked?'disabled':''}>${e.pending?'草案保存待确认':'保存草案（不换编）'}</button></div><p>影响现役部队：0。草案不扣资源，也不授予人员、装备或战力。</p>
 <details class="division-source-facts"><summary>查看文件定义与解锁来源</summary><p>${esc(d.profile.environmentLabel??"参考环境待核实")}。以下是已读取的营文件定义，不是引擎行为观察，也不是全师有效战力。本战役科技资格尚未核实；缺省字段显示未知，不补零。</p>${Array.from(new Set([...e.draft.regiments.flat(),...e.draft.support].filter(Boolean))).map(id=>{const r=d.demandReference.units[id!],a=r.baseAttributes??{};return `<p><b>${esc(catalog[id!].label)}</b> · 基础组织 ${a.max_organisation??'未知'} · 基础强度 ${a.max_strength??'未知'} · 宽度 ${a.combat_width??'未知'} · 日常供给 ${a.supply_consumption??'未知'}<br><small>科技定义：${r.unlockSources?.length?r.unlockSources.map((x:any)=>esc(x.technology)+(x.conditional?'（含条件）':'')).join('、'):'未检出，不能据此视为已解锁'}；仍需核对本战役科技。来源：${esc(r.source)}</small></p>`;}).join('')}<p>第五排：已找到 ${d.demandReference.columnSizeEffects?.length??0} 项学说里程碑扩展效果；尚未验证运行激活条件，继续禁用。团属支援、同团混编资格仍未核实。</p></details>
 <details><summary>属性与费用为何未显示数值？</summary><p>${d.blockers.map(esc).join('；')}。目标人员和装备基础需求已有来源；组织、攻击、防御、速度、供给、修改费用及换编规则仍待完整核实，不以猜测值代替。槽位与可选条目目前仅用于编辑草案，不代表已获原版采用资格。</p></details>
 ${d.pieceFixture?piecePanel(p,e):conversionPanel(p,unit,e,after)}
 ${!d.pieceFixture&&unit?`<h3>所选部队 ${esc(unit)} · 当前实装</h3>${statusBars(ownStatus(p,unit))}${equipmentDetail(ownStatus(p,unit))}<p>仍采用原编制与原结算，草案编辑不会影响其军团、岗位或命令。</p>`:''}</fieldset></section>`;
}
export function bindDivision(p:GrandPort,refresh:()=>void){if(p.data.divisions?.integrated){bindIntegrated(p,refresh);return;}if(!p.data.divisions)return;const e=editor(p),catalog=p.data.divisions.catalog;
 document.querySelectorAll<HTMLElement>('[data-piece-adopt]').forEach(el=>el.onclick=()=>{if(!e.id||e.dirty)return;e.adoptUnit=el.dataset.pieceAdopt;e.adoptRevision=Number(el.dataset.pieceRevision);refresh();});
 const adoptConfirm=document.getElementById('piece-adopt-confirm');if(adoptConfirm)adoptConfirm.onclick=()=>{if(!e.adoptUnit||!e.id||e.dirty)return;const unit=e.adoptUnit;e.adoptUnit=undefined;void p.operation({type:'DIVISION_ADOPT',unit,expectedUnitRevision:e.adoptRevision,templateId:e.id,expectedTemplateVersion:e.version});};const adoptCancel=document.getElementById('piece-adopt-cancel');if(adoptCancel)adoptCancel.onclick=()=>{e.adoptUnit=undefined;refresh();};
 const refill=document.getElementById('piece-refill-step');if(refill)refill.onclick=()=>{void p.operation({type:'DIVISION_REFILL_TEST_STEP'});};
 const name=document.querySelector<HTMLInputElement>('#division-name');if(name)name.oninput=()=>{e.draft.name=name.value;e.dirty=true;};
 const lib=document.querySelector<HTMLSelectElement>('#division-library');if(lib)lib.onchange=()=>{const t=p.data.divisions.templates.find((x:any)=>x.id===lib.value);if(t){choose(p,t);refresh();}};
 const on=(id:string,f:()=>void)=>{const el=document.getElementById(id);if(el)el.onclick=f;};
 on('division-plan-set',()=>{const unit=document.getElementById('division-plan-set')?.dataset.unit;if(!unit||!e.id||e.dirty)return;void p.operation({type:'DIVISION_PLAN_SET',unit,templateId:e.id,expectedTemplateVersion:e.version});});
 on('division-plan-clear',()=>{const unit=document.getElementById('division-plan-clear')?.dataset.unit;if(unit)void p.operation({type:'DIVISION_PLAN_CLEAR',unit});});
 on('division-new',()=>{choose(p,{...blank(p.data.divisions.profile),id:null,version:0});refresh();});
 on('division-copy',()=>{choose(p,{...e.draft,id:e.id,version:e.version},true);refresh();});
 document.querySelectorAll<HTMLElement>('[data-division-slot]').forEach(el=>el.onclick=()=>{const [column,row]=el.dataset.divisionSlot!.split(':').map(Number);e.slot={column:column!,row:row!};refresh();});
 document.querySelectorAll<HTMLElement>('[data-division-type]').forEach(el=>el.onclick=()=>{if(!e.slot)return;const value=el.dataset.divisionType||null;if(value&&e.slot.column<0&&e.draft.support.some((x,r)=>x===value&&r!==e.slot!.row)){p.notice='同一种支援连已存在，请选择其他类型。';refresh();return;}if(value&&!catalog[value])return;if(e.slot.column<0)e.draft.support[e.slot.row]=value;else e.draft.regiments[e.slot.column]![e.slot.row]=value;e.dirty=true;e.slot=null;refresh();});
 on('division-save',()=>{if(e.pending)return;if(!e.draft.name.trim()){p.notice='请填写草案名称。';refresh();return;}e.pending=true;
  let requestId:string|undefined;const submitted=structuredClone(e.draft);
  const done=(ev:any)=>{const row=p.wire.history.find((r:any)=>r.command.requestId===ev.detail.requestId);if(ev.detail.requestId!==requestId)return;p.wire.removeEventListener('completed',done);e.pending=false;if(ev.detail.status==='applied'){const receipt=row?.result?.division;const t=receipt&&p.data.divisions.templates.find((t:any)=>t.id===receipt.templateId);if(t&&Number.isSafeInteger(receipt.templateVersion)&&t.version>=receipt.templateVersion){e.id=receipt.templateId;e.version=receipt.templateVersion;e.dirty=false;}else{e.pending=true;p.notice='保存回执缺少可核对的模板标识；草稿已保留并锁定，请重连核对，勿重复创建。';}}refresh();};
  p.wire.addEventListener('completed',done);void p.operation({type:'DIVISION_DRAFT_SAVE',referenceProfileId:p.data.divisions.profile.id,templateId:e.id,expectedTemplateVersion:e.version,draft:submitted}).then(id=>{requestId=id;if(!id){p.wire.removeEventListener('completed',done);e.pending=false;refresh();}});refresh();
 });
}
