import type {GrandPort} from './grand.js';
const esc=(x:any)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const reasons:Record<string,string>={MATERIAL_SHORTAGE:'缺物资',TRAIN_SHORTAGE:'缺火车',TRUCK_SHORTAGE:'缺卡车',LINE_INTERRUPTED:'铁路中断或未修复',LINE_CAPACITY:'线路容量已满',LINE_OR_SERVICE_RANGE:'线路中断或超出末端范围',NO_SERVICE_ROUTE:'无已知服务通路',ROUTE_UNAVAILABLE:'当前路线不能执行'};
export function uxMarkup(p:GrandPort,selected:string|null):string{
 const d=p.data,x=d.ux,off=p.locked||d.viewer!==d.owner||d.game.message.payload.view.pendingDecision?'disabled':'',last=x.last,names={IDLE:'暂停生产 / 转行政预算',...Object.fromEntries(Object.entries(x.products).map(([k,v]:any)=>[k,v.label]))},u=d.units.find((u:any)=>u.id===selected);
 const focus=(hex:string,label:string)=>`<button class="secondary-action" data-ux-focus="${esc(hex)}">${esc(label)}</button>`;
 return `<section class="panel-block grand-panel"><h3>生产与军队补给 · T${d.turn}/24</h3><p role="status">${esc(p.notice)}</p>
 <p><b>火车 ${x.vehicles.TRAIN.available} / ${x.vehicles.TRAIN.needed??'待结算'}；卡车 ${x.vehicles.TRUCK.available} / ${x.vehicles.TRUCK.needed??'待结算'}</b><br>可用 / 上轮路线需求估计；已扣基础近距能力，非最优下界。新产车辆下一T投入。</p>
 <p>先维护 → 装备前送 → 补足储备。直属单位选中即可规划移动，仍须确认执行。铁路与全军阶段由统帅处理；军官继续按明确委托行动。</p>
 <p>行政预算 ${d.account.I} I · 有限已训练后备 ${d.account.reserve} P。生产线分配的工业产能不再同时记为 I 收入。</p>
 <details open><summary>持续生产线</summary><p>每座已建工厂每E提供${x.work}产能；停产节点保留原4I收入，不按工厂数量重复发钱。切换保留各产品进度，失去控制冻结。人员由有限后备自动接驳，2I/P，并照管1I/每4P/E。</p>
 ${x.lines.map((l:any)=>`<div class="ux-line"><label>${esc(l.label)} ${l.controlled?'':'· 失去控制'}<select data-ux-line="${esc(l.id)}" ${off||!l.controlled?'disabled':''}>${Object.keys(names).map(k=>`<option value="${k}" ${k===l.product?'selected':''}>${(names as Record<string,string>)[k]}${x.products[k]?` · ${x.products[k].work}产能/${x.products[k].output}件`:''}</option>`).join('')}</select></label><p>分配 ${l.factories.length} 座厂 · ${l.factories.length*x.work}产能/E · ${l.product==='IDLE'?'暂停':`${names[l.product]} ${l.progress[l.product]}/${x.products[l.product].work}，累计${l.completed[l.product]}件`}</p><label>工厂数量<select data-ux-factories="${esc(l.id)}" ${off}>${Array.from({length:x.facilities.filter((f:any)=>f.warehouse===l.id&&f.status==='BUILT').length+1},(_,n)=>`<option value="${n}" ${n===l.factories.length?'selected':''}>${n}</option>`).join('')}</select></label><label>生产优先<select data-ux-production-priority="${esc(l.id)}" ${off}>${[1,2,3,4,5].map(n=>`<option value="${n}" ${n===l.priority?'selected':''}>${n}</option>`).join('')}</select></label>${focus(l.hex,'定位工厂')}</div>`).join('')}</details>
 <details><summary>装备型号与全军缺额</summary>${Object.entries(x.products).map(([k,v]:any)=>`<p><b>${esc(v.label)}</b> · ${v.work}产能/件 · 运输${v.load}载重 · 缺${x.deficit[k]} · 后方${d.warehouses.flatMap((w:any)=>w.lots).filter((l:any)=>l.type===k).reduce((n:number,l:any)=>n+l.qty,0)}<br>${esc(v.use)}</p>`).join('')}</details>
 <details open><summary>军队优先级与缺额</summary><p>1先配送，5后配送；维护始终先于装备。按实际兵种装备缺额与下一步恢复编制配送，已预约和到货均抵扣需求。送至部队的恢复材料下一T可用，恢复仍须原Core的基地、阶段与共同次数资格。</p>
 ${x.armies.map((a:any)=>`<div class="ux-army" data-ux-army="${esc(a.id)}"><b>${esc(a.id)} · ${a.units}单位</b><p>当前净维护缺${a.missingSP}SP；受损${a.damage}步；上轮装备缺${a.missingE2} E2。</p><label>配送优先<select data-ux-priority ${off}>${[1,2,3,4,5].map(v=>`<option value="${v}" ${a.priority===v?'selected':''}>${v}</option>`).join('')}</select></label><label><input type="checkbox" data-ux-materials ${a.materials?'checked':''} ${off}>自动接驳与前送恢复材料</label><label>额外预备包<select data-ux-reserve ${off}>${[0,1,2,3].map(v=>`<option value="${v}" ${a.reserve===v?'selected':''}>${v}</option>`).join('')}</select></label>${focus(d.units.find((u:any)=>u.alive&&u.army===a.id)?.hex??x.lines[0].hex,'定位军队')}</div>`).join('')}</details>
 <p><b>最近瓶颈：</b>${last?[...new Set(last.blocked.map((b:any)=>reasons[b.reason]??b.reason))].map(esc).join('、')||'无记录缺额':'尚未结束首个完整回合；不预先扣料或占用车辆。'}</p>
 ${u?`<p>${esc(u.id)} · ${esc(u.label)}：库存${u.stock/4}SP，欠账${u.debt/4}SP，维护${u.due/4}SP，连续缺供${u.short}轮。空仓沿用原战斗减效；每3轮维护不足损失一步。</p>`:''}
 ${u?(()=>{const g=x.equipment.find((g:any)=>g.id===u.id);return `<div class="unit-equipment"><h4>部队实际装备</h4>${Object.entries(g.required).map(([k,n]:any)=>`<p>${esc(x.products[k].label)} ${g.held[k]}/${n} · 待用${g.staged.filter((l:any)=>l.type===k).reduce((v:number,l:any)=>v+l.qty,0)}</p>`).join('')}<p>装备齐备${Math.round(g.ratio*100)}% · 攻${g.stats.attack} 防${g.stats.defense} 动${g.stats.movement}（供给/地形另计）</p><p>恢复一步：${Object.entries(g.recipe).map(([k,n])=>`${n} ${x.products[k].label}`).join('＋')}＋1人员</p></div>`;})():''}
 <label>本方部队定位<select id="grand-unit">${d.units.filter((u:any)=>u.alive).map((u:any)=>`<option value="${esc(u.id)}" ${u.id===selected?'selected':''}>${esc(u.id)} · ${esc(u.label)} · 损伤${u.step}</option>`).join('')}</select></label><button id="grand-focus">定位并选择部队</button>
 <details><summary>仓储、自动货运与详细路线</summary>${d.warehouses.map((w:any)=>`<p>${esc(w.label)}：人员${w.P}；装备${w.lots.filter((l:any)=>l.type!=='P').reduce((n:number,l:any)=>n+l.qty,0)}；仓内总量${w.lots.reduce((n:number,l:any)=>n+l.qty,0)}/${w.capacity} ${w.controlled?'':'· 服务失效'} ${focus(w.node,'定位仓库')}</p>`).join('')}<p>铁路与末端配送同E完成，下一T可用；恢复仍受原Core资格限制。</p><pre>${esc(JSON.stringify(last,null,1))}</pre></details>
 <details><summary>规则和回执</summary><p>初始每方4火车、8卡车。火车每E1024载重·铁路格；卡车每E32载重·地形费用。每站16载重基础近距（1格）；卡车最多6格，公路1、平原1、林丘2、沼泽3。线路192载重；仓容96是物理库存上限，不是额外运输额度。车辆不消耗，每E统一重置可用能力。源补给仍有限。</p><p>预备包与驻仓材料可能需要照管；预算不足仍隔离，不自动复活。人员不是工厂产品。新局/刷新不重抽军官属性。关闭页面保留当前服务内存会话，关闭服务会结束内存对局。</p><pre>${esc(JSON.stringify({income:d.lastLedger?.income,production:d.lastLedger?.production,care:d.lastLedger?.care,shipping:d.shipments,uses:d.uses},null,1))}</pre></details></section>`;
}
export function bindUx(p:GrandPort){
 document.querySelectorAll<HTMLSelectElement>('[data-ux-factories],[data-ux-production-priority]').forEach(el=>el.addEventListener('change',()=>{const id=el.dataset.uxFactories??el.dataset.uxProductionPriority,l=p.data.ux.lines.find((l:any)=>l.id===id);void p.operation({type:'PRODUCTION_LINE',warehouse:id,product:l.product,priority:el.dataset.uxProductionPriority?Number(el.value):l.priority,factories:el.dataset.uxFactories?p.data.ux.facilities.filter((f:any)=>f.warehouse===id&&f.status==='BUILT').slice(0,Number(el.value)).map((f:any)=>f.id):l.factories});}));
 document.querySelectorAll<HTMLSelectElement>('[data-ux-line]').forEach(el=>el.addEventListener('change',()=>void p.operation({type:'PRODUCTION_LINE',warehouse:el.dataset.uxLine,product:el.value})));
 document.querySelectorAll<HTMLElement>('[data-ux-army]').forEach(row=>{const priority=row.querySelector<HTMLSelectElement>('[data-ux-priority]')!,materials=row.querySelector<HTMLInputElement>('[data-ux-materials]')!,reserve=row.querySelector<HTMLSelectElement>('[data-ux-reserve]')!;const save=()=>void p.operation({type:'ARMY_PRIORITY',army:row.dataset.uxArmy,priority:Number(priority.value),materials:materials.checked,reserve:Number(reserve.value)});for(const el of [priority,materials,reserve])el.addEventListener('change',save);});
}
