import type {GrandPort} from './grand.js';
import {hexToPixel,hexPolygon,pointString} from '../geometry/hex.js';
import {building} from '../render/cityArt.js';
import {escStatus as esc,numberStatus as num} from './unitStatus.js';
import {industryEnabled,constructionTiming,districtFacilities,workLabels} from './industryModel.js';
const ns='http://www.w3.org/2000/svg',coord=(s:string)=>{const[q,r]=s.split(',').map(Number);return{q:q!,r:r!};};
const pos=(s:string)=>hexToPixel(coord(s));
let viewportPaint:()=>void=()=>{};
export const refreshIndustryViewport=()=>viewportPaint();
export const clearIndustry=()=>{viewportPaint=()=>{};document.querySelector('#industry-logistics')?.remove();document.querySelector('#eastfront-map')?.removeAttribute('data-industry-ms');};
function patch(layer:Element,parts:Map<string,string>){const old=new Map(Array.from(layer.children).map(e=>[e.getAttribute('data-key'),e]));for(const[k,html]of parts){let el=old.get(k);old.delete(k);if(!el){el=document.createElementNS(ns,'g');el.setAttribute('data-key',k);layer.append(el);}if(el.getAttribute('data-html')!==html){el.innerHTML=html;el.setAttribute('data-html',html);}}for(const el of old.values())el.remove();}
export function logisticsDetail(p:GrandPort){const m=p.data.modern,k=p.selections['logistics-object'];if(!k)return '';const type=k.slice(0,k.indexOf(':')),id=k.slice(k.indexOf(':')+1),o=m.logisticsObjects?.[k];
 const r=type==='RAIL'?m.rails.find((r:any)=>r.id===id):null,h=type==='HUB'?m.network.hubs.find((h:any)=>h.id===id):null;if(!r&&!h)return '<p>该对象当前不在授权视图中。</p>';
 const capacity=o?.capacity??(r?12*r.level:h.capacity),used=o?.used??(r?m.network.edges[id]??0:h.used),hex=r?.a??h.hex;
 return `<section class="industry-object"><h3>${r?'铁路 '+r.a+' → '+r.b:esc(h.label)}</h3><p>容量 ${num(capacity)} · 已占 ${num(used)} · 余量 ${num(o?.remaining??Math.max(0,capacity-used))}</p><p>${r?(r.damage?'线路损坏，需维修':used>=capacity-.001?'本次分配已满载':'线路可用'):(h.route?'已接通后方；覆盖'+h.coverage.length+'格':'未接通后方，增加车辆不能跨越断线')}</p><small>最近一次授权分配账目；不同路线共享同一容量，不可相加。</small><div class="button-row"><button data-ux-focus="${hex}">定位${r?'铁路':'枢纽'}</button>${r?`<button data-modern-build="${r.damage?'REPAIR_RAIL':'RAIL'}" data-target="${esc(id)}" ${p.locked||!r.damage&&r.level>=5?'disabled':''}>${r.damage?'排队维修':'排队升级'}</button>`:`<button data-modern-hub-view="${esc(id)}">覆盖／机动化</button>`}</div></section>`;
}
export function queueCards(m:any){const names:Record<string,string>={MIL:'军厂',CIV:'民厂',NEW_RAIL:'新铁路',NEW_HUB:'新枢纽',RAIL:'铁路升级',REPAIR_RAIL:'铁路维修',HUB:'枢纽升级',REPAIR_FACTORY:'厂房维修'};return m.queue.map((q:any)=>`<article class="industry-project"><header><b>${names[q.kind]??q.kind}</b><button data-ux-focus="${q.hex}">${esc(q.hex)} ↗</button></header><progress max="${q.cost}" value="${q.progress}"></progress><span>${num(q.progress)} / ${q.cost} 工时</span><small>${constructionTiming(m,q)}</small>${q.status!=='DONE'?`<label>队列优先<select data-modern-queue="${q.id}">${[1,2,3,4,5].map(n=>`<option ${n===q.priority?'selected':''}>${n}</option>`).join('')}</select></label>`:''}</article>`).join('')||'<p>暂无施工项目</p>';}
/** Keyed, viewport-limited overlay. It never mutates campaign or existing static SVG. */
export function paintIndustry(p:GrandPort,refresh:()=>void,canInspect:()=>boolean){
 const svg=document.querySelector<SVGSVGElement>('#eastfront-map');if(!svg)return;let layer=svg.querySelector<SVGGElement>('#industry-logistics');
 if(!p.data.modern||!industryEnabled(p)){layer?.remove();viewportPaint=()=>{};return;}
 svg.querySelector('#modern-supply-layer')?.remove();
 if(!layer){layer=document.createElementNS(ns,'g');layer.id='industry-logistics';layer.setAttribute('pointer-events','none');svg.insertBefore(layer,svg.querySelector('#compact-forces')??svg.querySelector('#battle-bubbles'));}
 const target=layer;
 const draw=()=>{const started=performance.now(),ctm=svg.getScreenCTM();if(!ctm)return;const scale=Math.hypot(ctm.a,ctm.b),px=1/scale,m=p.data.modern,supply=!!p.selections['modern-overlay'],parts=new Map<string,string>(),rect=(document.querySelector('#map-wrap')??svg).getBoundingClientRect();
 const visible=(a:{x:number,y:number},margin=90)=>{const x=a.x*ctm.a+a.y*ctm.c+ctm.e,y=a.x*ctm.b+a.y*ctm.d+ctm.f;return x>Math.max(0,rect.left)-margin&&x<Math.min(innerWidth,rect.right)+margin&&y>Math.max(0,rect.top)-margin&&y<Math.min(innerHeight,rect.bottom)+margin;};
 const clickable=(type:string,id:string,label:string,html:string)=>`<g data-logistics-object="${type}:${esc(id)}" tabindex="0" role="button" aria-label="${esc(label)}" style="pointer-events:${canInspect()&&!p.selections['build-pick']?'visiblePainted':'none'}"><title>${esc(label)}</title>${html}</g>`;
 const built=new Set(m.queue.filter((q:any)=>q.kind==='NEW_RAIL'&&q.status==='DONE').flatMap((q:any)=>q.segments.map((s:any)=>s.id)));
 for(const r of m.rails){const a=pos(r.a),b=pos(r.b);if(!visible(a)&&!visible(b))continue;const used=m.logisticsObjects?.['RAIL:'+r.id]?.used??m.network.edges[r.id]??0,cap=12*r.level,alert=r.damage||used>=cap-.001,chosen=p.selections['logistics-object']==='RAIL:'+r.id;
  let art='';if(built.has(r.id)){const length=Math.hypot(a.x-b.x,a.y-b.y),angle=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;art=`<g transform="translate(${a.x} ${a.y}) rotate(${angle})" stroke="#625c4d"><path d="M0 0H${length}" stroke-width="4" stroke-dasharray="1 3"/><path d="M0 -1.4H${length}M0 1.4H${length}" stroke-width=".7"/></g>`;}
  if(supply||chosen){const color=r.damage?'#c77057':alert?'#cfaa68':'#82aaa8';art+=clickable('RAIL',r.id,`铁路 ${r.a} 至 ${r.b} · ${r.damage?'损坏':alert?'满载':'可用'}`,`<circle cx="${(a.x+b.x)/2}" cy="${(a.y+b.y)/2}" r="${5*px}" fill="transparent"/><path d="M${a.x} ${a.y}L${b.x} ${b.y}" fill="none" stroke="#172b2d" stroke-width="${7*px}" opacity=".7"/><path d="M${a.x} ${a.y}L${b.x} ${b.y}" fill="none" stroke="${color}" stroke-width="${(chosen?4:2.5)*px}" ${r.damage?`stroke-dasharray="${5*px} ${5*px}"`:''}/>`);}
  if(art)parts.set('rail:'+r.id,art);
 }
 const selectedHub=m.network.hubs.find((h:any)=>h.id===p.selections['modern-hub']);if(supply)for(const k of selectedHub?.coverage??[]){if(visible(pos(k)))parts.set('coverage:'+k,`<polygon points="${hexPolygon(coord(k)).map(pointString).join(' ')}" fill="#648e95" opacity=".18"/>`);}
 for(const h of m.network.hubs){const a=pos(h.hex);if(!visible(a))continue;const city=p.data.cities.items.flatMap((c:any)=>c.districts).some((d:any)=>!d.hidden&&d.hex===h.hex&&d.type==='STATION'),s=Math.max(.6,Math.min(1.4,22*px/30));let art='';
  if(!city)art=`<g transform="translate(${a.x} ${a.y}) scale(${s})"><rect x="-19" y="-12" width="38" height="25" fill="#aaa48a" stroke="#797563" stroke-width=".6"/>${building(-16,-9,17,10,'close','house')}${building(4,-5,12,8,'close','factory')}<path d="M-18 8H18M-18 11H18" stroke="#5a6055"/><path d="M-17 6H17" stroke="#786f5b" stroke-width="5" stroke-dasharray="1 3"/><rect x="2" y="-11" width="5" height="3" fill="#8a7860"/></g>`;
  const color=!h.route?'#bf7962':h.used>=h.capacity-.001?'#c9a269':'#91b3a4',label=`${h.label} · ${h.route?'后方已接通':'后方未接通'}`;
  art+=clickable('HUB',h.id,label,`<g transform="translate(${a.x} ${a.y+17}) scale(${px})"><rect x="-10" y="0" width="20" height="13" rx="2" fill="#283b3b" stroke="${supply?color:'#c1c6ad'}" stroke-width="1.5"/><path d="M-6 9V4H6V9M-4 1H4M-4 11H4" fill="none" stroke="${supply?color:'#c1c6ad'}" stroke-width="1.4"/>${supply&&!h.route?'<text x="12" y="11" fill="#e4b29a" font-size="12">!</text>':''}</g>`);parts.set('hub:'+h.id,art);
 }
 for(const city of p.data.cities.items)for(const d of city.districts){if(d.hidden||d.unconfirmed||d.control!==p.data.viewer)continue;const fs=districtFacilities(p.data,d),built=fs.filter((f:any)=>f.status==='BUILT');if(!built.length)continue;const a=pos(d.hex);if(!visible(a))continue;const damaged=built.filter((f:any)=>f.damage).length,missing=built.filter((f:any)=>f.workState==='MISSING').length,active=built.filter((f:any)=>f.workState==='ACTIVE').length,color=damaged?'#bb846d':missing?'#d2b474':active?'#94bca3':'#b3b7a2';
 const label=`${city.label} · 厂房${built.length}座 · `+built.map((f:any)=>`${f.kind==='MIL'?'军厂':'民厂'} ${workLabels[f.workState]}`).join('；');
 parts.set('industry:'+d.id,clickable('DISTRICT',d.id,label,`<g transform="translate(${a.x-17} ${a.y-20}) scale(${px})"><rect x="-12" y="-8" width="${84*scale<45?26:43}" height="16" rx="2" fill="#2a3a37" stroke="${color}"/><path d="M-8 4V-3l4 2 4-2v7zM-7 -3v-3" fill="none" stroke="${color}" stroke-width="1.3"/><text x="4" y="4" font-size="11" fill="#e4e1cc">${built.length}${84*scale<45?'':damaged?' 破':missing?' !':active?' ▸':' Ⅱ'}</text></g>`));}
 for(const q of m.queue.filter((q:any)=>q.status!=='DONE')){const a=pos(q.hex);const color=q.status==='OCCUPIED'?'#bd846d':'#bcb494';for(const r of q.kind==='NEW_RAIL'?q.segments:[]){const x=pos(r.a),y=pos(r.b);if(visible(x)||visible(y))parts.set('build:'+q.id+':'+r.id,`<path d="M${x.x} ${x.y}L${y.x} ${y.y}" stroke="${color}" fill="none" stroke-width="${3*px}" stroke-dasharray="${6*px} ${4*px}"/>`);}
  if(visible(a)){const progress=Math.min(1,q.progress/q.cost);parts.set('project:'+q.id,`<g transform="translate(${a.x+19} ${a.y-18}) scale(${px})"><title>${esc(q.kind)} · ${constructionTiming(m,q)}</title><rect x="-7" y="-8" width="24" height="20" fill="#293936" stroke="${color}"/><path d="M-3 3V-4H12M0 -4V-7M10 -4V0" stroke="${color}" fill="none"/><path d="M-4 8H14" stroke="#131d1c" stroke-width="3"/><path d="M-4 8h${18*progress}" stroke="${color}" stroke-width="3"/></g>`);}
 }
 const plan=p.constructionPreview;if(plan?.valid&&plan.version===p.data.version){for(let i=1;i<plan.path.length;i++){const a=pos(plan.path[i-1]),b=pos(plan.path[i]);parts.set('preview:'+i,`<path d="M${a.x} ${a.y}L${b.x} ${b.y}" stroke="#e6dfbe" stroke-width="${4*px}" stroke-dasharray="${2*px} ${7*px}" fill="none"/>`);}const a=pos(plan.end);parts.set('preview:end',`<rect x="${a.x-15*px}" y="${a.y-15*px}" width="${30*px}" height="${30*px}" fill="none" stroke="#e6dfbe" stroke-width="${2*px}" stroke-dasharray="${3*px} ${4*px}"/>`);}
 patch(target,parts);svg.dataset.industryObjects=String(parts.size);svg.dataset.industryMs=(performance.now()-started).toFixed(2);
 };viewportPaint=draw;draw();
 target.onclick=event=>{const el=(event.target as Element).closest('[data-logistics-object]');if(!el||!canInspect()||p.selections['build-pick']||moved)return;event.stopPropagation();p.selections['logistics-object']=el.getAttribute('data-logistics-object')!;if(p.selections['logistics-object'].startsWith('DISTRICT:')){const id=p.selections['logistics-object'].slice(9),city=p.data.cities.items.find((c:any)=>c.districts.some((d:any)=>d.id===id));p.selections.city=city.id;p.selections.district=id;p.selections['ui-panel']='city';}else{p.selections['modern-tab']='supply';p.selections['modern-overlay']='1';p.selections['ui-panel']='economy';}refresh();};
 let start:{x:number,y:number}|null=null,moved=false;target.onpointerdown=e=>{start={x:e.clientX,y:e.clientY};moved=false;};target.onpointermove=e=>{if(start&&Math.hypot(start.x-e.clientX,start.y-e.clientY)>5)moved=true;};target.onkeydown=e=>{if(e.key==='Enter')(e.target as SVGElement).dispatchEvent(new MouseEvent('click',{bubbles:true}));};
}
