import {combinedAttributes,fuelAdjusted} from './combinedAttributes.mjs';
import type {GrandPort} from './grand.js';
import {escStatus as esc} from './unitStatus.js';
type Design={name:string;regiments:(string|null)[][];support:(string|null)[]};
type Editor={instance:string;base:string;draft:Design;slot:[number,number]|null;unit:string;pending:boolean;confirm:boolean;notice:string};
const editors=new WeakMap<GrandPort,Editor>();
const failureText=(code:string)=>({PIECE_REAR_DISCONNECTED:'后方补给通路未连通：请返回有后方连接的位置再换编',PIECE_IN_COMBAT:'正在交战，暂不能换编',PIECE_MOVING_OR_WITHDRAWING:'行军或撤退尚未完成',UNIT_COMMAND_CHANGED:'该部队命令已变化，请核对当前任务后重试',XP_INSUFFICIENT:'陆军经验不足',STALE_VERSION:'状态已变化，请核对后重试'} as Record<string,string>)[code]??code;

const labels:Record<string,string>={INFANTRY:'步兵营',ENGINEER:'工兵支援',RECON:'骑兵侦察',ARTILLERY:'炮兵营',SUPPORT_ARTILLERY:'支援炮兵',MOTORIZED:'摩托化步兵',LIGHT_ARMOR:'轻坦营 LT-0'},models:Record<string,string>={infantry_equipment_1:'步兵装备Ⅰ',support_equipment_1:'支援装备Ⅰ',artillery_equipment_1:'火炮Ⅰ',motorized_equipment_1:'卡车Ⅰ',leichttraktor_lt0:'轻型坦克 LT-0'};
const design=(t:any):Design=>({name:t.name,regiments:structuredClone(t.regiments),support:[...t.support]});
function state(p:GrandPort){let s=editors.get(p);const f=p.data.divisions.integrated;if(!s||s.instance!==p.data.instanceId){const t=f.templates[0];s={instance:p.data.instanceId,base:t.id,draft:design(t),slot:null,unit:p.selections['map-selected-unit']||f.units[0]?.id||'',pending:false,confirm:false,notice:''};editors.set(p,s);}return s;}
function needs(p:GrandPort,d:Design){const x={manpower:0,equipment:{} as Record<string,number>};for(const id of [...d.regiments.flat(),...d.support].filter(Boolean)){const r=p.data.divisions.demandReference.units[id!];x.manpower+=r.manpower;for(const[k,v]of Object.entries(r.equipment)){const model=p.data.divisions.integrated.catalog?.mapping[k]??k+'_1';x.equipment[model]=(x.equipment[model]??0)+Number(v);}}return x;}
function paper(p:GrandPort,d:Design){if(p.data.divisions.integrated.catalog){const n=needs(p,d),a=combinedAttributes(d,{personnel:n.manpower,held:n.equipment},p.data.divisions.integrated.catalog).paper;return {org:a.orgMax,hp:a.hp,attack:a.softAttack,defense:a.defense,supply:a.supply,hard:a.hardAttack,armor:a.armor,piercing:a.piercing,speed:a.speed,fuel:a.fuelHour,width:a.width};}const f=p.data.divisions.integrated,weapon={...f.models.infantry_equipment_1.archetypeFields,...f.models.infantry_equipment_1.modelFields},ids=[...d.regiments.flat(),...d.support].filter(Boolean);let org=0,hp=0,attack=0,defense=0,supply=0;for(const id of ids){const a=f.battalions[id!].scalarDefinitions;org+=a.max_organisation;hp+=a.max_strength;supply+=a.supply_consumption;attack+=weapon.soft_attack*(1+(a.soft_attack??0));defense+=weapon.defense*(1+(a.defense??0));}return {org:ids.length?org/ids.length:0,hp,attack,defense,supply,hard:0,armor:0,piercing:0,speed:3,fuel:0,width:0};}
// Read-only projection from authorized own inventory and the selected formal template.
export function adoptPreview(p:GrandPort,t:Design,u:any){if(p.data.divisions.integrated.catalog){const a=fuelAdjusted(combinedAttributes(t,u,p.data.divisions.integrated.catalog),p.data.divisions.integrated.fuel?.units[u.id]??0);return {attack:a.effective.softAttack,defense:a.effective.defense,org:a.paper.orgMax};}const d=needs(p,t),f=p.data.divisions.integrated,w={...f.models.infantry_equipment_1.archetypeFields,...f.models.infantry_equipment_1.modelFields};let attack=0,defense=0;const people=Math.min(1,u.personnel/d.manpower);for(const id of [...t.regiments.flat(),...t.support].filter(Boolean)){const r=p.data.divisions.demandReference.units[id!],a=f.battalions[id!].scalarDefinitions,fill=Math.min(people,...Object.keys(r.equipment).map(k=>Math.min(1,(u.held[k+'_1']??0)/(d.equipment[k+'_1']||1))));attack+=w.soft_attack*(1+(a.soft_attack??0))*fill;defense+=w.defense*(1+(a.defense??0))*fill;}return {attack,defense,...{org:paper(p,t).org}};}
function quote(s:Editor,base:any){let cost=0;for(let c=0;c<5;c++)for(let r=0;r<4;r++)if(s.draft.regiments[c]![r]!==base.regiments[c][r])cost+=5;for(let r=0;r<5;r++)if(s.draft.support[r]!==base.support[r])cost+=10;return cost;}
export function integratedPanel(p:GrandPort){const s=state(p),f=p.data.divisions.integrated,base=f.templates.find((t:any)=>t.id===s.base)??f.templates[0],d=needs(p,s.draft),u=f.units.find((u:any)=>u.id===s.unit),v=p.data.continuous.units[s.unit],cost=quote(s,base),preview=paper(p,s.draft),prior=paper(p,base),after=u?adoptPreview(p,base,u):null,drafts=p.data.divisions.templates;
 const slot=(c:number,r:number,id:string|null)=>`<button class="division-slot" data-integrated-slot="${c}:${r}" aria-label="${c<0?'支援':'第'+(c+1)+'团'}第${r+1}槽 ${id?labels[id]:'空'}" aria-pressed="${s.slot?.[0]===c&&s.slot?.[1]===r}"><b>${id==='INFANTRY'?'×':id==='ENGINEER'?'工':id==='RECON'?'⌕':id==='ARTILLERY'||id==='SUPPORT_ARTILLERY'?'●':id==='MOTORIZED'?'⊗':id==='LIGHT_ARMOR'?'▱':'＋'}</b><small>${id?labels[id]:'空'}</small></button>`;
 const tab=p.selections['designer-tab']??'edit';
 const stat=(label:string,before:number,after:number)=>`<div class="design-stat"><span>${label}</span><b>${after.toFixed(label==='供给需求'?2:1)}</b>${Math.abs(before-after)>.001?`<small>${before.toFixed(label==='供给需求'?2:1)} → ${after.toFixed(label==='供给需求'?2:1)}</small>`:''}</div>`;
 return `<section class="division-designer integrated-designer"><fieldset ${s.pending?'disabled':''}>
 <div class="designer-tabs"><button data-designer-tab="edit" aria-pressed="${tab==='edit'}">设计模板</button><button data-designer-tab="adopt" aria-pressed="${tab==='adopt'}">部队换编</button><b>陆军经验 ${f.xp}</b></div>
 <div class="design-library"><label>正式模板<select id="integrated-base">${f.templates.map((t:any)=>`<option value="${esc(t.id)}" ${t.id===s.base?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><button id="integrated-copy">复制模板</button>${tab==='edit'?`<input id="integrated-name" aria-label="模板名称" maxlength="48" value="${esc(s.draft.name)}"><button id="integrated-reset">还原</button>`:''}</div>
 ${tab==='edit'?`<div class="design-workspace"><div class="design-slots"><div class="division-grid"><div class="division-column"><small>支援连</small>${s.draft.support.map((id,r)=>slot(-1,r,id)).join('')}</div>${s.draft.regiments.map((a,c)=>`<div class="division-column"><small>第${c+1}团</small>${a.slice(0,4).map((id,r)=>slot(c,r,id)).join('')}</div>`).join('')}</div>
 <div class="division-palette" aria-label="选择正式编制条目">${s.slot?`${(s.slot[0]<0?(f.catalog?.supportIds??['ENGINEER','RECON']):Object.keys(f.catalog?.families??{INFANTRY:'infantry'})).map((id:string)=>`<button data-integrated-type="${id}"><b>${id==='INFANTRY'?'×':id==='ENGINEER'?'⚒':id==='RECON'?'⌕':id==='ARTILLERY'||id==='SUPPORT_ARTILLERY'?'●':id==='MOTORIZED'?'⊗':'▱'}</b> ${labels[id]}</button>`).join('')}<button data-integrated-type="">移除该槽</button>`:'<small>点一个槽位，添加或替换营／支援连</small>'}</div></div>
 <aside class="design-stats">${stat('组织上限',prior.org,preview.org)}${stat('软攻击',prior.attack,preview.attack)}${stat('防御',prior.defense,preview.defense)}${stat('强度',prior.hp,preview.hp)}${f.catalog?stat('硬攻击',prior.hard,preview.hard)+stat('装甲',prior.armor,preview.armor)+stat('穿甲',prior.piercing,preview.piercing)+stat('速度 km/h',prior.speed,preview.speed)+stat('燃耗 / 时',prior.fuel,preview.fuel):''}${stat('供给需求',prior.supply,preview.supply)}<div class="design-demand"><b>${d.manpower} 人</b>${Object.entries(d.equipment).map(([k,n])=>`<span>${models[k]} <b>${n}件</b></span>`).join('')}</div><small>显示满编属性；未到人员装备不提供满编战力。</small></aside></div>
 <details><summary>草案与规则说明</summary><select id="integrated-draft" aria-label="读取草案"><option value="">读取已保存草案</option>${drafts.map((t:any)=>`<option value="${esc(t.id)}">${esc(t.name)} v${t.version}</option>`).join('')}</select><p>每实际参战游戏小时最多获得1经验。最终修改差异：营槽5点，支援槽10点；复制、改名免费。${f.catalog?'轻坦固定为LT-0完整配置；军厂生产燃料，摩托和坦克行动耗油。各团只含同类别营。':'装甲等未映射兵种未开放；'}工兵渡河／壕沟和侦察战术特色未接入。项目适配，不是完整原版引擎。</p></details>
 <footer class="division-save-bar"><span>${cost} 经验<small>保存独立模板，不自动改全军</small></span><button id="integrated-save-draft">存草案</button><button id="integrated-formal" class="design-primary" ${f.xp<cost?'disabled':''}>保存模板 · ${cost}经验</button></footer>`:
 `<section class="design-adopt"><label>换编部队<select id="integrated-unit" aria-label="换编部队">${f.units.filter((x:any)=>p.data.continuous.units[x.id]?.alive).map((x:any)=>`<option value="${esc(x.id)}" ${x.id===s.unit?'selected':''}>${esc(x.id)} · ${Math.round(x.personnel)}人</option>`).join('')}</select></label>${u?`<h3>${esc(u.id)} → ${esc(base.name)}</h3><div class="adoption-impact"><table><tr><th></th><th>当前</th><th>换编即刻</th><th>补齐后${f.catalog?'（含燃料）':''}</th></tr><tr><td>软攻</td><td>${v?.division?.effective.softAttack.toFixed(2)??'—'}</td><td>${after!.attack.toFixed(2)}</td><td>${prior.attack.toFixed(2)}</td></tr><tr><td>防御</td><td>${v?.division?.effective.defense.toFixed(2)??'—'}</td><td>${after!.defense.toFixed(2)}</td><td>${prior.defense.toFixed(2)}</td></tr><tr><td>组织上限</td><td>${v?.division?.paper.orgMax.toFixed(1)??'—'}</td><td>${after!.org.toFixed(1)}</td><td>${prior.org.toFixed(1)}</td></tr></table><p>人员 ${Math.round(u.personnel)} → 需求 ${needs(p,base).manpower}</p>${Object.entries(needs(p,base).equipment).map(([k,n])=>`<p>${models[k]}：持有 ${u.held[k]??0}／需要 ${n}件</p>`).join('')}<small>增配支援但未补足人员时，比例分摊会暂时降低原步兵贡献。组织不赠满，多余人员装备退国家池，缺额由生产运输补齐。</small></div><footer class="division-save-bar"><span>${u.templateId===base.id?'已使用此模板':v?.engaged?'正在交战，暂不能换编':v?.march?'行军尚未结束':'脱战且后方连通时可换编'}<small>不收第二次模板费用</small></span><button id="integrated-adopt" class="design-primary" ${u.templateId===base.id||v?.engaged||v?.march?'disabled':''}>换用所选模板</button></footer><p>${esc(v?.refillStatus?.reason??'')}</p>`:''}</section>`}
 ${s.confirm?`<div class="design-confirm" role="group" aria-label="确认正式模板"><b>保存“${esc(s.draft.name)}”</b><p>消耗 ${cost} 经验。现役部队暂不变；下一步选择换编部队。</p><button id="integrated-formal-confirm">确认保存 · ${cost}经验</button><button id="integrated-cancel">返回编辑</button></div>`:''}<p class="designer-notice" role="status">${esc(s.notice)}</p>
 </fieldset></section>`;
}
export function bindIntegrated(p:GrandPort,refresh:()=>void){const s=state(p),f=p.data.divisions.integrated;const on=(id:string,fn:()=>void)=>{const el=document.getElementById(id);if(el)el.onclick=fn;};
 document.querySelectorAll<HTMLElement>('[data-designer-tab]').forEach(el=>el.onclick=()=>{p.selections['designer-tab']=el.dataset.designerTab!;refresh();});
 const base=document.querySelector<HTMLSelectElement>('#integrated-base');if(base)base.onchange=()=>{s.base=base.value;s.draft=design(f.templates.find((t:any)=>t.id===s.base));s.confirm=false;refresh();};
 const lib=document.querySelector<HTMLSelectElement>('#integrated-draft');if(lib)lib.onchange=()=>{const d=p.data.divisions.templates.find((t:any)=>t.id===lib.value);if(d){s.draft=design(d);s.confirm=false;refresh();}};
 const name=document.querySelector<HTMLInputElement>('#integrated-name');if(name)name.oninput=()=>{s.draft.name=name.value;s.confirm=false;};
 const unit=document.querySelector<HTMLSelectElement>('#integrated-unit');if(unit)unit.onchange=()=>{s.unit=unit.value;refresh();};
 document.querySelectorAll<HTMLElement>('[data-integrated-slot]').forEach(el=>el.onclick=()=>{s.slot=el.dataset.integratedSlot!.split(':').map(Number) as [number,number];refresh();});
 document.querySelectorAll<HTMLElement>('[data-integrated-type]').forEach(el=>el.onclick=()=>{if(!s.slot)return;const[c,r]=s.slot,id=el.dataset.integratedType||null;if(c<0&&id&&s.draft.support.some((x,i)=>x===id&&i!==r)){s.notice='此支援连已存在';refresh();return;}if(c>=0&&id&&f.catalog){const others=s.draft.regiments[c]!.filter((x,i)=>x&&i!==r);if(others.some(x=>f.catalog.families[x!]!==f.catalog.families[id])){s.notice='同一团只能放同类别营，请选一个空团';refresh();return;}}if(c<0)s.draft.support[r]=id;else s.draft.regiments[c]![r]=id;s.slot=null;s.confirm=false;refresh();});
 const submit=(operation:any)=>{s.pending=true;s.notice='等待权威回执';let id:string|undefined;const done=(ev:any)=>{if(ev.detail.requestId!==id)return;p.wire.removeEventListener('completed',done);s.pending=false;const row=p.wire.history.find((r:any)=>r.command.requestId===id);s.notice=ev.detail.status==='applied'?'已完成':failureText(String(row?.result?.reason??'未接受，请查看消息'));if(operation.type==='DIVISION_FORMAL_SAVE'&&ev.detail.status==='applied'){const receipt=row?.result?.division;if(receipt?.templateId){s.base=receipt.templateId;p.selections['designer-tab']='adopt';s.notice='正式模板已保存；请明确选择换编部队';}}refresh();};p.wire.addEventListener('completed',done);void p.operation(operation).then(x=>{id=x;if(!x){p.wire.removeEventListener('completed',done);s.pending=false;refresh();}});refresh();};
 on('integrated-copy',()=>{s.draft.name+=' 副本';s.confirm=false;p.selections['designer-tab']='edit';refresh();});on('integrated-reset',()=>{s.draft=design(f.templates.find((t:any)=>t.id===s.base));s.confirm=false;refresh();});
 on('integrated-save-draft',()=>submit({type:'DIVISION_DRAFT_SAVE',draft:structuredClone(s.draft)}));on('integrated-formal',()=>{s.confirm=true;refresh();});on('integrated-cancel',()=>{s.confirm=false;refresh();});
 on('integrated-formal-confirm',()=>{s.confirm=false;const b=f.templates.find((t:any)=>t.id===s.base);submit({type:'DIVISION_FORMAL_SAVE',baseId:b.id,expectedBaseVersion:b.version,draft:structuredClone(s.draft)});});
 on('integrated-adopt',()=>{const u=f.units.find((u:any)=>u.id===s.unit),t=f.templates.find((t:any)=>t.id===s.base);submit({type:'DIVISION_FORMAL_ADOPT',unit:u.id,expectedUnitRevision:u.revision,templateId:t.id,expectedTemplateVersion:t.version});});
}
