import type {GrandPort} from './grand.js';
import {escStatus as esc} from './unitStatus.js';
type Design={name:string;regiments:(string|null)[][];support:(string|null)[]};
type Editor={instance:string;base:string;draft:Design;slot:[number,number]|null;unit:string;pending:boolean;confirm:boolean;notice:string};
const editors=new WeakMap<GrandPort,Editor>();
const failureText=(code:string)=>({PIECE_REAR_DISCONNECTED:'后方补给通路未连通：请返回有后方连接的位置再换编',PIECE_IN_COMBAT:'正在交战，暂不能换编',PIECE_MOVING_OR_WITHDRAWING:'行军或撤退尚未完成',UNIT_COMMAND_CHANGED:'该部队命令已变化，请核对当前任务后重试',XP_INSUFFICIENT:'陆军经验不足',STALE_VERSION:'状态已变化，请核对后重试'} as Record<string,string>)[code]??code;

const labels:Record<string,string>={INFANTRY:'步兵营',ENGINEER:'工兵支援',RECON:'骑兵侦察'},models:Record<string,string>={infantry_equipment_1:'步兵装备Ⅰ',support_equipment_1:'支援装备Ⅰ'};
const design=(t:any):Design=>({name:t.name,regiments:structuredClone(t.regiments),support:[...t.support]});
function state(p:GrandPort){let s=editors.get(p);const f=p.data.divisions.integrated;if(!s||s.instance!==p.data.instanceId){const t=f.templates[0];s={instance:p.data.instanceId,base:t.id,draft:design(t),slot:null,unit:f.units[0]?.id??'',pending:false,confirm:false,notice:''};editors.set(p,s);}return s;}
function needs(p:GrandPort,d:Design){const x={manpower:0,equipment:{} as Record<string,number>};for(const id of [...d.regiments.flat(),...d.support].filter(Boolean)){const r=p.data.divisions.demandReference.units[id!];x.manpower+=r.manpower;for(const[k,v]of Object.entries(r.equipment))x.equipment[k+'_1']=(x.equipment[k+'_1']??0)+Number(v);}return x;}
function paper(p:GrandPort,d:Design){const f=p.data.divisions.integrated,weapon={...f.models.infantry_equipment_1.archetypeFields,...f.models.infantry_equipment_1.modelFields},ids=[...d.regiments.flat(),...d.support].filter(Boolean);let org=0,hp=0,attack=0,defense=0,supply=0;for(const id of ids){const a=f.battalions[id!].scalarDefinitions;org+=a.max_organisation;hp+=a.max_strength;supply+=a.supply_consumption;attack+=weapon.soft_attack*(1+(a.soft_attack??0));defense+=weapon.defense*(1+(a.defense??0));}return {org:ids.length?org/ids.length:0,hp,attack,defense,supply};}
// Read-only projection from authorized own inventory and the selected formal template.
export function adoptPreview(p:GrandPort,t:Design,u:any){const d=needs(p,t),f=p.data.divisions.integrated,w={...f.models.infantry_equipment_1.archetypeFields,...f.models.infantry_equipment_1.modelFields};let attack=0,defense=0;const people=Math.min(1,u.personnel/d.manpower);for(const id of [...t.regiments.flat(),...t.support].filter(Boolean)){const r=p.data.divisions.demandReference.units[id!],a=f.battalions[id!].scalarDefinitions,fill=Math.min(people,...Object.keys(r.equipment).map(k=>Math.min(1,(u.held[k+'_1']??0)/(d.equipment[k+'_1']||1))));attack+=w.soft_attack*(1+(a.soft_attack??0))*fill;defense+=w.defense*(1+(a.defense??0))*fill;}return {attack,defense,...{org:paper(p,t).org}};}
function quote(s:Editor,base:any){let cost=0;for(let c=0;c<5;c++)for(let r=0;r<4;r++)if(s.draft.regiments[c]![r]!==base.regiments[c][r])cost+=5;for(let r=0;r<5;r++)if(s.draft.support[r]!==base.support[r])cost+=10;return cost;}
export function integratedPanel(p:GrandPort){const s=state(p),f=p.data.divisions.integrated,base=f.templates.find((t:any)=>t.id===s.base)??f.templates[0],d=needs(p,s.draft),u=f.units.find((u:any)=>u.id===s.unit),v=p.data.continuous.units[s.unit],cost=quote(s,base),preview=paper(p,s.draft),prior=paper(p,base),after=u?adoptPreview(p,base,u):null,drafts=p.data.divisions.templates;
 const slot=(c:number,r:number,id:string|null)=>`<button class="division-slot" data-integrated-slot="${c}:${r}" aria-label="${c<0?'支援':'第'+(c+1)+'团'}第${r+1}槽 ${id?labels[id]:'空'}" aria-pressed="${s.slot?.[0]===c&&s.slot?.[1]===r}"><b>${id==='INFANTRY'?'×':id==='ENGINEER'?'工':id==='RECON'?'⌕':'＋'}</b><small>${id?labels[id]:'空'}</small></button>`;
 return `<section class="division-designer integrated-designer"><fieldset ${s.pending?'disabled':''}><div class="division-head"><b>正式编制 · 步兵先行候选</b><span>陆军经验 ${f.xp} · 下一点还需参战 ${60-f.earnedMinutes} 分钟</span><label>编辑基准<select id="integrated-base">${f.templates.map((t:any)=>`<option value="${esc(t.id)}" ${t.id===s.base?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>草案<select id="integrated-draft"><option value="">读取已保存草案</option>${drafts.map((t:any)=>`<option value="${esc(t.id)}">${esc(t.name)} v${t.version}</option>`).join('')}</select></label><label>名称<input id="integrated-name" maxlength="48" value="${esc(s.draft.name)}"></label><div class="button-row"><button id="integrated-copy">复制</button><button id="integrated-reset">撤销修改</button></div></div>
 <div class="division-grid"><div class="division-column"><small>支援连</small>${s.draft.support.map((id,r)=>slot(-1,r,id)).join('')}</div>${s.draft.regiments.map((a,c)=>`<div class="division-column"><small>第${c+1}团</small>${a.slice(0,4).map((id,r)=>slot(c,r,id)).join('')}</div>`).join('')}</div>
 ${s.slot?`<div class="division-palette" aria-label="选择正式编制条目">${(s.slot[0]<0?['ENGINEER','RECON']:['INFANTRY']).map(id=>`<button data-integrated-type="${id}">${labels[id]}</button>`).join('')}<button data-integrated-type="">移除</button></div>`:''}
 <div class="division-save-bar"><span>目标 ${d.manpower} 人<small>${Object.entries(d.equipment).map(([k,n])=>models[k]+' '+n+'件').join(' · ')}</small><small>正式修改 ${cost} 经验；现役不自动换编</small><small>满编软攻 ${prior.attack.toFixed(1)}→${preview.attack.toFixed(1)} · 组织上限 ${prior.org.toFixed(1)}→${preview.org.toFixed(1)}</small></span><button id="integrated-save-draft">保存免费草案</button><button id="integrated-formal" ${f.xp<cost?'disabled':''}>正式保存 · ${cost}经验</button></div>
 ${s.confirm?`<div role="group" aria-label="确认正式模板"><p>支付 ${cost} 经验，另存独立正式模板；现役影响0队。草案不获得人员或装备。满编防御 ${prior.defense.toFixed(1)}→${preview.defense.toFixed(1)}；强度上限 ${prior.hp}→${preview.hp}；供给需求 ${prior.supply.toFixed(2)}→${preview.supply.toFixed(2)}。</p><button id="integrated-formal-confirm">确认正式保存</button><button id="integrated-cancel">取消</button></div>`:''}<p role="status">${esc(s.notice)}</p>
 <section><h3>选择一队换编</h3><select id="integrated-unit" aria-label="换编部队">${f.units.map((x:any)=>`<option value="${esc(x.id)}" ${x.id===s.unit?'selected':''}>${esc(x.id)} · ${x.personnel}人</option>`).join('')}</select>${u?`<p>当前 ${u.personnel}／${u.target.manpower}人 · 组织 ${u.org.toFixed(1)} · 训练经验 ${u.trainingExperience}（本候选不应用未核实损耗）</p><p>${Object.entries(u.held).map(([k,n])=>`${models[k]} ${n}／${u.target.equipment[k]}件`).join(' · ')}</p><div class="adoption-impact" aria-label="采用前属性对比"><b>采用前核对：${esc(base.name)}</b><table><tr><th>属性</th><th>当前</th><th>换编后未补齐</th><th>目标满编</th></tr><tr><td>软攻</td><td>${v?.division?.effective.softAttack.toFixed(2)??'未知'}</td><td>${after!.attack.toFixed(2)}</td><td>${prior.attack.toFixed(2)}</td></tr><tr><td>防御</td><td>${v?.division?.effective.defense.toFixed(2)??'未知'}</td><td>${after!.defense.toFixed(2)}</td><td>${prior.defense.toFixed(2)}</td></tr><tr><td>组织上限</td><td>${v?.division?.paper.orgMax.toFixed(1)??'未知'}</td><td>${after!.org.toFixed(1)}</td><td>${prior.org.toFixed(1)}</td></tr></table><small>采用的是正式基准。增配工兵但尚未补足人员时，按比例重分会暂时降低现役步兵贡献。满编值不代表立即到货或恢复组织；不含当前供给修正。当前组织采用后最多${Math.min(u.org,after!.org).toFixed(1)}。</small></div><button id="integrated-adopt" ${u.templateId===base.id||v?.engaged||v?.march?'disabled':''}>将此队换用“${esc(base.name)}” · 不再收费</button><small>采用的是上方正式基准，不是未保存草案。须未交战、无行军撤退且后方连通；多余人员装备原子返库，缺额由生产运输补充。</small><p>${esc(v?.reason??'')}</p><p>${esc(v?.refillStatus?.reason??'')}${(f.inTransit??[]).filter((r:any)=>r.unit===u.id).map((r:any)=>` · ${models[r.model]}1件运输中 ${Math.floor(r.work/r.required*100)}%（不计已到货）`).join('')}</p><details><summary>纸面与当前有效属性</summary>${v?.division?`<table><tr><th>属性</th><th>满编</th><th>实有</th></tr>${(['softAttack','hardAttack','defense','breakthrough','hp','width','supply','armor','piercing'] as const).map(k=>`<tr><td>${({softAttack:'软攻',hardAttack:'硬攻',defense:'防御',breakthrough:'突破',hp:'强度上限',width:'宽度',supply:'供给需求',armor:'装甲',piercing:'穿甲'})[k]}</td><td>${Number(v.division.paper[k]).toFixed(2)}</td><td>${Number(v.division.effective[k]).toFixed(2)}</td></tr>`).join('')}</table><p>组织上限：${v.division.components?.map((x:any)=>`${labels[x.id]} ${x.orgTerm}`).join(" ＋ ")}，按 ${v.division.components?.length} 个营／支援连等权平均。换编只截断上限，不恢复当前组织。</p><table><tr><th>组成</th><th>满足率</th><th>有效软攻</th><th>有效防御</th></tr>${(v.division.components??[]).map((x:any)=>`<tr><td>${labels[x.id]}</td><td>${(x.satisfaction*100).toFixed(1)}%</td><td>${x.effective.softAttack.toFixed(2)}</td><td>${x.effective.defense.toFixed(2)}</td></tr>`).join('')}</table><small>人员和同型装备按全队需求比例分配，各组成取本身所需类别的最低满足率。缺支援装备不直接压低步兵；扩编未补人会通过人员分摊降低步兵贡献。这是项目适配。</small>`:''}</details>`:''}</section>
 <details><summary>规则范围与适配</summary><p>国家经验从实际交战小时获得，每阵营每小时最多1点。正式最终差异：步兵槽5点、支援槽10点；复制改名不收费。双方采用同一项目连续战斗尺度，非原版引擎复刻。第五排、团属支援及其他装备型号未开放；工兵壕沟、渡河修正和侦察选战术未接入；侦察不扩大情报权限。装甲、摩托等未映射类型不在本候选，不能视为完整战役升级。补充现为每队${f.reception?.personnelDay??60}人／日、每型号${f.reception?.equipmentDay??2}件／日（${f.reception?.policy==='DIVISION-RECEPTION-2'?'新建战役速率':'原存档速率'}）；库存充足仍受接收和共享运输限制。仅本规则新局有效，旧战役不迁移。</p></details></fieldset></section>`;
}
export function bindIntegrated(p:GrandPort,refresh:()=>void){const s=state(p),f=p.data.divisions.integrated;const on=(id:string,fn:()=>void)=>{const el=document.getElementById(id);if(el)el.onclick=fn;};
 const base=document.querySelector<HTMLSelectElement>('#integrated-base');if(base)base.onchange=()=>{s.base=base.value;s.draft=design(f.templates.find((t:any)=>t.id===s.base));s.confirm=false;refresh();};
 const lib=document.querySelector<HTMLSelectElement>('#integrated-draft');if(lib)lib.onchange=()=>{const d=p.data.divisions.templates.find((t:any)=>t.id===lib.value);if(d){s.draft=design(d);s.confirm=false;refresh();}};
 const name=document.querySelector<HTMLInputElement>('#integrated-name');if(name)name.oninput=()=>{s.draft.name=name.value;s.confirm=false;};
 const unit=document.querySelector<HTMLSelectElement>('#integrated-unit');if(unit)unit.onchange=()=>{s.unit=unit.value;refresh();};
 document.querySelectorAll<HTMLElement>('[data-integrated-slot]').forEach(el=>el.onclick=()=>{s.slot=el.dataset.integratedSlot!.split(':').map(Number) as [number,number];refresh();});
 document.querySelectorAll<HTMLElement>('[data-integrated-type]').forEach(el=>el.onclick=()=>{if(!s.slot)return;const[c,r]=s.slot,id=el.dataset.integratedType||null;if(c<0&&id&&s.draft.support.some((x,i)=>x===id&&i!==r)){s.notice='此支援连已存在';refresh();return;}if(c<0)s.draft.support[r]=id;else s.draft.regiments[c]![r]=id;s.slot=null;s.confirm=false;refresh();});
 const submit=(operation:any)=>{s.pending=true;s.notice='等待权威回执';let id:string|undefined;const done=(ev:any)=>{if(ev.detail.requestId!==id)return;p.wire.removeEventListener('completed',done);s.pending=false;const row=p.wire.history.find((r:any)=>r.command.requestId===id);s.notice=ev.detail.status==='applied'?'已完成':failureText(String(row?.result?.reason??'未接受，请查看消息'));if(operation.type==='DIVISION_FORMAL_SAVE'&&ev.detail.status==='applied'){const receipt=row?.result?.division;if(receipt?.templateId){s.base=receipt.templateId;s.notice='正式模板已保存；请明确选择换编部队';}}refresh();};p.wire.addEventListener('completed',done);void p.operation(operation).then(x=>{id=x;if(!x){p.wire.removeEventListener('completed',done);s.pending=false;refresh();}});refresh();};
 on('integrated-copy',()=>{s.draft.name+=' 副本';s.confirm=false;refresh();});on('integrated-reset',()=>{s.draft=design(f.templates.find((t:any)=>t.id===s.base));s.confirm=false;refresh();});
 on('integrated-save-draft',()=>submit({type:'DIVISION_DRAFT_SAVE',draft:structuredClone(s.draft)}));on('integrated-formal',()=>{s.confirm=true;refresh();});on('integrated-cancel',()=>{s.confirm=false;refresh();});
 on('integrated-formal-confirm',()=>{s.confirm=false;const b=f.templates.find((t:any)=>t.id===s.base);submit({type:'DIVISION_FORMAL_SAVE',baseId:b.id,expectedBaseVersion:b.version,draft:structuredClone(s.draft)});});
 on('integrated-adopt',()=>{const u=f.units.find((u:any)=>u.id===s.unit),t=f.templates.find((t:any)=>t.id===s.base);submit({type:'DIVISION_FORMAL_ADOPT',unit:u.id,expectedUnitRevision:u.revision,templateId:t.id,expectedTemplateVersion:t.version});});
}
