// UI006 receipt-first, monotone read recovery adapted to the main game's DTO transport.
import type{WorkerPort}from'../local-ai/client.js';import type{LocalRequest,LocalReply}from'../local-ai/types.js';
const KEY='playable002.pending.v1',FLOOR='playable002.floor.v1';
export class LogisticsPort implements WorkerPort{
 onmessage:WorkerPort['onmessage']=null;onerror:WorkerPort['onerror']=null;data:any=null;notice='';locked=false;
 plan:any=null;baselinePlan:any=null;choices:{reductions:Record<string,number>;priorities:Record<string,number>}={reductions:{},priorities:{}};
 private token='';private epoch=1;private dead=false;private pending:any=null;private floor:any=null;
 constructor(private update:()=>void){}
 private async api(path:string,body?:unknown){const c=new AbortController(),timer=setTimeout(()=>c.abort(),10000);try{const r=await fetch(path,{method:body===undefined?'GET':'POST',cache:'no-store',headers:{'X-Local-Session':this.token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?null:JSON.stringify(body),signal:c.signal});const d=await r.json();if(!r.ok)throw Error(d.error??'读取失败');return d;}finally{clearTimeout(timer);}}
 private emit(message:any){if(!this.dead)this.onmessage?.({data:{epoch:this.epoch,message,meta:this.data.game.meta}} as MessageEvent<LocalReply>);}
 private keep(p:any){this.pending=p;this.locked=!!p;if(p)sessionStorage.setItem(KEY,JSON.stringify(p));else sessionStorage.removeItem(KEY);this.update();}
 private read(d:any){const instance=this.pending?.instanceId??this.floor?.instanceId??this.data?.instanceId;const floor=Math.max(this.floor?.version??0,this.data?.version??0,this.pending?.confirmation?.minVersion??0);if(instance&&instance!==d.instanceId)throw Error('实例不符：未解除原请求锁定');if(!Number.isSafeInteger(d.version)||d.version<floor||d.game.message.payload.matchRevision!==d.version)throw Error('旧账本或地图版本不一致');this.floor={instanceId:d.instanceId,version:d.version};sessionStorage.setItem(FLOOR,JSON.stringify(this.floor));if(this.plan&&this.plan.version!==d.version)this.plan=null;this.data=d;this.emit(d.game.message);this.update();}
 async refresh(message?:string){try{this.read(await this.api('/api/state'));if(this.pending?.confirmation)this.keep(null);this.notice=message??'同一次提交的地图、库存及工业账本已读取。';this.update();return true;}catch(e){this.locked=true;this.notice='账本待刷新；操作保持锁定。'+String(e);this.update();return false;}}
 private confirmedGame(r:any){if(!r.ok)return;if(!Number.isSafeInteger(r.version)||r.version<=this.data.version)throw Error('动作确认版本无效');this.floor={instanceId:this.data.instanceId,version:r.version};sessionStorage.setItem(FLOOR,JSON.stringify(this.floor));}
 private async reconcile(r:any){const p=this.pending;if(!p)return true;if(['requestId','instanceId','operation','expectedVersion'].some(k=>r[k]!==p[k]))throw Error('回执标识不符');if(!['COMMITTED','REJECTED'].includes(r.status))return false;const minVersion=Math.max(p.expectedVersion,r.resultVersion??0);if(r.status==='COMMITTED'&&minVersion<=p.expectedVersion)throw Error('确认版本无效');this.keep({...p,confirmation:{status:r.status,minVersion}});this.notice=r.status==='COMMITTED'?'已确认提交；同一版本地图与账本已读取。':'已拒绝：'+r.code;await this.refresh(this.notice);return true;}
 async recover(){if(this.pending?.confirmation||!this.pending){const ok=await this.refresh();if(ok&&!this.pending)this.locked=false;this.update();return;}try{await this.reconcile(await this.api('/api/requests/'+this.pending.requestId));}catch(e){this.notice='结果待确认，保留原请求。'+String(e);}this.update();}
 async operate(operation:string){if(this.locked||this.dead||!this.data?.operations[operation]?.enabled)return;this.keep({requestId:crypto.randomUUID(),instanceId:this.data.instanceId,expectedVersion:this.data.version,operation});await this.retry();}
 setChoice(id:string,kind:'reductions'|'priorities',n:number){if(this.locked)return;this.choices[kind][id]=n;this.plan=null;this.update();}
 async previewFreight(reset=false){if(this.locked||!this.data.freightPlanning?.enabled)return;this.locked=true;this.update();try{
  if(reset)this.choices={reductions:{},priorities:{}};
  const version=this.data.version;
  if(this.baselinePlan?.version!==version)this.baselinePlan=await this.api('/play/freight-preview',{version,choices:{reductions:{},priorities:{}}});
  this.plan=reset?this.baselinePlan:await this.api('/play/freight-preview',{version,choices:this.choices});
  this.notice='预览未扣费、未推进阶段；请核对代价后明确确认。';
 }catch(e){this.plan=null;this.notice='预览未完成：'+String(e);}finally{this.locked=false;this.update();}}
 async confirmFreight(){if(this.locked||this.plan?.status!=='FEASIBLE'||this.plan.version!==this.data.version)return;
  this.keep({requestId:crypto.randomUUID(),instanceId:this.data.instanceId,expectedVersion:this.data.version,operation:'FREIGHT_'+this.plan.planId});await this.retry();}
 async retry(){if(!this.pending)return;if(this.pending.confirmation){await this.refresh();return;}this.locked=true;const {requestId,instanceId,expectedVersion,operation}=this.pending;try{let r=await this.api('/api/operations',{requestId,instanceId,expectedVersion,operation});for(let i=0;i<10;i++){if(await this.reconcile(r))break;await new Promise(r=>setTimeout(r,400));r=await this.api('/api/requests/'+requestId);}}catch(e){this.notice='结果待确认，未自动换ID重试。'+String(e);}this.update();}
 async aiStep(){if(this.locked)return;this.locked=true;this.update();try{const r=await this.api('/play/ai',{});this.confirmedGame(r);this.notice=r.ok?'AI已执行一个真实作战动作。':'AI停步：'+r.error;this.locked=!(await this.refresh(this.notice));}catch(e){this.notice=String(e);}this.update();}
 postMessage(m:LocalRequest){void this.handle(m);}
 private async handle(m:LocalRequest){try{
  this.epoch=m.epoch;
  if(m.kind==='START'){
   this.pending=JSON.parse(sessionStorage.getItem(KEY)||'null');this.floor=JSON.parse(sessionStorage.getItem(FLOOR)||'null');this.locked=!!this.pending;
   this.token=(await this.api('/play/connect')).token;
   const d=await this.api('/play/create',{mode:'industry018',side:'GERMAN'});
   if(!this.pending&&this.floor?.instanceId!==d.instanceId){this.floor=null;sessionStorage.removeItem(FLOOR);}
   this.read(d);if(this.pending)await this.recover();return;
  }
  if(m.kind==='TAKEOVER')return;
  if(m.kind==='REQUEST'){
   const p=m.payload as any;
   if(m.type==='RESYNC_MATCH'){await this.refresh();return;}
   if(m.type==='QUERY_MATCH'){const q=await this.api('/play/query',{id:m.requestId,version:p.expectedRevision,draft:p.draft});this.emit(q);return;}
   if(this.locked){await this.refresh();return;}
   if(['READY_FOR_PHASE_END','END_PHASE'].includes(p.action.type)){await this.operate('NEXT');return;}
   this.locked=true;this.update();const r=await this.api('/play/action',{id:m.requestId,version:p.expectedRevision,action:p.action});this.confirmedGame(r);this.notice=r.ok?'原Core行动已提交。':'行动未提交：'+r.error;this.locked=!(await this.refresh(this.notice));this.update();
  }
 }catch(e){this.notice='连接或读取失败，保持锁定：'+String(e);this.locked=true;this.update();}}
 terminate(){this.dead=true;}
}
const esc=(x:unknown)=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function logisticsMarkup(p:LogisticsPort):string{const d=p.data;if(!d)return '<p>正在连接本机事务服务。</p>';const i=d.extensions.industry018,s=d.supply,target=s.units.find((u:any)=>u.id==='G-I-01');
 return `<section class="panel-block logistics-panel"><strong>新补给＋工业 · T${d.turn}</strong><p>${esc(d.playableScope)}</p><p role="status">${esc(p.notice)}</p><div class="button-row"><button id="logistics-read">恢复读取</button><button id="logistics-retry" ${p.locked?'':'hidden'}>核对原请求</button><button id="logistics-repost" ${p.locked?'':'hidden'}>仅重试原请求</button></div><p>装备I：${d.equipmentBudget.freeI}；生产已付${d.equipmentBudget.productionSpent}；交接已付${d.equipmentBudget.handoffSpent}；托管${d.equipmentBudget.escrow}。人员I：${d.personnelBudget.availableI}。</p><p>生产 ${i.production.workCompleted}/${i.production.workRequired}；前线可用P ${d.availableFrontInventory.P} / E2 ${d.availableFrontInventory['E2:L']}；G-I-01步损 ${d.target.step}。</p><p>${(d.blockers??[]).map(esc).join("；")}</p>${freightMarkup(p)}<div class="logistics-ops">${Object.entries(d.operations).sort(([a,x]:[string,any],[b,y]:[string,any])=>Number(y.enabled)-Number(x.enabled)||['ALLOCATE_I','PLACE_ORDER','ACTIVATE_PERSONNEL','APPLY_PERSONNEL','CARE','RECOVER','NEXT'].indexOf(a)-['ALLOCATE_I','PLACE_ORDER','ACTIVATE_PERSONNEL','APPLY_PERSONNEL','CARE','RECOVER','NEXT'].indexOf(b)).map(([op,v]:[string,any])=>`<button data-logistics-op="${op}" ${p.locked||!v.enabled?'disabled':''}>${esc(v.label)}</button>`).join('')}</div><button id="logistics-ai" ${p.locked||d.game.meta.ownerSide!=='SOVIET'||(!['SOVIET_MOVEMENT','SOVIET_COMBAT'].includes(d.phase)&&!d.game.message.payload.view.pendingDecision)?'disabled':''}>让AI执行一个苏军作战动作</button><details><summary>已结算补给与运力</summary><p>当前库存：${target?target.stock/4:'—'}SP；维护份额${target?target.B/4:'—'}SP；欠账D ${esc(target?.debt)}。修路不会立即补仓。</p><table><thead><tr><th>单位</th><th>库存SP</th><th>目标SP</th><th>欠账D</th></tr></thead><tbody>${s.units.map((u:any)=>`<tr><td>${esc(u.id)}</td><td>${u.stock/4}</td><td>${u.target/4}</td><td>${esc(u.debt)}</td></tr>`).join('')}</tbody></table><h4>已结算运输</h4><table><tr><th>通路/能力</th><th>总量</th><th>SP占用</th><th>货运</th><th>余量</th></tr>${(d.transport??[]).map((x:any)=>`<tr><td>${esc(x.id)}</td><td>${x.originalCap}</td><td>${x.spUsed}</td><td>${x.freight??x.cargo}</td><td>${x.remaining}</td></tr>`).join('')}</table><p>容量保留原规则整数刻度，SP和工业货物共同占用；照管：${esc(d.care?.status??'尚未支付')}，到期E${esc(d.care?.endEpoch)}。</p><h4>本方补给源与枢纽</h4><p>${s.sources.map((x:any)=>`${esc(x.id)} · ${esc(x.node)} · 每结算上限${x.cap/4}SP`).join('；')}</p><p>${s.hubs.map((x:any)=>`${esc(x.id)} · ${esc(x.node)} · 库存${Number(x.stock??0)/4}SP / 容量${x.cap/4}SP / 吞吐${x.W/4}SP`).join('；')}</p><h4>最近实收与维护</h4><table><tr><th>单位</th><th>实收SP</th><th>维护/应付SP</th><th>缺供损失</th></tr>${(s.ledger[0]?.units??[]).map((u:any)=>`<tr><td>${esc(u.id)}</td><td>${u.received/4}</td><td>${u.maintenance/4}/${u.due/4}</td><td>${esc(u.loss)}</td></tr>`).join('')}</table><p>这里只显示结算结果；缺供不表示已定位隐藏敌军。</p></details><small>后备人员为原场景已训练池，不是新训练；模式创建后固定。任意T1工业初始化尚未定义。</small></section>`;}
export function bindLogistics(p:LogisticsPort){document.querySelector('#freight-default')?.addEventListener('click',()=>void p.previewFreight(true));document.querySelector('#freight-preview')?.addEventListener('click',()=>void p.previewFreight());document.querySelector('#freight-confirm')?.addEventListener('click',()=>void p.confirmFreight());document.querySelectorAll<HTMLInputElement>('[data-freight-unit]').forEach(e=>e.addEventListener('change',()=>p.setChoice(e.dataset.freightUnit!,e.dataset.freightKind as 'reductions'|'priorities',Number(e.value))));document.querySelectorAll<HTMLElement>('[data-logistics-op]').forEach(b=>b.addEventListener('click',()=>void p.operate(b.dataset.logisticsOp!)));document.querySelector('#logistics-read')?.addEventListener('click',()=>void p.recover());document.querySelector('#logistics-retry')?.addEventListener('click',()=>void p.recover());document.querySelector('#logistics-repost')?.addEventListener('click',()=>void p.retry());document.querySelector('#logistics-ai')?.addEventListener('click',()=>void p.aiStep());}

function freightMarkup(p:LogisticsPort):string{
 const d=p.data,f=d.freightPlanning;if(!f)return '';const plan=p.plan,base=p.baselinePlan?.version===d.version?p.baselinePlan:null;
 const status:Record<string,string>={FEASIBLE:'可运输1套',NO_CAPACITY:'当前选择下无解，可运输0套',SERVICE_INVALID:'服务资格不符',UNRESOLVED:'预算内未解，不能判断无解',EXECUTION_BLOCKED:'本版本执行受阻'};
 const changes=plan?.comparison?.filter((x:any)=>x.reference.received!==x.alternative.received||x.reference.maintenance!==x.alternative.maintenance||x.reference.after!==x.alternative.after)??[];
 const sp=(n:number)=>n/4;
 return `<section class="freight-planner"><strong>动态运输 · 先预览后确认</strong><p>保持现有维护：${base?esc(status[base.status]):'尚未预览'}。默认不削减任何单位的维护。仅E8窗口确认，其他阶段可继续普通行动。</p>
 <div class="button-row"><button id="freight-default" ${p.locked||!f.enabled?'disabled':''}>预览保持维护（重置选择）</button><button id="freight-preview" ${p.locked||!f.enabled?'disabled':''}>按我的选择重新规划</button></div>
 <details><summary>选择可减维护上限与配送优先级（四分之一SP）</summary><p>只允许所选单位减维护，数值是上限，实际代价见预览。已有库存先用于维护；配送优先级1低、3高，不覆盖维护底线。</p><table><tr><th>本方单位</th><th>最多少维护q</th><th>配送优先级</th></tr>${d.supply.units.filter((u:any)=>u.strength>0).map((u:any)=>`<tr><td>${esc(u.id)}</td><td><select aria-label="${esc(u.id)}最多少维护q" data-freight-unit="${esc(u.id)}" data-freight-kind="reductions" ${p.locked||!f.enabled?'disabled':''}>${Array.from({length:u.B+1},(_,n)=>`<option value="${n}" ${(p.choices.reductions[u.id]??0)===n?'selected':''}>${n}q (${n/4}SP)</option>`).join('')}</select></td><td><select aria-label="${esc(u.id)}配送优先级" data-freight-unit="${esc(u.id)}" data-freight-kind="priorities" ${p.locked||!f.enabled?'disabled':''}>${[1,2,3].map(n=>`<option value="${n}" ${(p.choices.priorities[u.id]??u.priority??1)===n?'selected':''}>${n}</option>`).join('')}</select></td></tr>`).join('')}</table></details>
 ${plan?`<p role="status"><b>${esc(status[plan.status])}</b>；${esc(plan.reason??'')} ${esc(plan.note)} 计算${plan.seconds.toFixed(2)}秒。</p><p>实际可送：${plan.kit?'1P＋2E2':'0套'}；路线 A10→B10→C10；${plan.kit?'E8到达，T9可用，E9到期':'未生成可确认运输'}。</p>
 ${changes.length?`<p>以下与保持维护比较；少收到为负数表示多收到。欠账增加会影响后续缺供风险，本次未掉步不代表没有代价。</p><table><tr><th>单位</th><th>少收到SP</th><th>少维护SP</th><th>库存SP 对照→方案</th><th>欠账D</th><th>攻击系数</th><th>掉步/积累</th></tr>${changes.map((x:any)=>`<tr><td>${esc(x.id)}</td><td>${sp(x.reference.received-x.alternative.received)}</td><td>${sp(x.reference.maintenance-x.alternative.maintenance)}</td><td>${sp(x.reference.after)}→${sp(x.alternative.after)}</td><td>${esc(x.reference.debt)}→${esc(x.alternative.debt)}</td><td>${x.referenceCombat.factor}→${x.alternativeCombat.factor}</td><td>${x.reference.loss}/${esc(x.reference.attrition)}→${x.alternative.loss}/${esc(x.alternative.attrition)}</td></tr>`).join('')}</table>`:''}
 <details><summary>共享运力与完整单位账目</summary><p>这里只是预览，不占用运力。材料列为需求，负余量表示缺口；各约束独立计量。</p><table><tr><th>约束</th><th>原容量q</th><th>SP占用q</th><th>材料q</th><th>余量q</th></tr>${(plan.capacity??[]).filter((x:any)=>x.cargo>0).map((x:any)=>`<tr><td>${esc(x.id)}</td><td>${x.originalCap}</td><td>${x.spUsed}</td><td>${x.cargo}</td><td>${x.remaining}</td></tr>`).join('')}</table><p>枢纽库存SP（保持维护→本方案）：${(plan.hubs??[]).map((h:any)=>`${esc(h.id)} ${h.reference/4}→${h.alternative/4}`).join('；')}</p><pre>${esc(JSON.stringify(plan.comparison??[],null,2))}</pre></details>
 <button id="freight-confirm" ${p.locked||plan.status!=='FEASIBLE'||plan.version!==d.version?'disabled':''}>确认上述代价并结束E8，执行运输</button>`:''}
 ${f.applied?`<p>动态运输已提交；地图、补给和材料账本来自同一版本。</p><details><summary>已确认选择与实际结果</summary><pre>${esc(JSON.stringify(f.applied,null,2))}</pre></details>`:''}
 </section>`;
}
