// UI006 receipt-first, monotone read recovery adapted to the main game's DTO transport.
import type{WorkerPort}from'../local-ai/client.js';import type{LocalRequest,LocalReply}from'../local-ai/types.js';
const KEY='playable002.pending.v1',FLOOR='playable002.floor.v1';
export class LogisticsPort implements WorkerPort{
 onmessage:WorkerPort['onmessage']=null;onerror:WorkerPort['onerror']=null;data:any=null;notice='';locked=false;
 private token='';private epoch=1;private dead=false;private pending:any=null;private floor:any=null;
 constructor(private update:()=>void){}
 private async api(path:string,body?:unknown){const c=new AbortController(),timer=setTimeout(()=>c.abort(),10000);try{const r=await fetch(path,{method:body===undefined?'GET':'POST',cache:'no-store',headers:{'X-Local-Session':this.token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?null:JSON.stringify(body),signal:c.signal});const d=await r.json();if(!r.ok)throw Error(d.error??'读取失败');return d;}finally{clearTimeout(timer);}}
 private emit(message:any){if(!this.dead)this.onmessage?.({data:{epoch:this.epoch,message,meta:this.data.game.meta}} as MessageEvent<LocalReply>);}
 private keep(p:any){this.pending=p;this.locked=!!p;if(p)sessionStorage.setItem(KEY,JSON.stringify(p));else sessionStorage.removeItem(KEY);this.update();}
 private read(d:any){const instance=this.pending?.instanceId??this.floor?.instanceId??this.data?.instanceId;const floor=Math.max(this.floor?.version??0,this.data?.version??0,this.pending?.confirmation?.minVersion??0);if(instance&&instance!==d.instanceId)throw Error('实例不符：未解除原请求锁定');if(!Number.isSafeInteger(d.version)||d.version<floor||d.game.message.payload.matchRevision!==d.version)throw Error('旧账本或地图版本不一致');this.floor={instanceId:d.instanceId,version:d.version};sessionStorage.setItem(FLOOR,JSON.stringify(this.floor));this.data=d;this.emit(d.game.message);this.update();}
 async refresh(message?:string){try{this.read(await this.api('/api/state'));if(this.pending?.confirmation)this.keep(null);this.notice=message??'同一次提交的地图、库存及工业账本已读取。';this.update();return true;}catch(e){this.locked=true;this.notice='账本待刷新；操作保持锁定。'+String(e);this.update();return false;}}
 private confirmedGame(r:any){if(!r.ok)return;if(!Number.isSafeInteger(r.version)||r.version<=this.data.version)throw Error('动作确认版本无效');this.floor={instanceId:this.data.instanceId,version:r.version};sessionStorage.setItem(FLOOR,JSON.stringify(this.floor));}
 private async reconcile(r:any){const p=this.pending;if(!p)return true;if(['requestId','instanceId','operation','expectedVersion'].some(k=>r[k]!==p[k]))throw Error('回执标识不符');if(!['COMMITTED','REJECTED'].includes(r.status))return false;const minVersion=Math.max(p.expectedVersion,r.resultVersion??0);if(r.status==='COMMITTED'&&minVersion<=p.expectedVersion)throw Error('确认版本无效');this.keep({...p,confirmation:{status:r.status,minVersion}});this.notice=r.status==='COMMITTED'?'已确认提交；同一版本地图与账本已读取。':'已拒绝：'+r.code;await this.refresh(this.notice);return true;}
 async recover(){if(this.pending?.confirmation||!this.pending){const ok=await this.refresh();if(ok&&!this.pending)this.locked=false;this.update();return;}try{await this.reconcile(await this.api('/api/requests/'+this.pending.requestId));}catch(e){this.notice='结果待确认，保留原请求。'+String(e);}this.update();}
 async operate(operation:string){if(this.locked||this.dead||!this.data?.operations[operation]?.enabled)return;this.keep({requestId:crypto.randomUUID(),instanceId:this.data.instanceId,expectedVersion:this.data.version,operation});await this.retry();}
 async retry(){if(!this.pending)return;if(this.pending.confirmation){await this.refresh();return;}this.locked=true;const {requestId,instanceId,expectedVersion,operation}=this.pending;try{let r=await this.api('/api/operations',{requestId,instanceId,expectedVersion,operation});for(let i=0;i<10;i++){if(await this.reconcile(r))break;await new Promise(r=>setTimeout(r,400));r=await this.api('/api/requests/'+requestId);}}catch(e){this.notice='结果待确认，未自动换ID重试。'+String(e);}this.update();}
 async aiStep(){if(this.locked)return;this.locked=true;this.update();try{const r=await this.api('/play/ai',{});this.confirmedGame(r);this.notice=r.ok?'AI已执行一个真实作战动作。':'AI停步：'+r.error;this.locked=!(await this.refresh(this.notice));}catch(e){this.notice=String(e);}this.update();}
 postMessage(m:LocalRequest){void this.handle(m);}
 private async handle(m:LocalRequest){try{
  this.epoch=m.epoch;
  if(m.kind==='START'){
   this.pending=JSON.parse(sessionStorage.getItem(KEY)||'null');this.floor=JSON.parse(sessionStorage.getItem(FLOOR)||'null');this.locked=!!this.pending;
   this.token=(await this.api('/play/connect')).token;
   const d=await this.api('/play/create',{mode:'industry018',side:'GERMAN'});
   if(!this.pending&&this.floor?.instanceId!==d.instanceId){this.floor=null;sessionStorage.removeItem(FLOOR);}
   this.read(d);if(this.pending)await this.recover();return;
  }
  if(m.kind==='TAKEOVER')return;
  if(m.kind==='REQUEST'){
   const p=m.payload as any;
   if(m.type==='RESYNC_MATCH'){await this.refresh();return;}
   if(m.type==='QUERY_MATCH'){const q=await this.api('/play/query',{id:m.requestId,version:p.expectedRevision,draft:p.draft});this.emit(q);return;}
   if(this.locked){await this.refresh();return;}
   if(['READY_FOR_PHASE_END','END_PHASE'].includes(p.action.type)){await this.operate('NEXT');return;}
   this.locked=true;this.update();const r=await this.api('/play/action',{id:m.requestId,version:p.expectedRevision,action:p.action});this.confirmedGame(r);this.notice=r.ok?'原Core行动已提交。':'行动未提交：'+r.error;this.locked=!(await this.refresh(this.notice));this.update();
  }
 }catch(e){this.notice='连接或读取失败，保持锁定：'+String(e);this.locked=true;this.update();}}
 terminate(){this.dead=true;}
}
const esc=(x:unknown)=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function logisticsMarkup(p:LogisticsPort):string{const d=p.data;if(!d)return '<p>正在连接本机事务服务。</p>';const i=d.extensions.industry018,s=d.supply,target=s.units.find((u:any)=>u.id==='G-I-01');
 return `<section class="panel-block logistics-panel"><strong>新补给＋工业 · T${d.turn}</strong><p>${esc(d.playableScope)}</p><p role="status">${esc(p.notice)}</p><div class="button-row"><button id="logistics-read">恢复读取</button><button id="logistics-retry" ${p.locked?'':'hidden'}>核对原请求</button><button id="logistics-repost" ${p.locked?'':'hidden'}>仅重试原请求</button></div><p>装备I：${d.equipmentBudget.freeI}；生产已付${d.equipmentBudget.productionSpent}；交接已付${d.equipmentBudget.handoffSpent}；托管${d.equipmentBudget.escrow}。人员I：${d.personnelBudget.availableI}。</p><p>生产 ${i.production.workCompleted}/${i.production.workRequired}；前线可用P ${d.availableFrontInventory.P} / E2 ${d.availableFrontInventory['E2:L']}；G-I-01步损 ${d.target.step}。</p><p>${(d.blockers??[]).map(esc).join("；")}</p><div class="logistics-ops">${Object.entries(d.operations).sort(([a,x]:[string,any],[b,y]:[string,any])=>Number(y.enabled)-Number(x.enabled)||['ALLOCATE_I','PLACE_ORDER','ACTIVATE_PERSONNEL','APPLY_PERSONNEL','CARE','RECOVER','NEXT'].indexOf(a)-['ALLOCATE_I','PLACE_ORDER','ACTIVATE_PERSONNEL','APPLY_PERSONNEL','CARE','RECOVER','NEXT'].indexOf(b)).map(([op,v]:[string,any])=>`<button data-logistics-op="${op}" ${p.locked||!v.enabled?'disabled':''}>${esc(v.label)}</button>`).join('')}</div><button id="logistics-ai" ${p.locked||d.game.meta.ownerSide!=='SOVIET'||(!['SOVIET_MOVEMENT','SOVIET_COMBAT'].includes(d.phase)&&!d.game.message.payload.view.pendingDecision)?'disabled':''}>让AI执行一个苏军作战动作</button><details><summary>已结算补给与运力</summary><p>当前库存：${target?target.stock/4:'—'}SP；维护份额${target?target.B/4:'—'}SP；欠账D ${esc(target?.debt)}。修路不会立即补仓。</p><table><thead><tr><th>单位</th><th>库存SP</th><th>目标SP</th><th>欠账D</th></tr></thead><tbody>${s.units.map((u:any)=>`<tr><td>${esc(u.id)}</td><td>${u.stock/4}</td><td>${u.target/4}</td><td>${esc(u.debt)}</td></tr>`).join('')}</tbody></table><h4>已结算运输</h4><table><tr><th>通路/能力</th><th>总量</th><th>SP占用</th><th>货运</th><th>余量</th></tr>${(d.transport??[]).map((x:any)=>`<tr><td>${esc(x.id)}</td><td>${x.originalCap}</td><td>${x.spUsed}</td><td>${x.cargo}</td><td>${x.remaining}</td></tr>`).join('')}</table><p>容量保留原规则整数刻度，SP和工业货物共同占用；照管：${esc(d.care?.status??'尚未支付')}，到期E${esc(d.care?.endEpoch)}。</p><h4>本方补给源与枢纽</h4><p>${s.sources.map((x:any)=>`${esc(x.id)} · ${esc(x.node)} · 每结算上限${x.cap/4}SP`).join('；')}</p><p>${s.hubs.map((x:any)=>`${esc(x.id)} · ${esc(x.node)} · 库存${Number(x.stock??0)/4}SP / 容量${x.cap/4}SP / 吞吐${x.W/4}SP`).join('；')}</p><h4>最近实收与维护</h4><table><tr><th>单位</th><th>实收SP</th><th>维护/应付SP</th><th>缺供损失</th></tr>${(s.ledger[0]?.units??[]).map((u:any)=>`<tr><td>${esc(u.id)}</td><td>${u.received/4}</td><td>${u.maintenance/4}/${u.due/4}</td><td>${esc(u.loss)}</td></tr>`).join('')}</table><p>这里只显示结算结果；缺供不表示已定位隐藏敌军。</p></details><small>后备人员为原场景已训练池，不是新训练；模式创建后固定。任意T1工业初始化尚未定义。</small></section>`;}
export function bindLogistics(p:LogisticsPort){document.querySelectorAll<HTMLElement>('[data-logistics-op]').forEach(b=>b.addEventListener('click',()=>void p.operate(b.dataset.logisticsOp!)));document.querySelector('#logistics-read')?.addEventListener('click',()=>void p.recover());document.querySelector('#logistics-retry')?.addEventListener('click',()=>void p.recover());document.querySelector('#logistics-repost')?.addEventListener('click',()=>void p.retry());document.querySelector('#logistics-ai')?.addEventListener('click',()=>void p.aiStep());}
