import type {GrandPort} from './grand.js';
import {escStatus as esc,numberStatus as num} from './unitStatus.js';
const names:Record<string,string>={TRAIN:'缺火车',TRUCK:'缺卡车',RAIL:'铁路拥堵',SOURCE:'来源满载',HUB:'枢纽满载',COVERAGE:'覆盖不到',DISCONNECTED:'线路中断',NO_ROUTE:'补充通路未接通',MANPOWER:'人力耗尽',STOCK:'缺库存'};
const objectName=(m:any,id:string)=>m.network.hubs.find((h:any)=>h.id===id)?.label??m.products[id]?.label??id;
const routeObjects=(m:any,r:any)=>r.objects.map((x:any)=>typeof x==='string'?m.logisticsObjects[x]:x);
const types:Record<string,string>={TRAIN:'火车工作量',SOURCE:'后方来源',HUB:'枢纽',RAIL:'铁路'};
export function unitLogistics(p:GrandPort,id:string){const m=p.data.modern,x=m.explanations?.[id];if(!x)return '';return `<details open><summary>具体瓶颈与补充通路</summary><p>最近5分钟实补 ${num(x.personnelSent)} 人；上次补充速率上限 ${num(x.rate)} 人/日（仍受库存和运输限制）。</p><p>${[...new Set(x.causes.map((r:any)=>r.type==='RAIL'?'铁路拥堵（'+x.causes.filter((b:any)=>b.type==='RAIL').length+'段，展开路线定位）':`${names[r.type]??r.type}：${esc(objectName(m,r.id))}`))].join('；')||'当前未发现硬性瓶颈'}</p>${x.deficits.map((d:any)=>`<p>${esc(m.products[d.product].label)}：缺${num(d.missing)}／国库${num(d.stock)}／最近5分钟到货${num(d.sent)}</p>`).join('')}<button data-modern-tab="production">查看装备与车辆生产</button><button data-modern-tab="construction">建设／维修</button>${x.routes.map((r:any)=>`<details><summary>${esc(objectName(m,r.source))} → ${esc(objectName(m,r.hub))} · 补充余量 ${num(r.available)}</summary><small>以下为同一共享能力，不能把不同路线的余量相加。</small>${routeObjects(m,r).map((o:any)=>`<p>${types[o.type]??o.type} ${esc(objectName(m,o.id))}：容量${num(o.capacity)}／占用${num(o.used)}／剩余${num(o.remaining)}${o.type==='RAIL'?`<button data-ux-focus="${esc(o.id.split('|')[0])}">定位铁路</button><button data-modern-build="RAIL" data-target="${esc(o.id)}">排队升级</button>`:o.type==='HUB'?`<button data-modern-hub-view="${esc(o.id)}">查看枢纽／机动化</button>`:''}</p>`).join('')}</details>`).join('')||'<p>没有当前可达后方通路；孤立地区只有有限当地供给与携行储备。</p>'}</details>`;}
export function constructionPlanner(p:GrandPort){if(!p.data.modern.planning)return '';const x=p.constructionPreview,kind=p.selections['build-kind']??'NEW_RAIL',stale=x&&x.version!==p.data.version,rate=p.data.modern.facilities.filter((f:any)=>f.kind==='CIV').reduce((n:number,f:any)=>n+6*(1-f.damage),0);return `<section class="panel-block"><h3>新线路与枢纽</h3><label>工程<select id="logistics-kind"><option value="NEW_RAIL" ${kind==='NEW_RAIL'?'selected':''}>新建铁路</option><option value="NEW_HUB" ${kind==='NEW_HUB'?'selected':''}>新建补给枢纽</option></select></label><p>先暂停世界，在地图选点；只读预览不下达部队行动。</p>${kind==='NEW_RAIL'?`<button data-logistics-pick="start">地图选接入点</button> ${esc(p.selections['build-start']??'未选')}`:''}<button data-logistics-pick="end">地图选终点</button> ${esc(p.selections['build-end']??'未选')}<div class="button-row"><button id="logistics-preview" ${p.selections['build-end']?'':'disabled'}>重新计算预览</button><button id="logistics-cancel">取消选点／预览</button></div>${x?`<p role="status">${stale?'状态已变化，请重新预览。':esc(x.reason)}</p><p>${x.path.map(esc).join(' → ')}</p><p>新建${x.segments.length}段 · ${num(x.cost)}民用工时；当前民厂独占施工约${rate?num(x.cost/rate)+'日':'无法施工'}。实际排队与失守另计。</p><button id="logistics-confirm" ${!x.valid||stale||p.locked?'disabled':''}>确认加入建设队列</button>`:''}<small>铁路最多24段；湖泊、山地、无桥河流不可新建。枢纽24工时，限平原／城镇／森林且邻接道路或铁路。全线受控才施工；孤立枢纽不会产生后方物资。建设不保证解除其他瓶颈。</small></section>`;}
export function bindPlanning(p:GrandPort,refresh:()=>void){if(!p.data.modern?.planning)return;document.getElementById('logistics-kind')?.addEventListener('change',e=>{p.selections['build-kind']=(e.target as HTMLSelectElement).value;p.constructionPreview=null;refresh();});document.getElementById('logistics-preview')?.addEventListener('click',()=>p.previewConstruction());document.getElementById('logistics-cancel')?.addEventListener('click',()=>{delete p.selections['build-pick'];p.constructionPreview=null;refresh();});document.getElementById('logistics-confirm')?.addEventListener('click',()=>{const x=p.constructionPreview;if(x?.valid)void p.operation({type:'ECON_BUILD',kind:x.kind,start:x.start,end:x.end,path:x.path,planVersion:x.version});});}

export function corpsLogistics(p:GrandPort,ids:string[]){if(!p.data.modern?.planning)return '';const m=p.data.modern,rows=ids.filter(id=>m.network.rows[id]),sum=(field:string)=>rows.reduce((n,id)=>n+m.network.rows[id][field],0);return `<details open><summary>本军团后勤 · 需求${num(sum('need'))}／收到${num(sum('received'))}</summary>${rows.map(id=>`<p><button data-ui-unit="${id}">${id}</button> 缺员${Math.ceil(m.explanations[id].missingPersonnel)} · ${esc(m.network.rows[id].reason)}${m.explanations[id].causes.some((x:any)=>x.type==='STOCK')?' · 装备库存不足':''}</p>`).join('')}<button data-modern-tab="supply">查看枢纽／建设</button></details>`;}
