import {paintIndustry,clearIndustry,logisticsDetail,queueCards} from './industryArt.js';
import {industryEnabled,equipmentIcon} from './industryModel.js';
import {unitLogistics,constructionPlanner,bindPlanning} from './logisticsPlanning.js';
import type {GrandPort} from './grand.js';
import {escStatus as esc,numberStatus as num} from './unitStatus.js';
import {hexToPixel,hexPolygon,pointString} from '../geometry/hex.js';
const resources:Record<string,string>={steel:'钢',tungsten:'钨',chromium:'铬',rubber:'橡胶'},kinds:Record<string,string>={MIL:'军用工厂',CIV:'民用工厂',RAIL:'铁路升级',REPAIR_RAIL:'铁路／桥梁维修',HUB:'枢纽升级',REPAIR_FACTORY:'厂房维修',NEW_RAIL:'新铁路',NEW_HUB:'新枢纽'};
export function modernUnit(p:GrandPort,id:string){const m=p.data.modern,c=p.data.continuous,v=c.units[id],r=m.network.rows[id],g=p.data.ux.equipment.find((g:any)=>g.id===id);if(!v||!r)return '';
 return `<section class="panel-block"><h3>补给与补充</h3><small>网络分配更新于${Math.max(0,c.minutes-(m.network.tick??0)*5)}游戏分钟前；补充按5分钟结算。</small><p>日常需求 ${num(r.need)} · 获得 ${num(r.received)}（当地 ${num(r.local)}）<br>${esc(r.reason)}；携行储备约 ${num(v.dailySupply?.carriedHours??12)}小时</p><p>缺员 ${Math.ceil(v.max-v.personnel)}；可用人力 ${Math.floor(m.manpower)}。${v.engaged?'交战中：补充速率25%。':v.march?'行军中：补充速率50%。':'驻留：按通达率补充。'}人员与装备分别补充。</p><p>${g?Object.entries(g.required).filter(([k,n]:any)=>g.held[k]<n-.001).map(([k,n]:any)=>`${esc(m.products[k].label)} 缺${num(n-g.held[k])}，国家库存${num(m.stock[k])}${m.demands?.[k]?.committed?`（运输占用${num(m.demands[k].committed)}，可补装${num(m.demands[k].free)}）`:``}`).join('；')||'装备齐备':''}</p><p>${esc(v.refillStatus?.reason??'待下一模拟步评估补充通道')}；日常供给优先，补充共享来源、铁路、枢纽与车辆剩余能力。</p>${unitLogistics(p,id)}<button data-ui-panel="economy">调整生产与补充优先级</button><button data-modern-tab="supply">查看补给网络</button></section>`;
}
export function modernPanel(p:GrandPort){const m=p.data.modern,tab=p.selections['modern-tab']??'production',disabled=p.locked?'disabled':'',total=(k:string)=>p.data.ux.equipment.reduce((n:number,g:any)=>n+Math.max(0,(g.required[k]??0)-(g.held[k]??0)),0),net=m.network;
 const vehicles=m.demands?`<details><summary>车辆需求与占用</summary>${['TRAIN','TRUCK'].map(k=>{const d=m.demands[k];return `<p>${esc(m.products[k].label)}：运输需求 ${num(d.transport)} ＋ 部队补装 ${num(d.formation)} ＝ 总需求 ${num(d.gross)}<br>国家库存 ${num(d.stock)}（运输占用 ${num(d.committed)}，空闲车辆 ${num(d.free)}）；净缺额 ${num(d.net)}</p>`;}).join('')}<small>显示数值独立取整，计算使用原值。净缺额仅扣一次国家库存。已占用车辆可重复运输，但不能同时补入部队；运输未满足的需求与部队补装共同计入生产需求。补装仍只使用运输余量。</small></details>`:'';
 const lineName=(l:any)=>'生产线 '+(m.lines.findIndex((x:any)=>x.id===l.id)+1);
 const lineCard=(l:any)=>`<details class="ux-line"><summary><b>${equipmentIcon(l.product)} ${esc(m.products[l.product].label)} · ${lineName(l)}</b><span>${l.factories.length}厂 · 效率${Math.round(l.efficiency*100)}%</span><span>${num(l.workDay/m.products[l.product].cost)}/日</span>${l.missing.length?'<em>缺原料</em>':l.factories.length?'':'<em>未分配工厂</em>'}</summary><div data-modern-line="${l.id}"><label>产品<select data-modern-product>${Object.entries(m.products).map(([k,v]:any)=>`<option value="${k}" ${k===l.product?'selected':''}>${esc(v.label)} · ${v.cost}工业工时</option>`).join('')}</select></label><p>${esc(m.products[l.product].use)}；在制${num(l.progress)}/${m.products[l.product].cost}，累计${l.completed}。${l.missing.map((x:any)=>'缺'+resources[x.resource]+' '+num(x.need-x.got)).join('；')||'资源充足'}</p><label>优先级<select data-modern-priority>${[1,2,3,4,5,6,7,8,9].map(n=>`<option ${n===l.priority?'selected':''}>${n}</option>`).join('')}</select></label>${m.facilities.filter((f:any)=>f.kind==='MIL').map((f:any)=>`<label><input data-modern-factory="${esc(f.id)}" type="checkbox" ${l.factories.includes(f.id)?'checked':''}>${f.hex} 厂房 ${f.id.split(':').at(-1)}${f.damage?' · 损坏'+Math.round(f.damage*100)+'%':''}</label>`).join('')}<button data-modern-apply="${l.id}" ${disabled}>应用生产分配</button><small>可从其他线调入工厂；新厂10%效率加权。跨品类保留40%效率，放弃该线未完工进度；成品保留。</small></div></details>`;
 let body='';
 if(tab==='production')body=`<p>军厂 ${m.facilities.filter((f:any)=>f.kind==='MIL').length} · 民厂 ${m.facilities.filter((f:any)=>f.kind==='CIV').length}；可用人力 ${Math.floor(m.manpower)}。</p><p>${Object.entries(m.resources).map(([k,v]:any)=>`${resources[k]} ${num(v)}（占用${num(m.resourceUsed[k]??0)}）`).join(' · ')}</p>${m.lines.filter((l:any)=>l.factories.length).map(lineCard).join('')}<details class="inactive-lines"><summary>未启用／添加生产线（${m.lines.filter((l:any)=>!l.factories.length).length}）</summary>${m.lines.filter((l:any)=>!l.factories.length).map(lineCard).join('')}</details>${vehicles}<h3>国家库存（每类仅计一次）／部队缺额</h3>${Object.entries(m.products).map(([k,v]:any)=>`<p>${esc(v.label)}：库存 ${num(m.stock[k])} · 缺额 ${num(total(k))}</p>`).join('')}<small>库存不含部队持有；车辆池包含仍在国家名下的已指派车辆，补装不能动用已指派份额。资源为各受控工区固定开采能力，无贸易或燃油系统。</small>`;
 if(tab==='supply')body=(industryEnabled(p)?logisticsDetail(p):'')+`<p>火车 ${num(m.stock.TRAIN)}/${num(m.demands?.TRAIN.transport??net.trainNeed)}；卡车 ${num(m.stock.TRUCK)}/${num(m.demands?.TRUCK.transport??net.truckNeed)}（国家库存／运输需求）。</p>${vehicles}<button id="modern-overlay">${p.selections['modern-overlay']?'关闭':'显示'}补给地图</button><p>青色为所选枢纽真实覆盖；红线断线／损坏，橙线满载。点击定位不下达行动。</p>${net.hubs.map((h:any)=>`<details><summary>${esc(h.label)} · ${h.route?'接通':'未接通'} · ${num(h.used)}/${num(h.capacity)}</summary><button data-modern-hub-view="${h.id}">覆盖与线路</button><button data-ux-focus="${h.hex}">定位</button><label>末端配送<select data-modern-motor="${h.id}" ${disabled}><option value="0" ${!h.motor?'selected':''}>畜力／基础近距</option><option value="1" ${h.motor?'selected':''}>机动化 · 需要2卡车</option></select></label><p>已配卡车${num(h.trucks)}/${h.truckNeed}；可达${h.coverage.length}格。${h.route?'瓶颈流量'+num(h.route.cap):'没有当前受控、完整铁路连接后方'}</p><button data-modern-build="HUB" data-target="${h.id}" ${disabled}>升级枢纽 · 18民用工时</button></details>`).join('')}<h3>部队日常供给</h3>${Object.entries(net.rows).map(([id,r]:any)=>`<p><button data-ui-unit="${id}">${id}</button> ${Math.round(r.ratio*100)}% · ${esc(r.reason)}</p>`).join('')}<h3>补充优先级</h3>${Object.entries(m.priorities).map(([a,n])=>`<label>${esc(a)}<select data-modern-army="${esc(a)}">${[1,2,3,4,5].map(v=>`<option ${v===n?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}`;
 if(tab==='construction')body=constructionPlanner(p)+`<p>民厂 ${m.facilities.filter((f:any)=>f.kind==='CIV').length} 座，完好厂各6工时/日。队列依优先级施工；易手停工，不重复生成资产。</p>${queueCards(m)}<details open><summary>建厂／厂房维修</summary>${m.sites.map((d:any)=>`<p>${esc(d.label)} · ${d.used}/${d.slots}厂位 <button data-ux-focus="${d.hex}">定位</button>${d.used<d.slots?`<button data-modern-build="MIL" data-target="${d.id}">军厂30工时</button><button data-modern-build="CIV" data-target="${d.id}">民厂36工时</button>`:''}</p>`).join('')}${m.facilities.filter((f:any)=>f.damage).map((f:any)=>`<button data-modern-build="REPAIR_FACTORY" data-target="${f.id}">维修${f.hex}厂房 · 10工时</button>`).join('')}</details><details><summary>铁路维修／升级 · ${m.rails.filter((r:any)=>r.damage).length}段损坏</summary>${m.rails.slice().sort((a:any,b:any)=>b.damage-a.damage).map((r:any)=>`<p>${r.a}→${r.b} · 等级${r.level}${r.damage?' · 断线待修':''}<button data-ux-focus="${r.a}">定位</button><button ${!r.damage&&r.level>=5?'disabled':''} data-modern-build="${r.damage?'REPAIR_RAIL':'RAIL'}" data-target="${r.id}">${r.damage?'维修6':'升级10'}工时</button></p>`).join('')}</details>`;
 return `<section class="panel-block"><div class="button-row">${[['production','生产与库存'],['supply','补给网络'],['construction','建设队列']].map(([k,n])=>`<button data-modern-tab="${k}" aria-pressed="${tab===k}">${n}</button>`).join('')}</div>${body}<details><summary>补给与生产说明</summary><p>日期与时间统一推进；工厂效率每日积累8个百分点，上限80%。人员最高60人/队/日、装备2单位/类/队/日，受真实后方通达和战斗状态限制，人员与装备独立到达。装备沿用原编制折算单位，不是现实单支枪。</p><p>七日有限陆战；无海空、贸易、燃料、科技与征兵法。资源来自己方控制的工区。</p></details></section>`;
}
export function bindModern(p:GrandPort,refresh:()=>void){if(!p.data.modern)return;bindPlanning(p,refresh);document.getElementById('industry-art-toggle')?.addEventListener('change',e=>{p.selections['industry-art']=(e.target as HTMLInputElement).checked?'on':'off';refresh();});const op=(o:any)=>void p.operation(o);
 document.querySelectorAll<HTMLElement>('[data-modern-tab]').forEach(el=>el.onclick=()=>{p.selections['modern-tab']=el.dataset.modernTab!;p.selections['ui-panel']='economy';refresh();});
 document.querySelectorAll<HTMLElement>('[data-modern-apply]').forEach(el=>el.onclick=()=>{const row=el.closest('[data-modern-line]')!;op({type:'ECON_LINE',line:el.dataset.modernApply,product:(row.querySelector('[data-modern-product]') as HTMLSelectElement).value,priority:Number((row.querySelector('[data-modern-priority]') as HTMLSelectElement).value),factories:Array.from(row.querySelectorAll<HTMLInputElement>('[data-modern-factory]:checked')).map(x=>x.dataset.modernFactory)});});
 document.querySelectorAll<HTMLElement>('[data-modern-build]').forEach(el=>el.onclick=()=>op({type:'ECON_BUILD',kind:el.dataset.modernBuild,target:el.dataset.target}));
 document.querySelectorAll<HTMLSelectElement>('[data-modern-motor]').forEach(el=>el.onchange=()=>op({type:'ECON_HUB',hub:el.dataset.modernMotor,motor:Number(el.value)}));
 document.querySelectorAll<HTMLSelectElement>('[data-modern-army]').forEach(el=>el.onchange=()=>op({type:'ECON_PRIORITY',army:el.dataset.modernArmy,priority:Number(el.value)}));
 document.querySelectorAll<HTMLSelectElement>('[data-modern-queue]').forEach(el=>el.onchange=()=>op({type:'ECON_QUEUE',id:el.dataset.modernQueue,priority:Number(el.value)}));
 document.querySelectorAll<HTMLElement>('[data-modern-hub-view]').forEach(el=>el.onclick=()=>{p.selections['ui-panel']='economy';p.selections['modern-tab']='supply';p.selections['modern-hub']=el.dataset.modernHubView!;p.selections['modern-overlay']='1';refresh();});
 document.getElementById('modern-overlay')?.addEventListener('click',()=>{p.selections['modern-overlay']=p.selections['modern-overlay']?'':'1';refresh();});
}
export function paintModern(p:GrandPort,refresh:()=>void,canInspect:()=>boolean){if(industryEnabled(p)){paintIndustry(p,refresh,canInspect);return;}clearIndustry();const svg=document.querySelector('#eastfront-map');if(!svg)return;let layer=svg.querySelector('#modern-supply-layer');const builtRails=new Set<string>((p.data.modern?.queue??[]).filter((q:any)=>q.kind==='NEW_RAIL'&&q.status==='DONE').flatMap((q:any)=>q.segments.map((s:any)=>s.id))),builtHubs=new Set<string>((p.data.modern?.queue??[]).filter((q:any)=>q.kind==='NEW_HUB'&&q.status==='DONE').map((q:any)=>'HUB:'+q.id));if(!p.data.modern||!p.selections['modern-overlay']&&!p.constructionPreview&&!builtRails.size&&!builtHubs.size){layer?.remove();return;}
 const ns='http://www.w3.org/2000/svg';if(!layer){layer=document.createElementNS(ns,'g');layer.id='modern-supply-layer';layer.setAttribute('pointer-events','none');svg.append(layer);}
 const px=p.data.modern.planning?Number(svg.getAttribute('viewBox')?.split(' ')[2]??1)/Math.max(1,svg.getBoundingClientRect().width):1;
 const m=p.data.modern,hub=m.network.hubs.find((h:any)=>h.id===p.selections['modern-hub']),coord=(s:string)=>{const[q,r]=s.split(',').map(Number);return{q:q!,r:r!};},parts=new Map<string,string>();
 const plan=p.constructionPreview;if(plan?.valid&&plan.version===p.data.version){for(let i=1;i<plan.path.length;i++){const a=hexToPixel(coord(plan.path[i-1])),b=hexToPixel(coord(plan.path[i]));parts.set('planned:'+i,`<path d="M${a.x} ${a.y}L${b.x} ${b.y}" stroke="#e5daae" stroke-width="${5*px}" stroke-dasharray="${8*px} ${6*px}" fill="none"/>`);}if(plan.kind==='NEW_HUB'){const a=hexToPixel(coord(plan.end));parts.set('planned:hub',`<circle cx="${a.x}" cy="${a.y}" r="${14*px}" fill="none" stroke="#e5daae" stroke-width="${3*px}" stroke-dasharray="${7*px} ${5*px}"/>`);}}
 for(const h of hub?.coverage??[])parts.set('area:'+h,`<polygon points="${hexPolygon(coord(h)).map(pointString).join(' ')}" fill="#459ba8" opacity=".25"/>`);
 for(const r of m.rails.filter((r:any)=>p.selections['modern-overlay']||builtRails.has(r.id))){const a=hexToPixel(coord(r.a)),b=hexToPixel(coord(r.b)),used=m.network.edges[r.id]??0,color=r.damage?'#ee705d':used>=12*r.level-.01?'#e3a556':'#74b5c7';parts.set('rail:'+r.id,`<path d="M${a.x} ${a.y}L${b.x} ${b.y}" fill="none" stroke="${color}" stroke-width="${(r.damage?5:3)*px}" ${r.damage?`stroke-dasharray="${8*px} ${4*px}"`:''}/>`);}
 for(const h of m.network.hubs.filter((h:any)=>p.selections['modern-overlay']||builtHubs.has(h.id))){const a=hexToPixel(coord(h.hex));parts.set('hub:'+h.id,`<rect x="${a.x-10*px}" y="${a.y-10*px}" width="${20*px}" height="${20*px}" fill="${h.route?'#65bec6':'#a3594d'}" stroke="#182329" stroke-width="${2*px}"/><path d="M${a.x-6*px} ${a.y+5*px}h${12*px}M${a.x-5*px} ${a.y}h${10*px}M${a.x-4*px} ${a.y-5*px}h${8*px}" stroke="#182329" stroke-width="${2*px}"/>`);}
 const keep=new Set(parts.keys());for(const child of Array.from(layer.children))if(!keep.has(child.getAttribute('data-key')!))child.remove();for(const[k,html]of parts){let el=Array.from(layer.children).find(el=>el.getAttribute('data-key')===k);if(!el){el=document.createElementNS(ns,'g');el.setAttribute('data-key',k);layer.append(el);}if(el.getAttribute('data-html')!==html){el.innerHTML=html;el.setAttribute('data-html',html);}}
}
