import type {GrandPort} from './grand.js';
import {equipmentIcon} from './industryModel.js';
import {escStatus as esc,numberStatus as num} from './unitStatus.js';

export function factoryPool(m:any){
 const military=m.facilities.filter((f:any)=>f.kind==='MIL'),assigned=new Set(m.lines.flatMap((l:any)=>l.factories));
 return {total:military.length,assigned:military.filter((f:any)=>assigned.has(f.id)).length,damaged:military.filter((f:any)=>f.damage>=1).length,free:military.filter((f:any)=>f.damage<1&&!assigned.has(f.id))};
}
export function factoryAdjustment(m:any,id:string,delta:number){
 const l=m.lines.find((l:any)=>l.id===id);if(!l)return null;
 const free=factoryPool(m).free.slice().sort((a:any,b:any)=>a.damage-b.damage||a.id.localeCompare(b.id));
 if(delta>0&&!free.length||delta<0&&!l.factories.length)return null;
 return {type:'ECON_LINE',line:id,product:l.product,priority:l.priority,factories:delta>0?[...l.factories,free[0].id]:l.factories.slice(0,-1)};
}
export function productionLines(p:GrandPort){
 const m=p.data.modern,pool=factoryPool(m),waiting=Array.from(p.wire?.pending.values()??[]).some((r:any)=>r.command?.payload?.type?.startsWith('ECON_'));
 const disabled=p.locked||waiting,chosen=p.selections['production-product'];
 const card=(l:any)=>{const product=m.products[l.product],candidate=p.selections['convert:'+l.id];return `<article class="production-line" data-line-key="${esc(l.id)}"><div class="production-line-controls"><header>${equipmentIcon(l.product)}<div><b>${esc(product.label.replace('（件）',''))}</b><small>第 ${m.lines.indexOf(l)+1} 生产线 · ${l.factories.length}座军厂</small></div><strong>${num(l.workDay/product.cost)}<small>${p.data.divisions?.integrated?'件':'单位'}／日</small></strong></header><div class="factory-allocation"><span>军厂</span><button data-factory-minus="${esc(l.id)}" aria-label="减少一座军厂" ${disabled||!l.factories.length?'disabled':''}>−</button><b>${l.factories.length}</b><button data-factory-plus="${esc(l.id)}" aria-label="增加一座空闲军厂" ${disabled||!pool.free.length?'disabled':''}>＋</button><span>效率 ${Math.round(l.efficiency*100)}%</span></div></div><div class="production-efficiency" aria-label="生产效率"><i style="width:${l.efficiency*100}%"></i></div><p class="line-shortage">${l.missing.length?l.missing.map((x:any)=>`缺${({steel:'钢',tungsten:'钨',chromium:'铬',rubber:'橡胶',aluminium:'铝'} as any)[x.resource]??esc(x.resource)} ${num(x.need-x.got)}`).join(' · '):!l.factories.length?'未启用 · 分配军厂即可生产':l.workDay>0?'持续生产 · 自动入库与补充':p.data.continuous.tick===0?'等待首个生产结算':'停产 · 检查厂房控制与损坏'}</p>${l.missing.length?'<button data-ui-panel="city">查看资源工区</button>':''}<button class="line-convert" data-convert-open="${esc(l.id)}">更换装备</button><details><summary>进度与优先级</summary><p>本件 ${num(l.progress)} / ${product.cost} 工时 · 累计完成 ${num(l.completed)}</p><p>${esc(product.use??'完整成品进入国家库存，自动配送给有需求部队。')}</p><label>资源优先级<select data-line-priority="${esc(l.id)}" ${disabled?'disabled':''}>${[1,2,3,4,5,6,7,8,9].map(n=>`<option ${n===l.priority?'selected':''}>${n}</option>`).join('')}</select></label><small>1优先。新调入军厂按10%效率加权；数量与库存为编制装备单位。</small></details>${candidate?`<div class="conversion-confirm" role="alert"><b>转产 ${esc(m.products[candidate].label)}</b><p>效率从 ${Math.round(l.efficiency*100)}% 降为 ${Math.round(Math.max(.1,l.efficiency*(m.config.switchRetention??.4))*100)}%；放弃 ${num(l.progress)} 未完工工时。已完成库存保留。</p><button data-convert-confirm="${esc(l.id)}" ${disabled?'disabled':''}>确认转产</button><button data-convert-cancel="${esc(l.id)}">取消</button></div>`:''}</article>`;};
 const picker=p.selections['production-picker'];
 return `<div id="production-workbench"><div class="factory-summary"><span>军厂 <b>${pool.total}</b></span><span>已分配 <b>${pool.assigned}</b></span><span>空闲 <b>${pool.free.length}</b></span></div>${pool.damaged?`<p>完全损坏 ${pool.damaged} 座 · <button data-modern-tab="construction">安排维修</button></p>`:''}${waiting?'<p role="status">分配待确认；地图与其他部队仍可操作。</p>':''}${m.lines.filter((l:any)=>l.factories.length||l.product===chosen||p.selections['convert:'+l.id]).map(card).join('')}<button id="production-add">＋ 选择装备／启用生产线</button>${picker?`<div class="equipment-picker"><h3>${picker==='add'?'选择装备':'更换生产装备'}</h3>${Object.entries(m.products).map(([k,v]:any)=>`<button data-equipment-choice="${k}">${equipmentIcon(k)}<b>${esc(v.label)}</b><small>${v.cost}工时／单位</small></button>`).join('')}<button id="production-picker-close">收起</button></div>`:''}<details class="stock-table" open><summary>国家库存与军队缺额</summary><table><thead><tr><th>装备</th><th>库存</th><th>部队缺额</th></tr></thead><tbody>${Object.entries(m.products).map(([k,v]:any)=>`<tr><th>${esc(v.label)}</th><td>${num(m.stock[k])}</td><td>${num(p.data.ux.equipment.reduce((n:number,g:any)=>n+Math.max(0,(g.required[k]??0)-(g.held[k]??0)),0))}</td></tr>`).join('')}</tbody></table><small>库存不含部队持有；火车和卡车的运输占用须在补给页查看，不可同时用于补装。</small></details></div>`;
}
export function bindProduction(p:GrandPort,refresh:()=>void){
 const each=(s:string,fn:(el:HTMLElement)=>void)=>document.querySelectorAll<HTMLElement>(s).forEach(el=>el.onclick=()=>fn(el));
 for(const [attr,delta]of [['factory-plus',1],['factory-minus',-1]] as const)each(`[data-${attr}]`,el=>{if(p.locked||Array.from(p.wire?.pending.values()??[]).some((r:any)=>r.command?.payload?.type?.startsWith('ECON_')))return;const op=factoryAdjustment(p.data.modern,el.getAttribute('data-'+attr)!,delta);if(op)void p.operation(op);});
 document.querySelectorAll<HTMLSelectElement>('[data-line-priority]').forEach(el=>el.onchange=()=>{const l=p.data.modern.lines.find((l:any)=>l.id===el.dataset.linePriority);void p.operation({type:'ECON_LINE',line:l.id,product:l.product,factories:l.factories,priority:Number(el.value)});});
 const add=document.getElementById('production-add');if(add)add.onclick=()=>{p.selections['production-picker']='add';refresh();};
 each('[data-convert-open]',el=>{p.selections['production-picker']=el.dataset.convertOpen!;refresh();});
 each('[data-equipment-choice]',el=>{const k=el.dataset.equipmentChoice!,picker=p.selections['production-picker'];if(picker==='add'){p.selections['production-product']=k;if(!p.data.modern.lines.some((l:any)=>l.product===k)){const spare=p.data.modern.lines.find((l:any)=>!l.factories.length);if(spare)p.selections['convert:'+spare.id]=k;else p.notice='没有空闲生产线；请在现有生产线上选择更换装备。';}}else if(picker)p.selections['convert:'+picker]=k;delete p.selections['production-picker'];refresh();});
 each('[data-convert-confirm]',el=>{const l=p.data.modern.lines.find((l:any)=>l.id===el.dataset.convertConfirm),product=p.selections['convert:'+l.id];if(product)void p.operation({type:'ECON_LINE',line:l.id,product,factories:l.factories,priority:l.priority});delete p.selections['convert:'+l.id];refresh();});
 each('[data-convert-cancel]',el=>{delete p.selections['convert:'+el.dataset.convertCancel];refresh();});
 const close=document.getElementById('production-picker-close');if(close)close.onclick=()=>{delete p.selections['production-picker'];refresh();};
}
