import {escStatus as esc} from './unitStatus.js';
export const releaseMode=()=>!!document.querySelector('meta[name="grand-release"]');
export function releaseHome(){return `<main class="home-screen"><h1>EASTFRONT · 第聂伯战役</h1><p>指挥德军三个军团，对手为苏军AI。生产、补给与战斗随同一时钟推进。</p><p>暂停或推进中都可下令。点击任意己方部队，再点地图目标即可移动或攻击；手动命令保留军团归属。</p><label>战役<select id="play-mode"><option value="continuous">领土投降战役 · 无时限</option></select></label><label>阵营<select id="ai-side"><option value="GERMAN">德军</option></select></label><p id="release-session" role="status">正在读取战役…</p><button id="ai-start">继续游戏／进入战役</button><button id="release-new">新游戏</button><div id="release-new-confirm" hidden><p>新游戏采用均衡面积战区 R1：德苏各约49%陆地，保留中立走廊。继续游戏不改旧边界。新游戏会替换当前战役及自动存档。服务器会保留一份新局前备份；其他操作端也将退出旧局。</p><button id="release-new-yes">确认建立新局</button><button id="release-new-no">取消</button></div><p>每30秒或推进1游戏小时自动保存；手动保存立即写入。全部操作端断线后世界暂停，重连后由你继续。</p><details><summary>同一账号的第二操作端</summary><a href="/?client=b" target="_blank">打开协同操作端</a><p>仍共同指挥德军，不是德苏真人对战。</p></details><p id="release-home-error" role="alert"></p></main>`;}
export function bindReleaseHome(){if(!releaseMode())return;let info:any;
 void fetch('/release/info').then(r=>r.json()).then(d=>{info=d;if(d.divisionIntegrated){const h=document.querySelector('.home-screen h1');if(h)h.textContent='编制一体化 · 新规则步兵战役';document.querySelectorAll('.home-screen > p').forEach((p,i)=>{if(i===0)p.textContent='双方统一步兵／工兵／侦察规则；陆军经验从0开始，通过实际交战获得。';if(i===1)p.textContent='保留旧战役；此新局使用独立型号库存、生产运输和编制战斗适配，不是原版引擎复刻。';});}if(d.pieceFixture){const h=document.querySelector('.home-screen h1');if(h)h.textContent='内部件数换编测试（非正式战役）';document.querySelectorAll('.home-screen > p').forEach((p,i)=>{if(i===0)p.textContent='经验、库存、部队初始件数与补充额度为显式测试注入，正常新局不会获得。';if(i===1)p.textContent='进入后打开编制草案。仅验证采用、扣库、返还与存档；此入口不推进战斗或旧经济。';});const mode=document.querySelector('#play-mode option');if(mode)mode.textContent='DIVISION-PIECES-TEST-1';}const el=document.getElementById('release-session');if(el)el.textContent=`${d.mid?'真实中期战役 · ':''}${d.ended?'已结束的战役':d.tick?'已有战役':'暂停的新战役'} · ${d.saved?'最近保存 '+new Date(d.saved).toLocaleString():'尚未保存'}`;}).catch(()=>{const el=document.getElementById('release-session');if(el)el.textContent='无法读取，请检查连接或重新登录。';});
 const confirm=document.getElementById('release-new-confirm')!;document.getElementById('release-new')!.onclick=()=>{confirm.hidden=false;};document.getElementById('release-new-no')!.onclick=()=>{confirm.hidden=true;};
 document.getElementById('release-new-yes')!.onclick=async()=>{const button=document.getElementById('release-new-yes') as HTMLButtonElement;button.disabled=true;try{if(!info)throw Error('尚未读取战役，请刷新。');const r=await fetch('/release/new',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instanceId:info.instanceId,revision:info.revision})}),d=await r.json();if(!r.ok)throw Error(d.error);location.reload();}catch(e){document.getElementById('release-home-error')!.textContent=String(e);button.disabled=false;}};
}
export function saveStatus(p:any){const s=p.data.release?.persistence;if(!s)return '';return `<small class="release-save" role="status" title="自动保存：30秒或1游戏小时；全部断线自动暂停。${esc(s.error??'')}">${s.state==='failed'?'⚠ 保存失败 · 已暂停':s.savedAt?'已保存 '+new Date(s.savedAt).toLocaleTimeString():'待首次保存'}</small>`;}
