import type {GrandPort} from './grand.js';
export const escStatus=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const numberStatus=(n:number)=>Number(n.toFixed(1)).toString();
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export type UnitStatus={id:string;org:number;orgMax:number;personnel:number;max:number;orgRatio:number;personnelRatio:number;low:boolean;threshold:number;stock:number;supplyLabel?:string|undefined;action:string;gear:{type:string;label:string;held:number;required:number;missing:number}[]|null};
/** Exact authorized own data only; coarse battle forecasts are deliberately not an input. */
export function ownStatus(p:GrandPort,id:string):UnitStatus|null {
 const u=p.data.game.message.payload.view.units.find((u:any)=>u.id===id&&u.side===p.data.viewer),v=p.data.continuous.units[id],r=p.data.continuous.unitStatusRules;
 if(!u||!v||!r||![v.org,v.personnel,v.max,r.orgMax,r.lowOrg,v.stock].every(Number.isFinite)||v.max<=0||r.orgMax<=0)return null;
 const g=p.data.ux?.equipment?.find((x:any)=>x.id===id),products=p.data.ux?.products??{},gear=g?.recipe&&g?.base?Object.entries(g.recipe).map(([type,n])=>{const required=Number(n)*g.base.maxDamageSteps,held=g.held[type]??0;return {type,label:products[type]?.label??type,held,required,missing:Math.max(0,required-held)};}):null;
 const actions=p.data.continuous.map.actions.filter((a:any)=>a.unit===id&&a.status!=='COMPLETED'),types:Record<string,string>={MOVE:'行军',RETREAT:'撤回',ATTACK:'主攻',SUPPORT:'支援（不跟进）'};
 return {id,org:v.org,orgMax:r.orgMax,personnel:v.personnel,max:v.max,orgRatio:clamp(v.org/r.orgMax),personnelRatio:clamp(v.personnel/v.max),low:v.org<r.lowOrg,threshold:r.lowOrg,stock:v.stock/4,supplyLabel:p.data.modern?'日常供给 '+Math.round((p.data.modern.network.rows[id]?.ratio??0)*100)+'%':undefined,action:actions.length?[...new Set(actions.map((a:any)=>types[a.kind]??a.kind))].join('、'):v.engaged?'交战中':v.direct?.paused?'手动驻守':v.rest?'休整／驻留':'待命',gear};
}
export function aggregateStatus(ss:(UnitStatus|null)[]){if(!ss.length||ss.some(s=>!s))return null;const us=ss as UnitStatus[],personnel=us.reduce((n,u)=>n+u.personnel,0),max=us.reduce((n,u)=>n+u.max,0),orgRatio=us.reduce((n,u)=>n+u.orgRatio,0)/us.length;
 return {orgRatio,personnelRatio:clamp(personnel/max),personnel,max,low:us.filter(u=>u.low).length,threshold:us[0]!.threshold,count:us.length,equipmentUnknown:us.some(u=>u.gear===null),shortUnits:us.filter(u=>u.gear?.some(g=>g.missing>0)).length,gear:[...new Set(us.flatMap(u=>u.gear?.map(g=>g.type)??[]))].map(type=>{const gs=us.flatMap(u=>u.gear?.filter(g=>g.type===type)??[]);return {type,label:gs[0]!.label,held:gs.reduce((n,g)=>n+g.held,0),required:gs.reduce((n,g)=>n+g.required,0),missing:gs.reduce((n,g)=>n+g.missing,0)};})};}
export function gearSummary(s:{gear:UnitStatus['gear']}|null){if(!s?.gear)return '装备信息未知';const missing=s.gear.filter(g=>g.missing>0);return missing.length?'满编装备缺：'+missing.map(g=>g.label+' '+numberStatus(g.missing)).join('、'):'满编装备齐备';}
export function statusText(s:UnitStatus|null){if(!s)return '组织度、人员、装备与补给未知';return `组织度 ${numberStatus(s.org)}/${s.orgMax}；人员 ${Math.round(s.personnel)}/${s.max}（${numberStatus(s.personnelRatio*100)}%）；${s.low?'低组织：低于'+s.threshold+'，可能需要撤退；':''}${s.action}；${s.supplyLabel??('补给 '+numberStatus(s.stock)+' SP')}；${gearSummary(s)}`;}
export function statusBars(s:UnitStatus|null){if(!s)return '<span class="unit-state-unknown">组织／人员 未知</span>';return `<span class="unit-dual-bars" data-status-unit="${escStatus(s.id)}" data-org="${s.org}" data-personnel="${s.personnel}" data-max="${s.max}"><span class="unit-status-row"><span>组织</span><span class="unit-status-track"><i class="unit-org-fill" style="width:${s.orgRatio*100}%"></i></span><span>${numberStatus(s.org)}/${s.orgMax}</span></span><span class="unit-status-row"><span>人员</span><span class="unit-status-track"><i class="unit-personnel-fill" style="width:${s.personnelRatio*100}%"></i></span><span>${Math.round(s.personnel)}/${s.max}</span></span><small>${numberStatus(s.personnelRatio*100)}%人员${s.low?' · ⚠ 低组织':''}</small></span>`;}
export function equipmentDetail(s:UnitStatus|null){if(!s?.gear)return '<small>装备未知</small>';return `<details id="unit-gear-${escStatus(s.id)}" class="unit-gear-detail"><summary>${escStatus(gearSummary(s))}</summary><small>以下为满编需求，装备包独立于人员；不是综合战力。</small>${s.gear.map(g=>`<div>${escStatus(g.label)} ${numberStatus(g.held)}/${g.required}${g.missing?' · 缺'+numberStatus(g.missing):''}</div>`).join('')}</details>`;}

export function battleStatus(p:GrandPort,u:any):UnitStatus|null {const r=p.data.continuous.unitStatusRules;if(u.side!==p.data.viewer||!r||![u.org,u.personnel,u.max,u.supply].every(Number.isFinite)||u.max<=0)return null;const gear=u.equipment&&u.equipmentCapacity?Object.entries(u.equipmentCapacity).map(([type,n])=>({type,label:p.data.ux.products[type]?.label??type,held:u.equipment[type]??0,required:Number(n),missing:Math.max(0,Number(n)-(u.equipment[type]??0))})):null;return {id:u.id,org:u.org,orgMax:r.orgMax,personnel:u.personnel,max:u.max,orgRatio:clamp(u.org/r.orgMax),personnelRatio:clamp(u.personnel/u.max),low:u.org<r.lowOrg,threshold:r.lowOrg,stock:u.supply,action:'接战记录',gear};}
